### ISSUE TITLE
Commands entered via command history (cmd-history-prev) are sometimes not inserted properly into the history.

### ISSUE THREAD

**Issue by camoz** [gokcehan/lf#1003]
**Steps to reproduce**

- Start `lf`
- Run `:echo hello`
- Enter `:` followed by `<c-p>` (`:echo hello` appears) and change `hello` into `world`, then press enter
- Enter `:` followed by `<c-p>`

**Expected behavior**

- `:echo world` appears (i.e. the previously run command)

**Actual behavior**

- `:echo hello` appears (and btw after pressing `<c-n>`, `:echo world` appears)

**Additional info**

- When omitting the `:` before pressing `<c-p>`, the expected behavior occurs.

**Comment by p-ouellette** [comment]
This was fixed in https://github.com/gokcehan/lf/pull/953.

**Comment by camoz** [comment]
Ah thanks, didn't browse the PRs, only issues.
