### ISSUE TITLE
Is there some way to hide dot files & folders in Windows?

### ISSUE THREAD

**Issue by Jeff-411** [gokcehan/lf#1006]
I'm using the r27 release for Windows. I'm running C:\\Program Files\\Git\\bin\\bash.exe in Windows Terminal.

**As stated in the Docs**, "On Windows, only files with hidden attributes are considered hidden files."

I tried adding `set hiddenfiles '.*'` but this had no effect.

Is there some way to hide dot files & folders in Windows?

TIA ~ Jeff.

**Comment by cv1618** [comment]
The syntax seems wrong to me, usually the glob{asteric} comes first. It might be worth a try to change it to `set hiddenfiles '*.'` I don't really know for sure though I"m just throwing it out there.

**Comment by owenstake** [comment]
No way now. According to the  [lf doc](https://pkg.go.dev/github.com/gokcehan/lf)
> Show hidden files. On Unix systems, hidden files are determined by the value of 'hiddenfiles'. On Windows, only files with hidden attributes are considered hidden files.

**Comment by joelim-work** [comment]
I'm pretty sure the `hiddenfiles` option has no effect on Windows. But you can use `filter` to hide files/folders starting with a dot (the `!` means to negate the search pattern):

```
:set globsearch; setfilter '!.*'
```
