### ISSUE TITLE
Simple question: show only selected columns

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1012]
Is there a way to show only the **second** (actual directory/content) and **third** column (preview or seconf column directory content) (aka ranger)?

**Comment by DusanLesan** [comment]
Try to set ratios like:
`set ratios 1:2`

**Comment by og900aero** [comment]
Ohh my god is working! Thank u so much . Bye bye ranger and vifm, hello lf :)

I would like to thank you for your work. You have managed to write a fast and responsive file manager that is as good as vifm and easy to program/customize and miles faster than ranger.

**Comment by DusanLesan** [comment]
@og900aero You are welcome. I am not the contributor here, I just like helping new users set up.

I share your sentiment and would like to thank all people making this app awesome.
