### ISSUE TITLE
Data request in the bottom line

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1025]
I would like to know how to delete the line after requesting data in the lower bar and direct linux requests there, such as the password request after the sudo command. Example wrote the custom command

cmd change_chown ${{
	clear
	set -f
	printf "New owner:group -> "
	read own
    for f in $fx; do
        sudo chown "$own" "$f"
    done
}}

This working fine, because open the shell, and run. But I want run in the bottom info line (where show the internal command), so I change $ to %:

cmd change_chown %{{
	set -f
	printf "New owner:group -> "
	read own
    for f in $fx; do
        sudo chown "$own" "$f"
    done
}}

Then show the message (New owner:group -> ) in the botton line, but if I enter the data and then press enter, the password request for the sudo command does not pop up.
How can I delete the line after the data request and also place the password request in the bottom line?

**Comment by SeekingBlues** [comment]
You can use `sudo -S` to force `sudo` to read from the standard input. But your password will be echoed on the bottom line, and there doesn't seem to be a method of disabling that.

**Comment by og900aero** [comment]
> You can use `sudo -S` to force `sudo` to read from the standard input. But your password will be echoed on the bottom line, and there doesn't seem to be a method of disabling that.

That would be an almost perfect solution. There is a problem that the password I type can be seen by anyone because it displays it. Could it be hidden somehow, not show the password, as in normal case?

**Comment by SeekingBlues** [comment]
I don't think that's possible given how `lf` always displays whatever you type in the prompt. Currently, there is no way to change this behavior. I think your best bet would be to use the `$` style of shell commands, or invoke `sudo` with a `-A` argument to use an external (graphical) program to read your password.

**Comment by og900aero** [comment]
Unfortunately, this is unsolvable without the lf developer.
