### ISSUE TITLE
Error on check

### ISSUE THREAD

**Issue by tylerwolf35** [gokcehan/lf#1030]
Hello, I am attempting to rebuild lf but am now getting errors. I assume this is due to some sort of incompatibility with some go build software that I recently updated.

Here is the error I get:
```
phase `build' succeeded after 1.2 seconds
starting phase `check'
# github.com/gokcehan/lf
src/github.com/gokcehan/lf/colors_test.go:77:4: Errorf format %d has arg test.st of wrong type github.com/gdamore/tcell/v2.Style
FAIL	github.com/gokcehan/lf [build failed]
FAIL
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "go" arguments: ("test" "github.com/gokcehan/lf") exit-status: 2 term-signal: #f stop-signal: #f> 
phase `check' failed after 1.0 seconds
command "go" "test" "github.com/gokcehan/lf" failed with status 2
```

Any help is appreciated.

Thanks!

**Comment by p-ouellette** [comment]
If think you need to pull the latest commits. Line 77 of colors_test.go doesn't use %d since this commit https://github.com/gokcehan/lf/commit/a94015d2210a7983744f47395f542459a56175d9#diff-89fff58c92279529eda2fbee221d12b5b3ca94d9f33cd84ddd424e063ab5a37c

**Comment by tylerwolf35** [comment]
> If think you need to pull the latest commits. Line 77 of colors_test.go doesn't use %d since this commit [a94015d#diff-89fff58c92279529eda2fbee221d12b5b3ca94d9f33cd84ddd424e063ab5a37c](https://github.com/gokcehan/lf/commit/a94015d2210a7983744f47395f542459a56175d9#diff-89fff58c92279529eda2fbee221d12b5b3ca94d9f33cd84ddd424e063ab5a37c)

Thanks, that is it. The package manager (Guix) I was using was trying to build from an old commit. I have now opened an issue through the proper channels.
