### ISSUE TITLE
features sum file size

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1034]
when i selected folder, the lf show folder size is not true,
![image](https://user-images.githubusercontent.com/87791643/204782998-63b75041-ed7d-4279-a29f-31e8adcb0c88.png)

look this, is show 4.0k, is not contain file in folder. show is not size
,
two :

![image](https://user-images.githubusercontent.com/87791643/204783393-ed805556-8dfd-4340-96d0-cdfcbda39638.png)

when i selected all files, lf not sum all file size, it just show one file size, so, can add show all files size in features

**Comment by SeekingBlues** [comment]
The sum can be displayed if you do `set info size` and `calcdirsize` on the directory. The bottom line showing a size of 4.0K for directories just mimics what you would see in the output of `ls`.
