### ISSUE TITLE
How do I enable cyclic motion from top to bottom

### ISSUE THREAD

**Issue by UtkarshVerma** [gokcehan/lf#1045]
Vertical motion in `lf` is not cyclic as the cursor gets stuck at the top position. How do I configure `lf` so that the cursor moves to the last item if I press `Up` on the first item in the list?

**Comment by DusanLesan** [comment]
Try to set : `set wrapscroll true`

**Comment by UtkarshVerma** [comment]
Thanks a lot!

**Comment by DusanLesan** [comment]
> Thanks a lot!

Thank you for all your work with dwmblocks async
