### ISSUE TITLE
lf has recently started ignoring open-with commands

### ISSUE THREAD

**Issue by matoro** [gokcehan/lf#105]
Recently updated to the newest git master and it seems open-with commands for file of mime-type `text/plain` have suddenly broken.  No matter what I do with my xdg spec they continue to open in Firefox, and that's with a manual override in `lfrc`.

Relevant config:

```
# define a custom 'open-file' command
# 'open-file' is called by 'open' when current file is not a directory. You may
# want to use either file extensions and/or mime types here. Below uses an
# editor for text files and a file opener for the rest.
cmd open-file ${{
    case $(file --mime-type "$f" -b) in
        inode/x-empty) vim $fx;;
        text/*) vim $fx;;
        image/*) nohup sxiv $fx > /dev/null 2> /dev/null &;;
        application/pdf) nohup zathura $fx > /dev/null 2> /dev/null &;;
        application/x-tar) ;&
        application/x-debian-package) ;&
        application/x-cpio) ;&
        application/x-rar-compressed) ;&
        application/x-xz) ;&
        application/x-7z-compressed) ;&
        application/java-archive) ;&
        application/zip) ;&
        application/vnd.ms-cab-compressed)
            als $fx | $PAGER;;
        *) for f in $fx; do nohup xdg-open $fx > /dev/null 2> /dev/null & done;;
    esac
}}
```

```
$ xdg-mime query default text/plain
vim.desktop
```

**Comment by gokcehan** [comment]
@matoro I have recently renamed `open-file` special command `open` to avoid confusion for new users. You just need to rename it similarly in your configuration to make it work. Sorry for inconvenience.

We have a note about this in changelog in releases section. Even if you install from source, it may be a good idea to check changelogs there when you update.

**Comment by matoro** [comment]
@gokcehan Thanks mate!  My bad for not reading.  Cheers
