### ISSUE TITLE
Backspace to normal mode should not apply to command arguments

### ISSUE THREAD

**Issue by Limero** [gokcehan/lf#1052]
The recent change to [go to normal mode when backspacing on empty prompt](https://github.com/gokcehan/lf/pull/836) makes sense when explicitly entering command mode, however, I don't think it should apply when calling a command that wants an argument.

For example, the rename command. I expect pressing `r` (to rename) and holding backspace would remove the filename and stop at  `Rename:` not continue and go back to normal mode.

In vim, opening netrw (`:E`) and pressing `R` to rename, holding backspace would stop at the command, not go back to normal mode.

The change also makes it possible to leave a search (`/`) by pressing backspace, but that matches the behavior of vim.

**Comment by ilyagr** [comment]
You can always press `<c-u>` in the command-line to erase until the beginning on the line. I was hoping that would be enough.

If not, the main benefit of this feature is in the `$/!/%/&` modes and for people used to this in `/` mode. I can remove it from most or all others.

**Comment by Limero** [comment]
I agree that `<c-u>` is the preferred way compared to holding backspace, however I think we should match the behavior of netrw here and not apply it to commands like rename. It makes sense for the others, where you explicitly enter that mode.
