### ISSUE TITLE
Installation command in the wiki Tutorial page is outdated

### ISSUE THREAD

**Issue by kumralcem** [gokcehan/lf#1053]
This is the command. https://github.com/gokcehan/lf/wiki/Tutorial
`env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w" github.com/gokcehan/lf
`

On the main page, the commands are specified for golang versions. I guess the wiki page never got updated?

**Comment by joelim-work** [comment]
This is fixed. The instructions in the wiki now specify `go install` instead of `go get`, see this [comparison](https://github.com/gokcehan/lf/wiki/Tutorial/_compare/f94b3a98bc9600ae78d09d3242a7cfe9930dd7a6...01ae7b725f7e309934f9b040191b21784851bf61).
