### ISSUE TITLE
Search next via n like in vim?

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1054]
Anyway to get find bound to / jump to the next match with n as in vim?

**Comment by SeekingBlues** [comment]
If you are using find (<kbd>f</kbd>/<kbd>F</kbd>), then next/previous match is <kbd>;</kbd> and <kbd>,</kbd>. If you are using search (<kbd>/</kbd>/<kbd>?</kbd>), then next/previous match is <kbd>n</kbd> and <kbd>N</kbd>. This is documented here:
https://github.com/gokcehan/lf/blob/b47cf6d5a525c39db268c2f7b77e2b7497843b17/doc.go#L66-L73

**Comment by se7en-x230** [comment]
Oh ??? 
For whatever reason I added map n in my lfrc long time ago .... 

My fault. Thanks
