### ISSUE TITLE
Backspace in rename prompt causes unexpected behavior

### ISSUE THREAD

**Issue by karabaja4** [gokcehan/lf#1059]
A regression from lf 27 in lf 28:

If you try to rename a file and hold the backspace key to delete the whole filename, it will not stop at the beginning of the prompt, instead when it reaches the beginning it will exit the rename and start triggering the backspace key (if you have it mapped to something, it will execute that action unexpectedly).

I had backspace mapped to `updir`, so when I held the backspace key to change the filename, suddenly I found myself looking at the `/` directory.

**Comment by SeekingBlues** [comment]
Similar issue: #1052

**Comment by joelim-work** [comment]
This is actually fixed in #1060 and can be closed. It turns out this issue wasn't linked properly because the `Fixes` has to be specified for each individual issue in the PR description if there are multiple issues being linked.
