### ISSUE TITLE
Reload/Update buffers does randomly not work

### ISSUE THREAD

**Issue by dase78** [gokcehan/lf#1061]
Relying to this issue https://github.com/gokcehan/lf/issues/914 I wanted to bring the issue up again:

When cutting, pasting, copying, renaming files (or creating new directories/files), lf does randomly not update the new dircount-numbers.

I even chained commands with e.g. "map p :paste; reload", does not help always.

As said, this happens completely randomly.

For me this is a very serious thing.

lf, version 27 (installed via debian bookworm package)

**Comment by joelim-work** [comment]
Forgot to close this earlier, but filesystem watching was recently introduced in #1667, so that should hopefully address this need.
