### ISSUE TITLE
When I use read command, get error message

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1062]
I created custom command:

```
cmd change_permission %{{
	clear
	set -f
	read -p "New permission -> " -s perm
    for f in $fx; do 
        sudo -S chmod "$perm" "$f"
    done
    lf -remote "send $id reload"
}}
```
When I used %{{ (so get input message on statusbar), the read command doesnt work perfectly. Illegal option -s error message, and the -p option doesnt work too. So when I use % for the command, the read command options/switches doesnt work.

**Comment by SeekingBlues** [comment]
What shell are you using?

**Comment by og900aero** [comment]
> What shell are you using?

Debian 11.6 with bash shell 5.1.4 version. When I type in terminal (st - simple terminal, that works well.)
So I try (in terminal) I type dash + enter, so dash shell, and the error message equal in lf. So, although bash shell works under the terminal, the lf program uses dash shell for some reason.

**Comment by SeekingBlues** [comment]
I think in your case `lf` is using `sh`, which is probably symlinked to `dash`? You have to do `set shell bash` to use the `-s` and `-p` options, which are not POSIX-compliant and thus not supported by `dash`. Also, the `-s` (silent) option will not work because the shell's input is piped from `lf`, just like in #1025.

**Comment by og900aero** [comment]
> I think in your case `lf` is using `sh`, which is probably symlinked to `dash`? You have to do `set shell bash` to use the `-s` and `-p` options, which are not POSIX-compliant and thus not supported by `dash`. Also, the `-s` (silent) option will not work because the shell's input is piped from `lf`, just like in #1025.

Indeed. Under Debian, sh is symlinked to dash. Then, unfortunately, this cannot be solved completely, because even if I change it to bash, the password entry cannot be removed.
