### ISSUE TITLE
Copy and move files asynchronously with progressbar with advanced copy

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1064]
I use advanced copy and move program: [https://github.com/jarun/advcpmv](url)
I try the following code, and works with rsync:

```
cmd paste &{{
    set -- $(cat ~/.local/share/lf/files)
    mode="$1"
    shift
    case "$mode" in
        copy)
            rsync -av --ignore-existing --progress -- "$@" . |
            stdbuf -i0 -o0 -e0 tr '\r' '\n' |
            while IFS= read -r line; do
                lf -remote "send $id echo $line"
            done
            ;;
        move) mv -n -- "$@" .;;
    esac
    rm ~/.local/share/lf/files
    lf -remote "send clear"
}}
```
But if I replace rsync's row with: advcp -ag "$@" . | , it does not show its value in the bottom bar, only flashing the text.
The output of advcp is slightly different than that of rsync. rsync lists what it does line by line, and advcp is fixed as above:

![screenshot2](https://user-images.githubusercontent.com/49487376/209967675-547ab79b-0f38-4307-a3ea-1e8ff485ba52.jpg)

How can I write out only the progress bar row on lf's bottom bar?

**Comment by SeekingBlues** [comment]
Try changing this
```sh
rsync -av --ignore-existing --progress -- "$@" . |
stdbuf -i0 -o0 -e0 tr '\r' '\n' |
```
to this
``` sh
advcp -ag "$@" . | grep -Po --line-buffered "(?<=^\033\[K).+%$" | sed -nu 'n;p' |
```
You will need a `grep` that supports PCRE. Since `advcp` outputs two progress bars (one for summary and one for individual files), the `sed` command only prints the second bar. You can change `n;p` to `p;n` if you want the first bar.

**Comment by og900aero** [comment]
> 

Working great only foreground paste cmd %{{: advcp -ag "$@" . | grep -Po --line-buffered "(?<=^\033\[K).+%$" | sed -nu 'p;n'
But I want to use this in async mode copy. So I want use cmd paste &{{.
I think it should somehow be mixed with lf-remote "send $id echo".

**Comment by SeekingBlues** [comment]
Yes, I meant to replace the part in your snippet that uses `rsync` and keep the remote sending code. Like this:
```sh
cmd paste &{{
    set -- $(cat ~/.local/share/lf/files)
    mode="$1"
    shift
    case "$mode" in
        copy)
            advcp -ag "$@" . | grep -Po --line-buffered "(?<=^\033\[K).+%$" | sed -nu 'n;p' |
            while IFS= read -r line; do
                lf -remote "send $id echo $line"
            done
            ;;
        move)
            mv -n -- "$@" .
            ;;
    esac
    rm ~/.local/share/lf/files
    lf -remote "send clear"
}}
```

**Comment by og900aero** [comment]
> Yes, I meant to replace the part in your snippet that uses `rsync` and keep the remote sending code. Like this:
> 
> ```shell
> cmd paste &{{
>     set -- $(cat ~/.local/share/lf/files)
>     mode="$1"
>     shift
>     case "$mode" in
>         copy)
>             advcp -ag "$@" . | grep -Po --line-buffered "(?<=^\033\[K).+%$" | sed -nu 'n;p' |
>             while IFS= read -r line; do
>                 lf -remote "send $id echo $line"
>             done
>             ;;
>         move)
>             mv -n -- "$@" .
>             ;;
>     esac
>     rm ~/.local/share/lf/files
>     lf -remote "send clear"
> }}
> ```

Ohh yes, it is working! Thank u so much :)

Can you help me with one more thing? I see that there is a perl syntax for grep, so I don't really understand this, and the result is a little different than using the advcp command in terminal, because the % value moves together with the progress bar now in lf, while if I use it plainly in the terminal , then the strip has a fixed length, and thus the progress bar increases.
By issuing the command exactly like this in a terminal:
```
[========                                     ] 22.2 %
[================                             ] 46.2 %
[===================================          ] 90.2 %

```
In Lf, with the command line you specified, it looks like this:
```
[========] 22.2 %
[================] 46.2 %
[====================================] 90.2 %
```

Is there any way to display the very first version? Or is this lf's fault?

**Comment by SeekingBlues** [comment]
Turns out the remote command swallows all the extra spaces. We need to put quotes around the line like this: `lf -remote "send $id echo '$line'"`.

**Comment by og900aero** [comment]
> Turns out the remote command swallows all the extra spaces. We need to put quotes around `$line` like this: `lf -remote "send $id echo '$line'"`.

Works, works! Thank u :)
