### ISSUE TITLE
on-cd changes WITHOUT subdirectory

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1065]
Is it possible to use the on-cd command to sort a directory by time BUT NOT the subdirectory?
 
#restore sorting on directory exit
does not work for me (zsh) 
Neither if I move to a subdirectory or parent.
`
cmd on-cd &{{
    case "$PWD" in
        ~/Data/Down*)
            lf -remote "send $id set user_prev_sortby $lf_sortby"
            lf -remote "send $id set sortby time"
            lf -remote "send $id set reverse"

            lf -remote "send $id echomsg changed sort to time"
            ;;
        *)
            # restore sorting on directory exit
            if [[ "$lf_user_prev_sortby" != "" ]]; then
                lf -remote "send $id set sortby $lf_user_prev_sortby"
                lf -remote "send $id set reverse"

                lf -remote "send $id echomsg restored sort to $lf_user_prev_sortby"
                lf -remote "send $id set user_prev_sortby ''"
            fi
            ;;
    esac
}}`

**Comment by SeekingBlues** [comment]
If you want to sort by time only for `~/Data/Down` and not its subdirectories, remove the wildcard (`*`) in the first switch case.

**Comment by se7en-x230** [comment]
hmmm I can't figure it out. 

changing the path to ~/Data/Down does set the last downloaded folder to the top but also the subfolder is changed AND all other folder up to ~/ 

ALSO the second part of the command seams not to work. I never see the `echomesg resrord sort to ...`

![shop-2022-12-31-14-26](https://user-images.githubusercontent.com/69777713/210129117-c2c2ec43-8d8c-4790-8841-78575af3cf53.png)

**Comment by SeekingBlues** [comment]
Are you using the latest version of `lf`? The support for user-defined options and environment variables is added in r28. The reason you are not seeing the message is probably that `$lf_user_prev_sortby` is equal to `""` because your old version of `lf` does not set it at all.

**Comment by se7en-x230** [comment]
Oh that is strange?
I installed years ago the lf-git package from AUR and that did for whatever reason not update.

![image](https://user-images.githubusercontent.com/69777713/210158736-385b0b90-cc47-4a69-944a-8143bd93fb8d.png)

A specific paru -S lf-git did update to lf-git-22.r2.g8739087-1

Is there a different to the community/lf 28-1 [1.30MiB 3.71MiB] package?

Thanks and happy new year

**Comment by se7en-x230** [comment]
Is there a way to send a "gg" signal right after entering the directory to end up on top and not somewhere in the middle of the directory
?

**Comment by SeekingBlues** [comment]
Happy new year. `gg` is mapped to the command `top`, so you can try `lf -remote "send $id top"`.

**Comment by se7en-x230** [comment]
Nice feature.
Can I add multiple directories to the same pattern.
Something like 
`~/Data/Down ; ~/Downloads)`

**Comment by SeekingBlues** [comment]
`~/Data/Down | ~/Downloads)`

**Comment by se7en-x230** [comment]
Amazing. Thanks
