### ISSUE TITLE
How to resolve 'nested' lf running processes?

### ISSUE THREAD

**Issue by ipstone** [gokcehan/lf#107]
Hello,

Recently it happened: when working under `lf`,  after opening a shell through `w`; I often forgot that I was already under `lf` => so I started several 'nested' instance of `lf`.

Though it only occured occasionally, I am wondering if there's a way (or a real need) to remind/warn user for these nested situation? Or in practicality, does it matter?

Thanks,
Isaac

**Comment by TeddyDD** [comment]
Oh yeah, It's not big issue, but it's kinda funny when you close five nested instances of lf :laughing:

**Comment by gokcehan** [comment]
@ipstone Thanks for reminding this.

I have now added a commit to export `$LF_LEVEL` environmental variable in shell commands to denote the nest level similar to `$RANGER_LEVEL` in ranger. You can check this variable in your `~/.bashrc` and change your prompt accordingly to remind you that you're already in `lf` with something like:

    [ -n "$LF_LEVEL" ] && PS1="$PS1""(lfception: $LF_LEVEL) "

I'm closing this issue now. Feel free to suggest alternatives if there is a better way to do this.

**Comment by ipstone** [comment]
awesome! thanks @gokcehan
