### ISSUE TITLE
r28 cursor reset when rename

### ISSUE THREAD

**Issue by jetgogol** [gokcehan/lf#1070]
In last update. When I rename, file cursor now changes to block (I using "|") and after exit terminal keep it as block.

My terminal emulator st if it means anything.

**Comment by SeekingBlues** [comment]
See gdamore/tcell#559. Try changing the default cursor style of your terminal emulator to `|`.

**Comment by jetgogol** [comment]
May be it's st problem, but I changed default cursor to "|" in config.h already. Also I tested same build of lf in tilix and it works fine.

**Comment by jetgogol** [comment]
st version 0.8.5, but in st version 0.9 same problem.

**Comment by SeekingBlues** [comment]
It does seem like `st`'s problem. It assumes the "default" cursor style (`\e[0 q`) to be blinking block, which is supposed to be the standard behavior. `tcell` makes a different assumption that it really means the user's default, which is an extension supported by many terminals (but not `st`).

**Comment by jetgogol** [comment]
> It does seem like `st`'s problem. It assumes the "default" cursor style (`\e[0 q`) to be blinking block, which is supposed to be the standard behavior. `tcell` makes a different assumption that it really means the user's default, which is an extension supported by many terminals (but not `st`).

Anyway r27 works right, so don't closing this issue to keep my finger on pulse. May be someone else will add details.

**Comment by joelim-work** [comment]
I don't think there's anything we can reasonably do about this. As mentioned above, `tcell` sends `\e[0 q` to instruct the terminal to reset its cursor style to the default, but `st` interprets this as blinking block.

The expectation of `st` and other suckless projects is that the user should be able to patch them to suit their needs. For your case, you should be able to modify the code (e.g. the [`xsetcursor`](https://git.suckless.org/st/file/x.c.html#l1738) function) to map `0` to your preferred cursor style.
