### ISSUE TITLE
Send notification after action finished

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1071]
![shop-2023-01-02-09-05](https://user-images.githubusercontent.com/69777713/210190740-74fe6c7d-a2a7-47e7-96b1-1017cf2c0652.png)

I fail to understand why this does not work. I have similar notification lines for creating directories and other actions and sometimes they send a notification sometimes not. 
Can't see a pattern.

**Comment by SeekingBlues** [comment]
You are invoking a shell command called `paste`, so it will not work as expected. You need to send a remote command to `lf` like `lf -remote "send $id paste"`.

**Comment by se7en-x230** [comment]
Thanks for the hint. 
Now I understand and it works.

**Comment by SeekingBlues** [comment]
I think this will also work: `cmd paste-notify :paste; ${{ dunstify ... }}`.

**Comment by se7en-x230** [comment]
Not sure what changed but the notification does not wait till the end of the task anymore ????
