### ISSUE TITLE
Execute commands sequentially (not just group)

### ISSUE THREAD

**Issue by Lodifice** [gokcehan/lf#1082]
Hi, I'm aware that commands can be mapped in groups using `:cmd1; cmd2` but this does not enforce a strict order of execution.
For instance, mapping something to `:filter; setfilter` I would expect that I first enter the filter prompt to type some pattern (and having `incfilter` enabled, see the pattern's effects), and then, when I press return, the filter is cleared and I see the entire directory again. However, as it is, the `setfilter` is not executed after pressing enter and thus the filter stays in place.

In particular, the behaviour I desire would be useful to mimic the find-while-type functionality of ranger using `map f :filter; setfilter; open` (with the difference that you have to press return once, but I actually prefer it this way). The closest I could get to that was either using two mappings (so you'd have to press return twice) or using some shell command, but then there is no preview in lf.

**Comment by joelim-work** [comment]
Grouped commands (e.g. `:cmd1; cmd2`) are executed sequentially, however your confusion probably comes from the fact that `filter` is a modal command and probably doesn't do what you expect.

In reality, `filter` simply just sets the UI in 'filter' mode, where `filter: ` is displayed on the command line. The actual filter isn't applied until you press <kbd>Enter</kbd>, which is mapped to `cmd-enter`, and it is at this point where you need to map `setfilter; open`.

To achieve what you want, you can use a user-defined value to keep track of whether `lf` is in filter mode or not. Hopefully the following snippet works for you:

```
set incfilter

map f :filter; set user_filter true

cmap <enter> &{{
    if [ "$lf_user_filter" = true ]; then
        lf -remote "send $id :cmd-enter; set user_filter false; setfilter; open"
    else
        lf -remote "send $id cmd-enter"
    fi
}}

cmap <esc> &{{
    if [ "$lf_user_filter" = true ]; then
        lf -remote "send $id :cmd-escape; set user_filter false"
    else
        lf -remote "send $id cmd-escape"
    fi
}}
```

**Comment by Lodifice** [comment]
Thank you very much for your elaborate answer which achieves precisely what I wanted.
My confusion came indeed from the fact that modal commands cannot be grouped (or, at least, grouping them does not what I would expect), so maybe this should be documented somewhere?

Also, regarding your particular answer, I think that it would be a nice addition to the wiki.
I just wonder if there is any way around using `lf -remote` since it seems like a waste to launch an `lf` process every time I enter a command.

**Comment by joelim-work** [comment]
I don't think there's any cleaner way of solving this problem - `cmap <enter>` has to do two different things based on some condition, which means the logic has to be implemented as an `if` statement in a shell script, and the only way to invoke builtin commands from a shell script is via `lf -remote` (this is actually a common and recommended technique).

I think the wiki can be edited by anyone (or maybe it's locked to contributors only, correct me if I'm wrong), so you're more than welcome to tweak this config snippet and add it to the Tips section in the wiki. If you don't have permission then I can add it for you.

**Comment by joelim-work** [comment]
I finally got around to adding this as an [example](https://github.com/gokcehan/lf/wiki/Tips#using-incfilter-to-select-and-open-files) in the wiki. I felt it was a good addition since showcases how user-defined variables can be used. Thanks again for the idea!
