### ISSUE TITLE
LF_COLORS

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1083]
I have a problem understanding the color settings.

I used the a modified version of the documentation example in my .zshrc
But as moving the icons out of my .zshrc into ~/.config/lf/icons worked just fine I  tried to do the same with the colorcoding.

This where my color settings in .zshrc:
 export LF_COLORS="\
~/Server=01;33:\
~/Sync=01;31:\
~/Data/System=01;31:\
~/Data=01;33:\
~/Music=01;33:\
~/x500=01;33:\
~/Documents=01;31:\
~/Downloads=01;31:\
~/.local/share=01;31:\
~/.config/lf/lfrc=31:\
.git/=01;32:\
.git*=32:\
*.gitignore=32:\
*Makefile=32:\
README.*=33:\
*.txt=34:\
*.md=34:\
ln=01;36:\
di=01;96:\
ex=01;32:\
"

Looking like this:
![shop-2023-01-19-09-29](https://user-images.githubusercontent.com/69777713/213342988-35216b18-8bba-4dc4-b591-8cc283d18009.png)

Problem now is as soon as I move the color codes to ~/.config/lf/colors 
1. I give di  the color code 01;96 (same as in my .zshrc and it turnes into a light blue and not the green as seen in the screenshot.
2. I fail to understand the syntax how to give folder a different color

**Comment by pbwn** [comment]
i have this issue on windows 10.
for windows the config files are located here: C:\Users\...\AppData\Local\lf
i added the colors file but it doesn't seem to be recognised. For other users it works fine: https://old.reddit.com/r/linux4noobs/comments/ttcfph/how_do_i_get_lf_to_recognize_a_different_set_of/
the dir colours are unfortunately unreadable in powershell (it is a company computer so i have limited ability to tweak things)

**Comment by gokcehan** [comment]
@se7en-x230 Please take a look at `etc/colors.example` for the syntax.

@pbwn Color file is added with r28 so make sure you have the latest version.
