### ISSUE TITLE
how to generate config file /Arch v28

### ISSUE THREAD

**Issue by Data-007** [gokcehan/lf#1089]
I am new to lf, and would like to know how to generate a config file?
I have run sudo pacman -S lf     this install's program, I can run lf

Iam unable to find the config dir, or config file?
I have watched youtube videos and cant seem to find the path given in videos.
I do have hidden files and folders turned on, it's as if they (the config file)had not been generated!!

Installing the package I would have thought should have set it up.
So how is it generated?

**Comment by DusanLesan** [comment]
I am not sure if the config is auto-generated during install. Either way, you can copy example file from here: https://github.com/gokcehan/lf/blob/master/etc/lfrc.example and paste in into this file: `~/.config/lf/lfrc`

**Comment by Data-007** [comment]
Thanks   ~/.config/lf/lfrc   is not there I will create it and do as you suggest copy the file across.
