### ISSUE TITLE
Touch command failing in script

### ISSUE THREAD

**Issue by Mugworth** [gokcehan/lf#1091]
I have this little script: 
`#make directories and files`
`cmd mkdir ${{`
`  if [ "${1: -1}" = "/" ]; then`
`    mkdir -p "$1"`
`  else`
`    CDF=$(grep -o ".*/" <<< $1)`
`    if [ "$CDF" != '' ]; then`
`      mkdir -p "$CDF";`
`    fi`
`    touch "$1"`
`  fi`
`}}`

Im not sure why but part with 'touch "$1"'  gives me an error, could someone give me a tip?

**Comment by Mugworth** [comment]
I changed it to:
`cmd mkdir ${{`
`  CACHE=$(mktemp)`
`  for ((i=$#; i>0; i-- )); do`
`    if [ "${1: -1}" = "/" ]; then`
`      mkdir -p "$1"`
`    else`
`      echo "$1" >> "$CACHE"`
`      CDF=$(grep -o ".*/" "$CACHE")`
`      if [ "$CDF" != '' ]; then`
`        mkdir -p "$CDF";`
`      fi`
`      touch "$1"`
`      cat /dev/null > "$CACHE"`
`    fi`
`  shift;`
`  done`
`}}`

it's still not work as it's working when i run it from the normal shell, what i mean is when i write ":mkdir foo"    i get eroor running shell: exit status 1
but i tried prefixing foo with "./" and it works. I'm lost as to why i have to prefix it

**Comment by slavistan** [comment]
Just what are you trying to do? Are you just trying to create a simple lf command to basically do what `mkdir` does?

**Comment by Mugworth** [comment]
i want to create a command that:
- without forward slash on the end makes file
- with forward slash makes dir
- if i provide some path, for example poo/poo1/file_poo it will make recursively (dir/dir/file)
- will work with multiple arguments
the problem is that the only problem is that, as i said, if i want to make only file i have to start with ./ prefix at least in lf.
if i start this script inside bash, i dont have to prefix file with ./ , so i assume it doest work as expected.

**Comment by slavistan** [comment]
Here's a bash script to do what you want.
```
#!/bin/bash

for path in "$@"
do
	if [[ "${path: -1}" == "/" ]]; then
		mkdir -p "$path"
	else
		basedir="$(dirname "$path")"
		mkdir -p "$basedir"
		touch "$1"
	fi
done
```

Name it ***mktouch*** or so, place it in your $PATH, make it executable and create an lf command to wrap it. You can also put the instructions directly into a lf command, but then you must use bash as your shell.

**Comment by Mugworth** [comment]
It seems like wrapping either of these scripts inside separate executable do the job, i dont know why making lf command dont work, i will use your scripts because it's just better, thank you!
