### ISSUE TITLE
Using the built-in delete command with sudo

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1092]
I started to solve it so that if an operation fails, try again with sudo -A . This works fine for me when creating a directory or file, because I use cmd &{{ . In the case of %, the egg freezes.
Now I want to mix the built-in delete command with the sudo -A command, when if the factory delete command runs with an error. I use this now:
map DD :delete; $rm ~/.local/share/lf/files
How can I express here that if :delete runs with an error, then run it with sudo -A ? 

I solved the directory creation of the library in a script as follows:
cmd New directory name: &{{
     mkdir -p -- "$1" 2> /dev/null || sudo -A mkdir -p -- "$1"
But in case of deletion, I would like to use the built-in deletion, because it is a good solution to write all questions and answer options in the bottom line.
Is it possible to do this, or do you have to go into the program's code?

**Comment by DusanLesan** [comment]
Maybe something like this: 
```
cmd delete_dir &{{
	if sudo -u "$USER" test -w "$f"; then
		lf -remote "send $id delete"
	else
		sudo -A rm $f
		lf -remote "send $id reload"
	fi
}}

map DD delete_dir
```

**Comment by og900aero** [comment]
> Maybe something like this:
> 
> ```
> cmd delete_dir &{{
> 	if sudo -u "$USER" test -w "$f"; then
> 		lf -remote "send $id delete"
> 	else
> 		sudo -A rm $f
> 		lf -remote "send $id reload"
> 	fi
> }}
> 
> map DD delete_dir
> ```

Thx reply. The problem is not how to solve the use of sudo, because it goes like this too:
```
for file in $fx; do
      rm -rf "$file" 2> /dev/null || sudo -A rm -rf "$file"
done
```
The problem is that since I use the & sign for the command, I can't display a question in the bottom bar like the factory solution: delete 'path/file' ? [y/n]
Is there a way to do this if I use & to the command? A solution marked with $ is not good, because it does not show the lf. % sign is also not good, because then the whole tty freezes if you try to use sudo

**Comment by og900aero** [comment]
Its working great. But my problem is not how to get it to use sudo, I solved that, but my problem is that if I use sudo, then how can I write out the factory question that sure you want to delete y/N? If I use the & sign for the command, I can't write text at the bottom. If I use $, the lf disappears, if I use the % sign, the whole tty freezes when using sudo

**Comment by DusanLesan** [comment]
I think solution is breaking it down and using different symbols for cmd-s. This probably still isn't perfect, but it might give you some ideas 
```
cmd custom_delete &{{
	if xargs -n 1 sudo -u "$USER" test -w <<<"$fx"; then
		lf -remote "send $id delete"
	else
		lf -remote "send $id root_delete"
	fi
}}

cmd root_delete :{{
	push :Delete files [y/n] -><space>
}}

cmd Delete files [y/n] -> ${{
	if [ $1 == 'y' ]; then
		for x in $fx; do
			sudo -A rm -rf "$x"
		done
		lf -remote "send $id reload"
	fi
}}

map DD custom_delete
```

**Comment by og900aero** [comment]
Uhh, nice idea! I modified it a little bit and it works perfectly:

```
cmd custom_delete &{{
		if sudo -u "$USER" test -w "$fx"; then
			lf -remote "send $id delete"
		else
			lf -remote "send $id root_delete"
		fi
}}

cmd root_delete :{{
	push :Delete files [y/N] -><space>
}}

cmd Delete files [y/N] -> &{{
	if [ "$1" = "y" ]; then
		for file in $fx; do
			sudo -A rm -rf "$file"
		done
		lf -remote "send $id reload"
	else
		exit 0
		lf -remote "send $id unselect"
		lf -remote "send $id clear" 
		lf -remote "send $id reload" 
	fi
	rm -rf ~/.local/share/lf/files
}}
```
Two more questions:
- Is there a way to solve the question so that it is processed immediately after pressing 1 letter and you don't have to press enter? (like read -n 1)
- lf remote does not work when I use it with sudo . For example: sudo -A lf -remote "send $id echo hello world". Can this limitation be bypassed?

**Comment by DusanLesan** [comment]
> * Is there a way to solve the question so that it is processed immediately after pressing 1 letter and you don't have to press enter? (like read -n 1)
> * lf remote does not work when I use it with sudo . For example: sudo -A lf -remote "send $id echo hello world". Can this limitation be bypassed?

I do not think these are possible but I might be wrong.

**Comment by og900aero** [comment]
Okay, thx.
