### ISSUE TITLE
escape key for quitting? 

### ISSUE THREAD

**Issue by azinsharaf** [gokcehan/lf#1093]
pressing `<escape>` key closes `lf`. If this is a default behavior how can i disable it and just use `q` for quitting?

**Comment by DusanLesan** [comment]
I do not think that is default behavior. Do you have `map <esc> quit` in your config? If you do not have that, you can try disabling escape key by just mapping it without command like this: `map <esc>`

**Comment by azinsharaf** [comment]
that is true. I had `map <esc> quit` in lfrc.
