### ISSUE TITLE
Feature: Don't hilight first filename in preview pane when navigating

### ISSUE THREAD

**Issue by robrecord** [gokcehan/lf#1102]
I frequently find `lf` hard to use because I'm not sure which pane I'm controlling. Mostly this is due to the hilighting of the filename in the right most pane, which is unneccesary and thus confusing. Please turn this off? Or configurable?

Either this, or please provide an alternate highlight colour so that the pane that is actively being controlled can easily be recognised.

**Comment by ilyagr** [comment]
This should be fixed by https://github.com/gokcehan/lf/pull/1086.
