### ISSUE TITLE
Create files and directory in powershell

### ISSUE THREAD

**Issue by jatz27** [gokcehan/lf#1104]
I'm new to this and want to know
how can i create files and directories in powershell windows
```
map ad ${{
  printf "Directory Name: "
  read ans
  mkdir $ans
}}
map af ${{
  printf "File Name: "
  read ans
  touch $ans
}}

```
this works in linux but not in windows powershell and i want to know how i can do it

**Comment by nasu-oldhand** [comment]
I use lf in powershell windows ( powershell=`PowerShell core 7.3.2` ).
I can make a directory and file using this setting `lfrc`.

```
map ad ${{
  $dir_name = Read-Host "Directory Name: "
  New-Item $dir_name -ItemType Directory
}}

map af ${{
  $file_name = Read-Host "File Name: "
  New-Item $file_name -ItemType File
}}
```

**Comment by jatz27** [comment]
Thank you very much, but it didn't work :(
I'm using powershell 7.3.2
![image](https://user-images.githubusercontent.com/11084039/221394506-079840b8-dd02-4a3e-a4a1-bc564d36f53c.png)
it just blinks but doesn't ask me for the file name :(

**Comment by jatz27** [comment]
If it was that of `set shell pwsh`  but now I have another problem not the file to edit it from neovim

For example I want to open an achivo hello.txt from LF and opens hello.txt" and it is not the same file because it is blank

To open files I use this command `cmd open $nvim $Env:f`

**Comment by nasu-oldhand** [comment]
ok

Please use this command `cmd open ${{nvim $Env:f.Replace('"','')}}`.

Because `$Env:f` is surrounded by double quotes on windows powershell lf.
ex. `"C:\Users\nasu\Work\memo\test.txt"`

example lfrc to display `$Env:f`

```
cmd echo_path ${{
  Write-Host "Raw Env:f"
  Write-Host $Env:f
  Write-Host "Replaced Env:f"
  Write-Host $Env:f.Replace('"','')
  Read-Host "Press the Enter key to continue"
}}

map ep echo_path
```

**Comment by jatz27** [comment]
Works, thank you very much. 🙏😁

Taking advantage, sorry for the inconvenience I would like to know how I can define my icons in PowerShell because others appear.
![image](https://user-images.githubusercontent.com/11084039/223625662-40810d86-3ea2-456c-8af0-5d4d9f3f96ee.png)
In linux an icons file is defined but in powershell it does not take into account the icons or colors.

**Comment by nasu-oldhand** [comment]
I'm glad to hear that. very nice.😊

>orry for the inconvenience I would like to know how I can define my icons in PowerShell because others appear.

Please set enviroment variable `LF_ICONS`.
Example, powershell profile

```
#######################
# lf
#######################

$Env:LF_ICONS = 'di=d'
```

other reference

- https://github.com/gokcehan/lf/issues/1007#issuecomment-1445139507

This topic would be discussed in another issue.
so, please close this issue.

thanks

**Comment by jatz27** [comment]
Ready, thank you very much 😁
Closed issue
