### ISSUE TITLE
lf -version gives no output

### ISSUE THREAD

**Issue by krackout** [gokcehan/lf#1108]
As the title, `lf -version` gives no output. It could return commit (or release for downloadable binaries).

**Comment by joelim-work** [comment]
How are you obtaining `lf`?

If you are downloading an [official release](https://github.com/gokcehan/lf/releases), then the version number comes from `git describe --tags`, and this is filled in using the `-X main.gVersion=$version` option in [`xbuild.sh`](https://github.com/gokcehan/lf/blob/r28/gen/xbuild.sh).

If you are building from source, then there won't be a version number unless you include that option when running `go build`.

If you are downloading from an external package repository, the maintainers may override this with their own versioning scheme if they wish to do so.

**Comment by krackout** [comment]
I'm building from source. Can you tell me the option to include it in my builds?

**Comment by joelim-work** [comment]
Clone this repository, ensure the Git tags are present, and then run either `gen/build.sh` or the following command:

```shell
CGO_ENABLED=0 go build -ldflags="-s -w -X main.gVersion=$(git describe --tags)"
```
