### ISSUE TITLE
How to cmap <c-left>?

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#111]
I'm trying to map (`cmap`) <kbd>Ctrl-Right</kbd> and <kbd>Ctrl-Left</kbd> to `cmd-word` and `cmd-word-back`, respectively but I keep getting the characters `1;5D` and `1:5C` when pressing these keys when editing the `lf`'s command line.

It seems to be a well known problem in many TUI programs:
- http://jmoiron.net/blog/cleft-and-cright/
- https://superuser.com/questions/532431/control-left-and-control-right-not-working-in-vim-within-a-screen-session

I wonder how this can be fixed but I hope we can discuss this.

**Comment by gokcehan** [comment]
@doronbehar Ideally these keys should have been special keys with names like `<c-left>` and `<c-right>` but they are not provided by [termbox-go](https://godoc.org/github.com/nsf/termbox-go). You can try to open an issue for termbox to include those keys but as far as I'm aware they are terminal specific and not standard and the general attitude for termbox is not to implement those kinds of behavior.

On the lf side, the following hack kind of works in normal mode:

    map '<a-[>1;5D' echo left
    map '<a-[>1;5C' echo right

But the following somehow does not work in command mode:

    cmap '<a-[>1;5D' cmd-word
    cmap '<a-[>1;5C' cmd-word-back

I need to play with the code to see if it is possible to make this work but I would not get my expectations high. Terminals are inherently limited with historical cruft.

**Comment by alivefromupstairs** [comment]
+1

**Comment by alexandrenavarro** [comment]
+1

**Comment by joelim-work** [comment]
Support for this was added in #1248 so this issue can be closed.

The following should solve the problem in the initial post:

```
cmap <c-left> cmd-word-back
cmap <c-right> cmd-word
```

**Comment by doronbehar** [comment]
Can confirm. Thanks for the info! Waiting for the new release..
