### ISSUE TITLE
LF_ICONS

### ISSUE THREAD

**Issue by ghostranger047** [gokcehan/lf#1111]
Why aren't my lf_icons showing? I'm getting only the default icons.

**.zshrc config:**
`[ -f ~/.config/lf/LF_ICONS ] && {
	LF_ICONS="$(tr '\n' ':' <~/.config/lf/LF_ICONS)" \
		&& export LF_ICONS
}`

**LF_ICON file:**
[LF_ICONS.txt](https://github.com/gokcehan/lf/files/10759840/LF_ICONS.txt)

**lfrc file:**
[lfrc.txt](https://github.com/gokcehan/lf/files/10759845/lfrc.txt)

**Comment by joelim-work** [comment]
If you're using the `LF_ICONS` environment variable to configure icons, you need to use `=` as a delimiter, not whitespace. Anyway `lf` now supports using icons files directly, so it's probably easier if you use that approach instead.
