### ISSUE TITLE
lf bottom status bar information

### ISSUE THREAD

**Issue by SiddidMandi** [gokcehan/lf#1113]
In lf at the bottom status bar on the right-hand corner where it says 9/37 or something, basically, which file out of all files you are on, it also shows a red box next to it with the number 1 in it. What does this red box mean? is it linked to permissions or something? if so how do I disable it?

When I run lf as sudo, the red box is no longer there and the colors also looks like ranger regardless of the lack of config for root. When run normally, the lf file manager has lots of yellow background highlights and all and the red box at the bottom.

What is this box and how do I get rid of it?

**Comment by ilyagr** [comment]
It indicates the number of files selected. Try executing `:clear`.
