### ISSUE TITLE
Is there an equivalent to "cd -" in LF?

### ISSUE THREAD

**Issue by jpmvferreira** [gokcehan/lf#1117]
It is quite convenient to navigate back and forth between specific directories.
In my terminal, I would cd into one directory, perform something there, and then `cd -` back to where I was.
In LF I can simply open another window, which is a fine solution, but being so used to use this solution I was wondering if something like this would be possible to implement in LF or is already available (which I haven't been able to find out how to do with the features currently available)

**Comment by se7en-x230** [comment]
You can map different path

map gh cd ~/
map gc cd ~/.config
...

There  is also [ and ] to jump to the last dir

**Comment by jpmvferreira** [comment]
> There is also [ and ] to jump to the last dir
That is exactly what I was looking for and I completely missed it when reading the docs. 
Many thanks!
