### ISSUE TITLE
Get lf to return path of file?

### ISSUE THREAD

**Issue by lukepighetti** [gokcehan/lf#1121]
Is there any way to get `vim $(lf)` to use lf to pick a file and then open it with vim? the goal here is to have `lf` exit and print the path to the first file that is picked

this is how `vim $(fzf)` works

as a note, there are other ways to open files in vim with lf, but this particular way is important (will be used to add file picker support to my Helix environment)

**Comment by ilyagr** [comment]
Look at the `-seleciton-path` option in `lf -help`.

**Comment by lukepighetti** [comment]
```zsh
function lfp(){
  local TEMP=$(mktemp)
  lf -selection-path=$TEMP
  local PATHS=$(cat $TEMP)
  echo $PATHS
}
```
