### ISSUE TITLE
Where to set environment variables?

### ISSUE THREAD

**Issue by shasherazi** [gokcehan/lf#1124]
I saw this in the `lf` docs:

```
EDITOR
    If this variable is set in the environment, use the same value, otherwise set the value to 'vi' on Unix, 'notepad' in  Windows.
```

I have set my `EDITOR` to `nvim` in my `.zshrc` file but `lf` still tries to open my files with `vi`. Where do I set this variable to `nvim`?

**Comment by DusanLesan** [comment]
I have my variables set in `.zprofile` file but `.zshrc` should be a valid option too. Are you sure you are setting it right or that you have not overwritten the open function? Could you try printing value of editor variable from `lf` to validate it?

**Comment by shasherazi** [comment]
Oh yeah, sorry. I should've explained a bit more. 

I'm running `lf` with `sxhkd` using
```
kitty --class lf -e lf
```
because I have a `bspc rule` that `lf` should open in the second workspace. If I run `lf` manually in a terminal, then the `EDITOR` is correctly set to `nvim`.

Incorrect behavior only happens if I run it via the keyboard shortcut using `sxhkd`. Printing `EDITOR` from within `lf` prints `vi` if started via `sxhkd`.

Might the reason be that `.zshrc` didn't get a chance to get sourced?

**Comment by DusanLesan** [comment]
I do not know what is the issue then. I am starting lf like `_START_LFCD=1 alacritty` and then I have something like this in top of my `.zshrc`. I think that was because I wanted ability to exit `lf` but keep the window
```
if [ "$_START_LFCD" ]; then
	unset _START_LFCD
	lf
fi
```

**Comment by slavistan** [comment]
@shasherazi Here's a guess: Your window manager or desktop environment loads its environment from _~/.profile_, whereas zsh uses _~/.zprofile_ (and _.zshrc_, of course). You thus have two distinct branches of declarations of environment variables.

Now, dependending on _how_ sxhkd is started, one of those two options is chosen:
1. If sxhkd runs as a child process of your zsh login shell, such as is the case if you use `startx`, it will inherit its environment from the zsh-side, i.e. _~/.zprofile_.
2. Desktop environments tend to care about _~/.profile_, but not about _~/.zprofile_, and thus, if your DE is responsible for starting sxhkd, it will inherit the environment defined in _~/.profile_.

The simple solution to this nuisance is to stuff your environment declarations into _~/.profile_, and make _~/.zprofile_ source it. That's the solution I roll with.

**Comment by deepaknegilachu** [comment]
Are u using display manager?

**Comment by slavistan** [comment]
@deepaknegilachu I don't, no. I start my window manager [dwm](dwm.suckless.org) via `startx`.

**Comment by shasherazi** [comment]
For future reference, I ended up using this command to run `lf`
```
alacritty -e zsh -ic lf
```

And I still don't really understand why it was happening

**Comment by slavistan** [comment]
Try `alacritty -e zsh` only and run `env` in that shell to print all environment variables. See what the *EDITOR* var has to say.

**Comment by slavistan** [comment]
Both look good. Can't tell why *$EDITOR* seems to be ignored when you manually run `lf`.

**Comment by shasherazi** [comment]
@slavistan if you are curious enough then let me know if you want to have a call where you can explore more into my setup

**Comment by cstrahan** [comment]
In case others were stumped like myself, see this change: https://github.com/gokcehan/lf/commit/28b550a7ec963b8daccbbcb1cd851ede6af67e83

If the `VISUAL` env var exists, `lf` will replace `EDITOR` with what `VISUAL` is set to.

This is documented like so now:

> EDITOR
>
> If VISUAL is set in the environment, use its value. Otherwise, use the value of the environment variable EDITOR. If neither variable is set, this is set to 'vi' on Unix, 'notepad' in Windows.

**Comment by shasherazi** [comment]
> In case others were stumped like myself, see this change: [28b550a](https://github.com/gokcehan/lf/commit/28b550a7ec963b8daccbbcb1cd851ede6af67e83)
> 
> If the `VISUAL` env var exists, `lf` will replace `EDITOR` with what `VISUAL` is set to.
> 
> This is documented like so now:
> 
> > EDITOR
> > If VISUAL is set in the environment, use its value. Otherwise, use the value of the environment variable EDITOR. If neither variable is set, this is set to 'vi' on Unix, 'notepad' in Windows.

But my `VISUAL` is also `nvim`
