### ISSUE TITLE
What if there was an unmapped built-in command for deletion?

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#113]
In the [Wiki's tutorial](https://github.com/gokcehan/lf/wiki/Tutorial#file-deletion), it is mentioned that:
> lf does not come with an actual file deletion command to avoid accidental file losses.

I understand the idea behind this design choice but I think it has more drawbacks then profits. I've read #45 and I think that from a user point of view, having to look in the documentation in order to learn how to do such a basic operation takes too much energy as a start from the users.

I'd like to suggest a mid point between these two design approaches - create a built-in `:delete` command that won't be mapped. This way it'll be hard for users to actually accidentally delete files with a wrong guess of key mappings.

BTW, the somewhat cumbersome shell commands suggested in https://github.com/gokcehan/lf/issues/45#issuecomment-260407520, and here:

https://github.com/gokcehan/lf/blob/d86e9c991c3426685a70715aacc47548ff7fe9b9/etc/lfrc.example#L56-L63

I'd like to point out these don't work when having multiple files and some of them have spaces and working around this can potentially open security holes when dealing with files with very obscure file names which may contain characters like `$'\n'` or `\`. I think it'll be best for `lf` to handle these internally and provide us with a `:delete` command.

Please correct me if I'm wrong as for the statement above.

Thanks for creating `lf`. It's still so much better then `ranger`, trust me :)

**Comment by gokcehan** [comment]
@doronbehar Commands in the example config assumes `set ifs "\n"` so it should handle file names with spaces although newlines can still be a problem. I'm not sure about `\` characters. I agree it would be easier to handle these internally.

File deletion has become a major pain point. Lately I have come to agree that "sharp tools" approach might be a better approach for `lf` much like shells. Another similar issue is the use of `-i` flag for `cp` and `mv` to not overwrite existing files with the same name. This is a safe approach but it is rarely desired. Sure it is configurable but defaults should be much more useful.

I will try to add a `:delete` command when I have a chance. We should decide whether it should be a prompting command though I think there is currently no prompting mechanism for builtin commands. If we make it a prompting command, we can even consider mapping it to `<delete>` key by default.

**Comment by doronbehar** [comment]
Thanks for your agreement, will you be willing to accept a PR without a prompt as a start?

**Comment by gokcehan** [comment]
@doronbehar Sure, go ahead.

**Comment by doronbehar** [comment]
First of all, I have no experience at all in go development but I'm willing to give this challenge a `go`. From reading your code:

https://github.com/gokcehan/lf/blob/6193885a55cbbac9bea54792dc2670242036afcf/os.go#L117-L140

I've noticed you are just calling shell commands for copying or moving the files. I was wondering, why didn't you implement a copy operation, as suggested [here](https://opensource.com/article/18/6/copying-files-go) or [here](https://stackoverflow.com/questions/21060945/simple-way-to-copy-a-file-in-golang) and a [`os.Rename`](https://godoc.org/os#Rename). This could bring more consistency with the up coming usage of [`os.Remove`](https://godoc.org/os#Remove).

**Comment by gokcehan** [comment]
@doronbehar I did not implement a copy operation for the same reason they don't include a copy operation in golang standard library as discussed [here](https://go-review.googlesource.com/c/go/+/1591). I have not tried to implement such a function myself but from what I know there are many corner cases to consider like properly handling links, file permissions, owners or different file types like sockets ans such, and these are mostly operating system dependent so it is not easy to test. It was one of my longer term plans to work on this maybe as a separate library so others can help to make it portable but I have not found a chance to work on this yet. I remember there were a few libraries for this purpose but they were not properly maintained. Maybe there are now some more.

This is also relevant to #61 to display the progress of copy operations.

**Comment by doronbehar** [comment]
Thanks for the links, I understand better now the various complications and considerations. In [agreement with @dumblob](https://github.com/gokcehan/lf/issues/61#issuecomment-282549816) think you've chosen rightly to use `cp` and `mv` for the paste command but I'd say this should be more configurable for users who want a progress bar with rsync or `cp` and `mv` with `-i` (or even [`-g`](https://github.com/atdt/advcpmv)). 

What if instead of the current `pasteCommand` in [`os.go`](https://github.com/gokcehan/lf/blob/6193885a55cbbac9bea54792dc2670242036afcf/os.go#L117-L140) and [`os_windows.go`](https://github.com/gokcehan/lf/blob/6193885a55cbbac9bea54792dc2670242036afcf/os_windows.go#L92-L117) we would use default values for a `cmd paste` (different for every OS) and this command would know to read a list of files separated by default in this command with `filesep` set to `\0`. My opinion is that it'd bring a much more consistent and safer overall design for `lf`. Not to mention of course the advantages of this design in comparison to ranger with all of it's slow pythoness.. `lf` will just use the shell, as in a truly Unix philosophically designed software.

**Comment by gokcehan** [comment]
@doronbehar I'm not sure I understand your suggestions. You mean instead of functions in the code we should define a default `paste` command with shell syntax? What would be the advantage of this approach?

Please note that it is currently already possible to define a custom `paste` command with a different behavior. There are a few examples in [tips](https://github.com/gokcehan/lf/wiki/Tips) wiki page.

Lastly, as far as I remember `filesep` can't be set to `\0` since variables in shell can't have the null character, hence the use of `\n` value as the default.

**Comment by doronbehar** [comment]
Sorry for the late reply, I've been thinking about it for a while.

> You mean instead of functions in the code we should define a default `paste` command with shell syntax?

Yes.

> What would be the advantage of this approach?

After reading and considering what's written in the WiKi and in #61, I guess there isn't very much that should be done in regard to the copy and paste operations. How ever, I would summarize in regard to our original discussion as for a *delete* command, that we should leverage [`os.Remove`](https://godoc.org/os#Remove) for that task.

I'll try to craft something when I'll find the time, thank you for your time.

**Comment by doronbehar** [comment]
@gokcehan , I've pulled the latest version today and I saw that the `os.Remove` was used to create a builtin `delete` command that can be bind, it works great. Would you like to close this issue or keep it open for tracking the implementation of builtin `copy` and `move` commands?

**Comment by gokcehan** [comment]
@doronbehar Ah yes, I almost forget we had an issue to track this. You're right, `delete` is added in #121 a few weeks ago. Still I think it is would be better to keep this issue open to track prompting mechanism and the implementation of a built-in copy and move operations as you say. I will probably make a new release later today and then I'm planning to work on these things in the upcoming days.

**Comment by gokcehan** [comment]
Prompting has been added to the `delete` command and builtin copy and move operations are now implemented which is available in `r11`. Closing this issue now.
