### ISSUE TITLE
[Q] browse on server

### ISSUE THREAD

**Issue by tuyenpm9** [gokcehan/lf#114]
Similar to `winscp` on windows, using a secure protocol to surf for files on remote system, this is critical for system admin and maybe operations that deal a lot with remote servers.

Is there integration for this to work?

**Comment by tuyenpm9** [comment]
Doesn't concern about lf itself, closed.

**Comment by gokcehan** [comment]
@tuyenpm9 I have been using [sshfs](https://github.com/libfuse/sshfs) happily for those needs for quite some time. It does not need any integration on the lf side. There are also other fuse file systems for many similar things these days.

**Comment by tuyenpm9** [comment]
@gokcehan: Thanks I adapted sshfs but I have a question that not answered, in winscp we still can surf all files and folder that the `user` has `x` permission to surf through but with mount technique you have to mount under a specific owner, e.g: called `root` because we want to surf throught probably has owner `root:root`, use `sudo` and mount under `root` means you have all permissions on that mounted folder and `have` to take more caution to act on, the thing here we just want to take a visual review contents of folder and what files are under in, less action on it but mount under root is overkill for some simple check task, also I find sshfs pretty slow when using fuse, uncomparable to `winscp`. I am somehow just need this for work task before a switch for transparency between work and home.

**Comment by gokcehan** [comment]
@tuyenpm9 I'm not sure I understand what you mean exactly but I think what you mention is possible. I'm able to mount a remote directory using `sshfs` on somewhere in my home folder without using `sudo`. On my machine, it shows the user's id instead of its name when I use `ls -l` but apart from this permissions work as expected. Whichever remote user you used when mounting with `sshfs` is the active one used for permissions.

Regarding the performance, I can't say much about it. I have never used `winscp` so far so I don't know how `sshfs` compares to it. On my machine, there are times when `sshfs` feels slower to me as well especially on poor wireless connections.

**Comment by tuyenpm9** [comment]
I mean you have to `sudo` to use `sftp-server` that need to be `root` on remote, so you have that mouted folder as root on remote server and have all permission.

Can't use `sftp-server` without `sudo` on folder that own by `root`.

**Comment by gokcehan** [comment]
@tuyenpm9 Is `sftp-server` different than `sshfs`?

You should be having a regular user on remote other than `root` to be able to mount without root permissions. The way I use it is as follows for a machine named `remote` with a regular user named `user`:

    sshfs user@remote: ~/remote

If you only have a `root` user on the remote machine then this does not work. Anyway, I'm no expert on this anyway. I think there might be better guides on the internet.

**Comment by tuyenpm9** [comment]
Problem is that, we can't mount as normal user, must sudo, this somehow as designed and we can't change in current setup of remote servers. Kind of legacy.

`Winscp` somehow does this, because `o` perm of any user still can surf through directory (default linux umask is `022`) so `scp` be able to do that without mouting. It's kind of offtopic here, anyway good talk :)
