### ISSUE TITLE
move parent directory

### ISSUE THREAD

**Issue by jackielii** [gokcehan/lf#1142]
Just switched from ranger. I used to use `[` or `]` to move parent directory up & down. Is this possible in lf?

**Comment by Nehctarg** [comment]
Yes just write 
```
map [ updir
map ] open
```
in the config file

**Comment by ilyagr** [comment]
I think the following is closer to what was asked for:

```
map { :updir; up; open
map } :updir; down; open
```

I used `{}` because `[]` are already bound, but you're welcome to use `[]` instead.

This has some limitations, since a file is after the parent dir, this will open the file. I'm not sure if there's an easy way to work around that.

**Comment by joelim-work** [comment]
BTW this has been asked a few times before:

- https://github.com/gokcehan/lf/pull/242#issuecomment-544622214
- https://github.com/gokcehan/lf/pull/759#issuecomment-1060389915
- https://github.com/gokcehan/lf/discussions/773

I have added an [example](https://github.com/gokcehan/lf/wiki/Tips#move-to-nextprevious-sibling-directory) to the wiki, so I think this issue can be closed.

**Comment by jackielii** [comment]
Thanks! the wiki link is very useful!
