### ISSUE TITLE
Change directory on exit - but on windows?

### ISSUE THREAD

**Issue by reDpz** [gokcehan/lf#1147]
I'm using git bash on windows and I installed lf with the choco package manager.
Followed instructions on tutorial but instead of placing lfcd.sh in ~/.config/lf/ i placed it in appdata/local/lf/ then changed .bashrc with that location as the location of the lfcd.

But it doesnt exactly seem to work so maybe its an os thing or maybe im just stupid idk one of the 2.

**Comment by joelim-work** [comment]
You have to ensure the `lfcd` function is defined in your `.bashrc` file, either by copying the contents of `lfcd.sh` into your `.bashrc` or by using the `source` command. This is explained in the comments: https://github.com/gokcehan/lf/blob/dddf437c42a5e61afefaae6bb39f0c484cd2f0e0/etc/lfcd.sh#L3-L4
