### ISSUE TITLE
Icons and Colors documentation missing

### ISSUE THREAD

**Issue by madrigal1** [gokcehan/lf#1157]
### Discussed in https://github.com/gokcehan/lf/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **madrigal1** March 15, 2023</sup>
Its very hard to understand how to setup icons and colors. the wiki is completely missing all this info.
if someone could restore the old icons docs would be great</div>

**Comment by gokcehan** [comment]
@madrigal1 Is there a reason for duplicating all your issues as discussion as well?

**Comment by madrigal1** [comment]
No it's started off as a discussion and i thought it would add appropriate to add the issue. Anyways thanks for resolving this issue. Will close it.
