### ISSUE TITLE
custom preview for the powershell

### ISSUE THREAD

**Issue by PavelMikuMr** [gokcehan/lf#1165]
Hi, there ! I would like to set up a custom preview inside PowerShell like this 
`case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l   ##"$1";;
    *.rar) unrar l "$1";; /
    *.7z) 7z l   ##"$1";;
    *.pdf) pdftotext "$1" -;;
    *) highlight -O ansi "$1";;
esac`  I lack the knowledge of how to implement it. Does anyone have any ideas? /

**Comment by PavelMikuMr** [comment]
If you are like me looking for a solution, I made something that works . I put `set previewer D:\\scripts\\preview.bat` in my `lfrc`
and set its content to the following 
```
@echo off
set item=%1 
IF not x%item:.md=%==x%item% (
	glow %1 -s dark
) ELSE IF not x%item:.7z=%==x%item% (
	7z l %1 | bat
) ELSE IF not x%item:.zip=%==x%item% (
	unzip -l %1 | bat
) ELSE IF not x%item:.rar=%==x%item% (
	unrar l %1 | bat
) ELSE (
	bat --color=always %1
)
```

**Comment by gokcehan** [comment]
@PavelMikuMr Unfortunately I'm not good with powershell either but thanks for coming up with a solution. If you think it can also be helpful for other users, feel free to add it somewhere appropriate in the wiki pages so it won't get lost in here. Closing this issue now.
