### ISSUE TITLE
File permission changes are not reloaded when using period 

### ISSUE THREAD

**Issue by bluesuncat** [gokcehan/lf#1172]
When the period option is used, file changes will be refreshed within the specified time interval.
This works well with changed file names, but for some reason it does not work for permissions.

To reproduce:

1. run lf
2. change the permissions of a file by running chmod in a terminal
3. move to the changed file: The permissions displayed in lf will be the old ones and dont include the changes

When I run reload manually, the file information is updated correctly but that should also happen automatically when the period option is used.

**Comment by bluesuncat** [comment]
Related issue: https://github.com/gokcehan/lf/issues/776

It looks to me like the load function does not update some of the file information like the reload function does.
Is there a reason why this is different? I'm also not quite sure where the related code is located, perhaps someone could point it out to compare how the two functions do things differently

**Comment by gokcehan** [comment]
@bluesuncat I think you can take a look at the evaluation of `load` and `reload` in `eval.go` to see how they work under the hood. From the top of my head, it is likely that permission change of a single file does not update the modification time of the directory so it does not read the directory again. In a way, this is considered working as intended, because if `period` option would trigger `reload` instead of `load`, then the program would always be in a loading state somehow. To get around this issue, I think I have seen people using a custom commands for changing permissions with an explicit reload after change.

**Comment by bluesuncat** [comment]
There was a decision a while back https://github.com/gokcehan/lf/issues/73 to implement the period option instead of using [fsnotify](https://github.com/fsnotify/fsnotify) due to concerns regarding its future maintenance. The project seems to be maintained and stable as of today, so I am wondering if that is something to be reviewed again, at least as an optional dependency.

Perhaps there are other alternatives that have been added to the Go standard library as well? I'm not too familiar with it though.

**Comment by gokcehan** [comment]
@bluesuncat I try to be more inclusive towards patches these days but I think my personal stance on this has not changed much. Let me know if there is something in the Go standard library about this. Othewise, I still assume this is a solution that is difficult to maintain. Sure, we have many contributors these days, but most often they submit patches that is only tested on their own systems. This may not work well in practice with non-portable things such as this one. From looking at the repository, fsnotify still seem to be on constant change. Also it says in the repo:

> As a rule, it's typically best to ignore Chmod events. They're often not useful, and tend to cause problems.

So even if we use fsnotify, we may not be able to use chmod events to solve this issue.

**Comment by bluesuncat** [comment]
I may have found a solution for some cases at least.
One of the most common use cases where this issue is relevant, is when using the shell command inside lf for file operations.

Example:
1. use lf to navigte to a file
2. execute file operations on the shell, including changing a files permissions
3. quit the shell, returning to lf

In this example, right now lf would show the incorrect file permissions.

However, we could just run reload when the shell inside lf is quit to fix this.
