### ISSUE TITLE
Zsh integration without tmux

### ISSUE THREAD

**Issue by octaskin** [gokcehan/lf#1178]
Hey,

I was checking out how I could [integrate lf as file picker to zsh](https://github.com/gokcehan/lf/wiki/Integrations#zsh-file-picker--directory-changer) on the wiki added by @cruegge. Which is based on the user being on tmux. 
As suggested I tried to adopt it to my setup (foot) to no avail.

More concretely,
```zsh
tmux split -bf zsh -c "exec {ZLE_FIFO}>$d/fifo; export ZLE_FIFO; exec lf"> || return 1
```
line needs to prompt for foot instead. In my newbie attempt with
```zsh
foot "exec {ZLE_FIFO}>$d/fifo; export ZLE_FIFO; exec lf"> || return 1
```
I get the following
```zsh
 err: slave.c:406: exec {ZLE_FIFO}>/tmp/tmp.FzXiPOMFod/fifo; export ZLE_FIFO; exec lf: failed to execute: No such file or directory
 err: fdm.c:215: no such FD: 6
```
I can't say I was able to follow the logic of ZLE_FIFO around the script that needs to be added to lfrc as well, probably due to my limited understanding of the concepts. 
I would highly appreciate if someone can help out.

**Comment by cruegge** [comment]
Foot doesn't run the command in a shell, so you probably only need to replace `foot "(...)"` by `foot zsh -c "(...)"`.

Also, is the `>` after the closing quote a copy-paste error?

**Comment by octaskin** [comment]
> `foot "(...)"` by `foot zsh -c "(...)"`.
I tried this one already but to make sure I do it again. The current
_zlf function at my .zshrc becomes:
```zsh
 _zlf() {
    emulate -L zsh
    local d=$(mktemp -d) || return 1
    {
        mkfifo -m 600 $d/fifo || return 1
        foot zsh -c "exec {ZLE_FIFO}>$d/fifo; export ZLE_FIFO; exec lf" || return 1
        local fd
        exec {fd}<$d/fifo
        zle -Fw $fd _zlf_handler
    } always {
        rm -rf $d
    }
}
```
When I execute it, I indeed get a new foot window albeit with nothing on
it, not even my prompt.

The parent terminal has some unrelated info logs, about font and sway
but no errors.

> Also, is the `>` after the closing quote a copy-paste error?
Yes! Sorry for that, I was copying it over from an e-mail.

**Comment by cruegge** [comment]
Ah, I remember, you need to replace the `|| return 1` by `&!`. The terminal needs to fork, otherwise it will be deadlocked waiting for the fifo.

**Comment by octaskin** [comment]
> Ah, I remember, you need to replace the `|| return 1` by `&!`. The
> terminal needs to fork, otherwise it will be deadlocked waiting for
> the fifo.
Alright! That actually gets the lf running. And it is totally one me
since you mentioned this on the wiki. I was ignorant enough to wrongly
place the `&!` in the beginning and then I removed it.

Now I can proceed to try
```sh
$ xdg-open <press alt+k>
```
But this time lf doesn't get my key bindings. ` unknown mapping: a `

My lfrc is just 4 lines:

```conf
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id
```
+ the snippet you provided for lfrc.

**Comment by cruegge** [comment]
I saw in your dotfiles repo that your `/bin/sh` is a link to `dash`. Dash doesn't support `[[ ... ]]` conditionals, so you need to replace the double brackets in the last line of the lfrc snippet by single brackets.

**Comment by octaskin** [comment]
That works finally, thanks for the help! 
The foot doesn't exit at the end, I guess I need to get the pid of the foot terminal somehow and kill it after the line
```zsh
zle -Fw $fd _zlf_handler
```
I guess the fifo there is doing smth similar so it should be possible without too much addition but tbh idk.

**Comment by cruegge** [comment]
At what point do you want it to exit? The snippet is written in a way that the terminal stays open until you explicityly quit lf, allowing you to add multiple files to the prompt, editing the prompt in between, or even using it on multiple prompts. If you want to quit after pressing e.g. `a`, you can add `lf -remote "send $id quit"` after the for-loop in `zle-insert-relative`.

**Comment by octaskin** [comment]
That is great to know! All my questions are covered, thanks @cruege.
