### ISSUE TITLE
I have idea, all line make the number and use vim keyboard

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1182]
![image](https://user-images.githubusercontent.com/87791643/228575391-604d6b86-4e95-4539-9a08-a7607563262c.png)

use all line  set relate number and use vim key board to jump it

like 10+j ,or 12+k 
like this

**Comment by ilyagr** [comment]
I'm not sure I understood the question, but perhaps you're looking for the `relativenumber` option? Try `set relativenumber`.
