### ISSUE TITLE
lfrc and environment variable (like $GOPATH)

### ISSUE THREAD

**Issue by davmaz** [gokcehan/lf#119]
I'd like to add a command in the lfrc to "goto" the $GOPATH.
I can't find any examples of using external (shell) variables, like GOPATH, inside lfrc.
What am I missing?

**Comment by TeddyDD** [comment]
You can do this from shell scope
```
# example mapping
map g G ${{
    lf -remote "send $id cd $GOPATH"
}}
```

**Comment by davmaz** [comment]
That works perfectly! Wow.
