### ISSUE TITLE
i set nvim to open json file  defualt , but it not work

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1191]
![image](https://user-images.githubusercontent.com/87791643/229405278-5ec33979-a850-403e-8b50-23e28e9ea9ee.png)
![image](https://user-images.githubusercontent.com/87791643/229405316-e1105207-a086-4f7d-bf1d-377bd8c2c646.png)

I use two way but it not work,
the json file always open in firefox

**Comment by joelim-work** [comment]
The correct MIME type for JSON files is `application/json`

**Comment by joelim-work** [comment]
@newyorkthink Does JSON files work for you now? I saw you moved onto JS files in #1195. 

If this is working for you, then please close this issue. Otherwise it is hard for others to determine what issues actually do need addressing.

**Comment by ilyagr** [comment]
Yes, I think this should be discussed as part of #1195. If anyone can solve the javascipt problem, that will probably also solve the json problem.
