### ISSUE TITLE
i set nvim to open js file defualt , but it not work

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1195]
![image](https://user-images.githubusercontent.com/87791643/229715724-afbcfd81-0ad1-48ad-bbb6-90c69cda1de1.png)
is not workin

**Comment by og900aero** [comment]
Because js file is javascript. The correct mime type is text/javascript. The js is not mime types, but extension. The two are not the same.

**Comment by ilyagr** [comment]
Good catch, @og900aero. OTOH, I think more might be going on here. On my machine (Debian stable), `file` has trouble recognizing Javascript, at least for some random `js` files I threw at it:

```
$ file --mime -Lb dev/libapps/hterm/js/hterm_notifications_tests.js
text/plain; charset=us-ascii
```

So, it might be pretty hopeless. Or perhaps some package can be installed to make it smarter?

**Comment by og900aero** [comment]
> Good catch, @og900aero. OTOH, I think more might be going on here. On my machine (Debian stable), `file` has trouble recognizing Javascript, at least for some random `js` files I threw at it:
> 
> ```shell
> $ file --mime -Lb dev/libapps/hterm/js/hterm_notifications_tests.js
> text/plain; charset=us-ascii
> ```
> 
> So, it might be pretty hopeless. Or perhaps some package can be installed to make it smarter?

Yes. The mime types is very tricky on Debian stable too, so at the beginning, I also wanted to solve the opening in the same way, then I preferred to stay with the extensions

[case "$f" in
		*.jpg|*.JPG|*.jpeg|*.gif|*.png|*.heic) 
			imv-x11 -n "$fx" "$PWD" ;;
		*.flac|*.mp3|*.wav|*.dsf|*.ogg|*.ac3|*.ape)
			mpv "$fx" ;;
		*.mkv|*.mp4|*.avi|*.mpg|*.flv|*.mpeg|*.vob|*.3gp|*.wmv|*.m4v|*.asf|*.ts|*.mts|*.webm|*.mov)
			mpv "$fx" ;;
		*.xlsx|*.docx|*.pptx|*.doc|*.xls|*.ppt|*.rtf|*.odt)
			libreoffice "$fx" ;;
		*.pdf|*.htm|*.html)
			google-chrome-stable "$fx" ;;
		*.tar.bz|*.tar.bz2|*.tbz|*.tbz2|*.tar.gz|*.tgz|*.tar.zst|*.tar.xz|*.txz|*.zip|*.rar|*.iso)
			mkdir -p "$fx.temp"
			archivemount -o readonly "$fx" "$fx.temp"
	    	lf -remote "send $id cd \"$fx.temp\""
	    	lf -remote "send $id reload"
	    	;;
		*.AppImage)
			"$fx" ;;
	    *)
	        for f in $fx; do
	        	$EDITOR $f
	        done;;
	 esac](url)

**Comment by joelim-work** [comment]
Even if the file type resolves as `text/plain`, this should have been picked up by the `text/*` pattern in the configuration provided in the issue description.

@newyorkthink To figure out this kind of issue, you need to identify what type these files actually are by running `file` yourself:

```shell
file --mime-type /path/to/file
```

**Comment by ilyagr** [comment]
You can also use `xdg-mime query /path/to/file` to find out how `xdg-open` sees it, and `xdg-mime query default MIME_TYPE` (e.g. `xdg-mime query default application/javascript`) to see how it will open those kinds of files.

Both of these commands have a `--manual` option as well.
