### ISSUE TITLE
How to install lf latest version on Debian stable

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1202]
I try install the latest verison from source on Debian 11 Stable, but I get error message:

sudo apt install -y golang
sudo env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
Error: **"package github.com/gokcehan/lf@latest: cannot use path@version syntax in GOPATH mode"**

**Comment by ilyagr** [comment]
Try the following:

- Remove the golang package you installed; `sudo apt remove golang`.
- Install the [backports repo](https://backports.debian.org/Instructions/).
- `sudo apt update && sudo apt install -t bullseye-backports golang-1.19`
- Then try `sudo env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest` again.

**Comment by ilyagr** [comment]
Aside: it might help others if you insert "Debian stable" in the title of the bug.

**Comment by og900aero** [comment]
> * sudo env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

I try, but I get error message: env: ‘go’: No such file or directory
When I search go command, and not found.

**Comment by ilyagr** [comment]
This is strange, I didn't have this problem.

First try opening a fresh new terminal or logging out and back in. It's possible that there's some environment issue or some old `go` binaries still running in the system.

Try replacing `go` with `/lib/go-1.19/bin/go` in the command to install `lf`.

Also, try `sudo apt install -t bullseye-backports golang-go`. That's the package that contains `/usr/bin/go` on my system.

**Comment by og900aero** [comment]
> Try replacing go with /lib/go-1.19/bin/go in the command to install lf.

> Also, try sudo apt install -t bullseye-backports golang-go. That's the package that contains /usr/bin/go on my system.

Both methods work. This way env CGO_ENABLED=0 /lib/go-1.19/bin/go install -ldflags="-s -w" github.com/gokcehan/lf@latest and env CGO_ENABLED=0 go install -ldflags=" -s -w" github.com/gokcehan/lf@latest. In fact. There is no feedback that it has good result, it does not display anything. 
╭─shyciii@debian ~
╰─$ sudo env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
╭─shyciii@debian ~
╰─$

If I search for it with the which lf command, it does not find the lf command, and thus cannot be started.

**Comment by og900aero** [comment]
Ohh. It instaled /root/go/bin. So I moved to /usr/bin/local, and work flawessly. Thank u!
