### ISSUE TITLE
XDG_CONFIG_HOME doesn't seem to be working on windows

### ISSUE THREAD

**Issue by alok-mishra** [gokcehan/lf#1209]
My XDG_CONFIG_HOME environment variable is set to: C:\Users\<user>\.config

But lf isn't recognizing lf\lfrc inside the .config directory.

Other programs like neovim (nvim) use this environment variable just fine

Or is this always set to C:\Users\<user>\AppData\Local\lf\lfrc , if so, can we allow looking up XDG_CONFIG_HOME on windows?

Thanks

**Comment by gokcehan** [comment]
@alok-mishra On windows, I think we use the variable `LOCALAPPDATA` which by default is `C:\Users\<user>\AppData\Local` but you should be able to change it.

**Comment by alok-mishra** [comment]
Yes, but that variable is used by a lot of other windows programs, so it really can't be changed. I was trying to keep a separate .config directory just for my terminal apps, which can also be shared on linux, or can be accessed via msys2 or git bash via ` ~/.config`.

If this can't be done via a `XDG_CONFIG_HOME`, on windows, I understand.

**Comment by gokcehan** [comment]
@alok-mishra Wouldn't it be strange to use an XDG variable on Windows? In any case, I think there might be ways to do this without any change. For example, there might be a way to only set `LOCALAPPDATA` variable for `lf` (e.g. `env LOCALAPPDATA=$HOME/.config lf`). If not, maybe you could utilize symlinks for this purpose. Or maybe you could have a file with only a single line `source ~/.config/lf/lfrc` in the usual directory. To be honest, I would rather not complicate things further if there is already a way to achieve this.

**Comment by alok-mishra** [comment]
@gokcehan Yes, it does seem strange, although neovim uses it so I figured maybe it can be done here also.  
 I'll try your suggestion to see if I can use the LOCALAPPDATA variable only for lf, that's a good idea.
 Thank you, I'll close this now. Please reopen if you decide we could do something different i.e. even have a completely separate environment variable i.e. `LF_HOME`  like some other tools do.   If you do, then I can help with it if you like me to. Thanks!

**Comment by gokcehan** [comment]
@alok-mishra Sorry for late reply.

I should note that I'm not completely against this change. I'm only slightly worried that this might confuse some users if they have an accidental `XDG_CONFIG_HOME` variable setting without realizing it. A seperate variable for lf also sounds reasonable if you find it useful for your case. We have a command line parameter `lf -config ...` but that currently does not work with other configuration files (i.e. colors and icons). In any case, I don't see any downside to add a separate variable for this purpose. If we agree on the separate variable, I think we should name it `LF_CONFIG_HOME` just in case we add other corresponding variables `LF_DATA_HOME` and `LF_RUNTIME_DIR` later on.

I'll reopen the issue. Feel free to submit a PR if you have a patch ready so it becomes more visible to others.
