### ISSUE TITLE
using "map i $bat $f"  makes bat show up and exiting shouldn't the use of "$" make it stay in the screen 

### ISSUE THREAD

**Issue by yogeshdcool** [gokcehan/lf#1215]
I'm trying to replace less with bat

**Comment by ilyagr** [comment]
You probably have something (`$LESS` or `$PAGER`, for example) that gives `less` the `-F` AKA `--quit-if-one-screen` option. `bat` actually uses `less` for paging.

You can replace `$bat` with `!bat`, in which case it'll stay on screen, but will also prompt for a key unnecessarily sometimes. Or, you can clear the `$LESS`/`$PAGER` setup either globally or in `lfrc`.

I'm having a similar problem; if somebody has a more elegant solution I'd appreciate it.

**Comment by yogeshdcool** [comment]
> you can clear the `$LESS`/`$PAGER` setup either globally or in `lfrc`.

can you tell me how should I change a environment variable it in lfrc?

**Comment by yogeshdcool** [comment]
After some searching This worked fine for me
`map i $bat $f --pager="less -R"
`

**Comment by ilyagr** [comment]
Yes, on second thought I'm not sure that what I originally suggested is easily doable. So, what you did is probably as good as it gets.

I was also going to suggest the pretty much equivalent `map i $LESS=R bat $f`
