### ISSUE TITLE
bind ; to :

### ISSUE THREAD

**Issue by reDpz** [gokcehan/lf#1217]
I want to use semicolon enter command mode, I've tried

```
map ";" ":"
```
But I get `command not found: :` (guessing this means its trying to execute the : command rather than just inputting it)

**Comment by reDpz** [comment]
also there are red asterisks next to some of my folders and I got like no clue why, does anyone know how to get rid of them?
![image](https://user-images.githubusercontent.com/71374038/234695111-44be8a96-4d5a-4725-921e-9e1f764e9d57.png)

**Comment by joelim-work** [comment]
Use the `push` command to simulate keypresses:

```
map ; push :
```

---

The red asterisks are tags, which can be toggled using the <kbd>t</kbd> key. Tags are just visual markers that you can assign to files/directories.
