### ISSUE TITLE
the lf wiki "Select all files or directories in the current directory"  have problem 

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1228]
![image](https://user-images.githubusercontent.com/87791643/236594950-97ccac25-3134-4f95-8e1d-753faf41836d.png)

when i select have chinese font or other country font, the script is not work

it just select the english font file
![image](https://user-images.githubusercontent.com/87791643/236595032-ce8aa7cf-868c-4b9f-8d10-392620e408ea.png)

**Comment by joelim-work** [comment]
This has nothing to do with Chinese characters. If you look at the error message at the bottom, you'll find that only the last part of the filename is being passed to `lstat`, which means the script doesn't handle filenames with spaces properly.

I have fixed the script, it now looks like this:

```
cmd select-files ${{
    { echo "$fs"; find -L "$(pwd)" -mindepth 1 -maxdepth 1 -type f; } |
        if [ "$lf_hidden" = "false" ]; then
          # remove any hidden files so you only select files you can see.
          grep -v '/\.[^/]\+$'
        else
          cat
        fi |
        sed '/^$/d; s/ /\\ /g' | sort | uniq -u |
        xargs -d '\n' -r -I{} lf -remote "send $id toggle {}"
}}

cmd select-dirs ${{
    { echo "$fs"; find -L "$(pwd)" -mindepth 1 -maxdepth 1 -type d; } |
        if [ "$lf_hidden" = "false" ]; then
          grep -v '/\.[^/]\+$'
        else
          cat
        fi |
        sed '/^$/d; s/ /\\ /g' | sort | uniq -u |
        xargs -d '\n' -r -I{} lf -remote "send $id toggle {}"
}}
```

**Comment by joelim-work** [comment]
Actually I decided to reimplement this to make it easier, this is the final version:

```
cmd select-files ${{
    if [ "$lf_hidden" = 'false' ]; then
        find "$PWD" -mindepth 1 -maxdepth 1 -type f -not -name '.*' -print0
    else
        find "$PWD" -mindepth 1 -maxdepth 1 -type f -print0
    fi |
    sed 's/ /\\ /g' |
    xargs -0 -I{} lf -remote "send $id toggle {}"
}}

cmd select-dirs ${{
    if [ "$lf_hidden" = 'false' ]; then
        find "$PWD" -mindepth 1 -maxdepth 1 -type d -not -name '.*' -print0
    else
        find "$PWD" -mindepth 1 -maxdepth 1 -type d -print0
    fi |
    sed 's/ /\\ /g' |
    xargs -0 -I{} lf -remote "send $id toggle {}"
}}
```

**Comment by newyorkthink** [comment]
is work 
awesome !!!!!!!!!!!!!!!!

**Comment by joelim-work** [comment]
@newyorkthink I'm glad this is working for you now 👍 

Would you mind closing this issue if it's resolved? It makes it much easier for others to see what issues are actually outstanding. Normally I would do this myself , but I don't have permission - I believe only the person who raised the issue or the project owner has permission.

**Comment by newyorkthink** [comment]
> @newyorkthink I'm glad this is working for you now +1 @newyorkthink 我很高兴这现在对您有用 +1
> 
> Would you mind closing this issue if it's resolved? It makes it much easier for others to see what issues are actually outstanding. Normally I would do this myself , but I don't have permission - I believe only the person who raised the issue or the project owner has permission.如果此问题已解决，您介意关闭此问题吗？它使其他人更容易看到哪些问题实际上是悬而未决的。通常我会自己做，但我没有权限 - 我相信只有提出问题的人或项目所有者有权限。

ok
