### ISSUE TITLE
what is the purpose of nav.saves

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [gokcehan/lf#123]
the variable (which is a hash map) is initialized at `newNav`
and re initialed again every time `save` and `sync` are called (both at the `nav.go` file)
and they are never used

is there a planned use for them (or past use) why are they there and should they be removed

**Comment by gokcehan** [comment]
@Kallinteris-Andreas It is used in `ui.go` to mark files in cut/copy buffer properly. You can check `win.printDir` function to see how this works. Closing this issue now.
