### ISSUE TITLE
[help] how to go back in jump history like vim?

### ISSUE THREAD

**Issue by lucasmsoares96** [gokcehan/lf#1231]
in vim we have the <C-O> and <C-I> keybindings that allow us to easily go back and forward in the jump history of the course. Given that lf jumps are done by directories, how do I go back and forward to previously accessed directories?

**Comment by joelim-work** [comment]
Jumps are mentioned in the documentation, is this what you are looking for?

https://github.com/gokcehan/lf/blob/f04401ba4d43f21a084e603a52cf20f80b0c437d/doc.go#L30-L31

**Comment by lucasmsoares96** [comment]
That's exactly it. Thank you very much.
