### ISSUE TITLE
should a :open_with builtin command be implemented 

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [gokcehan/lf#124]
the main reason i am posting this issue is to ensure that no 2 people are working on the same thing

planned default key binding r (same as ranger mapped from `vi`)

**Comment by gokcehan** [comment]
@Kallinteris-Andreas You can define an `open_with` command with something like:

    cmd open_with $$1 $f
    map r push :open_with<space>

Is there a reason you are adding this as a builtin?

**Comment by Kallinteris-Andreas** [comment]
well if there is no need for it i can close the issue

**Comment by Kallinteris-Andreas** [comment]
does the solution proposed above handle something with arguments like

``

**Comment by Kallinteris-Andreas** [comment]
1) well then there is no need for it to be built it
2) it is kinda of ugly that case "open" has 20+ lines in it
