### ISSUE TITLE
[Regression] bottom not working

### ISSUE THREAD

**Issue by avidseeker** [gokcehan/lf#1241]
In `lfrc`:
```
map , bottom
```
Pressing comma has the effect of `top` instead of `bottom`.

This is caused after the new update v29.

**Comment by gokcehan** [comment]
@avidseeker This is a duplicate for #1239 and the fix is merged a few hours ago in #1240. Closing this issue. Thanks for reporting.

**Comment by joelim-work** [comment]
@avidseeker As a temporary workaround you can use `map , push G`. But I think this is rather hacky and would be better to have the fix released.

@gokcehan Do you normally have a rule for when releases are scheduled? Looking back at the past few releases, it seems to be about once every six months. I guess you want to give new changes some time for them to stabilise, but half year does seem like a long time to wait for bug fixes.

**Comment by gokcehan** [comment]
@joelim-work I don't have a rule for the release schedule. There have been times I have pushes a new release with only a few changes when there are important bug fixes especially if the bug prevents users from upgrading. I guess we can make a new release with the fix #1240. I'm also not too happy that the disk free patch broke the builds on some platforms. I will pause PRs for the next couple of days just to be sure and then I can make a new release.
