### ISSUE TITLE
I have question, when i selected file , how can show the total file size 

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1245]
![image](https://github.com/gokcehan/lf/assets/87791643/e14a1fcd-6725-457d-b534-4719a5bea329)

![image](https://github.com/gokcehan/lf/assets/87791643/b86b0798-f4b4-49cb-8b01-87b1f7fe0a6d)

when i used the wiki script selected file, how can show i selected file title file size.

i means , for example
i selected three file , how can i show three file total (sum) size ,

**Comment by joelim-work** [comment]
Displaying the total size of selected files has already been asked before in #1214 

You can turn this into a custom command and call it directly after selecting the files:

```shell
cmd totalsize %du -ch $fx | tail -n 1 | cut -f 1

cmd select-files &{{
    get_files() {
        if [ "$lf_hidden" = 'false' ]; then
            find "$PWD" -mindepth 1 -maxdepth 1 -type f -not -name '.*' -print0
        else
            find "$PWD" -mindepth 1 -maxdepth 1 -type f -print0
        fi |
        xargs -0 printf ' %q'
    }

    lf -remote "send $id :unselect; toggle $(get_files); totalsize"
}}

cmd select-dirs &{{
    get_dirs() {
        if [ "$lf_hidden" = 'false' ]; then
            find "$PWD" -mindepth 1 -maxdepth 1 -type d -not -name '.*' -print0
        else
            find "$PWD" -mindepth 1 -maxdepth 1 -type d -print0
        fi |
        xargs -0 printf ' %q'
    }

    lf -remote "send $id :unselect; toggle $(get_dirs); totalsize"
}}
```

`lf` can become very powerful if you learn how to make use of the shell and script your own custom commands.

**Comment by newyorkthink** [comment]
thank you, you are good 棒棒！！！！
