### ISSUE TITLE
Allow configuring icons for full file basename

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#1249]
Hi,

Currently if we want to set an icon for a file like CMakeLists.txt we have to prefix or suffix it with a glob. For example

```text
*cmakelists.txt         
```

What is the reason for this? We can match a file directly by using an absolute path or a directory by using just the basename and suffixing with a slash there's no way to use the basename with a file without a glob pattern. I think it would make sense to allow matching full file basenames as well so one can configure just:

```text
cmakelists.txt         
```

**Comment by joelim-work** [comment]
The `*` isn't really a glob, it's a marker to indicate that the file basename should be matched exactly. The reason why such a marker is required is to prevent ambiguities with rules for file types, for example `di` means 'directory', and `*di` means a file named 'di'.

Please see #543 for more details.

**Comment by joelim-work** [comment]
Moving the `im.[f.Name()]` to after the file type check still doesn't work, at least not when I tried it. While this works for the case where an executable file is named `di`, the problem is that it won't work for regular files because the file type handling part of the code doesn't check for regular files - `fi` is only used as a fallback at the end.

**Comment by mohkale** [comment]
> the problem is that it won't work for regular files because

Sorry, do you mean it'll only work for regular files? That is if the file is executable the ex icon will take priority over the filename icon?

**Comment by joelim-work** [comment]
Assuming you were planning to change the code to the following, a regular file named `di` will still show up as a directory because of the newly added code, since the fallback to using the `fi` icon happens only at the end.

```go
func (im iconMap) get(f *file) string {
	if val, ok := im[f.path]; ok {
		return val
	}

	if f.IsDir() {
		if val, ok := im[f.Name()+"/"]; ok {
			return val
		}
	}

	var key string

	switch {
	case f.linkState == working:
		key = "ln"
	case f.linkState == broken:
		key = "or"
	case f.IsDir() && f.Mode()&os.ModeSticky != 0 && f.Mode()&0002 != 0:
		key = "tw"
	case f.IsDir() && f.Mode()&0002 != 0:
		key = "ow"
	case f.IsDir() && f.Mode()&os.ModeSticky != 0:
		key = "st"
	case f.IsDir():
		key = "di"
	case f.Mode()&os.ModeNamedPipe != 0:
		key = "pi"
	case f.Mode()&os.ModeSocket != 0:
		key = "so"
	case f.Mode()&os.ModeDevice != 0:
		key = "bd"
	case f.Mode()&os.ModeCharDevice != 0:
		key = "cd"
	case f.Mode()&os.ModeSetuid != 0:
		key = "su"
	case f.Mode()&os.ModeSetgid != 0:
		key = "sg"
	case f.Mode()&0111 != 0:
		key = "ex"
	}

	if val, ok := im[key]; ok {
		return val
	}

	// THIS PART IS NEW ////////////////////////////////////////////////////////
	if val, ok := im[f.Name()]; ok {
		return val
	}
	////////////////////////////////////////////////////////////////////////////

	if val, ok := im[f.Name()+"*"]; ok {
		return val
	}

	if val, ok := im["*"+f.Name()]; ok {
		return val
	}

	if val, ok := im[filepath.Base(f.Name())+".*"]; ok {
		return val
	}

	if val, ok := im["*"+strings.ToLower(f.ext)]; ok {
		return val
	}

	if val, ok := im["fi"]; ok {
		return val
	}

	return " "
}
```

Would you be able to try this (preferably without using any custom icon configurations) and see if you get the same result?

**Comment by gokcehan** [comment]
One thing I can add here is that this is also the way `LS_COLORS` works (e.g. `LS_COLORS='*cmakelists.txt=01;34'`) likely due to the same reason, to distinguish special names, and so far we have mostly kept color and icon configuration consistent.
