### ISSUE TITLE
running shell: exit status 134                                                                                                                                       2/3

### ISSUE THREAD

**Issue by nikinbaidar** [gokcehan/lf#1252]
I have been getting this `running shell: exit status 134` warning when I open `.tex` files from lf with `e` and I close the file to get back to lf. I realize I do have a shell script that runs when I close tex files but I don't want lf to show me these warnings. How can I suppress them?

**Comment by gokcehan** [comment]
@nikinbaidar I think maybe you can manually return zero after the editor command (e.g. `map e $vim $f; return 0`) so it would not show an error.
