### ISSUE TITLE
preview and cleaner scripts don't abide by shell settings

### ISSUE THREAD

**Issue by KaitlynEthylia** [gokcehan/lf#1256]
So I'm trying to create a config that works on both Linux and windows, so i have my shell set to `sh` (via git on windows). However, the paths of the cleaner and previewer scripts are always passed to cmd regardless of what the shell is set to.

**Comment by gokcehan** [comment]
@KaitlynEthylia Why should the choice of shell have an effect on the paths for those options? Can you share a minimal config file to explain what you mean further?

**Comment by KaitlynEthylia** [comment]
@gokcehan Well for example, since im trying to make my config work on both windows and linux, my preview file is a shell script. Windows ignores shebangs so it just tried to run the file based on its extension. If it ends in nothing or .sh it does nothiong. if it ends in .bat it runs it in CMD, etc.

```
lfrc
----
set previewer .../path/to/previewer.bat

set shell sh
set shellflag '-c'
set shellopts '-mue'
```

```
previewer.bat (ver 1)
-------------
#!/usr/bin/env sh
echo "test"
```

This does nothing as # is not the comment syntax in CMD, so it silently errors.

```
previewer.bat (ver 1)
-------------
:: some comment
echo "test"
```

This works just fine, printing "test" in the preview windows
renaming previewer.bat (and changing the lfrc) to `previewer`, `previewer.sh`, or even `previewer.ps1` causes it to error or print nothing, just as it would when run from CMD

**Comment by gokcehan** [comment]
@KaitlynEthylia Options `previewer` and `cleaner` take executables as arguments. They don't consider the option `shell` because they are not interpreted as shell commands. For example, you might as well use a regular executable (e.g. [pistol](https://github.com/doronbehar/pistol)). This is working as intended. I don't understand if you have a proposition here or not.
