### ISSUE TITLE
Wrap Scroll functionality

### ISSUE THREAD

**Issue by mustaqimM** [gokcehan/lf#126]
This is the same as the setting in [ranger](https://github.com/ranger/ranger/commit/2841f7b86b1d464eb5280a9c9e5c29c4f4fda249)

**Comment by TeddyDD** [comment]
I wonder if this couldn't be solved with some kind of hook system where user would be able to define commands that are executed when some predefined events happen. 

That's a topic for separate issue tho.

**Comment by gokcehan** [comment]
@TeddyDD That was also the first thing that came to my mind. But I think this is common and simple enough to be implemented as a separate option. On the other hand, I don't even know where to begin yet when it comes to implementing hooks. So yea maybe a separate issue for hooks :)
