### ISSUE TITLE
r30 version cannot start,error:zsh: segmentation faul

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1260]
![image](https://github.com/gokcehan/lf/assets/87791643/2705b22e-82ef-4093-913b-a5a82153192b)

**Comment by ilyagr** [comment]
Just to double-check:

Is this using the official r30 amd64 freebsd binary?

Could you check the official r29 binary in the same way?

**Comment by ilyagr** [comment]
Also, what does `uname -a` output?

**Comment by joelim-work** [comment]
For the record I tried [lf-linux-arm64.tar.gz](https://github.com/gokcehan/lf/releases/download/r30/lf-linux-arm64.tar.gz) and [lf-windows-amd64.zip](https://github.com/gokcehan/lf/releases/download/r30/lf-windows-amd64.zip) just now and they seem to be working fine.

Looking at your screenshot it looks like you installed r29 via your distribution's package manager, and then you downloaded a release of r30 that doesn't match your platform. I guess you can also try using `file` (for example `file $(which lf)` to inspect the `lf` binary that you currently have installed.

**Comment by newyorkthink** [comment]
every body i am so sorry , i  selected download error , yes it work.
is my probrem
