### ISSUE TITLE
Feature Proposal: Option to open with a custom geometry

### ISSUE THREAD

**Issue by Javyre** [gokcehan/lf#127]
Hi, I started working on a potential PR for lf to have it open with a custom maximum width and height as well as an `x, y` position.

I'd like to know if you'd be interested in having such a feature as part of your project. 

My approach to implementing this so far:
- having a new `drawableWin` struct holding the `x, y, w, h` of the drawable area that forwards the drawing calls to termbox with the offsets and `w,h` restrictions.
- refactoring direct calls to termbox to be calls to a `drawableWin` instance held in the`UI`

(for example, `drawableWin.Size()` would return the size of the screen but applying the max `w` and `h`)

Of course another approach is tracking and applying the offsets and restrictions everywhere there's a call to `termbox.Size()` or a `termbox` draw function. 

__Edit:__ come to think of it, the existing `win` struct could be extended to be the `drawableWin` that I describe above. Would make the `win` code cleaner as it wouldnt have to be applying offsets everywhere, instead would call its own termbox-wrapping functions

An issue I bumped into is disabling termbox's use of the alternative screen (at least on ANSI terms)

**Comment by Javyre** [comment]
About disabling the use of alternative screen,

This is necessary for being able to draw under the prompt without clearing switching to alternative buffer solely for the app.

Termbox doesnt support toggling this and is hard coded to go to the alternate screen and leave it on `Init` and `Close`:
https://github.com/nsf/termbox-go/blob/0938b5187e61bb8c4dcac2b0a9cf4047d83784fc/api.go#L81
https://github.com/nsf/termbox-go/blob/0938b5187e61bb8c4dcac2b0a9cf4047d83784fc/api.go#L134

I'm not sure what to do here... It might be worth me posting an issue on their repo, but it's obviously not guaranteed they'll do anything. They seem to be very proud of their low amout of api functions...

**Comment by gokcehan** [comment]
@Javyre I'm not sure I understand what you are trying to achieve. Is it like drawing the lf ui right below the current shell prompt? Or is it like a full screen ui with gaps on the sides. If it is the former, then I doubt termbox would be suitable for that. As you said, their api is quite limiting and as far as I know they are mostly in maintenance mode so it is unlikely to add anything to the current api.

Perhaps more importantly, what is the purpose of this patch? What problem you are trying to solve?

**Comment by Javyre** [comment]
@gokcehan 
> Is it like drawing the lf ui right below the current shell prompt?

Yes

> What problem you are trying to solve?

The problem that I want to solves (at least for me) is that lfcd breaks my flow by going fullscreen. When I have to switch to lfcd, it breaks my flow by making me dive into a fullscreen app and then exit and dive back into the terminal. I would be much more productive if the transition were less abrupt, for me that means drawing it below the prompt and not fullscreen. Right now the net gain in productivity is enough to make me use lf, but this is an important annoyance for me.

**Comment by gokcehan** [comment]
@Javyre I feel like window management should be left to external tools. Maybe something like this can be scripted with tmux splits. I can be convinced though as long as this does not disrupt the workflow of others and convolute the code significantly. But regardless of what we decide here, I think this is not possible with the current state of termbox. You can ping me again if you feel like this would be possible with termbox and we can consider whether we want to include something like this or not.

**Comment by Javyre** [comment]
@gokcehan I agree. Sucks that the showstopper here is really termbox :disappointed:

Closing issue as this would require to switch away from termbox and that's a substantial code change for this project.
