### ISSUE TITLE
shortcut go to the bottom is not work again

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1274]
the today, i install the ibus input,

and i use the lf , i find the go to the bottom is not work
![image](https://github.com/gokcehan/lf/assets/87791643/d4c7b36f-b668-4ed3-a522-11c29a256326)

so i change the shortcut ,use 'gb' is not work too
![image](https://github.com/gokcehan/lf/assets/87791643/673a6f82-9f86-402d-bfb7-1ce97e1c36fa)

![image](https://github.com/gokcehan/lf/assets/87791643/6fc97e8e-a584-4116-818f-00ff38a4c410)

**Comment by joelim-work** [comment]
Check the version and make sure you're running version r30 and not r29.

**Comment by newyorkthink** [comment]
i fixed , is my error , thank you ,
i download r30 version
now is ok

**Comment by jltbb** [comment]
Hey @newyorkthink - any chance I could get your visual/color config for LF? Sorry this is unrelated but I really like the look of your setup
