### ISSUE TITLE
custom delete and usage $ 

### ISSUE THREAD

**Issue by arozehnal** [gokcehan/lf#1275]
AIX v.7.2
go version 20.2

=================================================

I build a lf for AIX. Then I tried some fragments from the sample configuration (lfrc.example). I got stuck at:

\# define a custom 'delete' command
cmd delete  ${{
     set -f
     printf "$fx\n"
     printf "delete? [y/n] "
     read ans
     [ "$ans" = "y" ] && rm -rf $fx
}}

In its original form, deletion didn't work, i.e., the script didn't pause, and it didn't prompt for an ans input. However, when I swapped:
	cmd delete  ${{
 to
		cmd delete  %{{

the deletion works.
It occurred to me that it could be due to the shell used. AIX natively uses KSH. But the behavior is the same even if I explicitly set -> set shell /usr/bin/bash

Am I doing something wrong?

**Comment by gokcehan** [comment]
@arozehnal The difference between `$` and `%` commands is that `$` commands pauses the ui and drops to the terminal which might be related to this issue. Dropping to terminal is mostly handled by the terminal library tcell and I'm not sure how well it works on AIX systems. Maybe you can try using `!` commands also to see if it makes a difference or not.
