### ISSUE TITLE
Got EventError: 'EOF' at...

### ISSUE THREAD

**Issue by arozehnal** [gokcehan/lf#1278]
AIX 7.2
go v.20.2

I've returned to an old problem  https://github.com/gokcehan/lf/issues/771 . 
This time with a new build of lf running on AIX 7.2.

I made a simple one-liner cmd file with this content:
ls -l /tmp, I set "+x" and into the lfrc I added:
map x $$f
map X !$f

Then I tried three ways to run the cmdfile from lf

a) using 'x'
b) using 'X'
3) $
./cmdfile
Every time lf froze and in the log appeared
Got EventError: 'EOF' at ...

Running the cmdfile outside of lf works OK.
Doesn't the message "Got EventError: 'EOF'" help in resolving the issue?

**Comment by gokcehan** [comment]
@arozehnal I suspect this is also the same issue as #1275 . I found the following statement in [tcell repo](https://github.com/gdamore/tcell):

>POSIX (Linux, FreeBSD, macOS, Solaris, etc.)
>Everything works using pure Go on mainstream platforms. Some more esoteric platforms (e.g., AIX) may need to be added. Pull requests are welcome!

**Comment by arozehnal** [comment]
OK, I understand. I will continue testing for a while to see what works and what doesn't. It seems that only the transitions to/from the shell are causing issues.
