### ISSUE TITLE
Environment variables not changing

### ISSUE THREAD

**Issue by SDA-31** [gokcehan/lf#1284]
Hello. I set `$EDITOR` variable to `~/.zshenv`, but it is not affected on lf - editor is still `less`.
lf version: 30
Also i tried setting environment variables into `~/.zprofile`, `~/.zshprofile` and `~/.profile` as suggested in #1124, but doesn't work for me, and it is not because #1197 or #833 - `$echo $EDITOR` from lf cmd prints `less`

**Comment by ilyagr** [comment]
You need to make sure to export it (`export EDITOR=vim`) in the zsh config, if it's anything like bash. I also don't know if `~/.zshenv` is sourced by default.

Perhaps someone who actually uses zsh could be of more help.

**Comment by ilyagr** [comment]
Also, if you have `$VISUAL`  set, it will override `$EDITOR`

**Comment by SDA-31** [comment]
> You need to make sure to export it (`export EDITOR=vim`) in the zsh config, if it's anything like bash. I also don't know if `~/.zshenv` is sourced by default.

![image](https://github.com/gokcehan/lf/assets/80205117/e16e8247-96c1-4882-92c7-571fe0ca22dd)


> Also, if you have `$VISUAL` set, it will override `$EDITOR`

![image](https://github.com/gokcehan/lf/assets/80205117/be10d076-0e32-4411-9542-a46e9e7630a0)

**Comment by SDA-31** [comment]
Sorry, i double-checked and found that `$VISUAL` is actually set to `less` by default.
This solution is work for me:
![image](https://github.com/gokcehan/lf/assets/80205117/ebe95438-94b9-4052-991f-15e7d8ac7d46)
