### ISSUE TITLE
Show number of hidden items in the ruler

### ISSUE THREAD

**Issue by kosorin** [gokcehan/lf#1287]
I would like to have some kind of indicator to tell me if all items in the current directory are shown, or if some items are hidden, either hidden by `hiddenfiles` or `setfilter`.

The column also shows `empty`, but that is a bit confusing because it's not always true. So now I always have to turn on the hidden option and clear the filter to see if it's really empty. For example the other file manager I was using said something like "empty (4 hidden items)".

In the ruler it could added to the `ind`: `4/23 (7)` = current position is 4 of 23 visible items, 7 items are hidden.

I think it should be disabled by default for the same reason that `dircounts` is disabled by default.

**Comment by joelim-work** [comment]
It should be pretty easy to change the `ind` field to display a number in brackets if there are any files that aren't shown:

```diff
diff --git a/ui.go b/ui.go
index 1f8af2c..fb8b20c 100644
--- a/ui.go
+++ b/ui.go
@@ -819,6 +819,7 @@ func (ui *ui) drawStatLine(nav *nav) {
 
 	tot := len(dir.files)
 	ind := min(dir.ind+1, tot)
+	hid := len(dir.allFiles) - tot
 	acc := string(ui.keyCount) + string(ui.keyAcc)
 
 	selection := []string{}
@@ -881,7 +882,11 @@ func (ui *ui) drawStatLine(nav *nav) {
 				ruler = append(ruler, "\033[34;7m F \033[0m")
 			}
 		case "ind":
-			ruler = append(ruler, fmt.Sprintf("%d/%d", ind, tot))
+			if hid > 0 {
+				ruler = append(ruler, fmt.Sprintf("%d/%d (%d)", ind, tot, hid))
+			} else {
+				ruler = append(ruler, fmt.Sprintf("%d/%d", ind, tot))
+			}
 		default:
 			if val, ok := opts[s]; ok {
 				ruler = append(ruler, formatRulerOpt(s, val))
```

I might leave this here for a while before submitting a PR, to see if anyone else is interested in this.

**Comment by kosorin** [comment]
That's great. I'd like to hear other people's ideas. The number in brackets in `ind` was just my initial idea and I'm not sure if it's a good place.

**Comment by joelim-work** [comment]
I guess one other alternative is to create another `hid` field to support in the `ruler` setting, so that users have an option whether to display this or not independently of the current `ind`.
