### ISSUE TITLE
Upgrade to r30.

### ISSUE THREAD

**Issue by AbdullahZubair-UW** [gokcehan/lf#1289]
On Ubuntu, how can one upgrade from r8 to r30?

**Comment by ilyagr** [comment]
The easiest way is probably to uninstall the Ubuntu version, download the official release from https://github.com/gokcehan/lf/releases/ (probably https://github.com/gokcehan/lf/releases/download/r30/lf-linux-amd64.tar.gz), unpack the archive and move `lf` to somewhere in your PATH.
