### ISSUE TITLE
Feature request: numbered lines (absolute/relative)

### ISSUE THREAD

**Issue by tomarticek** [gokcehan/lf#130]
Would you consider implementing line numbers (same as 'number' and 'relativenumber' options in vim)? Maybe it can be achieved via configuration somehow, but I did not find out how and I think this might be very useful for faster navigation.

In case you are interested in such functionality, I have already implemented something like that (only hardcoded, conrol via options would still be needed)
![window](https://user-images.githubusercontent.com/33220144/51250512-de7c7d00-1996-11e9-842a-f27fc7aeffbc.png)

**Comment by gokcehan** [comment]
@AlienSVK Thanks for suggestion. I guess we can add numbering with a boolean option (e.g. `number`). I think we should keep this disabled by default if you're ok with it. Looking at your screenshot I was wondering if it would be better to use a different color for numbers to avoid confusion with file names. Maybe some dimm color like gray, or the orange color used in vim's default colorscheme.

I imagine adding an option control to your patch may not be difficult. We have a guideline in [contributing](https://github.com/gokcehan/lf/wiki/Contributing) wiki page. I can also try to help if you want. You can send this as a PR if you like and we can discuss it further there.

**Comment by AlienSVK** [comment]
Yes, I agree that it should be disabled by default. Also different color might be good idea, I will definitely try it and we will see how it looks.

I already saw guideline in contributing page, but I wanted to make sure that you actually want this feature before I implement option control. So, I will provide patch when it's ready (hopefully soon)

There is only one question left - vim has 2 boolean options for this - `number` and `relativenumber` and their combination might result in one of the following:
- no line numbers (off/off)
- absolute numbers on all lines (on/off)
- relative numbers on all lines (off/on)
- absolute number on cursor and relative on the rest - as on screenshot (on/on)

Ranger also implemented line numbers with just one string option `line_number` (false/absolute/relative)
Which approach do you suggest? Vim's, ranger's, or just one boolean `number` option?

**Comment by gokcehan** [comment]
@AlienSVK So far I have implemented most options using the names from vim, mostly because I'm not familiar with ranger's options much and also I think more people might be familiar with vim options. Since this is our current convention I think vim's `number` boolean option might be better for now.

**Comment by AlienSVK** [comment]
@gokcehan I am also more familiar with vim so this convention suits me very well. However, my question was not only about option name, but also about option(s) type/count. If we want to stick with vim's names, two separate boolean options `number` and `relativenumber` would be more convenient

**Comment by gokcehan** [comment]
@AlienSVK Ahh sorry, I'm a little distracted today so I can't read properly :) Two boolean options are fine I think.

**Comment by gokcehan** [comment]
@AlienSVK Sorry for late reply. I have been having problems with my computer in the last couple of days.

For the most part, git and github are also still a mystery to me :) I only know about things I do frequently so I may not be the best person to give advice unfortunately. I remember sending a few basic pull requests to other projects. The way I remember is as follows:

- Fork the project in the github website
- Clone my fork of the project to my computer
- Make and commit changes
- Push commits to my fork of the project
- Send pull request to the original repository using the github website

You may or may not need to create a branch to work with, I don't remember much. Following page shows how to do the pull request in the github website:

https://help.github.com/articles/creating-a-pull-request/

I also found the following longer article which I think shows you the whole process:

https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

Option name indeed seems a little long but don't worry about it. Maybe we can change it to `relative` or something similar at some point but I think it is better to stick to the original name for now. If you ask me, it is enough to only fix the indentation for now.

Don't hesitate to ask again if you get stuck and feel overwhelmed by the git process :) And don't worry about sending a wrong PR or so, we can deal with it one way or another. Also it can take a few days for me to merge your patch as I'm still trying to fix my computer.

**Comment by gokcehan** [comment]
This is implemented in #133. Closing the issue now.
