### ISSUE TITLE
Vim bindings

### ISSUE THREAD

**Issue by minhquoc0712** [gokcehan/lf#1300]
Hi,

I just want to ask do you plan to have support for Vim key bindings.

Thank you.

**Comment by joelim-work** [comment]
They are supported and it's listed as a feature in the README: https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/README.md?plain=1#L27

Have you tried installing and running `lf` and typing `h`/`j`/`k`/`l` to see what happens?
