### ISSUE TITLE
$EDITOR env variable not being set

### ISSUE THREAD

**Issue by SwayKh** [gokcehan/lf#1313]
This might be related to #1124 but I am having the same problem as well
The $EDITOR env variable is set in `.bashrc`, `.zshrc`, `.profile` and yet `lf` is opening files in vi.
This is only the case when opening `lf` with a custom keyboard shortcut in KDE Plasma with the command `kitty -e lf`.
If I open `lf` in a already running terminal then everything works as expected.
running `$echo $EDITOR` return vi but entering the SHELL with w(default is <enter>) and running the same command returns /usr/bin/nvim

I am running Arch Linux, KDE 5.27.5 and lf version is 30

**Comment by ilyagr** [comment]
Check whether you also have `$VISUAL` set. If you do, it takes precedence over `$EDITOR`.

**Comment by SumitKhatri712** [comment]
Echo-ing `$VISUAL` didn't output anything, so I exported it in `.profile` and in `.zshrc` but opening `lf` with keyboard shortcut still outputs nothing but it does out /use/bin/nvim in the shell inside`lf`

**Comment by ilyagr** [comment]
> This is only the case when opening lf with a custom keyboard shortcut in KDE Plasma with the command kitty -e lf.

I think that's your problem. For one reason or another, the environment Plasma is running in doesn't have `$EDITOR` set. You can try changing the command to `kitty -e zsh -c lf` or `kitty -e zsh -ic lf`.

Someone more familiar with Plasma or this kind of problem might be of more help. I think one place where you could set environment more globally is somewhere in `systemd` config.

**Comment by ilyagr** [comment]
Also, you can also remap `lf`'s bindings that you `$EDITOR` to make it use `nvim` directly.

**Comment by SumitKhatri712** [comment]
> Also, you can also remap `lf`'s bindings that use `$EDITOR` to make it use `nvim` directly.

Would I just need to change $EDITOR to $nvim in my open function for this to work? Or do I need to set this somewhere else?

**Comment by ilyagr** [comment]
You could change the `e` mapping and change the `open` command to something like `zsh -c -- "$OPENER $f"`, I think (so that `xdg-open` gets the correct value of `$EDITOR`).

Something along the lines of my previous suggestions is probably better if you can flesh them out (sorry they are not completely figured out).

**Comment by SumitKhatri712** [comment]
SO I tried out this suggestion and the previous one, here's the result

Using `kitty -e zsh -c lf` has no effect and LF still uses `vi`

Running `kitty -e zsh -ic lf` however does fix the `$EDITOR` issue but the `quit` keybind seems to get messed up as presssing q puts me in a empty shell with no prompt and I have to manually type exit to close the terminal

This was my previous `open` func that I used
```

cmd open ${{
	case $(file --mime-type "$f" -bL) in
		text/*|application/json) $EDITOR "$f" ;;
		*) xdg-open "$f" ;;
	esac
}}
```

I assume you wanted me to do something like this?
```
cmd open ${{
	case $(file --mime-type "$f" -bL) in
		text/*|application/json) zsh -c -- "$OPENER $f" ;;
		*) xdg-open "$f" ;;
	esac
}}
```
This function just opens any files with the `kate` editor, maybe its using `xdg-open` for everything.

Incidentally when trying this method manually I found the `$OPENER` env variable is not set to anything, as running `echo $OPENER` in a regular terminal outputs nothing, could that be the cause of this?

**Comment by ilyagr** [comment]
If you are using a custom open command, just put nvim there instead of $EDITOR. No need to deal with OPENER.

**Comment by SumitKhatri712** [comment]
I tried to to change `$EDITOR` to `$nvim` but I am getting a permission denied error `running shell: exit status 126`
and `--: line 3: /home/sumit/dotfiles/test.txt: Permission denied` is being printed in the shell

**Comment by ilyagr** [comment]
It's just `nvim`  or `path/to/nvim`. Figuring out that permissions denied error could be a good learning exercise.

**Comment by SumitKhatri712** [comment]
Thanks! Just using `nvim` worked. 
I still don't understand the permission denied error though, using `$echo` seems to work in the Lfrc, so why doesn't $nvim work?

Also I don't really have a problem with using `nvim` in the Lfrc but I'd still like to figure out the regular way for this. 
What would happen if nvim wasn't installed on a system, would it just use `xdg-open`? This way seems a bit too hard-coded.
