### ISSUE TITLE
Multiple command use

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1318]
I wrote the script, tha use ssh config file, and use sshfs and mount. That's work great, but I have problem with umount:

```
cmd umount %{{
	lf -remote "send cd ~"
	fusermount -u ~/Mount
	lf -remote "send reload"
}}
```
I get error message: failed to unmount: Device or resource busy
The problem is that they run commands one after the other without waiting for the previous one to finish. How can I make it run only when the previous command has been finished?

**Comment by ilyagr** [comment]
I'm not sure of the fix, but the problem is that all the `lf -remote` commands will be executed *after* `umount` stops executing. This has to do with the fact that all the work happens in a single thread, so while `umount` is running, nothing else can run in that instance of `lf`. This is a limitation of `lf` that's hard to fix. We discussed it in detail in https://github.com/gokcehan/lf/issues/1277#issuecomment-1573106737 and below.

**Comment by joelim-work** [comment]
> I'm not sure of the best workaround, but the problem is that all the commands queued for execution by`lf -remote` will be executed _after_ your custom `umount` command stops executing. This has to do with the fact that all the work happens in a single thread, so while `umount` is running, nothing else can run in that instance of `lf`.
> 
> This is a limitation of `lf` that's hard to fix. We discussed it in detail in [#1277 (comment)](https://github.com/gokcehan/lf/issues/1277#issuecomment-1573106737) and below.

No, that only applies for synchronous shell commands (i.e. `$` and `!`).

In this case what happens is that `lf -remote "send cd ~"` returns immediately without waiting for the `cd` command to actually finish, and then tries to unmount the disk. In general, this is how `lf -remote` works - it considers its task done and terminates when it sends the command to the `lf` server, without waiting for the client to actually execute the command.

In general, you can't use `lf -remote` if you want steps to run sequentially, Instead you should chain regular `lf` commands like this:

```
cmd umount :{{
    cd
    $fusermount -u ~/Mount
    reload
}}
```

I haven't tested this properly though, but this is more likely to achieve what you want.

**Comment by og900aero** [comment]
> eloa



> > I'm not sure of the best workaround, but the problem is that all the commands queued for execution by`lf -remote` will be executed _after_ your custom `umount` command stops executing. This has to do with the fact that all the work happens in a single thread, so while `umount` is running, nothing else can run in that instance of `lf`.
> > This is a limitation of `lf` that's hard to fix. We discussed it in detail in [#1277 (comment)](https://github.com/gokcehan/lf/issues/1277#issuecomment-1573106737) and below.
> 
> No, that only applies for synchronous shell commands (i.e. `$` and `!`).
> 
> In this case what happens is that `lf -remote "send cd ~"` returns immediately without waiting for the `cd` command to actually finish, and then tries to unmount the disk. In general, this is how `lf -remote` works - it considers its task done and terminates when it sends the command to the `lf` server, without waiting for the client to actually execute the command.
> 
> In general, you can't use `lf -remote` if you want steps to run sequentially, Instead you should chain regular `lf` commands like this:
> 
> ```
> cmd umount :{{
>     cd
>     $fusermount -u ~/Mount
>     reload
> }}
> ```
> 
> I haven't tested this properly though, but this is more likely to achieve what you want.

Works like a charm. Thank u! I learned something important today.
