### ISSUE TITLE
More Of a question.

### ISSUE THREAD

**Issue by Drunkenpanda2000** [gokcehan/lf#132]

**Comment by TeddyDD** [comment]
`map <right> $vim $f` should do the job

**Comment by gokcehan** [comment]
@Drunkenpanda2000 Feel free to ask further questions if you have any. Closing this issue now.

**Comment by Drunkenpanda2000** [comment]
It doesn't recognis $vimor $nvim as a command both are in my profile and work in a terminal.

**Comment by gokcehan** [comment]
@Drunkenpanda2000 Shell commands are non-interactive, meaning that they don't source your bashrc or profile files. So if you have `vim` or `nvim` as aliases I'm afraid they won't work within lf unless you define them again. You can try to see if a command would be available in lf or not by wrapping it as a string and passing it to `sh`. For example you can check `vim` command is avaiable as such:

    sh -c 'vim'

This is the way we run shell commands. Hope this helps.

**Comment by gokcehan** [comment]
@Drunkenpanda2000 I'm not sure what you mean by profile on windows but the same thing should hold. You can try if a command is available or not with:

    cmd /c "vim"

If `vim` is not an executable in path and instead it is something defined in profile, then you may need to redefine it in the command.
