### ISSUE TITLE
Open lf on last directory

### ISSUE THREAD

**Issue by Huray-hub** [gokcehan/lf#1321]
How to make lf preserve last visited directory when reopen?

**Comment by joelim-work** [comment]
You might want to have a look at #1145.

You can also have `lf` change to the last directory upon startup by inserting a `push ''` command into your config file:

```
push ''

cmd on-quit ${{
    marks=~/.local/share/lf/marks
    sed -i "/^'/d" "$marks"
    echo "':$PWD" >> "$marks"
}}
```

**Comment by Huray-hub** [comment]
The above does not work. error is: unknown mapping: '

**Comment by j-xella** [comment]
> The above does not work. error is: unknown mapping: '

Try opening/closing lf a couple of times?

**Comment by joelim-work** [comment]
`'` is mapped to `mark-load` by default, you probably disabled it with something like `map "'"`.

If you want to leave `'` unmapped, then you can replace `push ''` with `:mark-load; push '`.

**Comment by Huray-hub** [comment]
Okay, found it! Is it possible in the same line before quit too?

**Comment by joelim-work** [comment]
@Huray-hub I'm not sure what you mean by 'same line before quit', could you please clarify?

**Comment by Huray-hub** [comment]
Sure. I m in directory x "hovering over" file notes.txt . When I reopen lf I am at the x directory, but the hover indicator is at the top, instead of notes.txt

**Comment by joelim-work** [comment]
The marks file only stores directory locations. If you want to save the actual file that the cursor is on, then you can do something like this:

```shell
${{
    save=$(cat /tmp/lf_save)
    if [ -n "$save" ]; then
        lf -remote "send $id select \"$save\""
    fi
}}

cmd on-quit ${{
    echo "$f" > /tmp/lf_save
}}

```
