### ISSUE TITLE
Command zip don't work. 

### ISSUE THREAD

**Issue by seriiserii825** [gokcehan/lf#1326]
Hi, thanks for lf. 
Ubuntu, zsh.

This is my command from default file example. 
```
# compress current file or selected files with zip
cmd zip ${{
    set -f
    mkdir $1
    cp -r $fx $1
    zip -r $1.zip $1
    rm -rf $1
}}

```

I select files with space and run `:zip` but have an error 

```
running shell: exit status 2
```

Thanks in advance.

**Comment by joelim-work** [comment]
Have you tried providing a name for the zip file (e.g. `:zip foobar` to create `foobar.zip`)? That's what gets substituted into `$1`.

Also, those statements are ordinary shell commands, so you can try the usual debugging techniques like commenting stuff out, printing values, etc.
