### ISSUE TITLE
Unknown option: dupfilefmt

### ISSUE THREAD

**Issue by hiimsergey** [gokcehan/lf#1328]
When editing the option "dupfilefmt" (documented at [pkg.go.dev](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Options)), I get the error message "unknown option: dupfilefmt" when opening lf.

**Comment by gokcehan** [comment]
@hiimsergey That option has just been added a few hours ago and it will be available in the next release.

**Comment by hiimsergey** [comment]
Oops, I totally missed that. First time reading the docs.
Excuse me and thank you very much for adding this feature.

**Comment by joelim-work** [comment]
@hiimsergey FYI, the documentation is included in the `lf` executable itself. You can use the `doc` command (mapped to <kbd>F1</kbd> by default) to view the documentation for the version of `lf` that you're currently using. There is also a `man` page included if you're a Linux user.

**Comment by hiimsergey** [comment]
@joelim-work Thank you!
