### ISSUE TITLE
Default merge strategy

### ISSUE THREAD

**Issue by joelim-work** [gokcehan/lf#1339]
Hi @gokcehan,

I have just merged #1335 and #1336, but I have found that they create merge commits on the master branch, which makes the history look a bit more ugly. Judging from the commit history, I think what you prefer is squash merging?

In any case I think it would be better if you go into the repo settings and disable certain types of merging - as a collaborator I don't have access to this. I'm not sure if you also want to manually force push and clean up the history from these two commits, but I will leave this decision up to you.

My apologies for causing you any inconvenience.

**Comment by gokcehan** [comment]
@joelim-work It's no problem at all. I don't think we need force clean-up. I have now changed the repo settings to only allow squash merging from now on. Thanks for the warning.

**Comment by joelim-work** [comment]
Thanks very much!
