### ISSUE TITLE
[Question] How to keep terminal opened after quiting LF.

### ISSUE THREAD

**Issue by ikyokara** [gokcehan/lf#1356]
I've set up LF as my file manager, and its working great. Firefox -> Show in folder, opened a new lf instance with the correct directory. But one minor issue is when exit the LF program, it also close the terminal it was in as well.
I would like to closed the LF program but keep the new spawned terminal which the LF was run on and stay at the current directory using lfcd, is there a way to do it?

My lf.deskop
> Desktop Entry]
> Type=Application
> Name=file manager
> GenericName=terminal base file manager
> Exec=st -e lf %u
> MimeType=inode/directory
> NoDisplay=true
> Terminal=false

**Comment by gokberkgunes** [comment]
Below line may partially do what you want. You should change `zsh` to `bash`, `fish`, `sh` or whatever shell program you prefer.
```
Exec=st -e sh -c "cd %u; lf; zsh"
```
This does not follow the directory where lf ends up. The directory of the shell will be the  the downloaded directory.

**Comment by ikyokara** [comment]
@gokberkgunes
Awesome, it does indeed worked as I expected.
Yesterday, I was looking around and also found a solution to this. I created a script which included the `lfcd()` function then add `lfcd "$@"; $SHELL` at the end of the script. Call the script inside _lf.desktop_ `Exec=st -e /path/to/script %u` which does exactly the same thing as
```shell
Exec=st -e sh -c "cd %u; lf -last-dir-path='/tmp/tmp.lfdir'; cd \"$(cat /tmp/tmp.lfdir)\"; zsh"
```
 however, your version, it a lot shorter and doesn't require additional script and does exactly the same thing :+1: 

```
##### lf.sh
#!/bin/sh
lfcd () {
    tmp="$(mktemp)"
    # `command` is needed in case `lfcd` is aliased to `lf`
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

lfcd "$@"; $SHELL
```
