### ISSUE TITLE
Statfmt problem if I use show link (%l, %L)

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1357]
I use env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest for the latest version. Now I have a problem.
I use specific statfmt:
`set statfmt "\033[7;31m %p \033[32m %c \033[33m %u %g \033[34m %s \033[35m %t \033[36m %L \033[0m"`

But this new version the %L and %l options is not working ("previous" version working good).
- When using %L, then show %L always (not link with arrow, or nothing)
- When using %l, then show nothing when select not-link, and show link, when select link

**Comment by joelim-work** [comment]
The behavior of `statfmt` is changed in #1337, didn't you react with a ❤️ in the PR?

**Comment by og900aero** [comment]
> The behavior of `statfmt` is changed in #1337, didn't you react with a heart in the PR?

Yes, but only for this: "For the statfmt option, I finally found a way to support display text depending on whether a field exists or not."

I thought it would be resolved that if something has no value, then it doesn't show an empty field, but then it doesn't show anything. I didn't think that the %L option would disappear completely then,

**Comment by joelim-work** [comment]
`%L` is not needed anymore because it is effectively the same as `|-> %l`. Normally this would have been announced as a breaking change, however `statfmt` hasn't officially been released yet.

It is sort of expected that if you're building off the latest master branch, then you're working with features that are relatively unstable and subject to change.

**Comment by og900aero** [comment]
Thx the "idea". I was edited lfrc to the following code:
`set statfmt "\033[7;31m %p \033[32m %c \033[33m %u %g \033[34m %s \033[35m %t |\033[36m -> %l |\033[0m"`
