### ISSUE TITLE
Inaccessible files and directories should be shown in the file listing

### ISSUE THREAD

**Issue by jantatje** [gokcehan/lf#1359]
In some cases like on NFS the current user may not have permission to access or stat some directories. If you list them with `ls` they will be shown, but cannot be accessed. lf should not hide these directories.

example:
/etc/exports
```
/mnt            10.0.0.0/24(sec=krb5i,ro,fsid=0,no_subtree_check,async,sec=sys,all_squash)
/mnt/data       10.0.0.0/24(sec=krb5i,rw,no_subtree_check,async)
/mnt/backup     10.0.0.0/24(sec=krb5i,rw,no_subtree_check,async)
...
```
The first line allows mounting / both anonymously and authenticated via kerberos, the second and third lines exports other filesystems that can only be accessed as an authenticated user.

if you now mount with `mount -o sec=sys servername:/ /mnt/nfs` then `ls -la` output looks like this:
```
ls: cannot access 'data': Operation not permitted
ls: cannot access 'backup': Operation not permitted
total 12
drwxr-xr-x 6 root root 4096 Sep 10  2021 .
drwxr-xr-x 1 user user   68 Jul 28 17:52 ..
?????????? ? ?    ?       ?            ? backup
?????????? ? ?    ?       ?            ? data
drwxr-xr-x 2 root root 4096 Sep  9  2021 public
drwxr-xr-x 2 root root 4096 Sep 10  2021 public2
```
lf only shows the public and public2 directories.

The same can also happen on corrupted FAT filesystems.

**Comment by gokcehan** [comment]
@jantatje Thanks for reporting this. In general, I think this would be an acceptable change, though I'm not sure how this can be implemented. Maybe one could store some dummy values when there is a stat error and show question marks in the ui when there are such dummy values. There could be too many places in the code for these checks though, I'm not sure. If anyone want to give this a try, I think one could start with [the stat error during `readdir` in `nav.go`](https://github.com/gokcehan/lf/blob/dd8294952f3cda8d8671847a5ab4dc3613a2aabd/nav.go#L69).
