### ISSUE TITLE
Image preview using `wezterm` or `timg`

### ISSUE THREAD

**Issue by mangkoran** [gokcehan/lf#1361]
My setup is using `wezterm` as terminal emulator and `lf` as the file browser. How can I use `wezterm` or `timg` as the image previewer in lf? I can successfully display image using `timg -p iterm2 [file-name]`.

![image](https://github.com/gokcehan/lf/assets/57625126/1b1add74-64c1-4936-81da-b32eb5426730)

**Comment by joelim-work** [comment]
Don't know about `timg`, but `wezterm` supports Sixel so hopefully using `chafa` to convert the image to Sixel format should work: https://github.com/gokcehan/lf/wiki/Previews#with-sixel
