### ISSUE TITLE
lf display `unknown option: color256` when launched by a shortcut

### ISSUE THREAD

**Issue by jpggithub** [gokcehan/lf#1367]
I try to use the try to use the option `color256` with `set color256 on` on my `lfrc`.

When I launch `lf` from a terminal ( `alacritty` or `xfce4-terminal`), the option works well.

When I launch it with a shortcut managed by `sxhkd` (manager of shortcuts), `lf` display the message `unknown option: color256`. My shortcut launch `lf` by a terminal. I tested with `alacritty` and `xfce4-terminal`, the problem stays here.

**Comment by joelim-work** [comment]
There is no such option `color256` - it used to exist but was removed as it's no longer needed, see #439 for more details.

If you see two different sets of behaviors, then you possibly have two separate versions of `lf` installed on your system, in which case you should remove the old version and ensure you are running only the latest version. This might be related to your other issue #1368.

**Comment by jpggithub** [comment]
Arg... You're absolutely right! Thank you!
I had an old version that I have installed 3 years ago in `~/.bin` just to test `lf` (now adopted!)
