### ISSUE TITLE
Setting 'map e $nvim $Env:f' does not work for shell pwsh

### ISSUE THREAD

**Issue by saljic** [gokcehan/lf#1370]
I'm using powershell core for development and I use `set shell pwsh`  to make sure that LF usees the powershell core for shell commands . But When I put `map e $nvim $Env:f` in the lfrc file it does not work for powershell core. It opens an empty file for some reason. It works fine if I use `set shell powershell`, but I'd prefer to use pwsh instead of powershell if possible

**Comment by joelim-work** [comment]
For Windows, environment variables for filenames are wrapped in quotes to be compatible with CMD, although I guess it probably doesn't work so well with PowerShell. However, I did manage to get it work by removing the quotes:

```
set shell pwsh
map e $nvim $Env:f.Trim('"')
```

**Comment by saljic** [comment]
Yes that works like a charm! Should we update the lfrc example for powershell with some comment about this or should I just close the issue?

**Comment by joelim-work** [comment]
Leave it open, I think it's better if the decision to wrap in quotes is handled internally inside `lf`.
