### ISSUE TITLE
BUG:lf 2023/08/09 11:31:26 remote command: dialing to send server: dial unix /run/user/1000/lf.thinker.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1377]
```
lf
2023/08/09 11:31:26 remote command: dialing to send server: dial unix /run/user/1000/lf.thinker.sock: connect: no such file or directory
```
i dont not what happen

**Comment by newyorkthink** [comment]
is  cannot change folder and select FOloder

**Comment by joelim-work** [comment]
The `/run/user/1000/lf.thinker.sock` is the socket that `lf` uses to communicate with the `lf` server. It should be created automatically by the server when it starts, so `lf` can connect to it.

I'm not sure what happened, but check if the server is running and what socket location it is actually listening on. The socket path should evaluate to something like `${XDG_RUNTIME_DIR:-/tmp}/lf.${USER}.sock`.
