### ISSUE TITLE
Difference between $fx and $fs?

### ISSUE THREAD

**Issue by cbr9** [gokcehan/lf#1378]
Digging into lf, I have found three main variable to refer to files. $f, for the current file, and $fx and $fs. However, I don't understand the difference between $fx and $fs. They both seem to refer to the selection.

Any ideas?

**Comment by cbr9** [comment]
Okay, some more digging and I think i understood. $fx can refer to either the current file, or the current selection, while $fs only holds a value when the user selected some files. Is that correct?

I tried looking for information about this in the docs but I couldn't find anything

**Comment by shabahengam** [comment]
> I tried looking for information about this in the docs but I couldn't find anything

https://pkg.go.dev/github.com/gokcehan/lf#hdr-Environment_Variables
