### ISSUE TITLE
Set user option in commands

### ISSUE THREAD

**Issue by roylez** [gokcehan/lf#1379]
I am trying to set a user option in command, but in the context of subsequent commands, it does seem to work.

Did I do anything wrong?

```
# env variable correctly set here
cmd fzf_change_root &{{
  export lf_user_root=$PWD
  lf -remote "send $id :echomsg FZF root (lf_user_root) changed to '$lf_user_root'"
}}

# but it is not available in next command
cmd echo_root !{{
  echo $lf_user_root
}}
```

**Comment by joelim-work** [comment]
The syntax is the same as using `lf -remote` to set regular options:

```shell
lf -remote "send $id set user_root $PWD"
```

**Comment by roylez** [comment]
It works! I should have realized user options should be set using `set` command like regular ones earlier.
