### ISSUE TITLE
lfrc can't read zshrc alias

### ISSUE THREAD

**Issue by awaken233** [gokcehan/lf#1388]
zshrc config
```
alias rm="trash -F"
alias lg="lazygit"
```

lfrc config 
```
set shell zsh
map <enter> shell
map x :push $rm<space>$f<enter>
```
When I press<enter>lg,  response command not found
When I press x, It will actually call the rm command instead of an alias

![image](https://github.com/gokcehan/lf/assets/18060521/ed7d0eb1-9b60-46cc-8d3d-30501a1e43fa)

**Comment by michaelferon** [comment]
`zsh` only sources `.zshrc` in interactive shells, so in this case your aliases do not exist

**Comment by michaelferon** [comment]
I'm not sure exactly what effect mapping `<enter>` to `shell` will have, but in general, `zsh` only sources `.zshrc` in interactive shells. I generally forego aliases in `lf`. In this case, I'd prefer something like
`
map x &trash -F ${(f)fx}
`

**Comment by michaelferon** [comment]
So I've played around a bit with setting
```
set shellflag '-c'
set shellopts '-i'
```
to force interactivity (and hence the sourcing of .zshrc). This seems to work okay with `$` and `!` modal commands (with aliases active), but does not play well with `&` and `%`. I would definitely not recommend this approach. In the case of `&` (on my computer), the child process that is launched lingers (and apparently doesn't work). For `%`, something is wrong with the connection to the bottom command line.

One obvious solution in your case is to use `$$lf_shell` or `$$SHELL` (mapped to 'w' by default) to launch an interactive sub-process in which your aliases will be active. Another possibility is to place your aliases in `.zshenv`, which is usually a bad idea, as every instance of `zsh` (including those used to execute scripts), will have aliases active (unless the author of the script has taken precautions to disable them -- or unless `zsh` was invoked with the flag `-f`).

**Comment by michaelferon** [comment]
Okay, I thought of a workaround that you definitely should not do, but it will work. You can put the following in your `.zprofile` or `.zlogin`:
```zsh
if [[ -n $LF_LEVEL && -o nointeractive ]]; then
    # re-define aliases here that you only want with lf
    # for example
    source ~/.aliasrc
fi
```
In your `lfrc` file, place
```
set shellopts '-l'
```
This will work, but it will mean that every command you define using `$`, `!`, `%`, or `&` will be executed using a login shell. If you don't really use `.zprofile` or `.zlogin` or their `/etc` equivalents, this is a good solution.

**Comment by awaken233** [comment]
@michaelferon Thank you for your answer. Thank you🙏🏻
