### ISSUE TITLE
how to get lf to print version details

### ISSUE THREAD

**Issue by daniejstriata** [gokcehan/lf#1390]
Hi,

I've made a rpm spec file that creates a rpm package for lf. It compiles with the following command:
`CGO_ENABLED=0 go build -v -trimpath -buildmode=pie -modcacherw -ldflags="-s -w" -o %{name}`

`lf --version`
![image](https://github.com/gokcehan/lf/assets/13314239/0b676436-65ac-4d38-af00-6d07addb7607)

the compiled packages does not print the version information though. Must I set the version as a variable or is there another way to set the version number when compiling using the source archive?

**Comment by joelim-work** [comment]
You need to define the version number when running `go build`, please see https://github.com/gokcehan/lf/issues/1108#issuecomment-1459876298

**Comment by daniejstriata** [comment]
Here is the final SPEC that works for me:
```
Name: lf
Version: r30
Release: 2
Summary: Terminal file manager
License: MIT
URL: https://github.com/gokcehan/lf
Source0: %{name}-%{version}.tar.gz

%global _hardened_build 1
%global debug_package %{nil}

%description
lf (as in "list files") is a terminal file manager written in Go with a heavy inspiration from ranger file manager

%prep
%autosetup -n %{name}-%{version}

%build
CGO_ENABLED=0 go build -v -trimpath -buildmode=pie -modcacherw -ldflags="-s -w -X main.gVersion=%{version}" -o %{name}

%install
install -Dpm 0755 %{name} %{buildroot}%{_bindir}/%{name}

%files
%{_bindir}/lf

```
