### ISSUE TITLE
Remapping Keys for different Keyboard Layout

### ISSUE THREAD

**Issue by MunsMan** [gokcehan/lf#1392]
Due to my usage of the Colemak-DH Keyboard Layout, I have to remap `h j k l` to `h n e i`

Luckily, `H` works out of the box, and I got `n` to work with:

`map N :updir; set dironly true; down; set dironly false; open`

But that didn't work for the `E` because that defaults to open in Editor. How can I change that, and how can I get the `L` to remapped to the `I`?

**Comment by ilyagr** [comment]
You can use `:maps` to get the mapping for all the keys. You might need to edit that text slightly, but it shouldn't be too bad to come up with the mappings you need.
