### ISSUE TITLE
[HELP]: how to toggle hidden when in certain directories

### ISSUE THREAD

**Issue by noornee** [gokcehan/lf#1403]
I almost always launch `lf` from my home directory and i get bombarded with a lot of hidden files; it's overwhelming! /s (just about 12 hidden files)
I'm trying to setup a command? that would toggle hidden files when im not in the home directory. I mean, i know there's a keybinding that was provided by default to do that  `map zh set hidden!` and that works perfect but i dont want to keep doing that. i want it to be toggled in the UI just by detecting the current directory im on.

here's my attempt at figuring this out 

```bash
cmd on-cd %{{
	current_dir="$(pwd)"
	home_dir="$HOME"
	if [[ $current_dir != $home_dir ]];then 
		set hidden true
		echo "show hidden"
	fi

}}
on-cd
```

I mean yes, i know, the `set hidden true` in the script above  isnt using the lf  `set` special command and im also aware that im not going about this the right way but that's where help comes in!

I would greatly appreciate any help provided ^^

**Comment by joelim-work** [comment]
You might be interested in this post: https://github.com/gokcehan/lf/wiki/Tips#persistent-options-eg-sorting-for-some-directories

BTW we are working on making this a builtin command in #1381, but for now hopefully the above approach will work for you.

**Comment by noornee** [comment]
> You might be interested in this post: https://github.com/gokcehan/lf/wiki/Tips#persistent-options-eg-sorting-for-some-directories

hiii, Thanks for this (everything do be in the wiki's ^_^' )
I'll try this out soon as am close to my pc.

> BTW we are working on making this a builtin command in #1381, but for now hopefully the above approach will work for you.

That's awesome! it would be really great if that was builtin. keep up the good work!
I'll give you a feedback on my progress ^^

**Comment by noornee** [comment]
> You might be interested in this post: https://github.com/gokcehan/lf/wiki/Tips#persistent-options-eg-sorting-for-some-directories

hiii, Thanks for this (everything do be in the wiki's ^_^' )
I'll try this out soon as am close to my pc.

> BTW we are working on making this a builtin command in #1381, but for now hopefully the above approach will work for you.

That's awesome! it would be really great if that was builtin. keep up the good work!
I'll give you a feedback on my progress ^^
