### ISSUE TITLE
cmd-delete-unix-word doesn't stop at word separators that aren't white space

### ISSUE THREAD

**Issue by janpeterd** [gokcehan/lf#1406]
When renaming a file the `C-w` keybinding (mapped to `cmd-delete-unix-word`) doesn't stop at characters that separate words that aren't white space.
Expected behavior would be like in bash and vim where words are separated by for example `.` or `-` or `,`, .... When you press `C-w` in those programs you delete until that character.
The `A-d` keybinding (`cmd-delete-word`) in lf does stop at these separators, the `C-w` doesn't.

It would be more useful for example when replacing the file extension with the cursor at the end of the line. Lf deletes the entire filename when pressing `C-w` instead of only the extension.

version: git on commit [6aa3d2a](https://github.com/gokcehan/lf/commit/6aa3d2aa18ebc3defbdb45a811cc27fa8ec29de8)
on Arch Linux (using `lf-git` package from `AUR`)

**Comment by gokcehan** [comment]
@janpeterd I'm afraid this is the way it works in `bash`. If you meant `zsh`, an option to configure this behavior was proposed in #281 before, but I don't think anybody worked on it so far.

Note, we changed rename a while ago to put the cursor at the extension so you can use <kbd>C-k</kbd> or similar to delete the extension.

**Comment by janpeterd** [comment]
@gokcehan You're right, I meant `zsh`.

Issue #281 is indeed talking about the same thing.

I did not know about the new rename functionality, since I was using my own binding for that. In that case the existing functionality works too.

I am still interested in using this proposed feature. I don't think that I will be able to implement it, but maybe someone else with the knowledge.

But since the `cmd-delete-unix-word` is doing what it's supposed to do I am closing this issue.
