### ISSUE TITLE
Can't open text files with emacsclient -c

### ISSUE THREAD

**Issue by juacq97** [gokcehan/lf#141]
I set `emacsclient -c` as my default text editor. When I press `l` on `lf` to open a text file, in terminal appears 

```
--: line 3: emacsclient -c: order not found
```

(Actually, the error says `--: línea 3: emacsclient -c: orden no encontrada` but I tried to translate it.)

If I press `O` and opens the file selecting "Emacs (client)" it works. I can use `$emacsclient -c $f` inside lf and works too. Only when pressing `l`, `e` or `o` the error appears (all that use the `$EDITOR` variable). There's a way to fix this? Thanks!

**Comment by gokcehan** [comment]
@juacq97 This is an unfortunate interaction with the `ifs` option. Assuming you are using the example configuration file, this option is set to the newline character and space splitting is disabled so the `$EDITOR` command is run as a single word. Underlying shell command looks like the following:

    $ EDITOR='emacsclient -c' f='foo.txt' sh -c 'IFS="
    "; $EDITOR "$f"'
    sh: line 1: emacsclient -c: command not found

I don't think we can do anything to fix this. You can either:

- Set `ifs` option to empty with `set ifs`
- Use only single word values for `$EDITOR` variable (you can create a wrapper script for the `-c` option)
- Define your own shell command for `e` key with `map e $emacsclient -c "$f"`

Hope this helps.

**Comment by juacq97** [comment]
>  Set `ifs` option to empty with `set ifs`

This works. I also added `map e &emacsclient -c $f` to open emacs without hang the terminal. Thanks!

**Comment by gokcehan** [comment]
@juacq97 Glad to hear that. Just a heads up, when `ifs` is not set, you should be careful about quoting you variables. For example I think your current mapping may fail for filenames with space characters. So maybe you can change it to `map e &emacsclient -c "$f"` instead.

Also, reading what I wrote before, maybe I should have said "set `ifs` option to empty by commenting out `set ifs "\n"` line in the example configuration" since the default value of `ifs` option is already empty.

Closing this issue now. Feel free to ask any additional questions if you have.

**Comment by juacq97** [comment]
>  I think your current mapping may fail for filenames with space characters.

You are right, it fails for all the files with spaces, and it caused me problems with those files that I do not open with emacs, for example, the pdf, images or videos.

**But** I noticed that in the configuration file there is a script for the `open` command, so I slighty modified it:

```
cmd open &{{
    case $(file --mime-type "$f" -b) in
        text/*) /home/$USER/.config/lf/emc $f;;
        *) for f in $f; do $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```
So, if the file it's a mime text file, it opens with the `emc` script, that I has put on `/home/$USER/.config/lf/`; the & is to prevent the terminal from hanging. The `emc` script has this:

```
#! /bin/sh

emacsclient -c $1
```
And that's it. I revert the `set  ifs` option  to `set ifs "\n"` and now all works flawlessly.
