### ISSUE TITLE
new lfcd in zsh tmux

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1420]
I source the new lfcd.sh in my zshrc
I  start `tmux new lf` 
to be able to 
`map | $tmux split-window -vl23 -c`
and spawn another lf
`tmux splitw -h lf`
the vsplit opens a terminal under lf in the same directory but if I close lf I end up in my ~/

EDIT: even without tmux and an alias lf='lfcd' cd on exit does not work

![shop-2023-09-13-20-16](https://github.com/gokcehan/lf/assets/69777713/73213aba-2c5d-4a3f-8652-1e2a91c8df25)

**Comment by joelim-work** [comment]
When you are referring to the _new_ `lfcd.sh`, do you mean the one introduced in https://github.com/gokcehan/lf/pull/1402?

Are you running the latest version of `lf` built from master, and also do the below commands work for you?

```
lf -print-last-dir
```

```
cd "$(lf -print-last-dir)"
```

**Comment by se7en-x230** [comment]
> When you are referring to the _new_ `lfcd.sh`, do you mean the one introduced in #1402?
> 
> Are you running the latest version of `lf` built from master, and also do the below commands work for you?

yes 

` lf -version
r30-ig3
`
zshrc 
`lfcd () {
    # `command` is needed in case `lfcd` is aliased to `lf`
    cd "$(command lf -print-last-dir "$@")"
}

 bindkey -s '^o' 'lfcd\n'  # zsh
`
`alias lf="lfcd"`

**Comment by se7en-x230** [comment]
Sorry for the trouble ... I have not changed my alias for building and was still building  from  joelim-work 

All good sorry again my mistake all works fine

**Comment by joelim-work** [comment]
That's not very much for me to go on with, but one other thing to notice is that if you end up in your home directory, it's possible that `lf` doesn't output anything, in which case `cd` is called with no arguments. You'll sort of have to debug this on your own and see:

- `command lf -print-last-dir` should print the last directory to stdout
- Wrapping it in `cd $(...)` should take that result and pass it as an argument to `cd`
- Placing that in `lfcd() {...}` should create a function so all of that happens when you type `lfcd` on the command line
- Then once `lfcd` works, you can bind it however you want.

**Comment by se7en-x230** [comment]
hmmm I fail to find my mistake.

1. I add 
`lfcd () { 
cd "$(command lf -print-last-dir "$@")"
}`
to my .zshrc 

lfcd works as expected.

2. I add 
`alias lf="lfcd" `
to my aliasrc 

Now lf starts lfcd and exit works.

3. next step would be to start the entire thing in tmux. This is where I struggle.

![shop-2023-09-14-10-18](https://github.com/gokcehan/lf/assets/69777713/81c07e40-ce94-47f7-a7df-32f8c1c146d3)

**Comment by joelim-work** [comment]
Try `tmux new -c "$(command lf -print-last-dir)"`

**Comment by se7en-x230** [comment]
> Also I'm glad to see that it's not actually an issue with `lf` or `lfcd` itself.
yes it' my brain :)

would I be able to actually add that to the zsh function in my .zshrc?

**Comment by joelim-work** [comment]
> would I be able to actually add that to the zsh function in my .zshrc?

I think in theory yes, why don't you try it out?

**Comment by se7en-x230** [comment]
I will. That would make things much easier 

I just stuggle already with syntax and quotations ' " in the alias :)

**Comment by se7en-x230** [comment]
not pretty but I guess it works.

`lfcd() {
    local session_name="lf_session"

    # Check if the session already exists
    if [ -n "$TMUX" ]; then
        cd "$(command lf -print-last-dir)"
    elif tmux has-session -t $session_name 2>/dev/null; then
        tmux attach -t $session_name
    else
        tmux new-session -d -s $session_name
        tmux send-keys -t $session_name 'cd "$(command lf -print-last-dir)"' C-m
        tmux attach -t $session_name
    fi
}`

and i map Q to tmux kill-window
while q quits into the directory lf is in.
