### ISSUE TITLE
[Feature] Search within marks in free text

### ISSUE THREAD

**Issue by mertnuhoglu** [gokcehan/lf#1421]
I have more than 20 paths in marks. I forget which path is mapped to which letter. It would be very nice if I could filter the list of marks as I type some string within the path similar to fzf.

**Comment by joelim-work** [comment]
The marks are stored in `~/.local/share/lf/marks`. You should be able to pipe the contents of that file into `fzf`, and then call `lf -remote "send $id ..."` based on the result.

**Comment by gokcehan** [comment]
@mertnuhoglu Something along the following should work as @joelim-work suggested:

```
map B $lf -remote "send $id cd '$(cat ~/.local/share/lf/marks | fzf | cut -d: -f2)'"
```
