### ISSUE TITLE
Newest build from git and statfmt

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1423]
`set statfmt "\033[33;1m %p \033[0m\033[32;1m %u %g \033[0m\033[37;1m %c \033[0m\033[34;1m %s \033[0m:\033[31;1m %t \033[0m\033[36;1m %l \033[0m"
`

I build the latest version and now stafmt does not show at all anymore. It did a couple weeks back.
Did the syntax change?

**Comment by joelim-work** [comment]
Yes you now need to separate all the different components with `|`, see #1337 

The idea is that you can split the stat info into different sections, and if a section contains a failed expansion, then the entire section is not shown. Without any `|`, there is one big implicit section, so if any expansion (e.g. link target) fails, then nothing will be shown.

**Comment by se7en-x230** [comment]
Thanks
