### ISSUE TITLE
 [Feature] Filter by date and size

### ISSUE THREAD

**Issue by Inginn** [gokcehan/lf#1424]
I would love a filter by date and size.
I use **flat -1** in my downloads folders and would love to be able to filter the results by date or size.

**Comment by gokcehan** [comment]
@Inginn Unfortunately, we don't have a `flat` command in `lf`.

**Comment by Inginn** [comment]
I am a dumb ass, I use both Ranger and lf but somehow managed to make a feature request for ranger here, Sorry.
