### ISSUE TITLE
Sixel previews don't work

### ISSUE THREAD

**Issue by yonas** [gokcehan/lf#1433]
I have `set sixel true` in `~/.config/lf/lfrc`.

Using `foot` terminal: foot version: 1.15.3 (Aug 30 2023, branch 'master') +pgo +ime -graphemes -assertions
lf: c816343
go: `1.20.3 linux/amd64`

**Comment by DusanLesan** [comment]
How does your preview script look like? Is it similar to the example script from here: https://github.com/gokcehan/lf/pull/1211

**Comment by yonas** [comment]
@DusanLesan Thanks. I don't have a preview script. If `lf` supports sixel, why do I need one?
