### ISSUE TITLE
internal editor variable

### ISSUE THREAD

**Issue by muellerto** [gokcehan/lf#144]
I use lf on Windows. So I get notepad.exe as the default editor. Could I change this? I never use notepad, for nothing, I want gvim.

**Comment by gokcehan** [comment]
You can set your `%EDITOR%` variable to `gvim` and `lf` should pick it up automatically. See the documentation for more info about default variables.

Closing this issue now. Feel free to ask further questions.

**Comment by wdscxsj** [comment]
@gokcehan Can we set the editor in the config file? Maybe someone (i.e. me) wants to reserve the global `%EDITOR%` for all foolish-and-smart things, and use `lf` for "pro" work only. Thank you!

**Comment by gokcehan** [comment]
@wdscxsj `EDITOR` variable is only there to guess the name of the preferred editor. You don't have to use it at all. Currently we don't have a mechanism to set environmental variables but you can define a custom command for your edit key like so:

    map e $nano $f

You can also make an alias for `lf` with the corresponding `EDITOR` value if you like:

    alias lf="EDITOR=nano lf"

If you're using the example configuration file, you may also want to change the `open` command to use the editor of your choice. Hope this helps.

**Comment by wdscxsj** [comment]
@gokcehan Thank you! The key mapping is all I need. But `$f` is supposed to be the current file's path, isn't it? When I try the official lf r11 on Windows, the editor receives `$f` verbatim.

**Comment by gokcehan** [comment]
@wdscxsj Sorry, that was for unix. On windows, you can do something like:

    map e $notepad %f%

**Comment by wdscxsj** [comment]
@gokcehan Thanks a lot! Finally feeling cozy with Windows command line. 😄
