### ISSUE TITLE
mapped copy command to other keybindings and get error message

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1441]
I download r31 version, and doesnt work anymore my custom keybindings for copy and move. My lfrc contains the following rows:

```
# Remove default bindings
map d
map y

# Custom keybindings
map dd :cut
map yy copy

```
When I press y, I get error message: Unknown mapping y.

**Comment by joelim-work** [comment]
I can't reproduce, `yy` works perfectly fine for me with your config file. Have you tried using the `:maps` command to display the current mappings?

**Comment by og900aero** [comment]
Sorry. My mistake. My config contains an error, that cause global problem.
