### ISSUE TITLE
how can custom column width

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1454]
when i use TMUX first open lf
![image](https://github.com/gokcehan/lf/assets/87791643/4d6a5b16-e50b-4d3b-b36f-15d33ed3acd1)

the column Wight is nice,

when i close lf  and reopen ,
![image](https://github.com/gokcehan/lf/assets/87791643/553a2731-4a39-4a2e-978c-a1b6352bcfb0)

lf column is short

**Comment by joelim-work** [comment]
You should set the `ratios` command, although judging from #1459 it looks like you found it already.
