### ISSUE TITLE
File preview not working when using lf_kitty_preview

### ISSUE THREAD

**Issue by leoriohub** [gokcehan/lf#1457]
I followed the instructions on the wiki to enable image preview using kitty and it works! unfortunately, plain text files are not previewed anymore. Did I do something wrong or it is an intended behavior?. If I go back to a vanilla config, plain text files are previewed correctly.

**Comment by joelim-work** [comment]
I'm not sure how clearly the documentation explains it, but if you use set `previewer`, it applies to all files, not just images. For plain text files, you need to ensure the `previewer` writes the content to stdout (e.g. using `cat`), which will then be read and stored by `lf`.

The [sixel example](https://github.com/gokcehan/lf/wiki/Previews#with-sixel) demonstrates this technique.

**Comment by joelim-work** [comment]
Closing as there is no issue with `lf` itself. Feel free to reopen if you still have issues.

**Comment by pavvd** [comment]
Noob here with the same issue. Don't have much clue about shell scripts, so I "merged" Sixtel and Kitty preview examples and my **~/.config/lf/lf_kitty_preview** looks like this now:
```
#!/usr/bin/sh
file=$1
w=$2
h=$3
x=$4
y=$5

case "$(file -Lb --mime-type -- "$1")" in
    image/*)
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
        exit 1
        ;;
    *)
        cat "$1"
        ;;
esac

pistol "$file"
```
Somehow it works.

**Comment by DusanLesan** [comment]
> ```
>    *)
>        cat "$1"
>        ;;
>esac
>
>pistol "$file"
> ```

@pavvd What does pistol do in this case? Looks like you are matching images first, and then everything else with `*` and displaying with `cat`. Using both pistol and `*) cat` seems unnecessary to me

**Comment by pavvd** [comment]
@DusanLesan I think, you are right. Like I said I just copied parts of one script into another until it started **working**. I have no skill to take part in discussion about shell scripting. Just needed this thing fixed.
