### ISSUE TITLE
how to run command lf , just show two colume

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1459]
![image](https://github.com/gokcehan/lf/assets/87791643/b531dbc1-1aa4-476e-a715-1326fcd5880b)

i try this , but not work

**Comment by newyorkthink** [comment]
> ```shell
> lf -command 'set ratios 1:2'
> ```

i use this command but, not working


https://github.com/gokcehan/lf/assets/87791643/01337883-b676-473c-afd9-0b48fc6709c0

**Comment by joelim-work** [comment]
I played through your video and can see that when `lf` starts up there's a very short amount of time when the `ratios` is actually `1:2`, before being set back to `1:2:3`. There's probably something in your config file that causes that to happen.

![image](https://github.com/gokcehan/lf/assets/50560759/804d5136-9043-47b4-b2d3-7e29dba38aeb)

**Comment by newyorkthink** [comment]
```
# Dynamically set info displayed based on the number of panels
# cmd resize_panels %{{
# 	w=$(tmux display-message -p '#{pane_width}' || tput cols)
# 	if [ $w -le 62 ]; then
# 		lf -remote "send $id set ratios 1:4"
# 		lf -remote "send $id set nopreview"
# 	elif [ $w -le 80 ]; then
# 		lf -remote "send $id set ratios 1:2:2"
# 	elif [ $w -le 100 ]; then
# 		lf -remote "send $id set ratios 1:2:3"
# 	else
# 		lf -remote "send $id set ratios 1:2:7"
# 	fi
# }}
# resize_panels
```

its this config,  i found
