### ISSUE TITLE
result of a <paste> operation it not shown

### ISSUE THREAD

**Issue by muellerto** [gokcehan/lf#146]
if I copy a file using &lt;copy&gt;, change the directory and &lt;paste&gt; the result is not shown. Nevertheless the file has indeed been copied. But to see it really on it's new place I must change the directory and come back or do &lt;reload&gt;.

I use lf on Windows.

**Comment by gokcehan** [comment]
This works fine in unix systems but fails in windows. Copy and move operations are currently implemented using `robocopy` which has some problems that I can't get my head around. But I have been working on builtin copy and move operations for a while and I'm planning to push these in the upcoming days. Then, this problem should not happen anymore. Keeping this issue open for the while.

**Comment by muellerto** [comment]
> But I have been working on builtin copy and move operations for a while and I'm planning to push these in the upcoming days.

I guess this would really be the best solution.

**Comment by gokcehan** [comment]
@muellerto I have now added builtin copy and move operations which should not have this problem. I have also made a new release (r11) including this change. Closing this issue now. Feel free to reopen if necessary.
