### ISSUE TITLE
Is there a way to change the date format?

### ISSUE THREAD

**Issue by aabbccddeeffggj** [gokcehan/lf#1462]
Hi, currently my lf displays dates this way: "Tue  Sep  26  22:33:23  2023"
How can I manage it to look like "26/09/2023  - 10:33PM" or something similar?
Thanks.

**Comment by joelim-work** [comment]
See the `timefmt` option.

**Comment by aabbccddeeffggj** [comment]
> See the `timefmt` option.

It worked, thanks a lot.
For anyone who might need this help: go to "lfrc" and add " set timefmt 'Mon Jan _2 15:04:05 2006' " and replace the format with the one you would like.
