### ISSUE TITLE
copy an entire directory tree produces wrong result

### ISSUE THREAD

**Issue by muellerto** [gokcehan/lf#147]
I stand on a directory and want to copy that directory with all it's contents (files, subdirectories, hidden files, symbolic links) to another place. The structure of that tree should remain the same.

I used &lt;copy&gt;, select the destination and &lt;paste&gt;. In my case lf copied only the top most directory and the one file which was located at the origin correctly. All the subfolders have been copied to the home directory which is a totally wrong destination.

I use lf under Windows.

**Comment by gokcehan** [comment]
@muellerto As I mentioned in #146, we have a builtin copy/move implementation on its way, which should not have this problem. Keeping this issue open for the while.

**Comment by gokcehan** [comment]
@muellerto As I said in the other issue, builtin copy and move operations are now implemented and a new release is made (r11). Closing this issue now. Feel free to reopen if neccessary.
