### ISSUE TITLE
Is there a light color theme?

### ISSUE THREAD

**Issue by jabbalaci** [gokcehan/lf#1483]
I use light background in my terminal and when I start **lf**, it looks terrible. How to make it look acceptable? I don't want to use dark background, my eyes can't bear that. Thanks.

**Comment by gokcehan** [comment]
@jabbalaci By default, we inherit the same color configuration for `ls` in `lf`. You should be able to change this configuration to your liking. See the "Colors" section in the documentation.

**Comment by jabbalaci** [comment]
Thanks! I looked after it and I'll have to modify my `LS_COLORS` environment variable. Indeed, if I make changes, these changes also appear in `lf`.

Does anyone have some good settings for `LS_COLORS`  that is made for light background?

**Comment by gokcehan** [comment]
@jabbalaci Thank you for the example. Closing this issue now.

**Comment by CatsDeservePets** [comment]
> Hello I just tried vivid to change theme. But the bold font is gone. How do I bring back bold fonts in lf ?

This is controlled by `$LS_COLORS`. You can try different `vivid` themes.
