### ISSUE TITLE
promptfmt should reflect in terminal window title

### ISSUE THREAD

**Issue by avidseeker** [gokcehan/lf#1484]
1. Open up a graphical terminal.
2. Edit a file in Vim
3. Terminal window title changes to: `[No Name] - VIM`.

This is done using Operating System Command (OSC) escape sequence. For example, try this:
```bash
echo -ne "\033]0;Your Title Here\007"
```

It would be helpful to have info like promptfmt reflected in the window title of the terminal.

**Comment by gokcehan** [comment]
@avidseeker You can use hooks such as `on-cd` and `on-quit` for such purposes. See the doc/wiki and the previous discussions in #262 #544 #614 for some examples.

**Comment by avidseeker** [comment]
Thank you. Btw, the line in the Wiki can be more efficient; no need to invoke sed

```bash
	printf "\033]0; ${PWD/#$HOME/\~}\007" > /dev/tty
```

**Comment by avidseeker** [comment]
As for Konsole, it uses a slightly different escape code. You can add this to the [Wiki](https://github.com/gokcehan/lf/wiki/Tips#show-current-directory-in-window-title) to make it more compatible

```bash
	printf "\033]0; ${PWD/#$HOME/\~}\007" > /dev/tty
	printf "\033]30; ${PWD/#$HOME/\~}\007" > /dev/tty # Konsole escape code
```

**Comment by gokcehan** [comment]
@avidseeker Thank you for the suggestions. Note, wiki is publicly editable and maintained by the community. I'm not sure if those brace expansions are posix compatible. Maybe that's the reason they used `sed` instead, I'm not sure.

**Comment by avidseeker** [comment]
Thanks, I updated the Wiki.

It should be Posix-compatible: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

**Comment by gokcehan** [comment]
@avidseeker If I'm not mistaken, parameter expansions are posix compatible, but not the one that you are using. Try this:

```
$ bash -c 'printf "${PWD/#$HOME/\~}\n"'
~
$ sh -c 'printf "${PWD/#$HOME/\~}\n"'
sh: 1: Bad substitution
```
