### ISSUE TITLE
cannot bind to Shift-F4

### ISSUE THREAD

**Issue by jabbalaci** [gokcehan/lf#1488]
In MC, Shift-F4 is used to create a new file. I wanted to mimic it in `lf` but pressing this combo makes this warning:

    unknown mapping: S

Shift-F5 to Shift-F12 work well:

    unknown mapping: <s-f-5>
    ...
    unknown mapping: <s-f-12>

However, Shift-F1 to Shift-F4 behave differently. I'm under Linux (Manjaro, XFCE).

Is it possible to bind something to Shift-F4 ?

**Comment by joelim-work** [comment]
Shift-F4 works fine for me, it might be a system-specific issue. Does that mean if you map something to capital S (e.g. `map S down`) you can trigger it using Shift-F4?

**Comment by jabbalaci** [comment]
Thanks. Yes, it must be a system setting. The binding you suggest works but it moves down the cursor 2 positions, so it's not perfect. `S` goes down one, Shift-F4 goes down 2 lines. I'll try to figure out what causes this. I use konsole but it has no binding to Shift-F4.

In the micro text editor we can see what event each keypress produces (raw mode). Here is mine: https://i.imgur.com/CZsFTv7.png . The last three lines were produced with Shift-F4.

**Comment by joelim-work** [comment]
I'm quite sure this is not an issue with `lf` itself, and more to do with the terminal and/or its settings. I don't use konsole myself so I won't be able to help further, but anyway feel free to update this thread if you find the issue.

**Comment by jabbalaci** [comment]
Right, this is a terminal emulator issue. I'm using konsole. I tried a different one (alacritty), and there it worked well. However, alacritty didn't realize `Ctrl-/` , which works well in konsole. It's hard to find a good terminal emulator.
