### ISSUE TITLE
lf cannnot choose an application

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1489]
![image](https://github.com/gokcehan/lf/assets/87791643/c90bdc58-d866-4826-b11c-2505d48feae4)

**Comment by joelim-work** [comment]
I think this message comes from [`mimeopen`](https://github.com/mbeijen/File-MimeInfo). I suspect what happened is that you tried to open a file and `mimeopen` couldn't provide any suggestions for that file type, nothing to do with `lf`.

**Comment by newyorkthink** [comment]
> I think this message comes from [`mimeopen`](https://github.com/mbeijen/File-MimeInfo). I suspect what happened is that you tried to open a file and `mimeopen` couldn't provide any suggestions for that file type, nothing to do with `lf`.

i try but , i test ,it not work
![image](https://github.com/gokcehan/lf/assets/87791643/2848dee7-1cd1-44d1-a62c-833d97fbb96b)
![image](https://github.com/gokcehan/lf/assets/87791643/2210e7b7-7fb9-44f2-a03e-0ecffef434ee)
![image](https://github.com/gokcehan/lf/assets/87791643/0d3275fb-9a5a-41ea-ab45-dee073262820)
![image](https://github.com/gokcehan/lf/assets/87791643/b5b3bda9-1c86-4368-8a5c-bbc620bdb856)

**Comment by DusanLesan** [comment]
What does `xdg-mime query appimage.py` return for you? How about `mimetype -Mb appimage.py`? Second one might not be installed for yous since on my system is only optional dependency

Either way, for me the type is `text/x-python`

**Comment by joelim-work** [comment]
I got `text/x-python` too, when I tried it myself.

Also, do you happen to have a `mimeinfo.cache` file? It should be located at `/usr/share/applications`. I think this is where `mimeopen` loads its suggestions from.

It would be helpful if you show us what happens if you try running `mimeopen -a appimage.py` on the command line without using `lf`.

**Comment by joelim-work** [comment]
Closing as this is not an issue with `lf`.
