### ISSUE TITLE
active panel on resize and ratios change

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#1495]
I have set the following `on-redraw` command:
```
cmd on-redraw &{{
    if [ $lf_width -lt 90 ]; then
        lf -remote "send $id set preview false"
        lf -remote "send $id set ratios 1"
        $lf_cleaner
    elif [ $lf_width -lt 110 ]; then
        lf -remote "send $id set preview true"
        lf -remote "send $id set ratios 1:1"
    else
        lf -remote "send $id set preview true"
        lf -remote "send $id set ratios 3:5"
    fi
}}
```
It works fine, except that when going from ratios 1 to ratios 1:1 (one more pane), instead of opening the preview on the last pane and keep my cursor where it is, lf opens a panel with the parent directory and my cursor is still on the right panel.
It can be fixed by calling `redraw` after setting the ratio, however it seems that it triggers an infinite loop if I call it inside `on-redraw`, so the solution I found so far it to do it manually (pressing `<C-l>`). 
Is there a better way?

**Comment by joelim-work** [comment]
This is because when you go from `ratios 1` to `ratios 1:1`, the `set preview true` command fails as there is currently only one window. Please see the advice for [toggling the preview column](https://github.com/gokcehan/lf/wiki/Tips#toggling-the-preview-column) in the wiki:

> Note that the order of commands can matter. For example, `preview` cannot be enabled if `ratios` contains only a single number, so if `ratios` is currently set to `1`, then you must use `set ratios 1:1; set preview true` instead of `set preview true; set ratios 1:1`.

As you might have guessed, calling `redraw` inside the `on-redraw` hook is not a good idea.

**Comment by lucas-mior** [comment]
Indeed, setting preview to true *after* setting the ratio back to 1:1 worked. Thanks.
