### ISSUE TITLE
Icons not visiable in arch 

### ISSUE THREAD

**Issue by Sarthak950** [gokcehan/lf#1497]
I am using bash and alacrity as the terminal i have Jet Brains nerd font installed and fully working in neovim but cant get to work in "lf" 

i pasted this in the `~/.bashrc` and sourced it using `source .bashrc` but it did not work 

![231115_09-32-46](https://github.com/gokcehan/lf/assets/93645760/180d3d83-79a4-474e-828c-80a45e2ff624)

scraped the internet did not found any solution Help.

**Comment by joelim-work** [comment]
That definition looks fine. Did you enable the icons to be displayed using `set icons true`?

**Comment by Sarthak950** [comment]
yes i have set icons true
![231115_10-47-02](https://github.com/gokcehan/lf/assets/93645760/abeae8c7-ebca-4bcc-88d2-42de83b40b66)
![231115_10-47-43](https://github.com/gokcehan/lf/assets/93645760/13de5bbd-aa56-48f3-9cd4-7f05c62d91ba)

**Comment by joelim-work** [comment]
OK, so you have icons enabled, but it shows the default ones and not the ones you have defined. That would mean `lf` somehow didn't pick up the `LF_ICONS` environment variable. What do you see if you type `!env` or `!printenv LF_ICONS` in the command line inside `lf`?

**Comment by Sarthak950** [comment]
it show this on !env 
SHELL=/bin/bash
WINDOWID=94008242234560
lf_truncatepct=100
COLORTERM=truecolor
HYPRLAND_CMD=Hyprland
lf_shellopts=
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
lf_ratios=1:2:3
XDG_BACKEND=wayland
lf_dircache=true
lf=/usr/bin/lf
lf_numberfmt=
lf_ignorecase=true
OPENER=xdg-open
lf_cursorpreviewfmt=
lf_preserve=mode
lf_height=47
id=57235
DESKTOP_SESSION=hyprland
lf_incfilter=false
lf_timefmt=Mon Jan _2 15:04:05 2006
lf_ignoredia=true
lf_count=1
XCURSOR_SIZE=3
lf_number=false
EDITOR=vi
GTK_MODULES=canberra-gtk-module
lf_ifs=
XDG_SEAT=seat0
lf_smartcase=true
lf_findlen=1
PWD=/home/sarthak
lf_dirpreviews=false
lf_icons=true
fx=/home/sarthak/.anydesk
LOGNAME=sarthak
XDG_SESSION_DESKTOP=hyprland
fs=
XDG_SESSION_TYPE=wayland
lf_cursoractivefmt=
lf_filesep=

lf_incsearch=false
lf_sixel=false
lf_ruler=
lf_hiddenfiles=.*
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/sarthak
lf_anchorfind=true
MOTD_SHOWN=pam
lf_wrapscroll=false
f=/home/sarthak/.anydesk
LF_LEVEL=1
HOME=/home/sarthak
LANG=en_US.UTF-8
_JAVA_AWT_WM_NONREPARENTING=1
XDG_CURRENT_DESKTOP=Hyprland
lf_infotimefmtnew=Jan _2 15:04
lf_waitmsg=Press any key to continue
lf_history=true
lf_dirfirst=true
lf_drawbox=true
WAYLAND_DISPLAY=wayland-1
lf_previewer=/home/sarthak/.config/lf/lf_kitty_preview
lf_period=0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
lf_smartdia=false
lf_selmode=all
ALACRITTY_SOCKET=/run/user/1000/Alacritty-wayland-1-57042.sock
lf_hidden=true
lf_shell=sh
lf_globsearch=false
XDG_SESSION_CLASS=user
TERM=alacritty
lf_info=
lf_shellflag=-c
lf_tempmarks='
lf_cleaner=/home/sarthak/.config/lf/lf_kitty_clean
USER=sarthak
lf_width=103
lf_cursorparentfmt=
CUDA_PATH=/opt/cuda
lf_truncatechar=~
HYPRLAND_INSTANCE_SIGNATURE=1b48642fd15c433c53876f1b933dcd46265caf8f_1700011180
lf_dircounts=false
DISPLAY=:0
SHLVL=1
lf_relativenumber=false
MOZ_ENABLE_WAYLAND=1
PAGER=less
lf_promptfmt=%u@%h:%d%f
lf_preview=true
lf_errorfmt=
XDG_VTNR=8
lf_sortby=natural
lf_infotimefmtold=Jan _2  2006
XDG_SESSION_ID=2
lf_dupfilefmt=%f.~%n~
lf_reverse=false
XDG_RUNTIME_DIR=/run/user/1000
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
lf_mouse=false
lf_wrapscan=true
XCURSOR_THEME=Bibata-Modern-Classic
GTK3_MODULES=xapp-gtk3-module
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
lf_statfmt=%p| %c| %u| %g| %S| %t| -> %l
lf_dironly=false
ALACRITTY_LOG=/tmp/Alacritty-57042.log
lf_tabstop=8
GDMSESSION=hyprland
lf_borderfmt=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
lf_scrolloff=0
lf_tagfmt=
MAIL=/var/spool/mail/sarthak
lf_autoquit=false
ALACRITTY_WINDOW_ID=94008242234560
lf_rulerfmt=%a  |%p  | %m   | %c   | %s   | %f   |%i/%t
OLDPWD=/home/sarthak
_=/usr/bin/env
Press any key to continue
SHELL=/bin/bash
WINDOWID=94008242234560
lf_truncatepct=100
COLORTERM=truecolor
HYPRLAND_CMD=Hyprland
lf_shellopts=
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
lf_ratios=1:2:3
XDG_BACKEND=wayland
lf_dircache=true
lf=/usr/bin/lf
lf_numberfmt=
lf_ignorecase=true
OPENER=xdg-open
lf_cursorpreviewfmt=
lf_preserve=mode
lf_height=47
id=57235
DESKTOP_SESSION=hyprland
lf_incfilter=false
lf_timefmt=Mon Jan _2 15:04:05 2006
lf_ignoredia=true
lf_count=1
XCURSOR_SIZE=3
lf_number=false
EDITOR=vi
GTK_MODULES=canberra-gtk-module
lf_ifs=
XDG_SEAT=seat0
lf_smartcase=true
lf_findlen=1
PWD=/home/sarthak
lf_dirpreviews=false
lf_icons=true
fx=/home/sarthak/.anydesk
LOGNAME=sarthak
XDG_SESSION_DESKTOP=hyprland
fs=
XDG_SESSION_TYPE=wayland
lf_cursoractivefmt=
lf_filesep=

lf_incsearch=false
lf_sixel=false
lf_ruler=
lf_hiddenfiles=.*
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/sarthak
lf_anchorfind=true
MOTD_SHOWN=pam
lf_wrapscroll=false
f=/home/sarthak/.anydesk
LF_LEVEL=1
HOME=/home/sarthak
LANG=en_US.UTF-8
_JAVA_AWT_WM_NONREPARENTING=1
XDG_CURRENT_DESKTOP=Hyprland
lf_infotimefmtnew=Jan _2 15:04
lf_waitmsg=Press any key to continue
lf_history=true
lf_dirfirst=true
lf_drawbox=true
WAYLAND_DISPLAY=wayland-1
lf_previewer=/home/sarthak/.config/lf/lf_kitty_preview
lf_period=0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
lf_smartdia=false
lf_selmode=all
ALACRITTY_SOCKET=/run/user/1000/Alacritty-wayland-1-57042.sock
lf_hidden=true
lf_shell=sh
lf_globsearch=false
XDG_SESSION_CLASS=user
TERM=alacritty
lf_info=
lf_shellflag=-c
lf_tempmarks='
lf_cleaner=/home/sarthak/.config/lf/lf_kitty_clean
USER=sarthak
lf_width=209
lf_cursorparentfmt=
CUDA_PATH=/opt/cuda
lf_truncatechar=~
HYPRLAND_INSTANCE_SIGNATURE=1b48642fd15c433c53876f1b933dcd46265caf8f_1700011180
lf_dircounts=false
DISPLAY=:0
SHLVL=1
lf_relativenumber=false
MOZ_ENABLE_WAYLAND=1
PAGER=less
lf_promptfmt=%u@%h:%d%f
lf_preview=true
lf_errorfmt=
XDG_VTNR=8
lf_sortby=natural
lf_infotimefmtold=Jan _2  2006
XDG_SESSION_ID=2
lf_dupfilefmt=%f.~%n~
lf_reverse=false
XDG_RUNTIME_DIR=/run/user/1000
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
lf_mouse=false
lf_wrapscan=true
XCURSOR_THEME=Bibata-Modern-Classic
GTK3_MODULES=xapp-gtk3-module
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
lf_statfmt=%p| %c| %u| %g| %S| %t| -> %l
lf_dironly=false
ALACRITTY_LOG=/tmp/Alacritty-57042.log
lf_tabstop=8
GDMSESSION=hyprland
lf_borderfmt=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
lf_scrolloff=0
lf_tagfmt=
MAIL=/var/spool/mail/sarthak
lf_autoquit=false
ALACRITTY_WINDOW_ID=94008242234560
lf_rulerfmt=%a  |%p  | %m   | %c   | %s   | %f   |%i/%t
OLDPWD=/home/sarthak
_=/usr/bin/env

**Comment by Sarthak950** [comment]
and nothin on `printenv LF_ICONS` and an error `running shell: exit status 1`

**Comment by joelim-work** [comment]
Don't worry about `printenv`, that error message probably just means you don't have it installed.

Anyway according to the output of `env`, I don't see `LF_ICONS` (in capital letters), which means it's not defined in the environment `lf` is running in, and explains why you see the default icons. Are you sure you `source`d the file correctly? I'm not sure what you did, but running something like `LF_ICONS='fi=F' lf` should just work.

Also `env` does print all your environment variables, you might want to check if there's any sensitive data in there.

**Comment by Sarthak950** [comment]
i deleted the env output incase i mis any thing sensitive

also i sourced it through the command `source .bashrc`
and where should i run LF_ICONS='fi=F' lf

**Comment by Sarthak950** [comment]
![231115_12-33-22](https://github.com/gokcehan/lf/assets/93645760/11bf16d9-91b1-4792-83f7-d18cfacc968d)
i did this and noting seems to have happened

**Comment by joelim-work** [comment]
You should run `LF_ICONS='fi=F' lf` directly on the command line, or put `export LF_ICONS='fi=F'` in your `.bashrc` file.

That being said, why do you have `exec fish` in your `.bashrc` file? I think that will cause everything below to not be processed.

**Comment by Sarthak950** [comment]
yes i just moved it down and they seem to work now 
thanks @joelim-work

**Comment by joelim-work** [comment]
No worries, glad you fixed your problem. Closing this issue.
