### ISSUE TITLE
Search question

### ISSUE THREAD

**Issue by davmaz** [gokcehan/lf#150]
I just noticed that hitting Tab after a search / shows possible completions. However, if I let tab complete, it does not take me to that file or directory. What am I missing? Thanks!

**Comment by gokcehan** [comment]
@davmaz I guess autocompletion in searching is only accidental. We should either disable it or make it work with file names. Then we can also decide what should happen when it matches.

**Comment by davmaz** [comment]
Well, I guess it wasn't a big surprise -- using bash probably. It would be great if it actually did jump to the file. I thought it might be searching subdirectories since some of the possible completions were not in the current directory.

**Comment by davmaz** [comment]
This was just bash doing its thing. No need for changes.
