### ISSUE TITLE
No previews or opening in nvim but works in Ranger !

### ISSUE THREAD

**Issue by thorrrr** [gokcehan/lf#1501]
Hello anybody free for a quick query please 
How do you get documents to preview in LF and open in Nvim?
If i look at my docs in Ranger they preview and open in nvim but in LF i see no previews in terminal and nothing opens when pressing e!
 i have tried adding some code in the lfrc file but it freaks out lf So i guess i am doing some dumb noob stuff i have read the docs but what ever i try does not work! Open files with Neovim mime "^text/" , x/^text/markdown$/ , x/^text/plain$/ { $EDITOR "nvim %s" } I have also tried Open code files with Neovim mime ".c$" , ".cpp$" , ".h$" , ".py$" , ".js$" , ".java$" , ".sh$" , ".rb$" , ".pl$" , ".go$" , ".php$" , ".html$" , ".css$" , ".xml$" , ".json$" , ".yaml$" , ".toml$" { "nvim" %s } But again lf freezes up ! So not sure what i am doing wrong this is my main config lfrc
https://logs.notifiarr.com/?8205c17d7b662704#29jNoZBmEAruAeCoo9vQV2bBAUtoL6dVwo2FpGyGtTdY

**Comment by TheYellowArchitect** [comment]
Hello, newbie here. I pretty much got ready-made configs, but I'm pretty sure this is the part you are looking for. In `.config/lf/lfrc`
```bash
cmd open ${{
    case $(file --mime-type "$(readlink -f $f)" -b) in
	application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) localc $fx ;;
	image/vnd.djvu|application/pdf|application/octet-stream|application/postscript) setsid -f zathura $fx >/dev/null 2>&1 ;;
        text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;
	image/x-xcf) setsid -f gimp $f >/dev/null 2>&1 ;;
	image/svg+xml) display -- $f ;;
	image/*) rotdir $f | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|avif\|tif\|ico\)\(_large\)*$" |
		setsid -f nsxiv -aio 2>/dev/null | while read -r file; do
			[ -z "$file" ] && continue
			lf -remote "send select \"$file\""
			lf -remote "send toggle"
		done &
		;;
	audio/*|video/x-ms-asf) mpv --audio-display=no $f ;;
	video/*) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;
	application/pdf|application/vnd.djvu|application/epub*) setsid -f zathura $fx >/dev/null 2>&1 ;;
	application/pgp-encrypted) $EDITOR $fx ;;
	application/vnd.openxmlformats-officedocument.wordprocessingml.document|application/vnd.oasis.opendocument.text|application/vnd.openxmlformats-officedocument.spreadsheetml.sheet|application/octet-stream|application/vnd.oasis.opendocument.spreadsheet|application/vnd.oasis.opendocument.spreadsheet-template|application/vnd.openxmlformats-officedocument.presentationml.presentation|application/vnd.oasis.opendocument.presentation-template|application/vnd.oasis.opendocument.presentation|application/vnd.ms-powerpoint|application/vnd.oasis.opendocument.graphics|application/vnd.oasis.opendocument.graphics-template|application/vnd.oasis.opendocument.formula|application/vnd.oasis.opendocument.database) setsid -f libreoffice $fx >/dev/null 2>&1 ;;
        *) for f in $fx; do setsid -f $OPENER $f >/dev/null 2>&1; done;;
    esac
}}

```

Specifically this line `text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;` with $EDITOR being a enviroment variable (.zprofile) equal to "nvim" (so if you replace the above $EDITOR with "nvim", it should work)
`export EDITOR="nvim"`

The above command (open) is binded by default to the character `l` (see `man lf`)

**Comment by thorrrr** [comment]
> Hello, newbie here. I pretty much got ready-made configs, but I'm pretty sure this is the part you are looking for. In `.config/lf/lfrc`
> 
> ```shell
> cmd open ${{
>     case $(file --mime-type "$(readlink -f $f)" -b) in
> 	application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) localc $fx ;;
> 	image/vnd.djvu|application/pdf|application/octet-stream|application/postscript) setsid -f zathura $fx >/dev/null 2>&1 ;;
>         text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;
> 	image/x-xcf) setsid -f gimp $f >/dev/null 2>&1 ;;
> 	image/svg+xml) display -- $f ;;
> 	image/*) rotdir $f | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|avif\|tif\|ico\)\(_large\)*$" |
> 		setsid -f nsxiv -aio 2>/dev/null | while read -r file; do
> 			[ -z "$file" ] && continue
> 			lf -remote "send select \"$file\""
> 			lf -remote "send toggle"
> 		done &
> 		;;
> 	audio/*|video/x-ms-asf) mpv --audio-display=no $f ;;
> 	video/*) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;
> 	application/pdf|application/vnd.djvu|application/epub*) setsid -f zathura $fx >/dev/null 2>&1 ;;
> 	application/pgp-encrypted) $EDITOR $fx ;;
> 	application/vnd.openxmlformats-officedocument.wordprocessingml.document|application/vnd.oasis.opendocument.text|application/vnd.openxmlformats-officedocument.spreadsheetml.sheet|application/octet-stream|application/vnd.oasis.opendocument.spreadsheet|application/vnd.oasis.opendocument.spreadsheet-template|application/vnd.openxmlformats-officedocument.presentationml.presentation|application/vnd.oasis.opendocument.presentation-template|application/vnd.oasis.opendocument.presentation|application/vnd.ms-powerpoint|application/vnd.oasis.opendocument.graphics|application/vnd.oasis.opendocument.graphics-template|application/vnd.oasis.opendocument.formula|application/vnd.oasis.opendocument.database) setsid -f libreoffice $fx >/dev/null 2>&1 ;;
>         *) for f in $fx; do setsid -f $OPENER $f >/dev/null 2>&1; done;;
>     esac
> }}
> ```
> 
> Specifically this line `text/*|application/json|inode/x-empty|application/x-subrip) $EDITOR $fx;;` with $EDITOR being a enviroment variable (.zprofile) equal to "nvim" (so if you replace the above $EDITOR with "nvim", it should work) `export EDITOR="nvim"`
> 
> The above command (open) is binded by default to the character `l` (see `man lf`) so it's nowhere in my `.config/lf/lfrc`

Cheer for update i had to change my .zshrc file to 
![image](https://github.com/gokcehan/lf/assets/8170673/252e2d73-58d4-4bb3-b033-a8efc40e0d40)

Now working :)
