### ISSUE TITLE
[FR] let tag cmd accept $fx param

### ISSUE THREAD

**Issue by superiums** [gokcehan/lf#1514]
currently, `tag` cmd only accept a char for label.

it's better to accept a second param of files as destination. 

this could enhance the program usage, for i would like to mark new files/folder which was copied from somewhere or was just made.

select is usally for functional usage, such as cp, delete, bulk rename or sth else.
so tag is a better choice to mark it, the purpos is to distinct them from the old ones.

**Comment by joelim-work** [comment]
Allowing `copy` to accept arguments was discussed previously in #1115, and the suggestion was to use `toggle` to select the files first. I think the same applies to `tag` as well.

In fact because `tag` already accepts a single parameter as the tag name, I'm worried this could cause confusion. Would `tag a b c` mean to tag `b`/`c` with the label `a`, or tag `a`/`b`/`c` with the default label?

**Comment by superiums** [comment]
`tag` is short for `tag *` only when **no argument providded**.
`tag a b c` should be regconized as tag  b, c with the tag 'a'.
this should be safe and not break the old version.

**Comment by superiums** [comment]
`toggle` is an additional action, which takes some work more. ( both logically and visual effect)
with current behavor, if you want to tag, you have to see the file selected first.
how about lots of files ?

Thanks a lot for attention.

**Comment by joelim-work** [comment]
If you are scripting this, then it won't be very noticeable if you use `toggle...; tag` compared to `tag ...`.

If you are manually typing this out on the command-line, then I guess it's faster to type `:tag ...`.  Though I'm not sure how many users actually use the command line, especially for tagging files. Normally it's better to map commonly used operations to keybindings.

What is your actual use case regarding tags anyway?

**Comment by superiums** [comment]
i mainly use it in script, as mentioned here: [https://github.com/gokcehan/lf/issues/1512](https://github.com/gokcehan/lf/issues/1512)

**Comment by joelim-work** [comment]
OK, I'll see if anyone else is interested in having `tag` accept arguments, but for now you can use `toggle` followed by `tag`.
