### ISSUE TITLE
Coloured file icons

### ISSUE THREAD

**Issue by slavshik** [gokcehan/lf#1520]
Hello, everyone, and thank you for your work!

I'm sorry if this is a potentially stupid question, but is it possible to configure `lf` to display items with solid text but colorized icons? Colorized icons and solid file names appear consistent across my setup in the following tools:
- [lazygit](https://github.com/jesseduffield/lazygit)
- [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua)
- [Telescope](https://github.com/nvim-telescope/telescope.nvim)

However, this consistency is not present in `lf`, unfortunately. I have managed to copy pictograms from [web-devicons](https://github.com/nvim-tree/nvim-web-devicons) and set them up in [my icons file for lf](https://github.com/slavshik/.dotfiles/blob/main/lf/icons), but I'm stuck when it comes to separating the colors of the icon and the filename.

Here is how it looks in:
**nvim-tree**
<img width="334" alt="Screenshot 2023-12-03 at 22 14 35" src="https://github.com/gokcehan/lf/assets/621317/44cab93d-867d-4c4f-991b-08987c6809db">
**Telescope**
<img width="446" alt="Screenshot 2023-12-03 at 22 14 25" src="https://github.com/gokcehan/lf/assets/621317/dbc84d3c-6092-4f8e-8c8d-a5c8fb699660">

**lazygit**
<img width="374" alt="Screenshot 2023-12-03 at 22 58 12" src="https://github.com/gokcehan/lf/assets/621317/1e2956fa-97b6-47bb-b3e1-f302cedfd9ed">

**lf** 😢
<img width="741" alt="Screenshot 2023-12-03 at 22 14 58" src="https://github.com/gokcehan/lf/assets/621317/aee67647-33b7-4d57-8e6f-97da9d8a22aa">

In lazygit, this feature was added recently [#2968](https://github.com/jesseduffield/lazygit/issues/2968)

I believe it would be fantastic to make this possible in `lf` as well.

**Comment by joelim-work** [comment]
There is already an outstanding issue for this #928, but no one has gotten around to implementing it yet.

I think the main concern is what the configuration syntax should look like. Currently it is like this for the icons file:

```
di	d
ex	x
fi	-
```

And this for the `LF_ICONS` environment variable:

```
di=d:ex=x:fi=-
```

Adding a third column for the colors sounds reasonable, but I think might be a bit of work to implement as parsing is currently handled by a function called `readPairs`: https://github.com/gokcehan/lf/blob/6abce048550a582aff0105012baaf92e940a51da/misc.go#L158

I was going to suggest using commas as a separator, something like:

```
di	d,34
ex	x,32
fi	-     # use the same color as the filename if not specified
```

```
di=d,34:ex,32=x:fi=-
```

**Comment by joelim-work** [comment]
This is now officially supported by #1674
