### ISSUE TITLE
Normalize arguments unused

### ISSUE THREAD

**Issue by Michael-Gallo** [gokcehan/lf#1524]
It seems that the boolean arguments are left completely unused in favor of what's in gOpts. I am not sure whether the intended behavior here is to always use what's in gOpts, to always use what's passed in, or some hybrid behavior but as-is these arguments can be completely removed without changing any behavior.
https://github.com/gokcehan/lf/blob/6abce048550a582aff0105012baaf92e940a51da/nav.go#L199-L209

**Comment by ilyagr** [comment]
Good point. Judging by the callers, I think the intention here was to take into account the directory-specific options for `ignorecase` and `ignoredia`, as in #171. I'm not very familiar with that PR, though, so I'm not sure which behavior would be correct.
