### ISSUE TITLE
Last col shows a displaced line

### ISSUE THREAD

**Issue by zerinoid** [gokcehan/lf#1528]
After upgrading to r31 the last col shows this weird line, no matter how many cols. 
Even launching lf with no config produces the same effect.

![image](https://github.com/gokcehan/lf/assets/37341660/14919288-2238-4d4e-8a95-46bc177305f9)

![image](https://github.com/gokcehan/lf/assets/37341660/c74a63b0-d73f-47ea-a73f-5cab029c41eb)

**Comment by joelim-work** [comment]
Duplicate of #1258, please see that issue on how to solve.
