### ISSUE TITLE
no tabs for lf?

### ISSUE THREAD

**Issue by niksfirefly** [gokcehan/lf#153]
Is there any chance for tabs implementation in lf ?
I found lf way more faster to use than ranger :) but with no tabs it is useless as filemanager :(

Can somebody can confirm - that due to philosophy lf never implement tabs?
regards

**Comment by gokcehan** [comment]
@niksfirefly This was actually one of our non-features from the start. In my opinion, tabs provide an inferior functionality compared to using a screen multiplexer and/or multiple terminals. `lf` is designed to integrate seamlessly to the latter type of workflow. May I suggest you give `tmux` a try?

**Comment by niksfirefly** [comment]
I use tmux with multiple plugins and ranger ofcourse.
I strongly disagree with you.
There are at least 3 problems without tabs in filemanager when you work with projects:
1.I use fast filemanager as previewer for logs/project files/fast copy and download etc. 
so I open only 1 instance per visible window to quickly navigate and see file preview
2.In real world projects I constantly observe/use minimum 5-10 file trees views/tabs so in practice there is no way to put them on one tmux window. Well I can lf instances on additional windows but then I must move several windows to see tail logs or sth else.
3.another problem is shortcuts - use 1 shortcut to move beetween tmux panes and another in filemanager

**Comment by gokcehan** [comment]
@niksfirefly I don't quite understand how some of the things that are possible with tabs are not possible with tmux. In 1 and 2, you seem to describe your current workflow but I don't see how these things are not adaptable for tmux usage. For 3, you can define shell commands in `lf` to switch windows or panes in tmux (e.g. `map t1 $tmux select-window -t 1`), so again I don't see how that is not adaptable. Also I think there are some missing words in your sentences so to be honest I don't quite comprehend what you are actually describing. Please try to rephrase your issues and explain clearly what is currently not possible. In tmux, you have panes and windows and when these are not enough you also have sessions. You should explain why these things are not enough to create a similar workflow to using tabs in your file manager.

**Comment by niksfirefly** [comment]
ok
You cannot use reasonably 10 lf's instances in one tmux window agree?
So If I have project where I use 10 tmux windows for multiple tasks/views
I cant add another 10 tmux windows for filemanager to browse project/resources trees.

Simply put for me for now
tmux+lf without tabs is great replacement for tmux+midnight commander
not bad but not ideal
regards

**Comment by gokcehan** [comment]
@niksfirefly How about sessions? You can launch a new session dedicated to your `lf` instances.

**Comment by AeliusSaionji** [comment]
What do Windows users do?

**Comment by gokcehan** [comment]
@AeliusSaionji On windows, you can either launch multiple terminals or use one of the terminal emulators that provide tabs/panes and such.

**Comment by s-p-k** [comment]
Not the issue reporter but if tabs are such an important issue maybe the reporter could give tabbed a try?:

https://tools.suckless.org/tabbed/

**Comment by ipstone** [comment]
I think tab is a non-feature as in the readme - to me, the server-client architect is a more efficient way of file manger than the tabbed file manager. 

As `lf` is fast, when I need to manage files, often I was in a view (such as another tmux window, or screen) without the source files/folder to perform move/copy etc. I think it's a faster/simpler interface than the many tabbed view. If I really need tabs, when just launching ranger, or vifm will scratch the itch.

**Comment by sdsaati** [comment]
Ranger supports tabs, and it’s a very useful feature that I use daily. The reason is simple: it makes my workflow much easier. There’s no need to install additional applications, run multiple instances (server/clients), or deal with unnecessary complexity. In Ranger, you simply press Alt+2 to open a new tab, and Alt+1 to return to tab 1. If you can suggest an alternative that works just as seamlessly, I’d be happy to hear it.

**Comment by DusanLesan** [comment]
> Ranger supports tabs, and it’s a very useful feature that I use daily. The reason is simple: it makes my workflow much easier. There’s no need to install additional applications, run multiple instances (server/clients), or deal with unnecessary complexity. In Ranger, you simply press Alt+2 to open a new tab, and Alt+1 to return to tab 1. If you can suggest an alternative that works just as seamlessly, I’d be happy to hear it.

@sdsaati You can easily use tabbed for adding tabs to anything

https://github.com/user-attachments/assets/73740979-2b55-4a1d-94bf-8caa9458379a

**Comment by sdsaati** [comment]
@DusanLesan Thank you for your response and for creating a video. It's nice, yeah, your answer is acceptable thanks!
