### ISSUE TITLE
Change selected/copied/cut files highlight

### ISSUE THREAD

**Issue by flashrunnerGH** [gokcehan/lf#1538]
I have read the docs but haven't find any option to change the highlight of selected files (the box before the file name when you press space). Is it possible?

**Comment by joelim-work** [comment]
The colors are cut/copied/selected files are currently hardcoded: https://github.com/gokcehan/lf/blob/d8b7df87cbc0592fcb9ed2cb1f41e24279303ae2/ui.go#L351-L354

I think this is a reasonable feature to implement, given that there is already support for customizing the color of other things like `borderfmt` and `numberfmt`.

I have submitted a PR #1540 for this.
