### ISSUE TITLE
How to change the color of the error messages?

### ISSUE THREAD

**Issue by IKA3RUS** [gokcehan/lf#154]
![2019-03-14-150127_724x532_scrot](https://user-images.githubusercontent.com/20168152/54346659-5e446200-463d-11e9-954c-2dcd922a3536.png)
The current setting displays white text on a red background, which is not really readable due to my colorscheme. Is there any option to change this?

**Comment by gokcehan** [comment]
@IKA3RUS I will try to add an option to customize the style of error messages when I have some time.

**Comment by gokcehan** [comment]
@IKA3RUS Sorry for late reply. I have now added `errorfmt` option to customize error messages. You can use it as follows:

    set errorfmt "\033[7;31;47m%s\033[0m"  # default

Closing this issue now.
