### ISSUE TITLE
[BUG] mark-save jumps to mark-load on this situation

### ISSUE THREAD

**Issue by superiums** [gokcehan/lf#1541]
when i trying to launch mark-save via keybinding, it jumps to mark-load, and report:

`mark-load : no-such mark`

to reproduce:
1. config like this `map mb mark-save`
2. use `'` to launch mark-load, but type a charactor which was not in the list.
3. it reports not found, this is OK.
4. type `mb` to execute mark-save, and type any charactor
5. it reports : `mark-load: no-such mark` again! and mark-save fails.

**Comment by joelim-work** [comment]
Thanks for reporting, actually what happens is that `mark-save` succeeds, but doesn't wipe out the old error message.

I have submitted #1544 to address this.
