### ISSUE TITLE
Symlinks to directories are not colored as symlinks

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#156]
This is somewhat related to #20. The issues refers to the situation that a symlink targets a directory. It seems that it is being treated as a directory but it is not colored as one. Ranger handles this case by using the same color as for symlinks.

**Comment by gokcehan** [comment]
@doronbehar I agree they should be colored as symlinks. Also we still don't show the destination of a link anywhere.

**Comment by gokcehan** [comment]
@doronbehar Patch by @nvllsvm fixes the coloring but maybe we can still keep this issue open until we show the link target somewhere in the ui.

**Comment by nvllsvm** [comment]
@gokcehan should probably update the title and description then. Its not clear this is still open for the other reason.

**Comment by gokcehan** [comment]
@nvllsvm You're right, nevermind, I will just open a new issue for that.
