### ISSUE TITLE
Icons support

### ISSUE THREAD

**Issue by andpalmier** [gokcehan/lf#158]
Would it be possible to have something like [this](https://github.com/alexanderjeurissen/ranger_devicons) for lf?

Thanks in advance

**Comment by gokcehan** [comment]
@andpalmier At some point, I got interested in adding an icon configuration mechanism to `ls` using `$LS_COLORS`. I have even sent an email to the gnu mailing list about this:

http://lists.gnu.org/archive/html/coreutils/2018-05/msg00025.html

I was hoping to work on a patch to implement this myself but never had the chance to do so yet. If `ls` had icon support, we could simply implement the same mechanism on the `lf` side and stay compatible with it. If I ever get a chance to work on this, I think I would first try to push this feature to `ls` though the chances of such a patch being accepted may not be too high. Let's keep this issue open for a while.

**Comment by EmmChriss** [comment]
I think it would be beneficial to add support for an optional script (like the preview script), that determines both the icon of a given filesystem node, and also its color, and so optionally ditch LS_COLORS.

It may be beyond the scope of this project, but for absolute customizability, I think the script should just print what lf should display for a node. This way, for example, different handling of symlinks could be optionally added by the user (`symlink -> /path/to/target`), but also each file's color, and icon.

The only problem with this would be a large number of files getting displayed, but just like previews, this could also be cached.

**Comment by gokcehan** [comment]
Icons are implemented quite a while ago. I think I may have left this issue open with the hope that `ls` might add icons at some point and we can adopt it as our configuration which seems like a dream at this point. Closing the issue.
