### ISSUE TITLE
Problem with Korean being displayed garbled

### ISSUE THREAD

**Issue by elgar328** [gokcehan/lf#1581]
I am a Korean user. A problem occurred in the lf file manager where all file names and folder names written in Korean were displayed garbled. I'm not sure if this is a common problem in other non-English languages, but it does occur in Korean.

**Comment by ztclog** [comment]
maybe you should check your if your terminal support CJK characters. or look into your locale.conf file

**Comment by joelim-work** [comment]
I doubt the issue is with `lf` itself, since it worked for me out of the box:

![image](https://github.com/gokcehan/lf/assets/50560759/6343db59-a839-44d4-b228-ee5a66cd9514)

I agree with the above comment - check the other settings you might have, like the terminal, fonts, locale, etc.
