### ISSUE TITLE
How to open highlighted file not selected?

### ISSUE THREAD

**Issue by rhydb** [gokcehan/lf#1583]
When files are selected, opening (`l`) on a highlighted file instead opens all selected files.

I would much prefer if `l` only opened the highlighted file and `:open` open the highlighted or selected files.

**Comment by joelim-work** [comment]
That shouldn't happen, by default `l` is mapped to `open`, which is defined as `&$OPENER "$f"`.

`$f` means just the current file located at the cursor, if you want the selected files, you can try using `$fs` or `$fx` instead. See https://github.com/gokcehan/lf/blob/master/doc.md#environment-variables

**Comment by rhydb** [comment]
Thanks for confirming. I have just checked and this behavior comes from the example configuration file creating a custom `open` command.
