### ISSUE TITLE
Image previews

### ISSUE THREAD

**Issue by iamantu93** [gokcehan/lf#159]
I will switch to this if image previews work. It's a big deal for me. Right now I am using ranger, which is little slow to start.

**Comment by gokcehan** [comment]
@iamantu93 Feel free to use whichever program you like. If image previews are a big deal for you, then ranger may be a better choice for you for a long time. It is always nice to see people getting interested in what you like, though at the end of the day there is nothing much for me to have more users switch from ranger to lf, especially when people have no intention of contributing to the project but instead have only feature requests.

Anyway, we already have an issue discussing the possible integration of `ueberzug` with `lf` which currently seems like the best option for us right now. I'm closing this issue in favor of #134 . You may want to subscribe to the other issue for future progress.
