### ISSUE TITLE
Alternate paste workflow (select then move/copy) from tips section doesnt work

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1592]
I installed the fresh lf: env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

Then insert Alternate paste workflow (select then move/copy) code from tips, but doesnt work. Not show error messaging or other. Simple doesnt cut or copy.

**Comment by joelim-work** [comment]
I can't reproduce, can you provide more detailed info (e.g. config file / steps to reproduce / screenshots / videos etc.)? A description like "doesn't work" isn't very helpful on it's own.

You have to select some files first (with `<space>`) before pasting. Also I testted the alternate paste workflow thing in isolation without anything else in my config file, so I'm not sure if you have some conflicting configuration.

**Comment by og900aero** [comment]
Sorry for the superficiality. I started to test it, I deleted practically everything from the lfrc, but it doesn't respond to pressing p and P. The select file contains the selected file, but when I press p or P, nothing happens.

lf -version -> Go version: go1.19.8
Debian 12 stable

lfrc contains:

```
# interpreter for shell commands
set shell sh

# set '-eu' options for shell commands
# These options are used to have safer shell commands. Option '-e' is used to
# exit on error and option '-u' is used to give error for unset variables.
# Option '-f' disables pathname expansion which can be useful when $f, $fs, and
# $fx variables contain names with '*' or '?' characters. However, this option
# is used selectively within individual commands as it can be limiting at
# times.
set shellopts '-eu'

# set internal field separator (IFS) to "\n" for shell commands
# This is useful to automatically split file names in $fs and $fx properly
# since default file separator used in these variables (i.e. 'filesep' option)
# is newline. You need to consider the values of these options and create your
# commands accordingly.
set ifs "\n"

cmd load-select &{{
    # skip if triggered via save-select from itself
    if [ "$1" = "$id" ]; then
        exit 0
    fi

    lf -remote "send $id unselect"
    if [ -s ~/.local/share/lf/select ]; then
        files=$(tr '\n' '\0' < ~/.local/share/lf/select | xargs -0 printf ' %q')
        lf -remote "send $id toggle $files"
    fi
}}

cmd save-select &{{
    printf "%s" "$fs" > ~/.local/share/lf/select
    lf -remote "send load-select $id"
}}

map <space> :toggle; down; save-select
map u :unselect; save-select
map v :invert; save-select

cmd alt-paste &{{
    if [ -n "$fs" ]; then
        lf -remote "send $id :$1; save-select"
    fi
    lf -remote "send $id paste"
}}

map P alt-paste cut
map p alt-paste copy

# load selection on startup
load-select

```

**Comment by og900aero** [comment]
It is very strange. When I deactivate preview script, then activate again, now works again the alternate script with fresh version. Sorry for mistake.
