### ISSUE TITLE
please support tags function

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1593]
windows11 file manager have tag

**Comment by joelim-work** [comment]
`lf` already has tags, see https://github.com/gokcehan/lf/blob/master/doc.md#tag

However there are limitations - tags can only be a single letter long, and a file can only have a single tag. I am not sure if there is a use case for anything more sophisticated though.

**Comment by newyorkthink** [comment]
![image](https://github.com/gokcehan/lf/assets/87791643/512cebce-0723-48d3-bb66-db1f67ac5c5e)

i mean is not this

i meaing is like windows tag
![image](https://github.com/gokcehan/lf/assets/87791643/65a07618-98c5-4bcd-ac3b-5399f149d059)

like kitty terminal:
![image](https://github.com/gokcehan/lf/assets/87791643/87337c34-564b-47d4-a1c0-bf96164336b2)

**Comment by joelim-work** [comment]
Oh that is tabs (with a B), not tags.

Actually this was requested a long time ago in #153 but the idea was rejected. I don't think there's much I can personally do about it.

**Comment by alvaro17f** [comment]
Tabs support would be awesome, really awesome.
It would be great to have at least an option to use them.

**Comment by janpeterd** [comment]
This issue can be closed I think
