### ISSUE TITLE
Cannot map to keys starting with one of the default

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#16]
Which means, for example, that this doesn't work.

```
map dD trash
```

And it is copy/pasted from the tutorial :-).

I'd add that this makes sense that when some command is mapped to `d`, there would be no reasonable way to map `d<sth>`. Perhaps need a way to "unmap" the defaults?

**Comment by gokcehan** [comment]
This was in the example lfrc @KenjiTakahashi but I removed it the other day when I realized it wasn't working :) Traditionally people make use of key delays to make it possible to have such mappings. I haven't added this yet since synchronization might be necessary for ui and the rest.

Unmapping is on the agenda.

**Comment by KenjiTakahashi** [comment]
Oh, ok. But it still persisted in the tutorial (in the "custom command" example) :-).

**Comment by gokcehan** [comment]
I missed that one @KenjiTakahashi , I will take care of it.

**Comment by gokcehan** [comment]
@KenjiTakahashi I have pushed something for unmapping with the `map` keyword. It feels strange at first but I like the idea of not introducing a different keyword. Plus it is consistent with the `cmd` removal this way. We may change it later though if it becomes too counter-intuitive. Let us see how it goes.

**Comment by KenjiTakahashi** [comment]
Fine by me, thanks.

@gokcehan I think this can be closed, unless you want to track something more here.

**Comment by gokcehan** [comment]
@KenjiTakahashi it is still not possible to map to a key starting with another. I personally try to avoid those kinds of bindings and I guess you too. We may track that here but with a low priority. So maybe keep the issue open in case someone gets interested in this?

**Comment by KenjiTakahashi** [comment]
Agreed on both things :-).

**Comment by KenjiTakahashi** [comment]
@gokcehan It seems that unmapping got broken at some point, it doesn't work on current master.

**Comment by gokcehan** [comment]
@KenjiTakahashi Sorry, I have been trying to clean up the parser code. I have pushed a fix now. Can you get the master and try again?

**Comment by KenjiTakahashi** [comment]
Works again, thanks!

**Comment by gokcehan** [comment]
Now that many operations work asynchronously, a delay mechanism for keys with a common prefix needs to address what should happen when an event occurs during the delay. So implementing this in a correct manner may be quite difficult for little or no gain. I'm closing this issue as there is no current effort to implement this. Feel free to leave comments if you want to work on this or have a good idea for the implementation.
