### ISSUE TITLE
Integration with fzf fix

### ISSUE THREAD

**Issue by andpalmier** [gokcehan/lf#160]
In the [integrations section](https://github.com/gokcehan/lf/wiki/Integrations) it mentioned to add the following into the lfrc for jumping to a file or directory using fuzzy matching:

```
map f $lf -remote "send $id select $(fzf)"
```

But this retrieves an error (`select: requires an argument`) in case of matching paths containing spaces or special characters. I tried to replace it with:

```
map f $lf -remote "send $id select \"$(fzf)\""
```
And it seems to work.

**Comment by gokcehan** [comment]
@andpalmier Single quote also seems to fix this, and it doesn't require escaping. I have now change the wiki page accordingly. Thanks for the catch. Closing this issue now.

**Comment by andpalmier** [comment]
@gokcehan without escaping it doesn't work if in fzf I select a file containing a quote in the name. It still triggers `select: requires an argument`.

**Comment by gokcehan** [comment]
@andpalmier When you use the escaped double quote, then it triggers the error when the name contains a double quote. Isn't that the same problem kind of?

**Comment by andpalmier** [comment]
Yep, my bad.
