### ISSUE TITLE
buggy inputs / wrong file opening when starting terminal + lf per hotkey

### ISSUE THREAD

**Issue by quadans** [gokcehan/lf#1612]
Shell : zsh
Terminal : kitty
TWM : Xmonad

Everything works fine when I first start a terminal and then type `lf` in it.
BUT. 
When I try to hotkey it such that a terminal + lf opens, everything is buggy. Files getting opened with vim instead of nvim, the editing doesnt work (cant delete characters) and when i press arrow keys it writes  A,B,C or D. When i write `lf` in my .zshrc, it works. But then it ALWAYS opens lf even when i only want to start a terminal. 
I tried a lot of configurations in Xmonad and with kitty.
    ((modm , xK_e     ), spawn "kitty -e lf")
    ((modm , xK_e     ), safeSpawn "kitty" ["lf"])
    ((modm , xK_e     ), unsafeSpawn "kitty -e lf")
    ((modm , xK_e     ), spawn $ XMonad.terminal conf ++ " -e lf")
    ((modm , xK_e     ), spawn $ XMonad.terminal conf ++ " lf")

All lines open my terminal with lf in a buggy state. I tried sessions too but it doesnt work. I also tried different terminal (xterm) but it also doesnt work.

Does anyone know any tricks how to start my terminal + lf the correct way?

**Comment by joelim-work** [comment]
Try comparing the environment variables (e.g. `cat /proc/<pid>/environ`) between starting `lf` normally and via a hotkey. I suspect this might be related to issues like #1124 and #1313, where the `EDITOR`/`VISUAL` environment variables weren't being set properly by the user.

Also check the environment variables for XMonad since processes inherit environment variables from their parent process.

**Comment by quadans** [comment]
> Try comparing the environment variables (e.g. `cat /proc/<pid>/environ`) between starting `lf` normally and via a hotkey. I suspect this might be related to issues like #1124 and #1313, where the `EDITOR`/`VISUAL` environment variables weren't being set properly by the user.
> 
> Also check the environment variables for XMonad since processes inherit environment variables from their parent process.

There are many PID for the process so I dont know what to chose. So I started once terminal in normal way and typed `env` and once with hotkey and typed `env`. The variables seem to be the same, excep SHLVL and 1 or 2 order of lines are different. I dont have a `$VISUAL` line. The `kitty -e zsh -c lf` line also dont work.

My current solution is to open a terminal with `zsh --rcs ~/.zshrc2` , where the .zshrc2 file sources the orignal .zshrc but has the additional line `lf` at the end. Its a workaround with an extra file, I wish there was a one-liner without needing an extra file.

**Comment by joelim-work** [comment]
I'm guessing you have important stuff in your `.zshrc` file, but it isn't sourced anywhere when you run `lf` via a hotkey. `zsh -c lf` runs as a non-interactive shell, so it won't source `.zshrc`.

**Comment by joelim-work** [comment]
From my understanding, if you're trying to start `lf` via a hotkey, there is no interactive shell involved where you can type commands in. Try moving some of your settings to `.zprofile` instead, you'll have to keep experimenting to ensure the settings are sourced properly.
