### ISSUE TITLE
Screen tearing while previewing a pdf file

### ISSUE THREAD

**Issue by myrrc** [gokcehan/lf#1619]
Hi!

I've encountered screen tearing in lf while previewing a pdf file. This
happens around 80% of time while trying to preview the file.

[Asciinema cast](https://asciinema.org/a/iN9tasvIR06IUBEw6VW8JBixS)
[Video](https://disk.yandex.com/i/Y8ErY3qVnS5QZg)

In the video, it happens while renaming, however, on some invocations
it happens just on previewing the file

Error messages:

```
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
                                                                                                                              Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
<...>
```

While previewing the file directly with `chafa -f sixel file.pdf` it yields
the correct result (however, a message is printed to stderr):

```
**** Error: Form stream has unbalanced q/Q operators (too many q's)
               Output may be incorrect.
```

I'm not sure the issue is in lf itself. I've encountered
[another issue](https://github.com/hpjansson/chafa/issues/193) with chafa
so it may be related.

Unfortunately, I can't attach the file here as it contains sensitive
information. Send me a message at to@myrrc.dev and I'll reply with the file
attached.

lf version: r31
lf [config](https://git.sr.ht/~myrrc/dotfiles/tree/master/item/client/lf/lfrc)

ctpv version: v1.1
ctpv [config](https://git.sr.ht/~myrrc/dotfiles/tree/master/item/client/ctpv/config)

chafa version: 1.8.0

terminal: foot version: 1.11.0 -pgo +ime -graphemes -assertions

```
~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by hpjansson** [comment]
Those look a lot like errors from ImageMagick's PDF loader backend. Chafa used IM as a fallback loader up until version 1.14.0, where it was discontinued. Calling Chafa with `--animate off` may also help in previewers.

**Comment by hpjansson** [comment]
I took a look at the test files (thanks @myrrc!) Was able to confirm that the warnings come from ImageMagick. You should see the same warnings using `convert foo.pdf foo.gif`. This will also render multipage PDFs as animated GIFs.

**Comment by myrrc** [comment]
Closing issue, not lf related. Thanks
