### ISSUE TITLE
Windows r31 VirusTotal and CylanceProtect Warning 

### ISSUE THREAD

**Issue by marco9446** [gokcehan/lf#1622]
I tried to install the r31 arm64 version of ls on Windows 10, but cylanceProtect is putting the EXE in quarantine and a scan with VirusTotal produces the following result:

![image](https://github.com/gokcehan/lf/assets/7085069/fe106d4d-26f9-4c6c-88e5-c3b513a6c28c)

**Comment by marco9446** [comment]
@gokcehan thanks for the reply, I was expecting that, since cylance is giving me a ton of false positive. For those who are in my same situation, r29 or r28 don't cause any warnings

**Comment by gokcehan** [comment]
@joelim-work Yes, I think it is a good time to make a new release these days.

**Comment by joelim-work** [comment]
Closing this in favor of #1828
