### ISSUE TITLE
Unable to  copy selected files using `cp -r $fx` command

### ISSUE THREAD

**Issue by iamkhalil** [gokcehan/lf#1623]
**Description:**

I'm encountering an issue when trying to create a custom command involving the `cp` command and the `$fx` variable. The custom command is designed to create a directory and recursively copy selected files into it. However, calling the command results in a "No such file or directory" error.

**Steps to reproduce:**
1. Create a custom command as follows:
```
cmd foo ${{
        mkdir bar
        cp -r "$fx" bar
}}

map foo af
```
2. Select multiple files 
3. Calling `foo` will fail with the error:  `cp: cannot stat '/home/user/file1'$'\n''/home/user/file2': No such file or directory`

**Environment:**
* OS: Linux
* Shell: Bash
* lf version: r31

**Notes:**
* filesep = "\n" (default)
* It seems that the `$fx` variable is not correctly expanded, leading to the failure of the `cp` command.

**Comment by joelim-work** [comment]
You shouldn't quote `$fx`, that will cause all the paths to be joined into a single argument, instead of being split on `\n`.
