### ISSUE TITLE
Running an lf command on the output of a shell command

### ISSUE THREAD

**Issue by LukeSmithxyz** [gokcehan/lf#163]
I'm not sure if this is a feature request or me missing something in the documentation, but I'm looking for a way to run an lf command on the output of a shell command. This would be something that would make lf substantially more extensible if it doesn't already have it.

Here's an example of what I want to be able to do:
```
map c cd $(find -type d | fzf)
```
So if I press `c`, I get a list of all subdirectories selectable with fzf, and I cd to the one I choose. Obviously, this is not how it works now, at least, so far as I can see. If I overlooked something, please tell me.

It would be even better to be able to call user-created `cmd`s as arguments to lf commands as well, if you know what I mean.

**Comment by gokcehan** [comment]
@LukeSmithxyz Have you looked at remote commands for this? Maybe something along the line:

    map c $lf -remote "send $id cd $(find -type d | fzf)"

You should be able to call user commands in remote commands but I'm not sure if this is what you mean.

**Comment by LukeSmithxyz** [comment]
Ah I see. Yes, that's more or less what I was looking for. I saw remote commands but wasn't clear on how they actually work. Thanks for the clarification. I should be able to figure what I need out from that.
