### ISSUE TITLE
Toggle all items that are matched with  search ("/") in current directory

### ISSUE THREAD

**Issue by drkknigt** [gokcehan/lf#1630]
First off thank you for this wonderful software.
I am trying to figure out how to toggle all the items that are matched with search. 
- map a key to function search_toggle
- search '/' appears and user types the search term
- cursor jumps to the nearest match 
- all the items matching the search term are toggled 
I have written this function but this doesn't jump to the nearest match
```
cmd search_select %{{
  printf " "
  read ans
   for i in $(ls | grep $ans); do
        file_name=$(echo $i | sed 's/.*/"\0"/g')
         lf -remote "send $id toggle $file_name"
    done
}}
```
Basically search and toggle all matched items and jump to the nearest matched item. How do i acheive this. 
Thank you

**Comment by gokcehan** [comment]
@drkknigt Have you seen the `glob-select` command yet?

**Comment by drkknigt** [comment]
@gokcehan   `glob-select` doesn't navigate directly to the selected result, and I can't use n and N to move between matched results. I have to re-enter the glob-select pattern using `:search` to goto the result. Is there a way to toggle the result selection and navigate between matched results using n and N as with a normal search in one go ?

**Comment by joelim-work** [comment]
You can try something like this:

```
set globsearch

cmd search_select &{{
    lf -remote "send $id :glob-select $1; search; push $1<enter>"
}}
```

For example, use `:search_select *.go`

**Comment by drkknigt** [comment]
@joelim-work Thank you , thats exactly what i wanted .

**Comment by joelim-work** [comment]
No worries, I'll close the issue then.
