### ISSUE TITLE
On Windows with pwsh, external trash command doesn't work with $Env:fx variable

### ISSUE THREAD

**Issue by aasril** [gokcehan/lf#1639]
The aforementioned trash utility I'm using is this one https://github.com/sindresorhus/trash-cli

The command works fine for file under cursor `($Enf:f)`. Or if I run the command directyly from `pwsh` or from lf `$` and `!` prefix for multiple files at once. Both with relative paths and absolute paths. 

And I should mention that the files I test it on have no spaces on their paths and names.

My config is esentially the same as the one from example (with changes only on the shell it uses):
```
set shell pwsh
set icons
cmd open &start $Env:f
map e $nvim $Env:f
map i $less $Env:f
map w $pwsh
cmd doc $lf -doc | less
set scrolloff 10
map <enter> shell
```

I've tried to set the file separator to space `set filesep " "` but still the same, command finish with no error yet it doesn't remove the file.

What can I try to make the `trash` command works?

**Comment by Catalyn45** [comment]
It's because the command gets translated internally as `tash "$Env:fx"` which, if you have multiple files, will be `trash "file1.txt file2.txt"`  and I believe because of the quotation marks, the trash command interpret `"file1.txt file2.txt"` as a single argument. Now, if this command works in bash/sh as expected, it may be because bash treats them as 2 arguments, but this is just a speculation I need to confirm.

**Comment by Catalyn45** [comment]
It seems that trying to open a new shell with `w` after selecting the files and trying to do the delete command it's also not working.
<img width="331" alt="image" src="https://github.com/gokcehan/lf/assets/37979489/8747677e-538f-435a-9b9a-61cf450063ce">

**Comment by Catalyn45** [comment]
It seems powershell treats `Env:fx` as a single argument even if the value from the environment variable have spaces in it
<img width="450" alt="image" src="https://github.com/gokcehan/lf/assets/37979489/26097f38-0fa6-4567-905e-3ebd9b454db9">

**Comment by Catalyn45** [comment]
Seems to be a powershell specific problem, I don't think there is any fix that can be done in `lf`

**Comment by Catalyn45** [comment]
As a workaround you can try `$Env:fx.Split()`

**Comment by aasril** [comment]
It seems to be like it, `pwsh` treat the `fx` as one single long string, file separators don't matter.

I tried `$Env:fx.Split()`, the command doesn't work still.

**Comment by Catalyn45** [comment]
I made it to work like that:

```pwsh
map dd ${{
    $paths = $Env:fx.Split()
    trash @paths
}}
```

**Comment by aasril** [comment]
@Catalyn45 Thank you, it works!

The trash feature had been the last basic function I missed and keeping me away from using `lf` more. This was of great help to me, cheers.

**Comment by qrsp** [comment]
If the file paths contain spaces, I recommend splitting them with `\n`.

```ps1
map dd ${{
    $paths = $Env:fx.Split("`n")
    trash @paths
}}
```
