### ISSUE TITLE
Problem with disown command

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1648]
I want to use disown command. My goal is, when opened pdf file, the run google-chrome and dismount google-chrome from lf instance. So when close lf, then google-chrome keep runnning. Example:
_google-chrome-stable something.pdf 2>/dev/null & disown_
This works is terminal, but lf throw an error message: "disown: not found"

lfrc:

```
cmd open ${{
	case "$(echo "$f" | sed 's/\([A-Z]\)/\L\1/g')" in
                .
                .
	    *.pdf|*.htm|*.html)
			google-chrome-stable "$fx" 2>/dev/null & disown ;;
                .
                .
	    *)
	        for f in $fx; do
	        	if sudo -u "$USER" test -w "$f"; then
	        		$EDITOR $f
	        	else
	        		sudo -A $EDITOR $f
	        	fi
	        done;;
	 esac
}}
```

**Comment by Catalyn45** [comment]
'disown' is a BASH shell built-in, so if the shell is set to `sh` or not set at all (which defaults to `sh`) this will not work.
you could use `set shell bash`.

**Comment by og900aero** [comment]
> `disown` is a BASH shell built-in, so if the shell is set to `sh` or not set at all (which defaults to `sh`) this will not work. you could use `set shell bash`.

I modify to set shell bash
But doesnt work: when close lf, then google-chrome closing too.

**Comment by joelim-work** [comment]
You can try using `setsid` as mentioned in the [documentation](https://github.com/gokcehan/lf/blob/4b076d199b6d98c88483c5fecd5b48f23f6318a4/doc.md#opening-files)

**Comment by Catalyn45** [comment]
maybe you can try something like that?
<img width="532" alt="image" src="https://github.com/gokcehan/lf/assets/37979489/78df7c7a-5270-48d0-8301-74fe97a93263">

**Comment by og900aero** [comment]
> You can try using `setsid` as mentioned in the [documentation](https://github.com/gokcehan/lf/blob/4b076d199b6d98c88483c5fecd5b48f23f6318a4/doc.md#opening-files)

Thx, this working, when change to cmd open &{{
and
lf -remote "send $id \$$EDITOR \$f"

This working, but...I use a file check to see if sudo should be used (unfortunately, this function is not included in lf), and not working this method:

```
*)
	        for f in $fx; do
	        	if sudo -u "$USER" test -w "$f"; then
	        		lf -remote "send $id \$$EDITOR \$f"
	        	else
	        		lf -remote "send $id \$sudo -A \$$EDITOR \$f"
	        	fi
	        done;;
```
When open any config file must be sudo, then I get error message now: "-: 2: nano: parameter not set"

**Comment by joelim-work** [comment]
I guess you can't use `&` if `sudo` because it needs to be connected to the terminal so you can authenticate, I could be wrong about that though.

But I'm not sure why you had to change to `&` in the first place - `setsid` worked fine for me when I used `$`, I just had to pipe stderr to `/dev/null`.

**Comment by og900aero** [comment]
> I guess you can't use `&` if `sudo` because it needs to be connected to the terminal so you can authenticate, I could be wrong about that though.
> 
> But I'm not sure why you had to change to `&` in the first place - `setsid` worked fine for me when I used `$`, I just had to pipe stderr to `/dev/null`.

I changed it to & because that way it stopped flickering when I open something

I have a solution:
`lf -remote "send $id \$bash -c 'sudo -A $EDITOR $f'"`

But I still say that it would be nice if there was an option in lf to request a sudo prompt to the bottom (or even the sudo -A option), instead of having to quickly open another window with sudo lf .
