### ISSUE TITLE
Create a new file and select it

### ISSUE THREAD

**Issue by Limero** [gokcehan/lf#165]
I'm trying to write a command that creates a file and then selects it. As far as I've gotten, it works the second time it's run with the same filename. First time, it only creates the file.

My current command: `cmd touch %touch $1 && lf -remote "send $id select $_"`

After talking with @gokcehan on IRC, the best solution so far would be to add a sleep in the command like this: `cmd touch %touch $1 && sleep 1 && lf -remote "send $id select $1"`. Not a very pretty solution, so any ideas on how to improve this is appreciated.

**Comment by gokcehan** [comment]
@Limero I just realized you can simply send an explicit `load` command instead of sleeping as such:

    cmd touch %touch $1 && lf -remote "send $id load" && lf -remote "send $id select $1"

This seems to work fine on my machine. Closing this issue now if it is ok. Feel free to reopen or add comments if you like.

**Comment by Limero** [comment]
Thank you! This works perfectly. The same also works for creating directories:
`cmd mkdir %mkdir -p $1 && lf -remote "send $id load" && lf -remote "send $id select $1"`

**Comment by gokcehan** [comment]
For future reference, it turns out that `load` only works accidentally and with the latest update, `select` should work reliably, and `load` is not necessary since it is already called after shell commands.
