### ISSUE TITLE
cannot open file with typora

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1695]
i want to open markdown file with typora when i selected the .md item

i config all about .md file , it not work
![image](https://github.com/gokcehan/lf/assets/87791643/3fe8b18f-5fcf-4ff7-a55b-23e5b4a182b3)
not working to open markdown with typora

**Comment by DusanLesan** [comment]
Are you selecting multiple files to open? `$fx` file list is separated with `\n` by default and that probably would not work. If you are selecting only one file, can you try to remove error redirection to see if the app used showed some errors

**Comment by newyorkthink** [comment]
> Are you selecting multiple files to open? `$fx` file list is separated with `\n` by default and that probably would not work. If you are selecting only one file, can you try to remove error redirection to see if the app used showed some errors

i just only select one item

**Comment by DusanLesan** [comment]
And you are sure one those mime types matches md? 
If you set `text/*` in the first case (only as a test), does it open? 
Did you see any errors without error redirection?

**Comment by newyorkthink** [comment]
> And you are sure one of those mime types matches markdown? If you set `text/*` in the first case (only as a test), does it open? Did you see any errors without error redirection?

If i set text/* in the first, the csv cannot open with moderncsv, and cannot only with typora, the will all redirect using nvim

**Comment by DusanLesan** [comment]
I meant to use text/* only as a temporary test. To eliminate type as a issue. Did that open the markdown in that app? Have you tried removing error redirection? Did you try to see if file command returns expected output?
