### ISSUE TITLE
Can we get vim mode while renaming files?

### ISSUE THREAD

**Issue by shibisuriya** [gokcehan/lf#1707]
<img width="1728" alt="Screenshot 2024-05-07 at 10 06 54 PM" src="https://github.com/gokcehan/lf/assets/69033713/61fc4746-5d7c-4c77-b819-fed8c9bc234a">

See bottom left corner, can we please get vim mode in there?

**Comment by joelim-work** [comment]
This sounds non-trivial to implement when you consider things like Normal/Insert/Visual modes, Vim motions, etc.. IMO it sounds overkill for the purpose of editing a single filename.

You may want to have a look at integrating a [bulk renaming tool](https://github.com/gokcehan/lf/wiki/Tips#bulk-rename-multiple-files), which typically involves your favorite text editor.

**Comment by RadioFreieErde** [comment]
I have installed `vimv`. If I select the files and then enter `!vimv $fs`, I can change the file names with vim. If I only want to rename or move a single file, I can enter `!vimv $f`.

**Comment by joelim-work** [comment]
I think direct Vim support is closer to being a [non-feature](https://github.com/gokcehan/lf?tab=readme-ov-file#non-features), than being implemented. Will close since there are other alternatives available.
