### ISSUE TITLE
Dialing to send server error

### ISSUE THREAD

**Issue by AmaruCoder** [gokcehan/lf#1711]
When using the `lf` file manager in Alacritty, I keep receiving the message: `dialing to send server: dial unix ` (a file name ending in `sock`) followed by `connect: no such file or directory` (see below). 

I have tried `lf` with iTerm without getting this error.

To make things interesting, after I open `lf` in iTerm, `lf` stops giving the error message in Alacritty. Is this a bug or reflects a setting I am not aware of?

<img width="1448" alt="lf-in-alacritty" src="https://github.com/alacritty/alacritty/assets/2724075/2acd1071-5ba1-42e1-a7c1-2ffe7bf6666e">

### System

OS: MacOS Ventura 13.4.1
Alacritty version: 0.12.2
LF version: r31

**Comment by joelim-work** [comment]
That looks like the socket used for [remote commands](https://github.com/gokcehan/lf/blob/master/doc.md#remote-commands). Check that the file exists and the server is running. You can also perform a basic test using the following command:

```
lf -remote 'send echo hello world'
```

**Comment by AmaruCoder** [comment]
Thank you. When I run `lf -remote 'send echo hello world'`, I get the same error message (see below). When I navigate to the folder involved, there is no `lf.{user}.sock` file. However, when I run `lf` in iTerm, there is no error, and there is a `lf.{user}.sock` file.

<img width="1421" alt="lf-no-such-file" src="https://github.com/gokcehan/lf/assets/2724075/4e87f07d-b681-4544-829a-17fd6ef4a0a5">


So it seems that `lf` doesn't start the server under Alacritty. Is it there a way to fix that?

**Comment by joelim-work** [comment]
There must be something wrong with your settings for Alacritty then, if remote commands work on iTerm.

The socket path is defined in the following code, which depends on `XDG_RUNTIME_DIR`: https://github.com/gokcehan/lf/blob/12e99fdb641565e3122ab62dce0b77e836aa69a4/os.go#L123-L128

**Comment by joelim-work** [comment]
Also it might be possible for some reason the server itself doesn't start automatically on Alacritty? In that case you can try starting the server manually using `lf -server`.

**Comment by AmaruCoder** [comment]
Thank you for the detailed response. I tried starting the server in Alacritty, using `lf - server`, but it didn't resolve the issue. I also tried to define `XDG_RUNTIME_DIR` without better luck. It seems, then, that the problem is that, somehow, the server doesn't get started when `lf` runs in Alacritty.

Again, if I run `lf` in iTerm and then in Alacritty, everything works.

**Comment by joelim-work** [comment]
You have added an extra space, the command is `lf -server`, not `lf - server`.

Otherwise I'm not sure what the issue can be then. The server should either start and print `hi!` then continue running, or terminate with some error (e.g. socket already in use).

**Comment by AmaruCoder** [comment]
I posted in the Alacritty [Issues page](https://github.com/alacritty/alacritty/issues/7964), but they state that it is a problem with `lf`. Any suggestions to go from here?

**Comment by joelim-work** [comment]
I didn't think it was an issue with Alacritty to begin with in the first place. However since I don't have any issues with the server starting up using Alacritty, it's practically impossible for me to investigate.

Unless you're willing to clone the repo and debug the following code yourself:

https://github.com/gokcehan/lf/blob/12e99fdb641565e3122ab62dce0b77e836aa69a4/main.go#L335-L337

https://github.com/gokcehan/lf/blob/12e99fdb641565e3122ab62dce0b77e836aa69a4/main.go#L159-L179

**Comment by AmaruCoder** [comment]
Thank you for the detail reply. `lf -single` works fine. Of course, multiple windows are not an option for file operations. Regarding the code, unfortunately I haven't learned Go yet. I think that I will stick to iTerm for the time being. Thank you, again.

**Comment by AmaruCoder** [comment]
I

**Comment by AmaruCoder** [comment]
I don't know if this helps. 

I have tested under MacOs 13.4.1, Terminal, iTerm, and Alacritty, and all of them have the same issue discussed above. 

iTerm worked because I had a shortcut to start `lf` in the form: `lf /{bookmarks folder}`.

I tried the same shortcut under Terminal and Alacritty, and both also work fine. My `{bookmarks folder}` is the path to a folder with symlinks to the folders I use most often.

**Comment by joelim-work** [comment]
So you're saying that running `lf` by itself doesn't cause the server to start, but running `lf /some/path` does? Have you tried starting `lf` directly on the command line without any kind of aliases, shortcuts or any other configuration at all?

Also have you tried enabling logging with the `-log` option?

I still can't reproduce this issue, but I'm guessing it might have something to do with the value of `os.Args[0]` in the line `cmd := detachedCommand(os.Args[0], "-server")`, though I could be completely wrong.

**Comment by AmaruCoder** [comment]
**I solved the issue.** I downloaded Kitty, just to try another terminal, and after trying to run `lf`, I got the message `lf not in $PATH`. Which seemed strange, because I had installed `lf` under my user folder, which is in `$PATH`.

So I moved `lf` to `/usr/local/bin`, which appears earlier on my `$PATH`, and restarted the terminal. Now `lf` works everywhere!

Thank you for your help and patience. I really appreciate it. And, by the way, I wanted to troubleshoot this issue because I believe that `lf` is the best file manager out there.

**Comment by joelim-work** [comment]
No worries, glad you solved your issue. :+1:

It's good that you have the patience to try out different things (e.g. installing another terminal) to figure out the root cause. Others might have given up, assumed it was a bug in `lf`, and moved onto a different file manager.
