### ISSUE TITLE
Search-back command doesnt work

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1716]
lf --version
r32

When I try command :search, I get prompt: /
Type any character and press Enter, the cursor jump to the appropriate file
When I try command :search-next then jump to the following files
But I try :search-back then press Enter, then the prompt changes to ? and nothing happend

**Comment by joelim-work** [comment]
This behavior is consistent with Vim. Are you perhaps confusing `search-back` with `search-prev`?

**Comment by og900aero** [comment]
> This behavior is consistent with Vim. Are you perhaps confusing `search-back` with `search-prev`?

Yes, my fault. I'm confusing/mixed up the search-back and search-prev command.
