### ISSUE TITLE
<C-o> - like functionality. [ Enhancement ] [ Willing to help ]

### ISSUE THREAD

**Issue by highsanburger** [gokcehan/lf#1717]
It would be nice to jump between directories that are "far away" from each other.

Much like Vim, we could have a jump list that stores the directory paths where you are operating on files and directories. Then you could go back and forth using respective commands.

A workaround enhancement would be tagging certain directories and then switching between them like tabs.

**Comment by og900aero** [comment]
Well, yes. This is exactly why I miss the tab function too.

**Comment by joelim-work** [comment]
`lf` already has a jump list, is this what you are looling for? https://github.com/gokcehan/lf/blob/master/doc.md#jump-next-default--jump-prev-default-

**Comment by og900aero** [comment]
I made a simple solution for tab management:

```
cmd tab-search ${{
	res="$(cat ~/.local/share/lf/tabs | fzf --reverse --header='Jump to location' --exact --color=fg:#f8f8f2,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4 --preview 'tree {}' || true)"
    lf -remote "send $id cd \"$res\""
}}

cmd on-quit :{{
	$cat /dev/null > ~/.local/share/lf/tabs
}}

map ts tab-search
map tt &echo "$PWD" >> ~/.local/share/lf/tabs
map <a-1> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '1,1p')\""
map <a-2> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '2,2p')\""
map <a-3> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '3,3p')\""
```
Press tt to save actual directory.
Press ts to search saved tabs (required fzf and tree command under linux)
Press Alt+1 to jump the first tab
Press Alt+2 to jump the second tab
Press Alt+3 to jump the fthird tab
When quit from lf, then tabs erased.

As you can see, it is possible to switch between 3 tabs by default, but you can add an extra row at any time that changes.

Of course, this is not a complete solution, as you cannot visually see how many tabs exist and which tab is active, but it is good for not having to open another lf and waste space on the monitor, or to open the fixed window for another lf - and thus walk half the size. This is how I use it, and this solution is also perfect for me, for example to copy or do anything else, and to be able to quickly jump back and forth many "tabs".

**Comment by highsanburger** [comment]
> `lf` already has a jump list, is this what you are looking for? https://github.com/gokcehan/lf/blob/master/doc.md#jump-next-default--jump-prev-default-

Yup this is exactly what I was looking for. Thanks for pointing it out.

**Comment by highsanburger** [comment]
> I made a simple solution for tab management:
> 
> ```
> cmd tab-search ${{
>     res="$(cat ~/.local/share/lf/tabs | fzf --reverse --header='Jump to location' --exact --color=fg:#f8f8f2,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4 --preview 'tree {}' || true)"
>     lf -remote "send $id cd \"$res\""
> }}
> 
> cmd on-quit :{{
>     $cat /dev/null > ~/.local/share/lf/tabs
> }}
> 
> map ts tab-search
> map tt &echo "$PWD" >> ~/.local/share/lf/tabs
> map <a-1> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '1,1p')\""
> map <a-2> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '2,2p')\""
> map <a-3> &lf -remote "send $id cd \"$(cat ~/.local/share/lf/tabs | sed -n '3,3p')\""
> ```
> Press tt to save actual directory.
> Press ts to search saved tabs (required fzf and tree command under linux)
> Press Alt+1 to jump the first tab
> Press Alt+2 to jump the second tab
> Press Alt+3 to jump the fthird tab
> When quit from lf, then tabs erased.
> 
> As you can see, it is possible to switch between 3 tabs by default, but you can add an extra row at any time that changes.
> 
> Of course, this is not a complete solution, as you cannot visually see how many tabs exist and which tab is active, but it is good for not having to open another lf and waste space on the monitor, or to open the fixed window for another lf - and thus walk half the size. This is how I use it, and this solution is also perfect for me, for example to copy or do anything else, and to be able to quickly jump back and forth many "tabs".

Kind of hacky but works. Thanks for sharing!
