### ISSUE TITLE
lfcd quits shell on exiting LF, when lfcd is defined in another sourced file

### ISSUE THREAD

**Issue by SwayKh** [gokcehan/lf#1721]
I was recently cleaning up my cluttered `.zshrc` file, and ended splitting/modularizing the config file. However moving the `lfcd` function to `functions.sh` seems to break it. 

When having `lfcd` function in `function.sh` and sourcing the file in `.zshrc`, Running `lfcd` and then exiting `lf` doesn't cd into the current directory, instead the whole shell exits.

This wasn't the case when `lfcd` was defined in `.zshrc`, but even after moving the `lfcd` function back to `.zshrc`, the functionality still seems broken. It might be issue with sourcing of `.zshrc` though. Since if i source `.zshrc` manually and then run `lf` I get the error `lfcd:2: maximum nested function level reached; increase FUNCNEST?`

I didn't change many settings so, I am not aware how things broke suddenly.

here the lfcd function
```
lfcd() {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir" || exit
  fi
}
```
and my lfrc
```
set shell zsh
set shellopts '-euy'
set ifs "\n"
set drawbox true    # Shows the box around the panes
set dirfirst true
set mouse true
set hidden true     # Hidden Files
set ratios 1:2:2    # Preview should be set after setting ratios, Needed for singlePane function
set icons true      # Icons(Needs a Icons file or LF_ICONS env variable)
set preview true
set sixel true
set period 1
set incsearch true
set incfilter true
set ignorecase true # Ignore case when searching
set scrolloff 5    # Leaves space on Top and Bottom of the screen
set cursorpreviewfmt "\033[7;2m"


set previewer ~/.config/lf/preview
```

I am running Arch Linux 6.9.1-arch1-1
LF version 32.r13.g12e99fd

**Comment by DusanLesan** [comment]
That sounds like bad recursion to me. Could it be that you have created alias for `lfcd` to be `lf`? Could you try calling `/bin/lf` instead of `lf` inside of `lfcd`?

**Comment by SwayKh** [comment]
Okay, I found the issue about the second part of the problem, with `fcd:2: maximum nested function level reached; increase FUNCNEST?`.

It turns out that when I put the `lfcd` function back in `.zshrc`, I copied it over and the `lfcd` function in function.sh was still being sourced. Removing the function from function.sh, got rid of the errors.

although i still can't find the cause of the shell closing on quiting `lf`, when the `lfcd` function is defined in a separate file.

**Comment by joelim-work** [comment]
The shell shouldn't close after quitting `lf`. The only thing I can think of is if `lfcd` calls `exit` somewhere (I can see it in the script you provided), or if you use `exec lf` instead of just `lf`.

As usual with debugging in general, it's best to start small and then add complexity later. First try having `lfcd` print a test string, then change it to run `lf`,  then implement `cd` functionality.

Also we recently added `-print-last-dir` to `lf` to make `lfcd` implementations easier. Hopefully the new [`lfcd.sh`](https://github.com/gokcehan/lf/blob/master/etc/lfcd.sh) works for you.

**Comment by SwayKh** [comment]
Oh, I didn't know there was a new `lfcd` implementation. Yes, using the new function seems to solve the issue. And It also works if the function is sourced from a `functions.sh` file. 

Thanks for helping me solve this issue.

**Comment by joelim-work** [comment]
No worries, I will close this issue then.
