### ISSUE TITLE
Operations performed on sshfs mount no longer reloads

### ISSUE THREAD

**Issue by Limero** [gokcehan/lf#1731]
I've been using sshfs mounted directories for a long time and it's been working fine, but recently any operations (creating/renaming/moving/deleting) performed on files/directories on the mount in lf will not update automatically (ctrl+r still works). 

I'm not sure why it suddenly happens, but I can replicate it 100% of the times. I've tried rolling back from Fedora 40 to 38 and lf from r32 to r29 and it still happens, so it shouldn't be related to any recent changes in lf/sshfs.

The server I'm mounting is running Alpine Linux 3.20 (also happened before on 3.19) and the filesystem is ext4. It's possible that some update here caused it.

Map in `lfrc` I'm using to mount the directory: 
```
map gn %mkdir -p /tmp/nuc && sshfs -o follow_symlinks -o workaround=renamexdev nuc: /tmp/nuc; lf -remote "send $id cd /tmp/nuc"
```

Possibly a duplicate of https://github.com/gokcehan/lf/issues/582

**Comment by joelim-work** [comment]
I'm guessing it's a problem with `mtime` updating on `sshfs`/FUSE mounts.

The following code checks whether a directory should be reloaded or not: https://github.com/gokcehan/lf/blob/aaf5bbb22bfdeed4508c22433c7d863e38f9dc51/nav.go#L519

You can logging the variables and see what the values are.

**Comment by Limero** [comment]
@joelim-work I logged the modtime and noticed it always got set to 2016, ssh'ed in directly and noticed that the time was actually set to that. Turns out chrony (used for NTP timesync) stopped working for some reason, so I just changed over to using openntpd and everything works!

Thank you!
