### ISSUE TITLE
Chafa symbol preview error

### ISSUE THREAD

**Issue by pzant** [gokcehan/lf#1736]
Some pictures (usually big) previewed in a big or fullscreen using `chafa -а symbols` lose and become distorted at the end of lines.
For example with this picture:
![break lines](https://github.com/gokcehan/lf/assets/110853493/a5b52cbc-f1b1-49d1-b42e-d60d694587c2)

**Comment by joelim-work** [comment]
Thanks for the bug report. Can you try #1737 to see if this works for you?

**Comment by pzant** [comment]
> Thanks for the bug report. Can you try #1737 to see if this works for you?
I'm initially using https://github.com/NixOS/nixpkgs/pull/295587#issuecomment-2120852115

**Comment by joelim-work** [comment]
BTW you didn't answer my question, could you please confirm if the PR actually works for you?

**Comment by pzant** [comment]
This shows a preview but with the errors described in the first post.

**Comment by joelim-work** [comment]
Strange, the changes in the PR fixes the issue for me. Unless I fixed a different bug.

In that case I don't know what your issue is, unless you provide a screen recording or something containing more detail.

**Comment by pzant** [comment]
![alacritty](https://github.com/gokcehan/lf/assets/110853493/26704af1-c3fb-4a4d-a688-dea894848fd2)
![foot](https://github.com/gokcehan/lf/assets/110853493/9af18046-6eab-4e62-b76a-641d5cd031bf)
It looks like this in alacritty and foot.

**Comment by joelim-work** [comment]
Yeah, that's the same issue I have (the top half):
![image](https://github.com/gokcehan/lf/assets/50560759/1e2fe309-4259-44d7-9ee2-6bf2c9267e16)

The bottom half is after my change. Did you actually checkout the PR branch and build it?

**Comment by pzant** [comment]
Sorry. I made a mistake. Yes, your PR fixes the problem.

**Comment by joelim-work** [comment]
Thanks for confirming, I will go ahead and merge the PR.
