### ISSUE TITLE
Remove filesep for quoted list values

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#175]
Use the same approach than [Kakoune][Kakoune – Expansions].

**Example** – Print selected files:

``` sh
eval "set -- $fs"

# Using a for-loop
for file do
  echo "$file"
done

# Using printf
printf '%s\n' "$@"
```

[Kakoune – Expansions]: https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc

**Comment by gokcehan** [comment]
@alexherbo2 Is this a feature request? Can you give more details about this pls? I assume the example is a custom command. Can you also try to do the same using the current model to compare and then point out the problem with the current approach?

**Comment by alexherbo2** [comment]
Each element is single quoted, and single quotes inside doubled.

I can’t give an example with the current model, because it’s impossible to have arbitrary characters.

**Comment by gokcehan** [comment]
@alexherbo2 We are using `$@` for command arguments. For example you can use `:rename 'asd.txt'` and `asd.txt` is passed as `$1` so we can't combine `$fs` and `$@`.

**Comment by gokcehan** [comment]
Closing for the lack of further discussion. Feel free to leave comments if you have.
