### ISSUE TITLE
directories have another font type

### ISSUE THREAD

**Issue by axax-loll** [gokcehan/lf#1754]
![image](https://github.com/gokcehan/lf/assets/55180817/efa18fca-10db-459b-8fd8-a4739d125173)

directories have another font type on permissions? i dont know to fix that

![image](https://github.com/gokcehan/lf/assets/55180817/cb9cf2f9-12bd-4757-b88d-c8f9d676ca51)
![image](https://github.com/gokcehan/lf/assets/55180817/19ba7185-4d43-4e07-8150-63dd83122cb9)

**Comment by joelim-work** [comment]
Have a look at the [documentation](https://github.com/gokcehan/lf/blob/master/doc.md#colors) for colors.

The default for directories is `di 01;34`, where `01` means bold. But looking at your screenshot the directory permissions you have are not the standard 755, so I assume it must be resolving to another filetype (maybe `ow` or `tw`).

**Comment by axax-loll** [comment]
thanks bro
