### ISSUE TITLE
Feature request: add an lfrc switch to move duplicate copy suffixes at the beginning of filename.

### ISSUE THREAD

**Issue by siyia2** [gokcehan/lf#1759]
E.g.:  `dummy.iso -> 1~.dummy.iso` , instead of the default: `dummy.iso -> dummy.iso.~1`

The default renaming of duplicate copies messes the file extension, which can cause problems, if for example you want to spam the same file in the same folder, while retaining it's extension and type.

**Comment by DusanLesan** [comment]
You can do that already by setting [dupfilefmt](https://github.com/gokcehan/lf/blob/master/doc.md#dupfilefmt-string-default-fn) like `set dupfilefmt "%n~%f"`

It makes more sense to me to add duplicate appendage after filename and before the extension. `dummy.iso -> dummy1.iso`. I would like to use `set dupfilefmt "%b%n%e"` but now I see that one is broken for dotfiles like `.xprofile`

**Comment by siyia2** [comment]
what is `dupfilefmt`?

**Comment by DusanLesan** [comment]
Please follow the link for it. It is better explained than I could

**Comment by siyia2** [comment]
Alright, i see it works!!! thx again @DusanLesan!
