### ISSUE TITLE
Vim integration - open file in current window

### ISSUE THREAD

**Issue by ashemsay** [gokcehan/lf#176]
Hello,
I tried to use the included vim integration script (lv.vim). I can open lf with the vim ":LF" command and navigate to the desired file but when I hit "e", it opens another vim process instead of opening the file in my current vim tab or window.
Is this the intended behavior? 
If it is, is there anyway to do what I want? Since I'm new to lf there's probably something I am missing.

**Comment by gokcehan** [comment]
@ashemsay You may want to use the `open` command instead (default `l`) to open the current file or selected files in `vim`. When you spawn a `lf` process from `vim`, you can use any custom command you have within that process including the `e` command you mention which spawns a new `vim` instance in your case. I understand this can be a little confusing but I'm not sure how we can make this better. Let's keep this issue open for a while for possible ideas.

**Comment by ashemsay** [comment]
Thank you for your answer but I tried this as well and whereas `e` opens the file in my current terminal but in a new vim process, `l` opens a new vim process but in another terminal which is worse (at least further from what I want to do than the other option).
I guess what is bugging me is that I don't see the purpose of the integration script since I could just type `:!lf` in vim which would open lf and have the same behaviour as the integration script. I feel like I am definitely missing something here.
But we'll see if some people have some ideas or other explanations for a newbie like me :)

Great software by the way, very practical to use and fast, can't wait to be able to benefit from it in my favorite editor ;)

**Comment by gokcehan** [comment]
@ashemsay When you use `open` from a `lf` process spawned with `:LF`, it should not launch a new terminal. I'm not sure why this does not work for you. Can you check both your `lf` and `vim` configurations to make sure there are no settings that can change this behavior?

When you use `:!lf`, there is no way to open the new files within the same `vim` process, hence we have an integration script.

**Comment by ashemsay** [comment]
> @ashemsay When you use `open` from a `lf` process spawned with `:LF`, it should not launch a new terminal. I'm not sure why this does not work for you. Can you check both your `lf` and `vim` configurations to make sure there are no settings that can change this behavior?
> 
> When you use `:!lf`, there is no way to open the new files within the same `vim` process, hence we have an integration script.

Well well... I started of a clean configuration and it worked using `l`, opening the selected file in my current window, even current split, perfect.

Just to be sure I added it again in my custom config and ... it worked again. I don't know what I did wrong the first time but I must have messed up something.

Thank you again for your answers and sorry for wasting your time.

**Comment by pratz** [comment]
I am facing a similar issue, can you guys help me out

`EDITOR=nvim OPENER=nvim lf`
LF doesn't open up files with `l` command

**Comment by ashemsay** [comment]
> I am facing a similar issue, can you guys help me out
> 
> `EDITOR=nvim OPENER=nvim lf`
> LF doesn't open up files with `l` command

Try to start from a clean vim configuration.

Also did you paste the integration script content into your vim conf or did you include it? 
The first time I pasted it, maybe that's where I made a mistake, missed a line or something else, the second time I used the include as mentioned in the script comments and got it working.

**Comment by gokcehan** [comment]
@pratz If you don't have a custom `open` command in your configuration, default `open` command is defined as async command so when you set `OPENER=nvim` it is like trying to run `nvim foo.txt &` in the terminal. You can try to define a custom command as a regular shell command if you like to use `nvim` as the opener as such:

    cmd open $nvim $fx

**Comment by pratz** [comment]
@gokcehan `lf.vim` doesn't work with neovim, is it possible for you to create one for neovim?
Would like to use `lf` with neovim :)

**Comment by gokcehan** [comment]
@pratz It is a simple function that is about 20 lines of code. I'm not sure why it doesn't work in neovim. I think they were trying to remove shell commands in neovim. I'm not sure how you are supposed to make this work without shell commands.

We also have a similar script in a separate repo [here](https://github.com/ptzz/lf.vim) by @ptzz. It says it works with neovim as well. Can you give this a try and see if it works or not?

**Comment by pratz** [comment]
Hey @gokcehan,
that's where I first raised the issue
https://github.com/ptzz/lf.vim/issues/1

Anyway, its been fixed in ptzz/lf.vim repo now, thanks though
