### ISSUE TITLE
`autoquit` should be enabled by default

### ISSUE THREAD

**Issue by ladyrick** [gokcehan/lf#1761]
When I use `lf` and exit, there is a server process leave there forever. It doesn't auto exit.

I think `lf`'s server should works like `tmux` server: when all client exits, the server should close itself.

**Comment by ladyrick** [comment]
I watched about 30 mins. I'm sure the server cannot auto exit.

**Comment by joelim-work** [comment]
You need to use `set autoquit true`, see https://github.com/gokcehan/lf/blob/master/doc.md#autoquit-bool-default-false for more information.

**Comment by ladyrick** [comment]
OK, thank you for point out that config.

Maybe make `autoquit` default `true` is better? I use `lf` as an out-of-the-box tool. I put it on a distributed filesystem and use it in many different machines. I think such a tool shouldn't leave anything behind by default.

**Comment by joelim-work** [comment]
So I searched through the previous issues, the reason why `autoquit` is disabled by default comes from https://github.com/gokcehan/lf/issues/177#issuecomment-844464642:

> A new `autoquit` option is added to automatically quit server when there are no connected clients left. This option is off by default to keep the old behavior. I have added this as an option to avoid respawning server repeatedly when there is often a single client involved but more clients are spawned from time to time.

I personally don't have much opinion on what the default should be either way.

**Comment by joelim-work** [comment]
For what it's worth, `tmux` server automatically quits when there's no more remaining sessions.

**Comment by joelim-work** [comment]
As this is an opinionated request, I am closing this in favor of a poll, see #1767 

If there is enough support, I will consider changing the default value for `autoquit`.
