### ISSUE TITLE
Broken characters of dir when I use `-print-last-dir` option / change drive option `/d` in `lfcd.cmd`

### ISSUE THREAD

**Issue by Jaehaks** [gokcehan/lf#1769]
Thank you for your efforts, 

I'm Windows user and using lf really well.

First, In order to get `lfcd` to change directory between drives, It would be better to add `/d` to cd 
```cmd
for /f "usebackq tokens=*" %%d in (`lf -print-last-dir %*`) do cd /d %%d
```

Second, `lf -print-last-dir ` print broken characters when the path has non-english words. 
Is It encoding issue?

**Comment by joelim-work** [comment]
Thanks, you are welcome to submit a PR to add in the `/d` flag.

Regarding non-english words, it looks like `lf -print-last-dir` works fine by itself, and the problem is with the `lfcd.cmd` script. I don't know how to deal with it though.

**Comment by joelim-work** [comment]
Actually I did some research, if you change the console to use UTF-8, does it work? Add the following at the top of the `lfcd.cmd` script:

```bat
chcp 65001 > nul 2>&1
```

**Comment by Jaehaks** [comment]
> Actually I did some research, if you change the console to use UTF-8, does it work? Add the following at the top of the `lfcd.cmd` script:
> 
> ```batchfile
> chcp 65001 > nul 2>&1
> ```

Thank you for your advice, 
It works!! 
I'll submit PR with solution of this issue.
