### ISSUE TITLE
Feature request: precalculate previews for files around the cursor

### ISSUE THREAD

**Issue by heather7283** [gokcehan/lf#1774]
Hi!
Currently, preview is generated only for file under the cursor. When scrolling through list of files, previews don't render fast enough to be displayed - this causes preview window to go blank. However, when scrolling through same list of files again, previews are rendered because they are now cached. This behaviour is especially noticable on slow storage.
See video for demonstration:

https://github.com/user-attachments/assets/ebf38180-a4c3-41b3-a43e-0f9d1ea5eb9b

Proposal: add a new option (let it be called `previewpreload` for now).
If it is set to a non-negative integer n, previews will be calculated in the background (and cached) for n files around the cursor, and then fetched from cache when user scrolls up/down. This way, when user scrolls through long list of files, by the time file is selected its preview is already present in the cache.

Potential issues:
1. `previewpreload` set too high may cause excessive CPU and IO load. It should be disabled by default, and it is user's responsibility to set it to a reasonable amount
2. If preview script takes too long to finish, user might select the file while background preview script for it is still running
3. If caching is disabled for specific file, background preview might be called several times for it needlessly
4. Probably something else I missed?

That said, unfortunately I don't have any experience with Go, so I can't implement this myself, but I think it's a nice QoL feature to have, so I'd like to know developer's opinion.

**Comment by DusanLesan** [comment]
This is duplicate of https://github.com/gokcehan/lf/issues/1537. 
I think caching should not be a issue solved by `lf`.
I think preview script should determine surrounding files and cache them, or at most `lf` could call cache script with the file names surrounding current file

**Comment by heather7283** [comment]
I somehow completely missed issue 1537, sorry for that..
In that case, I'm closing this one
Have a nice day!

**Comment by DusanLesan** [comment]
I mean you can argue your case in original issue. I have just given my opinion as a user
