### ISSUE TITLE
Add a command to select all files

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#178]

**Comment by gokcehan** [comment]
@alexherbo2 You can combine `:unselect` and `:invert` commands for this purpose:

    cmd select-all :unselect; invert

**Comment by mohkale** [comment]
@gokcehan does that work recursively? or better question is there a way to get it to work recursively?

Today I had a simple problem. I wanted to select all files at depth 2.

eg.

```
foo/
foo/bar
foo/baz
foo/bag
...
bar/
bar/foo
bar/baz
bar/bag
...
```

but lf doesn't seem to support recursive globs I.E. `:glob-select **/*`. In ranger I'd normally do `:flat 0` and then filter out directories so I can select the files, but `lf` doesn't have that feature yet so is there another recommended way?

I tried the subprocess approach:

```
find -type f -maxdepth 2 -mindepth 2 -exec lf -remote "send $id :select \"{}\"" ';'
```

but that spawns a tonne of lf processes and seems to hang indefinitely if you try to do too many files at once.

**Comment by alexherbo2** [comment]
Don’t you think `select-all` merits a dedicated command?

**Comment by gokcehan** [comment]
@alexherbo2 It's not obvious what should happen to selections in other directories with a builtin `select-all` command. `invert` command should cover most use cases. In other cases where a user selects some files and then decides to select all files instead, I think it is fair to expect the user to be explicit about what should happen to the previously selected files.
