### ISSUE TITLE
lf does not open terminal text editor when going right

### ISSUE THREAD

**Issue by Dutt-A** [gokcehan/lf#1780]
Hello,
lf is not able to open any kind of text file (.txt, .c, etc) when I hit the right arrow on them while ranger is always able to open them via neovim. Is there any way to make lf open text files (preferably in another terminal window if possible)

Could this potentially be a bug with xdg-mime? I'm on Fedora Sway, and actually Thunar is similarly unable to open files. My guess is that ranger is relying on $EDITOR instead of xdg-mime, which is why it can open the file.

Also, how do I make it so that 'e' would open a terminal in an entirely different terminal window?

**Comment by DusanLesan** [comment]
Hi. Can you try defining a custom `open` command as shown here: https://github.com/gokcehan/lf/blob/master/etc/lfrc.example
My open command is not much different
```
cmd open ${{
	case $(file --mime-type "$f" -b) in
		image/*) lf -remote "send $id open_images" ;;
		*/x-raw-disk-image) dmenumount "$f" ;;
		*/zip) lf -remote "send $id mount_archive" ;;
		text/*) $EDITOR $fx ;;
		*) for f in $fx; do setsid $OPENER $f >/dev/null 2>&1 & done ;;
	esac
}}
```
it just adds several more types to handle

**Comment by Dutt-A** [comment]
Awesome, this is exactly what I wanted! Perhaps I should have tried to understand the intended behavior/code better prior to asking...

Thank you!

**Comment by Dutt-A** [comment]
For future reference, this is what I ended up doing:

in .bashrc I added `export TERMINAL=/usr/bin/foot` and `export EDITOR=/usr/bin/nvim` for my environment variables. Then I set open to

```
# Interpreter for shell commands
cmd open ${{
	case $(file --mime-type "$f" -b) in
		image/*) lf -remote "send $id open_images" ;;
		*/x-raw-disk-image) dmenumount "$f" ;;
		*/zip) lf -remote "send $id mount_archive" ;;
		text/*) $TERMINAL $EDITOR $fx;;
		inode/x-empty) $TERMINAL $EDITOR $fx;;
		*) for f in $fx; do setsid $OPENER $f >/dev/null 2>&1 & done ;;
	esac
}}
```
This opens the text in another window (my preferred behavior) and also handles the empty file case.

**Comment by DusanLesan** [comment]
You can see `mount_archive` and `open_images` in my `lfrc` and `dmenumount` alongside my other scripts. But unless you have already copied them over, you should be able to safely remove these lines like this:
```
cmd open ${{
	case $(file --mime-type "$f" -b) in
		text/*) $TERMINAL $EDITOR $fx &;;
		inode/x-empty) $TERMINAL $EDITOR $fx &;;
		*) for f in $fx; do setsid $OPENER $f >/dev/null 2>&1 & done ;;
	esac
}}
```
