### ISSUE TITLE
Toggle maximize preview

### ISSUE THREAD

**Issue by jvc84** [gokcehan/lf#1806]
Didn't find any solutions for this feature, so this is mine

https://github.com/user-attachments/assets/bd2f3177-6a6c-42f2-8cee-1cce62d7eb12

```
cmd toggle_max_preview ${{
    cache=$HOME/.cache/lf/max_preview
    mkdir -p $cache

    file=$(ls $cache | grep -w $id || echo 0)

    if [ $file -eq 0 ]; then
        touch $cache/$id
        lf -remote "send $id set ratios 1:1000"
    else 
        rm $cache/$id
        lf -remote "send $id set ratios 1:2" # or your ratios
    fi
}}

...

map T  toggle_max_preview 

...

cmd on-quit ${{
    cache=$HOME/.cache/lf/max_preview 
    rm $cache/$id  2&> /dev/null 
}}
```

**Comment by joelim-work** [comment]
The values of settings are exported as environment variables in the format `lf_<option>`, so you can just simply write this:

```sh
cmd toggle_max_preview %{{
    if [ "$lf_ratios" != 1:1000 ]; then
        lf -remote "send $id set ratios 1:1000"
    else
        lf -remote "send $id set ratios 1:2"
    fi
}}

map T toggle_max_preview
```

It is very similar to the wiki example https://github.com/gokcehan/lf/wiki/Tips#toggling-the-preview-column

**Comment by jvc84** [comment]
I was trying to use it as `$ratios`. Thanks for help

**Comment by joelim-work** [comment]
The environment variables are prefixed with `lf_` to avoid potential conflicts with anything else.

Anyway glad you solved your issue, will close this then.
