### ISSUE TITLE
maybe duplicated initialization 

### ISSUE THREAD

**Issue by zenyusy** [gokcehan/lf#1810]
https://github.com/gokcehan/lf/blob/4de690db5e40d463071ceac03a6cffa5a8ac80cf/client.go#L57-L67

hi! lf is a very nice tool, thanks for creating and maintaining it.

seems like nav.sync already calls readMarks and readTags, is this redundancy necessary?

**Comment by joelim-work** [comment]
I had a look through the project history, it appears that `nav.sync` was originally supposed to only sync the list of cut/copied files, but this was extended to sync the list of marks as well. See https://github.com/gokcehan/lf/pull/190#issuecomment-505108846:

> I think maybe instead of adding a new command we can directly integrate marks syncing functionality to the `sync` command. I can't think of any downsides to this.

So I suspect that you are correct and the code on lines 61-67 aren't necessary. You are welcome to try it out yourself and submit a PR if that is the case.
