### ISSUE TITLE
How to copy an image to the system clipboard like dolphin does?

### ISSUE THREAD

**Issue by tallguyupn** [gokcehan/lf#1813]
Hello!

i would like to use lf and use it as my only file manager. I have an issue tho. How do i copy a file so i could paste it into discord or something like that?
Thanks in advance.

**Comment by DusanLesan** [comment]
I have this for `lf` in X11:
```
cmd yank_image ${{
	if [ $(mimetype -Mb "$f") = "image/png" ]; then
		xclip -sel c -t "image/png" "$f" >/dev/null 2>&1 &
	else
		convert "$f" png:- | xclip -sel c -t "image/png" &
	fi
}}

map <a-y> yank_image
```

**Comment by DusanLesan** [comment]
Another useful tool I use is [dragon-drop](https://github.com/mwh/dragon). It makes you items that you can pick up and drag&drop wherever that is needed
```
map dr &dragon-drop -a -x $fx
```

**Comment by se7en-x230** [comment]
I use this for all files in wayland

`cmd y-f ${{
 ( echo -n "file://" && readlink -e "$f" ) | wl-copy -t text/uri-list
}}
#-------------------
map yf y-f Copy file to clipboard
#-------------------

`

**Comment by tallguyupn** [comment]
@se7en-x230 
I will be trying this today when i get home. Thanking in advance if it works.

**Comment by tallguyupn** [comment]
@se7en-x230 tysm it works. I am so grateful
