### ISSUE TITLE
lf doesnt close/kill, when closed window in tilling windows manager

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1819]
I use Debian 12.7.0 and Bspwm tilling windows manager, but I now reinstalling my system.

I installed the new lf (env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest). And now, when I closed or kill (bspc node -{c,k}) the window (which contains lf), then the window is disappeared, but the lf process doesnt closed/killed in background and it takes up about 7% of the cpu for each stuck piece.
I try r32 version (stable), and that version is working fine. Unfortunately I can't remember which version I used before the reinstall my debian system, what was the last commit of that version.

**Comment by joelim-work** [comment]
`lf` should quit when receiving `SIGHUP`: https://github.com/gokcehan/lf/blob/78413a6c9e052da63e0367ade0b7ba39271b63ef/app.go#L57-L59

Only the latest version is supported - can you reproduce this on r32, and if possible by building from the latest master branch?

**Comment by og900aero** [comment]
> `lf` should quit when receiving `SIGHUP`:
> 
> https://github.com/gokcehan/lf/blob/78413a6c9e052da63e0367ade0b7ba39271b63ef/app.go#L57-L59
> 
> Only the latest version is supported - can you reproduce this on r32, and if possible by building from the latest master branch?

No. r32 is working fine. When I close/kill window with Bspwm, the lf process closed. So r32 is working fine.
How can I install from the latest branch? I only find the following instructions:
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

**Comment by joelim-work** [comment]
You need have `go` installed, and then that command will build and place the executable in `$GOPATH/bin`. Alternatively, you can also clone this repo and run `go build`.

**Comment by og900aero** [comment]
> You need have `go` installed, and then that command will build and place the executable in `$GOPATH/bin`. Alternatively, you can also clone this repo and run `go build`.

But that's what I did 10 hours ago when I reported this error. Or has there been a change in the master branch since then?

**Comment by og900aero** [comment]
I try send signals:

kill -s SIGTERM 9448 -> nothing happend
kill -s SIGHUP 9448 -> nothing happend
kill -s SIGQUIT 9448 -> nothing happend

kill -s SIGKILL 9448 -> lf process closed

**Comment by joelim-work** [comment]
I can't reproduce the issue, and I'm pretty sure the relevant code hasn't been changed since r32.

If you want to spend time to debug the issue, then you can try cloning the repo and doing a `git bisect` starting from the r32 tag.

**Comment by joelim-work** [comment]
Also I don't use Debian - maybe the issue is something system-specific or to do with the fact that you are building the executable locally. It's fine to leave this issue open and see if anyone else can reproduce.

**Comment by og900aero** [comment]
> I can't reproduce the issue, and I'm pretty sure the relevant code hasn't been changed since r32.
> 
> If you want to spend time to debug the issue, then you can try cloning the repo and doing a `git bisect` starting from the r32 tag.

Unfortunately I do not understand git bisect.
It also occurred to me that I use the roundbox and colored icons feature. So it worked for me when I installed them. I don't know which one was made later. Maybe I can clone the state when the earliest of the two functions was added?

**Comment by joelim-work** [comment]
Once you clone the repo, you can use `git log` to look at the commit history, and `git checkout <commit>` to checkout the code at a particular commit. Hopefully that can help you locate the issue.

**Comment by og900aero** [comment]
> Once you clone the repo, you can use `git log` to look at the commit history, and `git checkout <commit>` to checkout the code at a particular commit. Hopefully that can help you locate the issue.

Thx. I will try it. Now tried the following procedure: lf -config /dev/null
And now working fine. When use my config, then stuck the process, and 25% cpu...So one of the commits might be messing with one of my settings. I'll start deleting the config file line by line to see which one is causing it, and then I'll start going backwards in the commits. It will be fun :D

**Comment by og900aero** [comment]
There you have the problem. I have one in lfrc:

```
cmd on-quit :{{
...
$cat /dev/null > ~/.local/share/lf/tabs
...
}}
```

What this line does is to empty the tabs file (this is where I store the directories that I've saved, as if I were using my tabs function under lf. I really miss this feature imho). This worked fine before, but for some reason it doesn't work with the new version. If I change this line to this:
&cat /dev/null > ~/.local/share/lf/tabs
then it works fine and all lf processes can be closed properly.
