### ISSUE TITLE
Unselect files selected to cut

### ISSUE THREAD

**Issue by JurisMajors** [gokcehan/lf#182]
When selecting files to cut, :unselect does not work to remove the selection, instead you must paste in the same directory.

Moreover, the files selected to cut, dont even unselect when you quit lf, and stay selected to cut for next instance. So having :unselect to work on them would be nice.

**Comment by gokcehan** [comment]
@JurisMajors We actually have a separate command to clear the cut/copy selection named `clear` (default <kbd>c</kbd>). I realized this is not mentioned anywhere in the documentation. I will try to add something about this to "File Operations" section in the documentation.
