### ISSUE TITLE
Documentation: ratio examples

### ISSUE THREAD

**Issue by EvgeniyBlinov** [gokcehan/lf#1835]
Please add examples for changing the aspect ratio.
I don't understand how to set up one little window for selecting files and for preview.

I tried these settings:
```
set preview true; set ratios 0:1:10
set preview true; set ratios 1:10
set preview true; set ratios 1
```

**Comment by DusanLesan** [comment]
I do not see the issue in your examples. That works for me if this is what you are trying to achieve:
![image](https://github.com/user-attachments/assets/59a175ad-11a7-4cda-99e3-eab6ac58ece6)

**Comment by EvgeniyBlinov** [comment]
Sorry, my fault.
If I run without config `lf -config /dev/null` I get needed behavior.

Apparently, some settings override the behavior I need.
Can you tell me if there is a command that can dump all current settings at runtime?

**Comment by joelim-work** [comment]
Settings are [exported as environment variables](https://github.com/gokcehan/lf/wiki/Troubleshoot#displaying-current-settings) in the form `lf_<option>`, you can use that to dump the current values at runtime.

You can also try [enabling logging](https://github.com/gokcehan/lf/wiki/Troubleshoot#enabling-logging) to see what config files are being loaded.
