### ISSUE TITLE
create repeated expr only when `count` is not 0 ?

### ISSUE THREAD

**Issue by zenyusy** [gokcehan/lf#1844]
https://github.com/gokcehan/lf/blob/0b5749f0ef749c9ce357bb16f0b6750b2b925563/ui.go#L1350-L1356

these lines are executed very often when doing basic operations, like moving j/k around (i added log hook and found this).

it is however only meaningful when `count != 0`. i think doing type assertions so often is unnecessary, and the code can be changed to:

```go
if count != 0 {
    switch e := expr.(type) {
    case *callExpr:
        eRepeat := *e
        eRepeat.count = count
        expr = &eRepeat
    case *listExpr:
        eRepeat := *e
        eRepeat.count = count
        expr = &eRepeat
    }
}
```

any advice? (the above code has identical-looking lines inside each case, it's a bit ugly, i dont know how to beautify though ...)

**Comment by joelim-work** [comment]
Hi, I think you suggestion is OK, and can be submitted as a pull request.

BTW I simplified the code a bit further, but I'm not sure about how to avoid repeating the code for each type of `expr`:

```go
if count != 0 {
	switch e := expr.(type) {
	case *callExpr:
		e.count = count
		expr = e
	case *listExpr:
		e.count = count
		expr = e
	}
}
```

**Comment by DusanLesan** [comment]
Is this ok:
```go
if count != 0 {
    switch expr := expr.(type) {
    case *callExpr, *listExpr:
        expr.count = count
    }
}
```

**Comment by zenyusy** [comment]
@joelim-work  haha this is the tricky thing here that i also ran into.
expr is the pointer pointing to the `expr` object in the `gOpts.keys` map, shared globally. so directly changing the `.count` field will change the global data in the map, *polluting* subsequent calls with that count. (that's why the original code needed to explicitly copy the objects) 

e.g. `2j` to move down 2 items, then just hit one `j` will keep moving down 2 items

**Comment by zenyusy** [comment]
i will just do this
```
if count != 0 {
    switch e := expr.(type) {
    case *callExpr:
        expr = &callExpr{name: e.name, args: e.args, count: count}
    ...
    }
}
```

one-liner literal copy

**Comment by joelim-work** [comment]
@zenyusy Ah sorry you're right, thanks for correcting me!

In that case the new version of the code looks fine to me - it's a one-liner that clearly expresses its intent. Thanks.
