### ISSUE TITLE
Cleaner not called on wayland /hyprland(For kitty and ctpv). Tmux issue also

### ISSUE THREAD

**Issue by PoutineSyropErable** [gokcehan/lf#1845]
I used the recent wiki for kitty command. 
I'm on hyprland. 

The cleaner script just isn't properly called as I move from one image to another

![image](https://github.com/user-attachments/assets/8fdb8547-0b41-4e4c-aaf0-4575088eb65d)

**Comment by joelim-work** [comment]
If you're using `ctpv` then report the issue there. Otherwise you can use a more minimal setup mentioned in the [previews section of the wiki](https://github.com/gokcehan/lf/wiki/Previews#with-kitty-and-pistol)

**Comment by PoutineSyropErable** [comment]
Oh sorry. I wasn't clear. 
I tried using both. Both do not work. 

The Minimal Kitty cleaner script. And the ctpv cleaner script. 

Both do not work.

**Comment by joelim-work** [comment]
If the minimal Kitty setup doesn't work for you either then there's a number of things that could be wrong:

- `previewer`/`cleaner` is located at the wrong path, or is not executable
- `previewer` script doesn't return `exit 1` when drawing an image, so 
- `cleaner` script has a syntax error

Have you tried [enabling logging](https://github.com/gokcehan/lf/wiki/Troubleshoot#enabling-logging), or adding test logging code (e.g. `echo "$@" >> /tmp/lf.log`)  to the `previewer`/`cleaner` scripts?

Also it might be helpful if you can provide minimal config files, with all the irrelevant settings removed.

**Comment by PoutineSyropErable** [comment]
It's due to being in  tmux session, ill try the test code

**Comment by joelim-work** [comment]
So you mean it works fine outside of `tmux`? Generally I assume that a given user doesn't is it unless it's specifically mentioned.

**Comment by PoutineSyropErable** [comment]
Yes, I've tried this version of lf with the exact scripts provided in the wiki for kitty.
I wasnt sure if i had a fork (lf-sixel), so i rm the binary and go files. then yay -S lf

I'm currently testing on hyprland.
outside of a  tmux session, the images preview and cleaning works perfectly.
Howver, inside tmux, it's broken.

I asked chatgpt and it said maybe its because its the wrong tty device. So it modifed the scripts, but it didn't help.

**Comment by PoutineSyropErable** [comment]
In fact, inside tmux, it looks likes it doesn't even preview images at all. 
it preview for a ms then fails and clean.  

I'll test inside tmux on x11

**Comment by PoutineSyropErable** [comment]
In fact, inside tmux, it looks likes it doesn't even preview images at all. 
it preview for a ms then fails and clean.  

I'll test inside tmux inside i3.

test result. It doesn't work either. inside tmux (wayland or x11)

**Comment by PoutineSyropErable** [comment]
here's lf -log lf.log

2024/11/13 00:36:29 hi!
2024/11/13 00:36:29 reading file: /home/francois/.config/lf/colors
2024/11/13 00:36:29 reading file: /home/francois/.config/lf/icons
2024/11/13 00:36:29 loading files: [/home/francois/Pictures/Desktop Background Slideshow/Cool Pictures/ciri-head.jpg /home/francois/Pictures/Desktop Background Slideshow/Cool Pictures/1340958.jpeg]
2024/11/13 00:36:29 reading file: /home/francois/.config/lf/lfrc
2024/11/13 00:36:29 loading files: [/home/francois/Pictures/Desktop Background Slideshow/Cool Pictures/ciri-head.jpg /home/francois/Pictures/Desktop Background Slideshow/Cool Pictures/1340958.jpeg]
2024/11/13 00:36:29 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:29 recv: set statfmt "[1;34md[33mr[31mw[32mx[0m[33mr[1;90m-[0m[32mx[33mr[1;90m-[0m[32mx[0m [1;90m-[0m [1;33mfrancois[0m [34m12 Nov 23:33[0m [36m/home/francois/.config/lf/[1;34mother_stuff[0m"
2024/11/13 00:36:30 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:30 recv: set statfmt ".[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [33m1.6M[0m [1;33mfrancois[0m [34m13 Nov 00:05[0m [36m/home/francois/.config/lf/[35m__image1.jpeg[0m"
2024/11/13 00:36:30 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:30 recv: set statfmt ".[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [1;32m411k[0m [1;33mfrancois[0m [34m13 Nov 00:05[0m [36m/home/francois/.config/lf/[35m__image2.jpg[0m"
2024/11/13 00:36:31 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:31 recv: set statfmt ".[1;33mr[31mw[4;32mx[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [32m104[0m [1;33mfrancois[0m [34m13 Nov 00:17[0m [36m/home/francois/.config/lf/[1;32mcleaner.sh[0m"
2024/11/13 00:36:31 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:31 recv: set statfmt ".[1;33mr[31mw[4;32mx[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [32m180[0m [1;33mfrancois[0m [34m13 Nov 00:31[0m [36m/home/francois/.config/lf/[1;32mcleaner_tmux.sh[0m"
2024/11/13 00:36:32 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:32 recv: set statfmt ".[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [1;32m3.4k[0m [1;33mfrancois[0m [34m 8 Aug 19:11[0m [36m/home/francois/.config/lf/[0mcolors"
2024/11/13 00:36:32 shell-async: &{{ lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\"" ... }} -- []
2024/11/13 00:36:32 recv: set statfmt ".[1;33mr[31mw[90m-[0m[33mr[1;90m--[0m[33mr[1;90m--[0m [1;32m26k[0m [1;33mfrancois[0m [34m18 Oct 16:45[0m [36m/home/francois/.config/lf/[0mi3_config"
2024/11/13 00:36:33 shell-async: &{{ pwd > "$LF_CD_FILE" ... }} -- []
2024/11/13 00:36:33 recv: quit
2024/11/13 00:36:33 bye!

Another run with the cleaner code log:
/home/francois/.config/lf/__image1.jpeg 120 46 118 1 /home/francois/.config/lf/__image2.jpg
/home/francois/.config/lf/__image2.jpg 120 46 118 1 /home/francois/.config/lf/cleaner.sh>

previewer log:
/home/francois/.config/lf/__image1.jpeg
/home/francois/.config/lf/__image2.jpg



-------
This seems to be a rather old issue, idk,
https://github.com/gokcehan/lf/discussions/1153
------

In fact, it seems to be a kitty + tmux issue as a whole.
But if like chatgpt said, all you'd need would be the right tty direction, then it would be cool.

**Comment by PoutineSyropErable** [comment]
https://github.com/kovidgoyal/kitty/issues/2457

I swtiched back to lf-sixel-git, as it works better, still have broken clear, but the images works better in tmux. 
both works correctly outsdie tmux. 

Again, maybe it's just about finding the right tty device and it will work.

**Comment by PoutineSyropErable** [comment]
To be precise, your version of lf, on X11, and with ctpv clearing works.(Even inside tmux). Works perfectly in fact. 
Same with lf-sixel-git (the fork)

It's when we use the kitty method, that it starts breaking. (on X11)



On wayland, however, lf-git (this one), isn't saved by ctpv inside tmux. Lf sixel works slighly better with ctpv and kitty, but the cleaning doesn't work. 
So you have to manually leave and come back, or execute a script, and  then the cleaning will work.

**Comment by PoutineSyropErable** [comment]
I tried a hacky way, which would be to clean in ctpv and just cat a huge empty file. It doesn'T work, but im a dumb undergrad. 
(as when text appears, it does clean the space where there are characters). 
Maybe all you need is a way to use ctpv (the one which works best on  wayland, currently lf-sixel works better then this on wayland), and just have a wrapper that cat spaces.txt

**Comment by PoutineSyropErable** [comment]
Another solution i have is to map a key im comfortable with double tapping to execute a script that does nothing (the press any key to continue auto clear)

**Comment by joelim-work** [comment]
So I tried this out myself and I also experienced the same issues. The logs confirm that the `previewer`/`cleaner` scripts are being called with the right arguments, so the issue isn't to do with `lf` at all.

I assume whoever added the `kitty` method in the wiki doesn't use `tmux`, I guess it's fine if you want to add a note saying that they're incompatible. Otherwise I'm not really sure what else can be done here - `lf` doesn't display images by itself, it delegates that task to external tools.

**Comment by PoutineSyropErable** [comment]
alright, well, the best solution i have is this:
Assuming kitty+tmux:
 (Use lf-sixel, and ctpv. It will work on X11). 

For wayland:
double tap one of these key or key+any other when the old previews are problematic. 
map C !~.config/lf/empty.sh > /dev/null &
map h !~/.config/lf/empty.sh > /dev/null &
map w !~/.config/lf/empty.sh > /dev/null &

---
empty.sh
#!/bin/bash
exit 0


and just double that one of these key when the non cleaned images is annoying

thanks for the help. And thanks for lf.

**Comment by se7en-x230** [comment]
This is not a solution. Super annoying. 
Any ideas how to fix this?
Wayland/Hyprland/Arch

**Comment by PoutineSyropErable** [comment]
Nope. lf-sixel and ctpv (or kitty) works if you don't have tmux. 

Maybe regular lf works on hyprland without tmux too. I just live with it now.

**Comment by PoutineSyropErable** [comment]
But on x11, kitty works with tmux, I think its because ctpv just wraps to Uberzug, and uerberzug works with kitty + tmux. But uerberUg is x11 only

**Comment by se7en-x230** [comment]
![image](https://github.com/user-attachments/assets/f08e1aa8-7327-4e30-950a-f005ae422e12)

this give me image preview but not pdf and text

**Comment by PoutineSyropErable** [comment]
Use lf-sixel-git and ctpv. Dcheck ctpv github oage and download its dependancies. (Both can be downloaded with yay/paru). 

Alsoif you copy their kitty script, oit falls back to something for text. If you dont have that package... it wont work. You can easily pick another fallback by just changing the line or downloading it.

**Comment by se7en-x230** [comment]
Hmmm ... after an wasted afternoon ...

lf-git 
and
set previewer ctpv
set cleaner ~/.config/lf/kitty-cleaner

works

**Comment by PoutineSyropErable** [comment]
Wait this config works for real? GG I spent like 2 days on gave up.

**Comment by se7en-x230** [comment]
I even tried to unset 
# set chafasixel

and that also work fine

**Comment by se7en-x230** [comment]
file:///home/seven/DataInt/Documents/Videos/Recordings/lf-preview.mp4

strange because it used to work since years ...
Anyway ... works again

**Comment by se7en-x230** [comment]
https://0x0.st/XFbQ.txt

there is for sure some "special sauce" inside ... many years of lf as the only file manager ...
