### ISSUE TITLE
Question: About usage on Windows with PowerShell

### ISSUE THREAD

**Issue by DBremen** [gokcehan/lf#186]
First of all thanks a lot for building such a great tool.
I would like to use this on Windows in combination with Powershell. Is it possible to set the shell to PowerShell. If yes,
 - where would I need to put the config file?
- how would I be able to access the variables e.g. $f for the selected file?

**Comment by gokcehan** [comment]
@DBremen You can `set shell powershell` but currently command string uses `/c` argument on windows so if I remember correctly this wasn't working. We should either add a way to configure the command string argument or just simply hardcode this for `cmd` and `powershell`.

Configuration file should be located at `C:\Users\<user>\AppData\Local\lf\lfrc`. See "Configuration" section in the documentation for more information.

I think powershell also uses `$` for variables so you should be able to access the variable as `$f` though I need to give this a try when I get back to my windows.

**Comment by DBremen** [comment]
Hi @gokcehan . Thanks a lot. Powershell works generally with that, I also get access to the variable through the env drive e.g. `$env:f`. Problem is, that the command gets only executed after I force out of it with CTRL+C. Example command `Invoke-Item $env:f.replace('"','')`

**Comment by gokcehan** [comment]
@DBremen I have taken a look at this again. There does not seem to be an easy way to solve shell command issues in windows. A workaround is to create commands as separate scripts and call them in commands and mappings. Closing this issue in favor of #431
