### ISSUE TITLE
Newbie, need help passing varaibles into commands

### ISSUE THREAD

**Issue by Set2Minecraft** [gokcehan/lf#1862]
I am currently attempting to have rename show the current file name when called ( exactly like ranger ).
current keybind is:
map a push :rename<space>$f

This is just outputting $f. I would like it to output the file name
I have tried $$f  "$f"

I need help, I dont know what im really doing

**Comment by joelim-work** [comment]
You don't need `push`, that is used for simulating keypresses. Just use the following:

```
map a rename
```

You can also have a look at https://github.com/gokcehan/lf/wiki/Tips#enhancing-the-rename-command for different variants of `rename`.

**Comment by Set2Minecraft** [comment]
Ah, thanks. This shows how much I know about lf. However the keybind or

map r push :rename<space>
is in the lfrc.example line 56
https://github.com/gokcehan/lf/blob/68a29c92848397e642e060a83f8a1bd7bd979af2/etc/lfrc.example#L56


Which is where I got confused and thought this was how it had to be.

**Comment by joelim-work** [comment]
That is only used for if you want to provide your own custom implementation of `rename`, for example using `mv` (uncomment the line above in that example config file), instead of using the built-in functionality.
