### ISSUE TITLE
Custom Folder Icons

### ISSUE THREAD

**Issue by Set2Minecraft** [gokcehan/lf#1863]
A simple concept

in the icons section there are matches for files and filetypes

an expansion could be a syntax for folder ( with perhaps a custom icon for lf )

If this already exists, please tell me how ( I am a newbie )

**Comment by joelim-work** [comment]
Change the following value in your icons config file:

https://github.com/gokcehan/lf/blob/68a29c92848397e642e060a83f8a1bd7bd979af2/etc/icons.example#L28

**Comment by Set2Minecraft** [comment]
Sorry, I miss communicated
I meant specific file names
example: I want the folder named "linux" to have this as the icon instead of the folder icon used by other folders ->  ( this should've been tux if the icon is in github )

**Comment by joelim-work** [comment]
Try using `linux/` instead of `di`. You can have a look at the [documentation](https://github.com/gokcehan/lf/blob/master/doc.md#colors), configuring icons is similar to colors.

**Comment by Set2Minecraft** [comment]
Works Perfectly! Thanks! I do have one more question though, it is about colors, what is it that determines what the color is? what I mean is that I see 01;36 creates a cyan like color, where can something like a wheel or table to fully customize my colors?
