### ISSUE TITLE
Deleting, clearing marks

### ISSUE THREAD

**Issue by JurisMajors** [gokcehan/lf#188]
Have been using the mark functionality a lot recently, but sometimes, when I move/delete directories, those old marks still stay there.

Is there any way to clear the mark list (or delete a specific mark) through lf?

(Clearly it can be done through editing the marks file, however, thats too much effort ;p)

**Comment by gokcehan** [comment]
@JurisMajors I tried editing the marks file with a shell command as such to delete mark `x`:

    $sed -i '/^x/d' ~/.local/share/lf/marks

But the file is overwritten again on exit. I guess this needs to be a builtin command somehow so we can clear the mark in the memory as well. We also need to consider the cases with multiple cases.

**Comment by JurisMajors** [comment]
@gokcehan Sounds like a doable enhancement. I'd love to do this, however, I dont know much about the server-client implementation. Is there a command that changes something to all clients, that I could take as an example?

**Comment by JurisMajors** [comment]
How exactly would we handle multiple clients. 
Do we update marks for immediately? Thats inconsistent with current functionality, i.e. when I load a new mark, it does not update for all clients.
or do the marks get updated after a refresh of lf. (just like it works with new marks right now)

I think it makes sense if they get updated instantly, just like cutting/selections do. However, that would require changes to the current mark-save functionality.
I would assume that we have to send a call to the server, so that it reads the marks file for each client (after its updated), however, not sure how to do that.
