### ISSUE TITLE
Crash upon using autocompletion on russian filenames 

### ISSUE THREAD

**Issue by Siborgium** [gokcehan/lf#193]
Autocompleting russian filenames leads to either broken autocompletion (`&zathura Ф` -> `&zathuФихтенгольц` ) or crash (`&mv Д` -> crash, where `Д` was expected to be autocompleted to `Демидович - Сборник задач по математическому анализу, 2005.pdf`).

**Comment by brualan** [comment]
I will study this problem and try to solve it

**Comment by Siborgium** [comment]
Thank you very much, I am looking forward to it.

**Comment by gokcehan** [comment]
I have now pushed a commit to fix this for autocompletion. Word movements can still leave artifacts behind. Keeping the issue open.

**Comment by Siborgium** [comment]
Thank you, it's much more comfortable now.

**Comment by gokcehan** [comment]
I have now fixed word movements as well. Everything should be ok now. Closing the issue. Feel free to leave further comments if something is not working.

@Siborgium Apologies for taking too long to solve this issue. I have been quite busy lately. Thanks for reporting.
