### ISSUE TITLE
odd look within tmux session

### ISSUE THREAD

**Issue by iamantu93** [gokcehan/lf#194]
Lf in tmux session looks odd, when drawbox setting is on. [tmux](https://imgur.com/a/wK4B8MN)

**Comment by gokcehan** [comment]
@iamantu93 That is quite strange. What font are you using? I feel like there might be an issue with [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) in your terminal font. Can you paste the following to your terminal to see if they display properly?

    ─  (horizontal line)

    │  (vertical line)

    ┌  (top left corner)

    ┐  (top right corner)

    └  (bottom left corner)

    ┘  (bottom right corner)

    ┬  (top T corner)

    ┴  (bottom T corner)

**Comment by iamantu93** [comment]
I am using Inconsolata font. Here is how everything looks like. I can't see any problem if it's running outside a tmux session [Look here](https://imgur.com/a/DBc5hyr)

**Comment by gokcehan** [comment]
@iamantu93 So then it is a tmux problem?

**Comment by gokcehan** [comment]
@iamantu93 Closing this issue as it is likely a tmux configuration problem. Feel free to leave further comments if you have.
