### ISSUE TITLE
Target file/directory is not shown for symbolic links

### ISSUE THREAD

**Issue by gokcehan** [gokcehan/lf#196]
Currently there is no way to tell which path a symbolic link directs to. We should add this information somewhere in the ui. Ranger shows this in the status line which we can adapt if there is no better alternative.

First mentioned in #156

**Comment by wedens** [comment]
I've migrated to lf from ranger recently and I like lf so far. But I really miss being able to see symlink destination. I use [NixOS](https://nixos.org/) on my machines which heavily uses symlinks and it's often useful to see their destination.

Simple implementation with destination near filename (like in ranger) would suffice,  but I'd also be nice to have an option to display symlinks like this (screenshot from dired in emacs):
![image](https://user-images.githubusercontent.com/697162/83895796-64ac8580-a77d-11ea-9d68-9aa4bfb9521b.png)
