### ISSUE TITLE
Respect gitignore file

### ISSUE THREAD

**Issue by pr4th4m** [gokcehan/lf#199]
How do I make `lf` respect gitignore file?

**Comment by gokcehan** [comment]
@pratz What do you mean by respecting? Is it like hiding files in gitignore files? Is it a good idea to do that in a file manager? I understand this can be useful for tools like `grep` but I'm not sure about file managers.

**Comment by pratz** [comment]
Ya, hiding or excluding files/directories which are in gitignore file.
For instance, all `.pyc` files in a project are listed with `lf`, which I feel is a distraction.
Would be really convenient to exclude files/directories.

**Comment by 097115** [comment]
> Is it a good idea to do that in a file manager?

It certainly isn't "as is". However, what about treating files in `.gitignore` as "hidden files", toggleable with `zh`?

**Comment by pratz** [comment]
Every developers workflow is different, if ignoring files with zsh works for you, do it :)
However, I personally feel hiding/unhiding should be file manager's job instead of shell's.

**Comment by TeddyDD** [comment]
This should be general mechanism that allow to use any *ignore file (dockerignore, helmignore etc.)

**Comment by adamtabrams** [comment]
I think there may be a pretty simple solution for this. When **hidden** is set, every file in a directory should be shown. But you could let the user set a script for **filehider** the same way we can with **previewer**. That way the lf project doesn't have to implement a ton of different options, but a user can customize what is hidden when hidden isn't set. Users could have their script use a tool like [fd](https://github.com/sharkdp/fd) which has lots of options and is made for this kind of stuff.

**Comment by gokcehan** [comment]
This should now be possible to implement as a custom command with `hiddenfiles` option and `on-cd` command.
