### ISSUE TITLE
handle symlinks

### ISSUE THREAD

**Issue by gregf** [gokcehan/lf#2]
Currently you can't seem to chdir into a symlink, it tries to open it as a binary file. For me it meant it loaded it in firefox.

**Comment by gokcehan** [comment]
It sounds quite annoying. Latest commits (6a2bdf472b47423c2f16ace1dfae54cb475ea8e6, fac1c9e8dec140dc0df890924029b6162fe4320d and bc4c3c127bad1c8c38c2395bf3394bffdbf5d135) should fix symlink problems. Closing this issue now. Feel free to open again if you continue to have any problems.
