### ISSUE TITLE
unreadable directories are previewed as empty

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#202]
I noticed that if a directory doesn't have read / execute permissions, the preview window shows the word `empty` while it **should** print something like `Permission denied` or perhaps more specifically: `Unreadable directory`.

BTW sorry for the [issues bombard](#201), these small issues have bothered me for a while but I didn't find the time to report them until now.

**Comment by gokcehan** [comment]
@doronbehar Actually thanks for reporting these issues. These are small and clear issue reports that makes things easier.
