### ISSUE TITLE
Support ctrl+arrow key binds

### ISSUE THREAD

**Issue by Limero** [gokcehan/lf#205]
It's not possible to bind `ctrl+arrow key`, like `ctrl+right`, because lf uses [termbox-go](https://github.com/nsf/termbox-go) which is missing `CtrlArrowRight`.

Termbox is no longer maintained, and the author recommends moving to tcell after being asked about ctrl+arrow support. https://github.com/nsf/termbox-go/issues/60

I guess there is three ways of adding this support to lf:
1. Move to tcell. We should probably not continue to rely on a deprecated dependency anyway.
2. Fork termbox-go
3. Try to solve it by listening to raw events in lf through termbox-go. Mentioned in the [termbox-go issue](https://github.com/nsf/termbox-go/issues/60)

Thoughts?

**Comment by gokcehan** [comment]
@Limero I have thought about moving to tcell before. It even has a compatibility layer for termbox that I have tried before but I remember not everything working properly. So simply moving to tcell will probably introduce some bugs though it might be a reasonable choice in the long term.

I have considered forking termbox-go before. It mostly works and it is somewhat stable though windows support has some issues. Maybe we can consider this as a short term solution though it might be difficult to maintain such libraries in all supported platforms.

I haven't looked into raw events much though my understanding is that using this strategy may not be portable among all platforms. However, if we can add something that works in some platforms and does not effect the others, we can consider such a feature.
