### ISSUE TITLE
Some directories have file icons by default

### ISSUE THREAD

**Issue by Naheel-Azawy** [gokcehan/lf#207]
Under icons.go we see:

```
	switch {
	case f.IsDir() && f.Mode()&os.ModeSticky != 0 && f.Mode()&0002 != 0:
		key = "tw"
	case f.IsDir() && f.Mode()&os.ModeSticky != 0:
		key = "st"
	case f.IsDir() && f.Mode()&0002 != 0:
		key = "ow"
	case f.IsDir():
		key = "di"
```

And up before it:

```
	defaultIcons := []string{
		"di=🗀",
		"fi=🗎",
	}
```

This result the first 3 cases to have files icons and not directories. I think this can be easily fixed with:

```
	defaultIcons := []string{
		"tw=🗀",
		"st=🗀",
		"ow=🗀",
		"di=🗀",
		"fi=🗎",
	}
```

I wanted to fork and pull request but I'm not sure if this is the right thing to do. From my side I'm happy after setting my LF_ICONS to `export LF_ICONS='di=🗀:tw=🗀:st=🗀:ow=🗀:fi=🗎:'`. But I think this would not make a lot of sense to new users so I thought better open an issue and see what do you think

**Comment by gokcehan** [comment]
@Naheel-Azawy I have now changed this as you recommended. Closing this issue now. Thanks for the patch.
