### ISSUE TITLE
Reload the view on file changes

### ISSUE THREAD

**Issue by wpcarro** [gokcehan/lf#213]
First of all, thank you for such a great piece of software. I love `lf` and I'm looking for more ways to integrate it into my workflow.

If I have two panes of `lf` open, A and B, and both have `dir` as the `CWD`. If I create a file in A, is there a way for B to refresh its view?

For now I just have `map r load` and I press `r` from time-to-time to ensure my view isn't stale.

**Comment by shabahengam** [comment]
use "period" option for auto reloading.put this in your lfrc file: `set period 1` 
now lf will reload every second.read [this comment](https://github.com/gokcehan/lf/issues/73#issuecomment-395991864) for more info

**Comment by wpcarro** [comment]
Great! Thanks so much
