### ISSUE TITLE
Make :delete async

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#215]
So today I wanted to delete a very large directory. It surprised me that Lf was frozen during the deletion. Is `:delete` async? I assume not, in comparison to `paste`. Anyway, I think it should be.

**Comment by gokcehan** [comment]
@doronbehar We are currently using [os.RemoveAll](https://golang.org/pkg/os/#RemoveAll) for `:delete` command. If we simply make it asynchronous, then there is a chance that the delete operation may not have finished on quit. So I think we first need to recurse into the directory to count the number of files first, and then remove these files one by one with [os.Remove](https://golang.org/pkg/os/#Remove), similar to what we do in `:paste`.

**Comment by doronbehar** [comment]
Then I think this dilemma is related to #177. If the server is running in the background all the time, even when the file manager quits, we can at least leverage that for the sake of long, asynchronous operations like these.

For inspiration, Ranger has a viewer of long time file related operations. If the server will manage all of the file operations it should be easy enough to mimic that feature right?

**Comment by gokcehan** [comment]
@doronbehar It sounds like an interesting idea to implement file operations in the server though it may require some effort to change it at this point. I think the easiest way forward would be to make `:delete` async for now and maybe create a separate issue for the server implementation to discuss the trade offs. We can display the progress of delete operation at the bottom for now similar to paste.

**Comment by JurisMajors** [comment]
@gokcehan I'd like to attempt doing this. 
Any chance you can guide me where exactly is the similar part for `:paste` ?
