### ISSUE TITLE
Cannot open files with  path containing complex  character(such as chinese word)  

### ISSUE THREAD

**Issue by linchangyi** [gokcehan/lf#216]
Cannot open Files with gedit while it performs normally with vim in the shell,   which the file's  path contains complex  character(such as chinese word) . 
Seems it was applying  wrong codec when opening files with gedit.
![2019-08-25_05-49](https://user-images.githubusercontent.com/6831676/63643167-48af8a00-c6fd-11e9-9640-65b19c37cb85.png)

ps: 
```
map O $mimeopen --ask $f
```
I used  configuration above  to open file with gedit

**Comment by gokcehan** [comment]
@linchangyi I can't copy that name from the image. Can you type the file name here?

**Comment by linchangyi** [comment]
> @linchangyi I can't copy that name from the image. Can you type the file name here?

You can try this "谢谢你ThankYou".

**Comment by gokcehan** [comment]
@linchangyi It seems like a strange issue, though I don't think this is related to lf. Same thing happens when you open the file from the terminal with `mimeopen --ask 谢谢你ThankYou`. If you open the file with `gedit 谢谢你ThankYou` then there is no problem. So this is likely an issue with `mimeopen`. Maybe you can use a mapping for gedit like `map e $gedit $f` as a workaround.

**Comment by linchangyi** [comment]
> @linchangyi It seems like a strange issue, though I don't think this is related to lf. Same thing happens when you open the file from the terminal with `mimeopen --ask 谢谢你ThankYou`. If you open the file with `gedit 谢谢你ThankYou` then there is no problem. So this is likely an issue with `mimeopen`. Maybe you can use a mapping for gedit like `map e $gedit $f` as a workaround.

Oh, I see,  turned out to be a problem of mimeopen.

**Comment by gokcehan** [comment]
@linchangyi I'm closing this issue. Feel free to reopen if there is something we can do about this.
