### ISSUE TITLE
Should we get rid of environment variables?

### ISSUE THREAD

**Issue by sach2** [gokcehan/lf#217]
lf config file can be used for setting up different mappings.
Environment variables are required for a bunch of settings like EDITOR.
I think it would be more portable if we just use one config file.

**Comment by gokcehan** [comment]
@sach2 Actually environmental variables are not mandatory. They are only used to guess the preferred application of the user. For example it is not uncommon for users to set `EDITOR` to their editor of choice which is used by many applications in the unix world. Though we have some non-standard variables like `OPENER`, it is not mandatory to use them. For example we provide the following keybindings by default:

    map e $$EDITOR $f
    map i $$PAGER $f
    map w $$SHELL

One can simply override these without using environmental variables as such:

    map e $emacs $f
    map i $most $f
    map w $zsh

The reason for using environmental variables by default is to avoid hard coding applications as much as possible. If a user has already set `EDITOR` variable, we want to borrow this value as the default in lf.

**Comment by sach2** [comment]
Hmm, it makes sense now 👍🏼.
map command can be used to use desired tool.

**Comment by sach2** [comment]
$f value is not getting translated into name of file, on windows.
when I tried following:
map e $notepad $f
it opens notepad prompting to edit $f.txt

**Comment by gokcehan** [comment]
@sach2 On windows, we use `cmd.exe` as the shell and it uses `%f%` to expand variables so I think you can try `map e $notepad %f%` though I don't remember if this handles whitespace properly or not.

**Comment by sach2** [comment]
%f% worked, on my work PC, $f works though.
