### ISSUE TITLE
Issue in example config file of lf 

### ISSUE THREAD

**Issue by sach2** [gokcehan/lf#218]
delete mapping doesn't work on windows.
Is this known issue?

**Comment by gokcehan** [comment]
@sach2 Example configuration assumes a unix shell. We currently don't have a windows equivalent. In the example configuration file, delete keybinding is commented out. Can you confirm you have the keybinding in your own configuration file? On my windows machine, I can successfully use this mapping:

    map <delete> delete

Note that in the example configuration file, there is a custom delete command is provided though as I said it assumes a unix shell so you should keep it commented out on windows. We already have a builtin `delete` command implemented that works on unix and windows so you don't need a custom implementation. Similarly other custom commands also works on a unix shell.

We have implemented `delete` command relatively recently and it seems that in our tutorial wiki page, we mention that you need to implement a `delete` command yourself. I have now removed this section from the tutorial. If you got confused there, that information is outdated.

**Comment by gokcehan** [comment]
@sach2 Closing this issue now. Feel free to leave further comments if you have.
