### ISSUE TITLE
lfcd.cmd doesn't continue after quitting lf

### ISSUE THREAD

**Issue by YongJieYongJie** [gokcehan/lf#219]
### Issue:
The [`lfcd.cmd`](https://github.com/gokcehan/lf/blob/master/etc/lfcd.cmd) file is supposed to create a temporary file for `lf` to save the last directory, in order for cmd to cd to that directory. However the script provided does not work as intended.

### Details:
I added the two `pause` statements so cmd will show `Press any key to continue . . . ` and wait for key press.  

```bat
@echo off
rem Change working dir in cmd.exe to last dir in lf on exit.
rem
rem You need to put this file to a folder in %PATH% variable.

:tmploop
set tmpfile="%tmp%\lf.%random%.tmp"
if exist "%tmpfile%" goto:tmploop
pause
lf -last-dir-path="%tmpfile%" %*
pause
if not exist "%tmpfile%" exit
set /p dir=<"%tmpfile%"
del /f "%tmpfile%"
if not exist "%dir%" exit
if "%dir%" == "%cd%" exit
cd "%dir%"
```  
  
Expected behavior:
- Script will prompt `Press any key to continue . . . ` twice, once before launching `lf`, and once just after `lf` exits.

Actual behavior:
- Script only prompts before launching `lf`, and not after `lf` exits.

**Comment by gokcehan** [comment]
@YongJieYongJie I don't understand what the issue is. Does the script not change the directory on exit? Why did you add `pause` statements for?

**Comment by YongJieYongJie** [comment]
@gokcehan, the script doesn't change directory for me, hence I added the `pause` statements to attempt to track execution in order to debug the script.

**Comment by YongJieYongJie** [comment]
@gokcehan (and whoever chance upon this in the future), I figured the issue out: I was launching `lf` itself from a batch file: i.e., the line `lf -last-dir-path="%tmpfile%" %*` in `lfcd.cmd` is actually running the `lf.bat` I have in my path. And when a batch file is launched from within a batch file (in this case, `lf.bat` is launched from this `lfcd.cmd`, the inner batch file will not return unless it is launched with `call <path_to_batch_file>`.
