### ISSUE TITLE
Support 24bit truecolor

### ISSUE THREAD

**Issue by Seirdy** [gokcehan/lf#223]
Currently, `lf` supports up to 256 colors, not including the terminal color scheme.
This limits the colors visible in the preview window, which is quite noticeable when
the preview window is used for file preview with syntax highlighting or image previews.
I'd specifically like to have 24bit colors in image previews using
[`chafa`](https://github.com/hpjansson/chafa) when using a terminal that doesn't
support graphics.

**Comment by TeddyDD** [comment]
I'm not sure but I think termbox-go does not support 24bit clolor so this might require porting lf to use https://github.com/gdamore/tcell

**Comment by gokcehan** [comment]
@Seirdy I thought we already had an issue for this but I guess not. @TeddyDD is right, termbox-go does not support more than 256 colors so we may need to move to tcell at some point. On a side note, I think 256 colors should be enough for syntax highlighting so I consider 24bit colors only as an enhancement for image previews.
