### ISSUE TITLE
Calling command with ! fails when shell is set to fish

### ISSUE THREAD

**Issue by hajdamak** [gokcehan/lf#224]
Only POSIX shells are supported?

Error:
```
-: Command substitutions not allowed
                                    from sourcing file -
                                                        	called on line 61 of file /nix/store/mrz55gplz08dvkcxxwm4bi41c6i0snn0-fish-3.0.2/share/fish/functions/eval.fish

                                                                  in function “eval”
                                                                                    	called on standard input

       source: Error while reading file “-”
                                           speed 38400 baud; line = 0;
                                                                      min = 1; time = 0;
                                                                                        -brkint -icrnl -imaxbel
      -opost
            -isig -icanon -echo
```

**Comment by gokcehan** [comment]
@hajdamak There are a few things in the code that requires a posix compatible shell. If you want to use a fish for a command, I think you should be able to wrap the command as such:

    cmd fish-example !{{
    export args="$*"
    fish << 'EOF'
        echo "this is running in fish"
        for i in (seq 5)
            echo $i
        end
        echo "f =" $f
        echo "fs =" $fs
        echo "fx =" $fx
        echo "argv =" $argv
        echo "args =" $args
    EOF
    }}

We should probably add this somewhere in the wiki pages.

**Comment by hajdamak** [comment]
Thanks for the tip.
Are there any plans to support non-POSIX in a more straightforward way or do you want to keep it simple with POSIX?

**Comment by gokcehan** [comment]
@hajdamak We only support POSIX shell because we had to hardcode a few things in the code. It would be nice to support non-POSIX shells as well but it is not very straightforward how to achieve this. So there are no immediate plans to do so. This was first discussed in #58 with more detail.
