### ISSUE TITLE
add on demand directory size calculation like on mc

### ISSUE THREAD

**Issue by nsklaus** [gokcehan/lf#225]
on mc there is the possibility to calculate a directory size by pressing 'ctrl+space'.
this only on demand and on selected dirs only.
i find it quite nice and if lf could implement it that would be good to have.
here's a  link to a video (3mb) to showcase the feature: [link](https://0x0.st/zyr1.mkv)
and screenshot:
![bleh2](https://user-images.githubusercontent.com/6810861/64806807-3904c200-d594-11e9-9cdf-21010b3639a4.png)
(update forget about the total count at the bottom, what's important is the calculate size, in size column, displayed inline)

**Comment by gokcehan** [comment]
As discussed in our chat channel, a workaround for this feature is to have a keybinding as such:

    map u %du -sh $f

This should show the size of the current directory at the bottom line.

**Comment by TeddyDD** [comment]
Another useful binding is `map u %du -shc $fx | tail -n1` that sums up size of all selected files/directories.

**Comment by nsklaus** [comment]
yes, this is workaround, but not as good as showing data inline in proper column.
because as soon as i type another command, or just move current selection the info is gone.
and it can only show one dir size calculation at a time.
the workaround while being nice, is nowhere near as useful as the complete feature.

**Comment by gokcehan** [comment]
This is now implemented in #750
