### ISSUE TITLE
Sort by file type?

### ISSUE THREAD

**Issue by wpcarro** [gokcehan/lf#228]
Hi. Is it currently possible to sort by file type? I haven't been able to find this setting.

I use a tool called `exa` which has a `--sort=type` option, which helps me understand the output much more quickly. It'll sort items in the following order:
- directories
- files
- symlinks

**Comment by gokcehan** [comment]
@wpcarro File types are sometimes not easy to determine. `lf` is not aware of file types. We could implement extension sorting for this purpose which should work in most cases.

Putting symlinks at the bottom seems like a different request. I remember originally we had symlinks showing up among other files but people wanted to see symlinks to directories among regular directories and we have changed it as such. So I think some people would object using such an order for symlinks.

**Comment by wpcarro** [comment]
@gokcehan I wasn't thinking about file types as in `file.el` is different from `file.txt`. I was thinking about a sort of directories on top, regular files next, followed by symlinks.

**Comment by gokcehan** [comment]
@wpcarro Ahh ok. I don't know why I considered them as separate. I guess maybe we can add an option to make symlinks show up at the bottom. Extension sorting is also something we should probably add at some point either but let's consider it in a different issue.

**Comment by wpcarro** [comment]
Great! My dotfile configuration involves a bunch of symlinks, which is why most of like file browsing commands sort them separately. It helps to parse the output.

**Comment by kmwenja** [comment]
@gokcehan I had so much fun doing the time sorting, I can jump on the extension sorting as well (around Sunday).

**Comment by kmwenja** [comment]
I got a little excited: https://github.com/gokcehan/lf/pull/230. It also doesn't hurt that it was an easy write.

**Comment by for-coursera** [comment]
Since `lf` already knows about `LS_COLORS`, may be use its groups as the file type criteria?

**Comment by mustafasegf** [comment]
I'm trying to search on how to set sort by ext, and #230 already solved this. I think we need to close this issue

**Comment by joelim-work** [comment]
I agree this can be closed. There is already `dirfirst` for placing directories first, and defining an order for file types isn't as straightforward as defining an order for extensions which can be alphabetically sorted.
