### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by davmaz** [gokcehan/lf#229]
Is there any way to add a key that would "undo" the last command? It may already be in lf and I just don't know about it. But every now and then I hit the key (by mistake) that takes me back to the root of the file system. Can this be undone easily?

In any case, I use 'lf' ALL the time. It is a fantastic tool!

**Comment by BrodieRobertson** [comment]
I hack fix would be to cache any files that you cut or delete and keep track of any files that you paste in a file and then write a handler function to deal with an undo.

**Comment by JurisMajors** [comment]
When moving around with bindings, you should be able to use marks to go to the last existing directory.

For example if i do `gd` (goes to my Downloads folder), then in my marks the previous folder i was at would show up. 
You can access marks by `'`

**Comment by gokcehan** [comment]
@davmaz Indeed you can jump to the previous folder using `'` mark as @JurisMajors mentions.

@BrodieRobertson Your suggestion is regarding undoing file operations, which is much more complicated. While I would like to see such a mechanism in `lf`, it is not straightforward to implement all corner cases. For example what should happen if there are errors in the copy and we also undo. Errors are currently not semantically interpreted by `lf` and only displayed to the user. Anyway, feel free to open an issue about it if you like. Closing this issue now.
