### ISSUE TITLE
Copy / Cut with arguments

### ISSUE THREAD

**Issue by MoerkerkeLander** [gokcehan/lf#231]
Hi,

I am creating an external script that takes path of a just downloaded file and sends it to LF. Now my question arises.. Is it possible with the builtin copy or cut commands to accept an argument, such as a filepath? This file should then be highlighted in LF.

When I try to copy with an argument, LF copies the file or folder of the selected item, not the specifc file enclosed in the argments.

My minimal code:

```sh
#!/bin/sh

FILE=$(readlink -f $1)
lf -remote "send $id copy '$FILE'"
```

Do I need to overwrite the original copy or cut command?

Thanks!

**Comment by gokcehan** [comment]
@MoerkerkeLander Command `copy` does not take arguments but you can first call `select` command on the file which should move the selection to the file and then call `copy` command without an argument to achieve what you want. I think an easier way would be to directly copy the filename in the server using the protocol. For example the following should copy `foo.txt` to the copy buffer:

    lf -remote "$(printf 'save\ncopy\nfoo.txt\n')"

You can change the filename to the name of the downloaded file in your case. Hope this helps.

**Comment by MoerkerkeLander** [comment]
It works! Thanks a lot.

```sh
#!/bin/sh

file="$1"

cmd=$(printf "save\ncopy\n$file\n")

lf -remote "$cmd"

notify-send "Copied to lf" "$file"

```
