### ISSUE TITLE
Feature Request: True Asynchronous xdg-open

### ISSUE THREAD

**Issue by alivefromupstairs** [gokcehan/lf#233]
I opened `mpv` or `zathura` expecting that if I shut down `lf` it wouldn't shut them as well; unlike `ranger`, it does. 

os: arch linux
lf -version: r13

**Comment by BrodieRobertson** [comment]
It's not a perfect solution but you could just use a custom open command and xdg-open as a background process:

```
cmd open ${{
    case $(file --mime-type "$f" -bL) in
        text/*|application/json) $EDITOR "$fx" &;;
        *) for f in "$fx"; do xdg-open "$f" & > /dev/null 2> /dev/null & done;;
    esac
}}
```

**Comment by alivefromupstairs** [comment]
@BrodieRobertson sorry for the later reply, but your implementation does not work. closing `lf` still closes opened apps.

**Comment by TeddyDD** [comment]
@alivefromupstairs try ` xdg-open "$f" & disown`

**Comment by alivefromupstairs** [comment]
@TeddyDD it works in a normal terminal emulator. but not inside `lf`.

**Comment by TeddyDD** [comment]
well `cmd open &xdg-open $fx & disown` works for me (lf from master branch, st terminal)

**Comment by alivefromupstairs** [comment]
@TeddyDD nope, still not working. but this worked and seem to use what I use:
```
cmd open ${{
    case $(file --mime-type $f -b) in
    	text/troff) man ./ $f;;
        text/*) $EDITOR $fx;;
	image/x-xcf|image/svg+xml) setsid gimp $f >/dev/null 2>&1 & ;;
	image/*) rotdir $f | setsid sxiv -ai >/dev/null 2>&1 & ;;
	audio/*) mpv --input-ipc-server=/tmp/mpvsoc$(date +%%s) $f ;;
	video/*) setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%%s) $f -quiet >/dev/null 2>&1 & ;;
	application/pdf) setsid zathura $fx >/dev/null 2>&1 & ;;
        *) for f in $fx; do setsid $OPENER $f >/dev/null 2>&1 & done;;
    esac
}}
```

**Comment by JurisMajors** [comment]
```
cmd open ${{
    case $(file --mime-type $f -b) in
        */json | inode/x-empty | text/*) $EDITOR $f;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```

@alivefromupstairs Indeed, using setsid is the best solution afaik.

**Comment by gokcehan** [comment]
This was first discussed in #148 though i have forgot to update the documentation. I have now added a mention to `setsid` in the documentation and added `setsid` to the example config file. Closing this issue now.

**Comment by pc00per** [comment]
@TeddyDD 
> well `cmd open & xdg-open $fx & disown works for me

I think defaulting to disown might not be the best solution. I've set `map <c-l> $xdg-open $f & disown` so that whichever I wanna open on it's own instance, I can do it explicitely.
