### ISSUE TITLE
Feature request: Add command to jump to prevoious/next dir

### ISSUE THREAD

**Issue by hajdamak** [gokcehan/lf#235]
When using fzf/skim to jump between dirs it would be handy to have shortcuts to jump to previous/next dir in history.

**Comment by JurisMajors** [comment]
when doing fzf, the directory you jumped from is saved in marks. 
I believe, by default, accessible through `'`

**Comment by gokcehan** [comment]
Is this not a duplicate of #212 ?

**Comment by hajdamak** [comment]
Yes, this exactly #212. Closing.
