### ISSUE TITLE
Moving files between disks results in "invalid cross-device link"

### ISSUE THREAD

**Issue by kmwenja** [gokcehan/lf#237]
Trying to move files between disks (cut and paste) results in "invalid cross-device link" in Linux (archlinux in this case). This seems to be due to `os.Rename` not being able to handle that as seen in this issue: https://github.com/jenkins-x/jx/issues/449

That project fixed it by swapping out `os.Rename` with their own implementation: https://github.com/rawlingsj/jx/commit/b8143bb9ab28ccbcac7607b55e30dd1025d9b8e2

**Comment by kmwenja** [comment]
In my case, this happened when trying to move files between my main disk and an external storage disk.

**Comment by shabahengam** [comment]
from https://godoc.org/github.com/gokcehan/lf 
"`Moving is performed using the rename operation of the underlying OS. This can fail to move files between different partitions when it needs to copy files. For these cases, users are expected to explicitly copy files and then delete the old ones manually.`"
you can use 'paste' command in [this page](https://godoc.org/github.com/gokcehan/lf) (in `File Operations` section)but it does not support progress bar.

**Comment by kmwenja** [comment]
My bad. I didn't see that. Thanks for the link. I can probably get by with that.

That being said, considering we have the option to work around the `os.Rename` issue, shouldn't `lf` at least have a native "move file" that works as expected (and on all platforms)?

**Comment by JurisMajors** [comment]
Interestingly, I am also on archlinux and have my media files on a seprate hard-drive, however, I have never had such issues (I am interested in reproducing it though). If this issue occurs often I would agree that fixing it would be much nicer than having to do things manually.

**Comment by gokcehan** [comment]
@kmwenja I'm not quite satisfied with our current situation either. I agree file managers should be able to handle this case properly. Documentation is only there to give users an idea about how to overcome this situation.

In the link you sent, I think they are simply doing a copy ignoring a potential rename operation altogether. This is not ideal as copy is usually a much heavier and more error prone operation then rename. I don't think it is a good idea to use this strategy in lf.

By the way, this is a duplicate for #151 so closing this issue in favor of the other one.
