### ISSUE TITLE
Panic when starting up lf in directory with single directory symlink.

### ISSUE THREAD

**Issue by occivink** [gokcehan/lf#24]
Hope the title is not confusing.

More precisely, given a directory structure like so:
```
$ pwd 
/home/occivink/tmp
$ tree
.
├── bar/
└── foo/
    └── bar -> /home/occivink/tmp/bar/

3 directories, 0 files
```
Trying to start lf lf in the directory `foo` will cause a panic on startup

**Comment by gokcehan** [comment]
@occivink Closing this issue as discussed in #25.
