### ISSUE TITLE
Jump to specific line

### ISSUE THREAD

**Issue by yangmillstheory** [gokcehan/lf#240]
`set number` displays absolute line numbers in the UI, but when I try to jump to a specific line using e.g. `20G` to jump to the 20th line (as one would in Vim), I'm taken to the last file, per the mapping 

```
bottom                   (default 'G' and '<end>')
```

This feature request is to support jumping to lines in the manner that Vim does. If you agree this should be supported, I'm happy to work on it.

**Comment by JurisMajors** [comment]
I'd like this feature to be there. Hopefully gokcehan agrees.

**Comment by gokcehan** [comment]
@yangmillstheory This sounds like a good idea. Feel free to work on this and ask me any questions if you get stuck at something.

**Comment by yangmillstheory** [comment]
OK - I can take a shot at this. Can you assign this to me for tracking purposes?

**Comment by gokcehan** [comment]
@yangmillstheory Sorry for late reply. I have been having trouble finding time with issues lately. I have now assigned the issue to you if you're still interested.
