### ISSUE TITLE
Can't turn off preview

### ISSUE THREAD

**Issue by valdoonicanlives** [gokcehan/lf#244]
lf r13 but same problem with r12
tried setting no preview in the lfrc file, but I still get previews
set preview false

**Comment by shabahengam** [comment]
use `set nopreview`

**Comment by valdoonicanlives** [comment]
Thanks, it works! In the onine documetation is said it was a booleen value, ie true or false

**Comment by shabahengam** [comment]
yes, documentation is wrong and needs to get fixed.
