### ISSUE TITLE
change directory to lf directory on quit

### ISSUE THREAD

**Issue by JakeHuneau** [gokcehan/lf#245]
Hello,

I'd like to be able to change my directory on my command line to the directory I am in in lf when I quit it. For example, if my working directory is `~/Documents` and I navigate to `~/Documents/path/to/somewhere/else` and then enter some command on lf, then I'd like my new working directory to be `~/Documents/path/to/somewhere/else`. I tried to do this with a command in lfrc like

`cmd cd_here $cd $(dirname $f)`
`map Q cd_here`

but that wouldn't change my working directory.

Is there a way to do this?

**Comment by shabahengam** [comment]
read `Working Directory` section in [tutorial](https://github.com/gokcehan/lf/wiki/Tutorial) and use lfcd from [etc folder](https://github.com/gokcehan/lf/tree/master/etc)

**Comment by JakeHuneau** [comment]
Thank you, that worked!

**Comment by swithun-liu** [comment]
> read `Working Directory` section in [tutorial](https://github.com/gokcehan/lf/wiki/Tutorial) and use lfcd from [etc folder](https://github.com/gokcehan/lf/tree/master/etc)

so how to do this with powershell

**Comment by shabahengam** [comment]
@swithun-liu 
I'm not using windows but I think [this file](https://github.com/gokcehan/lf/blob/master/etc/lfcd.ps1) is for powershell.read the comment section of that file for more info

**Comment by h11v** [comment]
lf, has an input flag **-print-last-dir**. I solved that problem by creating a bash alias

<code>alias llf='cd $(lf -print-last-dir)' </code>
