### ISSUE TITLE
Man-pages Integration

### ISSUE THREAD

**Issue by RuijieYu** [gokcehan/lf#247]
Hello, I just installed `lf` today, and was a bit surprised to not see it show up in under `man` in Linux. Since the documentation output is fairly large (using `lf -doc`), can we get it integrated into `man` so that displaying it is handled by said program?

**Comment by TeddyDD** [comment]
lf has a [manpage](https://github.com/gokcehan/lf/blob/master/lf.1), if you install lf manually you can copy it to appropriate directory. 

Maybe it should be included with release tarballs?

**Comment by RuijieYu** [comment]
Thank you for linking the file. I guess I didn't read that close enough and the AUR maintainer happened to miss that as well. I think I should close this issue.

**Comment by gokcehan** [comment]
@TeddyDD It seems that there is now an extra package for this purpose named [lf-extras](https://aur.archlinux.org/packages/lf-extras/) though I think it would be better to have everything in a single package so maybe it is a good idea to include these in tarballs. Reopening the issue in the meanwhile.

**Comment by RuijieYu** [comment]
In the meantime, I added a comment in the AUR on my approach to manually add in the man page (adding to `package()` function). https://aur.archlinux.org/packages/lf/ see comment from user “ruy16109”.

**Comment by kingliamb** [comment]
I just installed lf today and noticed that
`man lf`
returns
`No manual entry for lf
See 'man 7 undocumented' for help when manual pages are not available.`
Is there installation instructions on how to install a manpage? Thank you :)

**Comment by gokcehan** [comment]
@kingliamb You should be able to copy `lf.1` file in this repository to somewhere in your man path. I have put mine to `~/.local/share/man/man1/lf.1`. You can run `manpath` command to see your current man path. See `man manpath` for more information about setting your man path.
