### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by LORDTEK** [gokcehan/lf#248]
`go get -u github.com/gokcehan/lf` executed with no error but nothing happend.
PKGBUILD does not work as root.

I know that nothing will be done but I want to notice.

**Comment by gokcehan** [comment]
@LORDTEK `go get` command should have installed `lf` in a proper location (e.g. `$HOME/go/bin`). Check if you have this location in your `$PATH` variable.

Can you elaborate about the PKGBUILD issue?

**Comment by LORDTEK** [comment]
you are right
