### ISSUE TITLE
:push fails when given non English characters

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#250]
This might be a termbox issue, yet this is as far as I could go when trying to isolate it:

If I run `:push :rename<space>א` I get an error:

```
unknown key: א
```

With English letters instead of `א`, I don't get such error. It seems as if non English letters are interpreted as escape sequences?

**Comment by gokcehan** [comment]
@doronbehar This should now work as intended. Feel free to report here if the issue persists.

**Comment by doronbehar** [comment]
Confirmed this is fixed. Thanks!
