### ISSUE TITLE
certificate problem

### ISSUE THREAD

**Issue by LORDTEK** [gokcehan/lf#251]
on NetBSD I saw certificate problem on also curl and git. They have "ignore certificate" command. But here it is go. Any solution? Ignore certificate is also welcome.

```
$ /usr/pkg/go112/bin/go get -u github.com/gokcehan/lf
package gopkg.in/djherbis/times.v1: unrecognized import path "gopkg.in/djherbis/times.v1" (https fetch: Get https://gopkg.in/djherbis/times.v1?go-get=1: x509: certificate signed by unknown authority)
```

**Comment by gokcehan** [comment]
@LORDTEK It seems like an annoying problem but I think it has little to do with `lf`. Can you clone the repository with `git` as such:

    git clone https://gopkg.in/djherbis/times.v1

If not, then can you somehow try to update your certificates in your system?

**Comment by gokcehan** [comment]
Closing this issue. Feel free to leave further comments.
