### ISSUE TITLE
zsh automatic configuration

### ISSUE THREAD

**Issue by JurisMajors** [gokcehan/lf#252]
Related to #239 PR

So, I finally got a response from the zsh-completions maintainer and this is what he said.

![image](https://user-images.githubusercontent.com/32071671/67793287-d2236580-fa7a-11e9-94b9-8e36615eee7b.png)

This should make zsh completion installation automatic.

**Comment by gokcehan** [comment]
@JurisMajors Well, we don't have many packages as far as I know but we can add this information as an instruction to the comments I guess.

**Comment by doronbehar** [comment]
@JurisMajors I think you can add something to https://github.com/gokcehan/lf/wiki/Packages#packaging-guideline regarding completion.
