### ISSUE TITLE
Some indicator showing if the current pane with lf is active?

### ISSUE THREAD

**Issue by for-coursera** [gokcehan/lf#254]
For example, how one can tell, which `lf` pane is active in such case? :)

![](https://i.imgur.com/ggX7cNk.png)

Some indicator (terminal's cursor?) appearing in an active (selected) `lf` would be great, don't you think?

**Comment by gokcehan** [comment]
@for-coursera If you're in command line mode, you should see a cursor in the bottom line. In normal mode, we hide the cursor. It can be useful to show the cursor at all times for this case, but it can also be annoying at other times for some users. Maybe we can add an option to control whether the cursor should be shown or not. You can also configure your tmux to show the active panel with a better color.

**Comment by for-coursera** [comment]
@gokcehan , An option would be great :)

Thanks.

(I know about tmux's `pane-border-style` but that's not enough really :))

**Comment by joelim-work** [comment]
This can be achieved with the `cursoractivefmt` option, so I think this is no longer an issue.
