### ISSUE TITLE
Passing selected files from one instance to another?

### ISSUE THREAD

**Issue by for-coursera** [gokcehan/lf#256]
Is it possible to pass selected files from one `lf` instance to another?

Like, I have the following function in my `lfrc` to create symbolic links:

    cmd slink %{{
        linkpath=$(pwd)
        for i in $fx
        do
            filename=$(basename "$i")
            ln -s "$i" "$linkpath"/"$filename"
        done
        lf -remote "send $id unselect"
    }}

But obviously it only works within the current `lf` instance. Now, imagine two `lf`s running side by side. Wouldn't it be great to be able to select files in one instance, and to create links in another? Just like in `mc` :)) 

And for that, we need to pass the selection somehow...

**Comment by nostdm** [comment]
I know that you can already copy/paste selected files between `lf` instances since multiple `lf` instances share some state. That said, I don't know if they also share the selection variables like `$fx` you'd have to test it.
