### ISSUE TITLE
delete file not working

### ISSUE THREAD

**Issue by Monirzadeh** [gokcehan/lf#263]
hi
hi use this command in my config but when i try to delete a file or folder get this error
`delete: dialing to save files: dial unix /tmp/lf.me.sock: connect: connection refused `

```
cmd delete ${{
    set -f
    printf "$fx\n"                                        
    printf "delete?[y/n]"
    read ans
    [ $ans = "y" ] && rm -rf $fx
}}
map dd delete
```

**Comment by shabahengam** [comment]
run this command and try again 
`pkill lf; rm /tmp/lf.${USER}*`

note: `map d` is for cutting files and you can not use `map dd` without deleting existing binding
so you  should use something like this in your lfrc
`map d`
`map dd cut`
`map dD delete`

**Comment by Monirzadeh** [comment]
i test that and change my config to
```
cmd delete ${{
    set -f
    printf "$fx\n"                                        
    printf "delete?[y/n]"
    read ans
    [ $ans = "y" ] && rm -rf $fx
}}
map d
map dd cut
map dD delete
```
but when i try dD don't ask for any things
only a red block show beside file name and noting happen
if you press enter get this masseage
`command not found: shell   `

**Comment by shabahengam** [comment]
are you using the latest version? because
`Commands yank, delete, and put are renamed to copy, cut, and paste respectively`

if you using the latest version when you press `d` you should see something like this
![image](https://user-images.githubusercontent.com/53096747/69903379-87647880-13ad-11ea-82e2-3f045ad1f02c.png)
now if you press `D` you can delete the file and if you press `d` you can cut the file

**Comment by Monirzadeh** [comment]
i use the last version of lf for sure i install that again with this command
i use kubuntu with bspwm
`curl -L https://github.com/gokcehan/lf/releases/download/r1/lf-linux-amd64.tar.gz | sudo tar xzC /usr/local/bin
`
i see that. it is my screenshot
press d
![Screanshot-2019-11-30-21-43-17-223181106](https://user-images.githubusercontent.com/25131576/69904333-ba613900-13ba-11ea-80a4-daf32010cfe8.png)
than press D
![Screanshot-2019-11-30-21-43-22-387477841](https://user-images.githubusercontent.com/25131576/69904336-be8d5680-13ba-11ea-8dee-307b9c7d981d.png)

**Comment by shabahengam** [comment]
no you are not using the latest version.you are using `r1` and it is so old
the latest version is `r13`.check the release page 
https://github.com/gokcehan/lf/releases
you can check your version with `lf -version`

**Comment by Monirzadeh** [comment]
> no you are not using the latest version.you are using `r1` and it is so old
> the latest version is `r13`.check the release page
> https://github.com/gokcehan/lf/releases
> you can check your version with `lf -version`

thanks problem solved
i install that with command in wiki ( i will update that )
only one things when i try delete ask delete in a clear console (lf not show) not in bellow of the screen
can solve that?
![Screanshot-2019-11-30-22-20-20-726507355](https://user-images.githubusercontent.com/25131576/69904776-e92dde00-13bf-11ea-85e1-61617297cd1c.png)

**Comment by shabahengam** [comment]
this is normal.custom delete command pass the file/files names to the `rm` command.
like when you use `rm file.txt` and `rm` ask you are you sure.
remember you defined a custom delete command and not using the internal delete command
if you remove custom delete command from your lfrc, lf will use internal delete command

**Comment by Monirzadeh** [comment]
> if you remove custom delete command from your lfrc
is there any different or advantage?

**Comment by shabahengam** [comment]
custom delete command needs a unix shell
internal delete command works on every platform like Windows, MacOSX, Linux (as i know)

**Comment by gokcehan** [comment]
@Monirzadeh I will change the command in the wiki in such a way to avoid copy pasting blindly to avoid this issue.

@shabahengam Thanks for helping with this.
