### ISSUE TITLE
wrong icon in mount folder

### ISSUE THREAD

**Issue by Monirzadeh** [gokcehan/lf#265]
hi
i try to active custom icon in lf base on wiki for some reason i add that to `.zlogin` instead of `.zshrc`
i add something similar bellow code to my `.zlogin`
font is  [Nerd SourceCodePro](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro#:~:targetText=Source%20Code%20Pro%20is%20a,being%20made%20by%20Kim%20Silkeb%C3%A6kken.)
```
export LF_ICONS="\
di=:\
fi=:\
ln=:\
or=:\
ex=:\
*.7z=:\
*.a=:\
*.mkv=:\
"
```
every thing work fine but when i go to a drive that mount in `/media/` icons not show correct
for folder show 
```
ln=:\
```
and for files
```
ex=:\
```
there is some screenshots
a folder contain mkv file in `/home/username/`
![Screanshot-2019-12-02-20-33-42-282420772](https://user-images.githubusercontent.com/25131576/69980018-a0ebf880-1544-11ea-8060-896c3f0a8298.png)
a folder contain mkv file in one of the mounted disk partition into `/media`
![Screanshot-2019-12-02-20-31-33-289693941](https://user-images.githubusercontent.com/25131576/69980457-81a19b00-1545-11ea-9f2d-e615c6d187af.png)

**Comment by shabahengam** [comment]
how you mount the partition? i mean which options do you use for mount?
is that an ntfs partition?

**Comment by Monirzadeh** [comment]
> n ntfs p

i have two partition
in this screanshot is a ntfs partition 
other is a smb server that mount by cifs in `/media/ with 
both of them mount at boot with fstab

**Comment by shabahengam** [comment]
use this options and test again
`mount -o uid=[your uid],gid=[your gid],fmask=117,dmask=007 /dev/[your partition] /media`
ps:
1.to check your uid and gid: `echo $UID` and `echo $GID`
2.dmask and fmask cannot be used for CIFS and you should use dir_mode and file_mode

**Comment by Monirzadeh** [comment]
i test below command for mount local partition and that work fine (files and folders icon fixed) 
but how should i set this command into `etc/fstab`
```
mount -o uid=[my uid],gid=[my gid],fmask=117,dmask=007 /dev/[your partition] /media
```
________________
for samba first i use this command 
```
mount -o uid=[my uid],gid=[my uid],credentials=[path to credentials file],vers=3.0,file_mode=117,dir_mode=007,iocharset=utf8 //sambaserverIP /media

```
and i get this error
```
WARNING: 'file_mode' not expressed in octal.
```
so i change that into this (remove `file_mode=117`)
```
mount -o uid=[my uid],gid=[my uid],credentials=[path to credentials file],vers=3.0,iocharset=utf8,dir_mode=007 //sambaserverIP /media/
```
samba server mount and directory icon fixed but files icon not fix

**Comment by shabahengam** [comment]
change `file_mode=117` to `file_mode=0117`
and you can change `dir_mode=007` to `dir_mode=0007`

**Comment by Monirzadeh** [comment]
mount but when i go to `/media' get me `permission denied`

**Comment by shabahengam** [comment]
ok,this if off topic now and i think we should close this issue cause it's not relate to lf anymore
and i don't know anymore about cifs.sorry

**Comment by Monirzadeh** [comment]
> ok,this if off topic now and i think we should close this issue cause it's not relate to lf anymore
> and i don't know anymore about cifs.sorry

i am not sure about that
i do more test
the problem is lf prioritize permission (others) of files  or directory instead of type of them to show icons.
if a file has `x` permission (execute) for other user  show `ex=:\` and ignore type of file for showing icons.
so a file with `-rw-rw-r-x` show ` ex=:\` only because of last `x` 
for directory lf ignore directory icon and show `ln=:\` only because of `w` permission  (write) of other user.
so a directory with `drwxrwxrwx` show `ln=:\` only because of last `w` 

for reproduce this problem you can do this
````
mkdir testDir
touch testFile.mkv

# for now icons show correctly, check permission of directory (drwxrwxr-x) and file(-rw-rw-r--)
ls -l
# change permission of directory to drwxrwxrwx and folder icon change 
chmod o+w testDir
 # change permission of file to -rw-rw-r-x and file icon change and ignore mkv
chmod o+x testFile.mkv

# change permission to default and icons fix
chmod o-w testDir
chmod o-x testFile.mkv
````

expected behavior
if it is file, lf don't ignore file format to show icon (currently show base permission)
if it is directory lf  dont set icon base on permission (currently show base permission)
by the way lf always show the permission below the window so it is necessary show in icon

**Comment by Monirzadeh** [comment]
for now if i mount with `file_mode=0664,dir_mode=0755` folder and file same permission as usual file icon fixed
but the problem still is there.
for example dolphin mount partition in 'file_mode=0777,,dir_mode=0777' and you can't change that
bedside i can't mount normal partition with this permission in fstab

**Comment by gokcehan** [comment]
There has been changes in the color and icon configuration mechanism. It's not easy for me to test the specific case described in this issue. But many things that were not possible before are now possible so it is likely to work for this case as well. If not, then it is likely to be considered expected behavior at this point. Closing this issue. Feel free to reopen if necessary.
