### ISSUE TITLE
scan.go: scan() shall support adjacent quoting

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#267]
Currently it's impossible to write e.g. `:select 'my'""'file'` (not even `:select 'my''file'`) to select the file `myfile`. This is needed for safe handling of files containing either control characters (see `scan.go: scan(): case s.chr == '"': ...` for the full list of them) or `'` or both in their names.

I stumbled upon this when writing a safe lf command like this:

```
# won't work for files with ' in their name
cmd c1 &{{ lf -remote "send $id select '$f'" }}
```

**Comment by gokcehan** [comment]
@dumblob Quotes in `lf` are implemented differently than shell. You can use `'` by quoting it in between `"` and control characters by escaping them with octal escapes between double quotes.

**Comment by dumblob** [comment]
Yeah, I saw the implementation, but I'm unable to find a way for the described issue. It also doesn't sound right to me to list all special cases (e.g. escape all control characters `lf` understands) by doing something like

```sh
cmd c1 &{{ lf -remote 'send '"$id"' select "'"$(sed -Ez -e 's|('"'"')|"\1"|g' -e 's|(\\)|"134"|g' -e '...for_each_ctrl_char' <<END
$f
END
)"'"' }}
```
(not even sure the code above will work)

as that's really not nice and in addition it's fragile (e.g. if `lf` will change it's behavior in this regards even slightly, there'll be a bug in the sed regex).

**Comment by gokcehan** [comment]
@dumblob How does concatenating strings solve the example you provided?

**Comment by dumblob** [comment]
One can easily guarantee (in a forward compatible manner) no control character nor any quote will get interpreted by something like:
```sh
cmd c1 &{{ lf -remote "send $id select '$( sed -Ez -e "s|'|'\"'\"'|g" <<END
$f
END
printf "'"  # this is to overcome subshell removing all trailing newlines (in case filename has trailing newline(s)
)" }}
```
I.e. filename `abc' def` will be transformed into`'abc'"'"' def'`.

**Comment by gokcehan** [comment]
@dumblob I still don't understand. You only escaped `'` and did not do anything about control characters. If you want to escape `'`, you can already escape it within `"` with the current implementation.

**Comment by dumblob** [comment]
>You only escaped ' and did not do anything about control characters.

The point is, that if one is inside of `''` block, there are no control characters at all. So one needs to escape only the `'` character itself. Or am I missing something?

**Comment by gokcehan** [comment]
@dumblob What about the control characters then?

**Comment by dumblob** [comment]
Inside of anything enclosed in single apostrophes (`'`), there are **no control characters**. That's how I read:
https://github.com/gokcehan/lf/blob/3c5abbbc5dafa2eff0593a8e27aadb3f325d2d43/scan.go#L260-L268

**Comment by gokcehan** [comment]
@dumblob Weren't you trying to handle control characters in filenames? That is what you told in the beginning of the issue. If that's the case, why are you trying this with single quotes rather than double quotes?

**Comment by dumblob** [comment]
I meant control characters `lf` recognizes, but not control characters the terminal (emulator) or whatever else recognizes.

**Comment by dumblob** [comment]
Is there any better way than exhaustively list all **currently** implemented *lf control characters* as [outlined above](https://github.com/gokcehan/lf/issues/267#issuecomment-566955001 )?

Shouldn't this issue stay open (at least until any better solution will be found/implemented)?
