### ISSUE TITLE
will be mouse-support added at some point?

### ISSUE THREAD

**Issue by astier** [gokcehan/lf#268]
Hi. I just wanted to ask if mouse-support is something that you are going to implement sometime in the future or if this is just hypothetical but you don't have any plans on doing it right now?

**Comment by gokcehan** [comment]
@astier It's more like the latter. Someone asked me about mouse support on irc and I have added that to the list. I have trouble sparing time for adding features to lf and I don't have any plans of working on mouse support at the moment. There does not seem much interest from others to work on this either. So I would not count on it being implemented soon.

I don't think we have a dedicated issue for mouse support so I will keep this open.

**Comment by yassinebridi** [comment]
This is the only thing keeping me from using lf over ranger, i hope for this to be implemented at some point.

**Comment by gokcehan** [comment]
I have now added basic mouse buttons/wheel support to clear this off our readme. You may update to master to try this. See the "Key Mappings" section in the documentation for information about buttons/wheel names for bindings. Current support should allow basic use to bind mouse wheel to `up/down` commands to scroll through the file list and bind buttons to `open/updir` commands to navigate directories. More complicated events (i.e. click positions, double/triple clicks, modifiers) are not implemented. If anyone intends to work on implementing such events, feel free to open a new issue for discussion, though I think they may not be easy to implement.
