### ISSUE TITLE
Verify correct lfrc is used

### ISSUE THREAD

**Issue by jeroenbourgois** [gokcehan/lf#270]
I have my `lfrc` as a plain text file at `~/.config/lf/lfrc`, but whatever I put in there it does not seem to affect `lf`. Using osx.

Platform:
osx

Version:
latest

Tried setting the `XDG_CONFIG_HOME` var explicitly to `~/.config` but this does not help. Can I turn on some logging or verbose mode? Tnx!

**Comment by gokcehan** [comment]
@jeroenbourgois Can you check your log file after launching to see if there is some useful information regarding this? You can find more information about the log file in contributing wiki page.

**Comment by jeroenbourgois** [comment]
@gokcehan sorry, no log to be found, anywhere... I then got the source code and tried putting some `log.Print` statements around, but everything after the `termbox.Info()` call seems to get swallowed, I cannot seem to get that info. The `gConfigPaths` var seems to be correct, but I wanted to try and debug what it actuallly reads out.

**Comment by jeroenbourgois** [comment]
@gokcehan ok nevermind, it _was_ working. But, the `scrolloff` setting does not seem to do anything, and I was judging if it works based on that.
