### ISSUE TITLE
unknown option :  editor on windows 10

### ISSUE THREAD

**Issue by Zaplanincan** [gokcehan/lf#271]
Hi,
I'm trying to set vim as default editor, but when I use:
set editor vim
in lfrc I get error: unknown option editor when starting lf.

**Comment by alivefromupstairs** [comment]
To set `vim` as your editor in `lf` and be able to edit files in it when you press `e`, you need to set `$EDITOR` to `vim` in your shell config file (`~/.bashrc` for `bash`, `~/.zshrc` for `zsh`) for it to be permanent. you can try in a single session this:
```
$ export EDITOR="vim"
```

If you want to open files in `vim` when right clicking a file or pressing `l`, you need to have `xdg-open` open those types of files with vim. You can change the `open` command in `lf` to open text files with `vim`:
```
cmd open ${{
    case $(file --mime-type "$f" -bL) in
        text/*|application/json) $EDITOR "$fx";;
        *) for f in "$fx"; do xdg-open "$f"> /dev/null 2> /dev/null & done;;
    esac
}}
```

The way I do it is by using [mimi](https://github.com/march-linux/mimi) (replaces `xdg-open`), which allows me to define how to open files with a config file `~/.config/mimi/mime.conf`:
```
inode/directory: $TERM -e lf
text/: $TERM -e nvim
```
change `$TERM` to your terminal or define it in your shell config `export TERM="st"`

**Comment by Zaplanincan** [comment]
Hi, sorry I was not precise enough, I have no problem with lf on wsl, but trying to change default editor from notepad to vim on windows install.
Thanks for the help.

**Comment by alivefromupstairs** [comment]
What's your shell?
I have 0 experience with Windows, but `lf`'s manual (`$ lf -doc`) reads:
```
 The following default values are set to the environmental variables on unix when they are not set or empty:

           $OPENER  open      # macos
           $OPENER  xdg-open  # others
           $EDITOR  vi
           $PAGER   less
           $SHELL   sh

The following default values are set to the environmental variables on windows when they are not set or empty:

           %OPENER%  start
           %EDITOR%  notepad
           %PAGER%   more
           %SHELL%   cmd

```
so, on Linux, a simple `export EDITOR="vim"` before you open `lf` (however you wanna do that) is enough. This process's counterpart on Windows, based on a quick google search, seem to be more graphical [[source](https://appuals.com/how-to-edit-environment-variables-in-windows-10/)]:

![image](https://user-images.githubusercontent.com/46059092/71017157-78dcc780-20f6-11ea-8acf-c5ae6b4b65d8.png)

Perhaps, change the EDITOR (or, add) env var. Hope this helps.

**Comment by Himujjal** [comment]
I have the same question. I changed the default env variable in windows for EDITOR to `nvim-qt` but when I press `e` which is the default mapping for opening the same, the whole ___lf___ editor get's stuck. Only when I close nvim-qt window, the lf finally starts working.

Is there a way to get the editor start working? Probably open EDITOR in an async manner

**Comment by gokcehan** [comment]
@Himujjal Does this work for you?

    map e &nvim-qt %f%

**Comment by Himujjal** [comment]
perfect. thanks!

**Comment by davmaz** [comment]
Does anyone have a basic WindoZe 10 lfrc?
