### ISSUE TITLE
UI Nitpicking: Unnecessary Padding 

### ISSUE THREAD

**Issue by alivefromupstairs** [gokcehan/lf#273]
Columns have a bit of padding to their left that could be otherwise utilized. centering the preview pane would also be nice.
 
![cut](https://user-images.githubusercontent.com/46059092/70886687-5f475d00-1fdc-11ea-96fd-3d7c3208bf23.gif)

**Comment by gokcehan** [comment]
@alivefromupstairs That space is used for marks and which is not obvious in your example. Left pad in preview pane is to mimic the directory view padding so you see them aligned when switching between a file and directory.

**Comment by alivefromupstairs** [comment]
Fair enough.
