### ISSUE TITLE
Copy/Move Sucess to Massage Line

### ISSUE THREAD

**Issue by smhmd** [gokcehan/lf#276]
Display a message of success on successful copy/move (in green). Sometimes, I don't know what `lf` was doing being open after a long copy operation; there is just no way to tell. This may be possible to change locally, but I don't like to change core commands if possible.

**Comment by YerinAlexey** [comment]
This is how I think it should look (buggy, but works):
[![asciicast](https://asciinema.org/a/0FfkujKd4sF8QAn82XMZVdcVv.svg)](https://asciinema.org/a/0FfkujKd4sF8QAn82XMZVdcVv)
