### ISSUE TITLE
Making prompt line optional?

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#278]
I find that the prompt on the top is kind of useless, and even if I set it to "",
there still will be a blank line where the prompt would be.

**Comment by gokcehan** [comment]
@lucas-mior How else can you see the current directory?

**Comment by alivefromupstairs** [comment]
@gokcehan `%pwd` or togglable.

**Comment by lucas-mior** [comment]
In #262 I explain how I do it.

**Comment by lucas-mior** [comment]
I've just noticed that the prompt is actually useful when the filename is so large that it can't be fully displayed in the column. I'll close the issue now.
