### ISSUE TITLE
Rename To Preserve Extension

### ISSUE THREAD

**Issue by smhmd** [gokcehan/lf#279]
`rename: README.md│` should instead be `rename: README│.md` as keeping the extension is a more common use case.

The recommended way in the [wiki](https://github.com/gokcehan/lf/wiki/Tips#rename-commands-similar-to-those-of-ranger) removes the extension (and leaves the dot) and forces you to have multiple keybindings for files, files without extensions and directories.

**Comment by lucas-mior** [comment]
very ugly solution (map it to A or whatever you like)

`
cmd renameappend ${{
	filename="${f%.*}"
	nome="$(basename "$filename")"
lf -remote "send $id :rename; cmd-home"
	vezes="$(echo $nome | wc -m)"
	n=1
	while [[ $n -lt $vezes ]]
	do
lf -remote "send $id cmd-right"
		n=$((n+1))
	done
}}
`

**Comment by roket1428** [comment]
My solution:
```
cmd rename-before-ext &{{
	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
		lf -remote "send $id echo You can't change more than one file name"
		lf -remote "send $id unselect"
	else
		if [ -d "$f" ]; then
			lf -remote "send $id rename"
		else
			ext_len="$(echo ${f##*.} | wc -m)"
			for i in $(seq "$ext_len"); do
				pos="${pos}<left>"
			done
			lf -remote "send $id rename"
			lf -remote "send $id push "$pos""
		fi
	fi
}}
```

**Comment by Limero** [comment]
I agree that keeping the extension is the most common when renaming. Should we make this the default behavior? Should there be an option to toggle it? Would be nice to not have to use custom commands.

**Comment by alivefromupstairs** [comment]
@Limero I think it should be the default. If you wanna change the entire name you would `ctrl+u`.

**Comment by roket1428** [comment]
> I agree that keeping the extension is the most common when renaming. Should we make this the default behavior? Should there be an option to toggle it? Would be nice to not have to use custom commands.

I think there gotta be at least 4 default naming function: One for renaming it entirely (like just let me change its name to this new value), one for appending (at the very end of the file/directory), one for inserting (at the very beginning of the file/directory), one for appending before the extension of the file (default behavior for directories should be same as appending IMHO).

Here is my lfrc for those (yes, I use hard tabs and I don't care what you think):
```
# insert
cmd rename-insert &{{
	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
		lf -remote "send $id echo You can't change more than one file name"
		lf -remote "send $id unselect"
	else
		len="$(basename "$f" | wc -m)" # length of selected file/directory
		for i in $(seq "$len"); do
			pos="${pos}<left>" # how many times do I have to press <left> in order to get first char
		done
		lf -remote "send $id rename"
		lf -remote "send $id push $pos"
	fi
}}

# append before ext
cmd rename-before-ext &{{
	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
		lf -remote "send $id echo You can't change more than one file name"
		lf -remote "send $id unselect"
	else
		if [ -d "$f" ]; then
			lf -remote "send $id rename"
		else
			ext_len="$(echo ${f##*.} | wc -m)" # extention length
			for i in $(seq "$ext_len"); do
				pos="${pos}<left>"
			done
			lf -remote "send $id rename"
			lf -remote "send $id push "$pos""
		fi
	fi
}}

# change its name entirely
cmd rename-new &{{
	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
		lf -remote "send $id echo You can't change more than one file name"
		lf -remote "send $id unselect"
	else
		lf -remote "send $id rename"
		lf -remote "send $id push <c-u>"
	fi
}}

map cc rename-new # new name
map I rename-insert # at the very begging
map A rename # at the very end
map aa rename-before-ext # right before the extention
```

**Comment by gokcehan** [comment]
Thank you all for the feedback. For the record, this is why I try not to include commands as builtin because everyone has some slightly different favorite and expects it to be the default. The current default seems to be the simpler one rather than the common one. You should be able to define other versions of rename commands using either `push` command:

    map R push r<a-b><c-b>

Or by using command line commands:

    map R :rename; cmd-word-back; cmd-left

Examples in the wiki page dates back to times we did not have a builtin rename command. Perhaps it is time to remove those examples in favor of these.

**Comment by alivefromupstairs** [comment]
I really think sane, great defaults are better than having two commands for renaming.

**Comment by roket1428** [comment]
> > I agree that keeping the extension is the most common when renaming. Should we make this the default behavior? Should there be an option to toggle it? Would be nice to not have to use custom commands.
> 
> I think there gotta be at least 4 default naming function: One for renaming it entirely (like just let me change its name to this new value), one for appending (at the very end of the file/directory), one for inserting (at the very beginning of the file/directory), one for appending before the extension of the file (default behavior for directories should be same as appending IMHO).
> 
> Here is my lfrc for those (yes, I use hard tabs and I don't care what you think):
> 
> ```
> # insert
> cmd rename-insert &{{
> 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> 		lf -remote "send $id echo You can't change more than one file name"
> 		lf -remote "send $id unselect"
> 	else
> 		len="$(basename "$f" | wc -m)" # length of selected file/directory
> 		for i in $(seq "$len"); do
> 			pos="${pos}<left>" # how many times do I have to press <left> in order to get first char
> 		done
> 		lf -remote "send $id rename"
> 		lf -remote "send $id push $pos"
> 	fi
> }}
> 
> # append before ext
> cmd rename-before-ext &{{
> 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> 		lf -remote "send $id echo You can't change more than one file name"
> 		lf -remote "send $id unselect"
> 	else
> 		if [ -d "$f" ]; then
> 			lf -remote "send $id rename"
> 		else
> 			ext_len="$(echo ${f##*.} | wc -m)" # extention length
> 			for i in $(seq "$ext_len"); do
> 				pos="${pos}<left>"
> 			done
> 			lf -remote "send $id rename"
> 			lf -remote "send $id push "$pos""
> 		fi
> 	fi
> }}
> 
> # change its name entirely
> cmd rename-new &{{
> 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> 		lf -remote "send $id echo You can't change more than one file name"
> 		lf -remote "send $id unselect"
> 	else
> 		lf -remote "send $id rename"
> 		lf -remote "send $id push <c-u>"
> 	fi
> }}
> 
> map cc rename-new # new name
> map I rename-insert # at the very begging
> map A rename # at the very end
> map aa rename-before-ext # right before the extention
> ```

After tweaking a bit, I realized that I can shorten this:
```
map cc push A<c-u> # new rename
map I push A<c-a> # at the very beginning
map A rename # at the very end
map i push A<a-b><a-b><a-f> # before extention
map a push A<a-b> # after extention
```

**Comment by doronbehar** [comment]
Hey all :) I'm the one who wrote that section at the wiki and I've just stumbled upon this discussion. Just wanted to let you know I've edited that wiki section with a link to this issue and I've made the commands handle filenames with quotes and possibly other characters better, using a `printf '%q'`.

You might also be interested in https://github.com/gokcehan/lf/issues/306 .

**Comment by roket1428** [comment]
> > > I agree that keeping the extension is the most common when renaming. Should we make this the default behavior? Should there be an option to toggle it? Would be nice to not have to use custom commands.
> > 
> > 
> > I think there gotta be at least 4 default naming function: One for renaming it entirely (like just let me change its name to this new value), one for appending (at the very end of the file/directory), one for inserting (at the very beginning of the file/directory), one for appending before the extension of the file (default behavior for directories should be same as appending IMHO).
> > Here is my lfrc for those (yes, I use hard tabs and I don't care what you think):
> > ```
> > # insert
> > cmd rename-insert &{{
> > 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> > 		lf -remote "send $id echo You can't change more than one file name"
> > 		lf -remote "send $id unselect"
> > 	else
> > 		len="$(basename "$f" | wc -m)" # length of selected file/directory
> > 		for i in $(seq "$len"); do
> > 			pos="${pos}<left>" # how many times do I have to press <left> in order to get first char
> > 		done
> > 		lf -remote "send $id rename"
> > 		lf -remote "send $id push $pos"
> > 	fi
> > }}
> > 
> > # append before ext
> > cmd rename-before-ext &{{
> > 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> > 		lf -remote "send $id echo You can't change more than one file name"
> > 		lf -remote "send $id unselect"
> > 	else
> > 		if [ -d "$f" ]; then
> > 			lf -remote "send $id rename"
> > 		else
> > 			ext_len="$(echo ${f##*.} | wc -m)" # extention length
> > 			for i in $(seq "$ext_len"); do
> > 				pos="${pos}<left>"
> > 			done
> > 			lf -remote "send $id rename"
> > 			lf -remote "send $id push "$pos""
> > 		fi
> > 	fi
> > }}
> > 
> > # change its name entirely
> > cmd rename-new &{{
> > 	if [ "$(echo "$fx" | wc -l)" -gt 1 ]; then
> > 		lf -remote "send $id echo You can't change more than one file name"
> > 		lf -remote "send $id unselect"
> > 	else
> > 		lf -remote "send $id rename"
> > 		lf -remote "send $id push <c-u>"
> > 	fi
> > }}
> > 
> > map cc rename-new # new name
> > map I rename-insert # at the very begging
> > map A rename # at the very end
> > map aa rename-before-ext # right before the extention
> > ```
> 
> After tweaking a bit, I realized that I can shorten it to this:
> 
> ```
> map cc push A<c-u> # new rename
> map I push A<c-a> # at the very beginning
> map A rename # at the very end
> map i push A<a-b><a-b><a-f> # before extention
> map a push A<a-b> # after extention
> ```

Okay, this is last, I promise. :)

I realized that "before extension" keybinding has one bug. Right now, it goes to the very end of filename thanks to default `rename` function then goes back one word, and then goes one word back again. After that, it goes forward by one word.

 This goes right before the `.` in a filename format like this `<alphanumeric file name>.<ext>` but if the file name contains something like `"` right before the `.`, it just goes right before the `"`. So, it needs a fix and that is `map i push A<a-b><c-b>`.

This first goes to the very end of filename, and goes one word back (right after the `.`), and then, goes back one character which is the `.`. So, you'll end up right before the `.`.

 Thanks to @doronbehar to help me realize it. :)

Anyways, have a nice day. :)

**Comment by doronbehar** [comment]
Answering your comment https://github.com/gokcehan/lf/issues/306#issuecomment-599030414 which to my view relates to the discussion here more then there.

> And while you are writing functions/scripts to lf, prefer POSIX shell scripting as not everyone uses bash as default shell.

Totally agree with you, but replacing `printf '%q'` with a posix shell equivalent seems like too much effort for an edge case, see https://stackoverflow.com/a/29824428/4935114 . I've added a note to the wiki indicating this was tested with zsh.

**Comment by gokcehan** [comment]
I think the best argument in favor of this is that it is easier to define the other behaviors when the default is keeping the extension since there could be files with no extension or multiple extensions. If anyone wants to implement this, I'm now willing to accept a PR. The function [filepath.Ext](https://golang.org/pkg/path/filepath/#Ext) can be used for this purpose which seems to have a proper extension definition.

**Comment by yogeshdcool** [comment]
I this this is a better solution

map rr push rw<a-b><a-b><a-f> # before extension
map re push rw<c-u> # new rename
map rw rename # at the very end
map rq push rw<c-a> # at the very beginning
map rt push rw<a-b> # after extension

I got this from lukesmith's conf

**Comment by joelim-work** [comment]
I have updated the [tips](https://github.com/gokcehan/lf/wiki/Tips#enhancing-the-rename-command) to reflect the new behavior of the `rename` command.

**Comment by doronbehar** [comment]
> I have updated the [tips](https://github.com/gokcehan/lf/wiki/Tips#enhancing-the-rename-command) to reflect the new behavior of the `rename` command.

What is the new behavior you are talking about exactly? Speaking of the wiki, that wiki section is very unclear TBH :). I think the previous version was better - It's not clear what is the purpose of showing that table - keybindings after / before applying your config? Also, what happened to the `map ra` and `map re` mappings? How does the example config there is implementing them?

Link to wiki diff: https://github.com/gokcehan/lf/wiki/Tips/_compare/8311fe2f2d0fef74cbd1baf858dbac44d0f4c865...12982d7d605d108e2bdd1a2fa35037f890fad631

**Comment by joelim-work** [comment]
> What is the new behavior you are talking about exactly? 

`rename` places the cursor at the extension by default as of #1162 so the `map re` mapping isn't needed anymore.

> Speaking of the wiki, that wiki section is very unclear TBH :)

I agree that the descriptions by themselves can be vague, I have added another column to the table to visually show the effects of each mapping. Thanks for the feedback.

> I think the previous version was better

I fail to see how. Positioning the cursor can be implemented entirely using native `lf` commands, so why involve shell scripting and the complexity it brings?

> It's not clear what is the purpose of showing that table - keybindings after / before applying your config?

After. That is rather obvious when comparing the table with the mappings below.

> Also, what happened to the `map ra` and `map re` mappings? How does the example config there is implementing them?

As I have explained above, `map re` is the default behavior already. `map ra` has the same effect as `A` in the new example.

**Comment by doronbehar** [comment]
Thanks for the link to the PR, I missed that. The table indeed looks better now. I still felt that the phrasings around the table and the config example was a bit confusing, so I expanded that a bit.

**Comment by joelim-work** [comment]
OK, thanks for tidying the example up. I think it looks even better now that the mapping table comes after the config.

@gokcehan Unless I'm missing something I believe this ticket can actually be closed now, since preserving the extension is now the default behavior.
