### ISSUE TITLE
Question: Cancel Selection, Copy, Move.

### ISSUE THREAD

**Issue by alivefromupstairs** [gokcehan/lf#280]
If one pressed "d" accidentally, how to "unselect" (similar to `u` with normal selection) to be moved/copied files? it remains in the to be moved buffer even if you exit `lf` which is good, but in this case quite unsettling.

I think `esc` is a good candidate to do all these things, and also, upon confirmation, cancel copying/moving files.

**Comment by TeddyDD** [comment]
<kbd>u</kbd> or `:unselect` to remove <kbd>space</kbd> selection.
<kbd>c</kbd> or `:clear` to deselect files marked to move or delete.

see `lf -doc`

**Comment by Mati20187** [comment]
I have a similar question but regarding key mappings. When I accidentally press "g" and the menu with directories appears, how can I exit it without getting the "unknown mapping" error? Is there a way to bind esc to such operations?
