### ISSUE TITLE
Question: cd $OLDPWD

### ISSUE THREAD

**Issue by alivefromupstairs** [gokcehan/lf#282]
How to `cd $OLDPWD`/`cd -`/move to the previous working directory?

I sometimes accidentally move instead of copy between two separate partitions (https://github.com/gokcehan/lf/issues/151), and would love to either go back and copy the file, or go back and remove the file. Is there currently a way to do this? maybe a `mark-save`/`mark-load` that lasts only the session?

**Comment by gokcehan** [comment]
@alivefromupstairs Last directory is saved in `'` mark at each directory jump. You should be able to jump back using by default `''` binding.

**Comment by alivefromupstairs** [comment]
Thanks. to clarify `''` is two separate `'`.
