### ISSUE TITLE
Follow Directories/Files With Hints

### ISSUE THREAD

**Issue by smhmd** [gokcehan/lf#283]
In Zathura and other places, you can follow links by pressing `f` then a pattern of numbers/letters as hints.
![zathura follow links feature](https://user-images.githubusercontent.com/46059092/71783114-5d245d00-2fe2-11ea-9a14-5bb55f7ab859.png)

I think having `set number/relativenumber` all the time is kinda ugly (and, IMO, should only be enabled on the current directory); but another way is to follow (open, not highlight) directories/files (on demand).

[vimium-c](https://github.com/gdh1995/vimium-c), for example, generates unique characters (which are themselves configurable), so you don't need to press enter for your selection to take effect. And also visually helpful as hints get narrower.

**Comment by gokcehan** [comment]
@alivefromupstairs We already have `find` commands for easier jumping without the enter key.

**Comment by alivefromupstairs** [comment]
It would be great if you could do `find s` here (wanting to get to dir `summaries`) and have it display `s` (same character used in find) on the first finding, and numbers on the rest.
![image](https://user-images.githubusercontent.com/46059092/72165356-9f291680-33c7-11ea-8e89-91b364d026e5.png)

So to get to `schools-of-linguistics`, you enter `f s s`; `summaries`, `f s 3`.

**Comment by alivefromupstairs** [comment]
a more extreme case:
![image](https://user-images.githubusercontent.com/46059092/72172472-7f98ea80-33d5-11ea-81d9-c3d8cfb4ae82.png)
find is helpless here, and search really puts a cognitive load on the user and shouldn't be used if the directory right in front of you (for navigation, that is).

**Comment by alivefromupstairs** [comment]
It could look like something like this on pressing `f`:
![image](https://user-images.githubusercontent.com/46059092/72173987-fe435700-33d8-11ea-83c6-6817def7b47c.png)

**Comment by alivefromupstairs** [comment]
Otherwise, I am open to any suggestion on how to enter a directory on sight like you would with a mouse on a GUI. we need a solution for this.

**Comment by shabahengam** [comment]
i think implementing filtering feature will solve this problem.([128](https://github.com/gokcehan/lf/issues/128))

**Comment by alivefromupstairs** [comment]
This reminds me of [dmenu](https://dwm.suckless.org/), maybe it would work with tab to jump between filtered entries. It's more of enhancement to search than it is to find. However, It still would require you to know the name of the dir you want. Most of the time, you recognize the dir you want, not know its name or even the character it begins with (e.g., the dir after the one with the long name, the dir with all capital letters). Scrolling to `m` in your phone contacts is easier than searching for `mom`.

**Comment by shabahengam** [comment]
@alivefromupstairs 
offtopic: check [fff](https://github.com/jacokoo/fff) and its jump mode (also its filtering mode)

**Comment by alivefromupstairs** [comment]
That's not bad at all. It has some comfy keybindings that I'll incorporate in my `lfrc`, too. Wish it didn't remove entries on `tab` like `fish` wouldn't.
![fish shell cycling on tab like a chad](https://user-images.githubusercontent.com/46059092/72181714-343d0700-33ea-11ea-9596-c2d7e6fa3df9.png)

This is a pain point in `lf`; `tab` does not cycle at all which forces you to enter more characters (any reason for that, @gokcehan?)
![lf, not cycling on tab](https://user-images.githubusercontent.com/46059092/72181860-84b46480-33ea-11ea-90ce-15a9ad67c90a.png)
