### ISSUE TITLE
incsearch mode ignores search direction

### ISSUE THREAD

**Issue by halturin** [gokcehan/lf#284]
Enabling `incsearch` feature performs a search in a forward direction only, whether you use `ctrl-/` or `ctrl-?`

**Comment by gokcehan** [comment]
@halturin I don't think this is intentional. It seems that it correctly searches backwards with `?` when you finally press the enter key though it does not select the correct one during search.

**Comment by halturin** [comment]
there is a case with similar names of directories and files and the cursor in the middle of this list. what if i want to jump up (to the directory)?

**Comment by gokcehan** [comment]
@halturin I don't understand what you mean. Can you give an example? Is it related to this bug or something else?

**Comment by gokcehan** [comment]
@halturin I have pushed a fix for this. This should now work as intended. Closing the issue. Thanks for reporting.
