### ISSUE TITLE
Bug: Incomplete Drawing in st

### ISSUE THREAD

**Issue by alivefromupstairs** [gokcehan/lf#288]
I call `lf` using `st -e lf`. the UI is often incomplete in various degrees (in pic, all are the same dir, the highlighted one being the most complete)

![image](https://user-images.githubusercontent.com/46059092/72540862-d7c26780-3881-11ea-92c9-c358aed6df99.png)

I tried to reproduce this with other terminals (I remember trying alacritty, konsole, and kitty) none of which had incomplete UI.
I don't mind it myself, but would love others to confirm that st behaves in this way.

**Comment by bcaccia** [comment]
I am unable to reproduce this issue with the following setup:

* lf r13
* [Luke Smith ST fork(st 0.8.2)](https://github.com/lukesmithxyz/st) 
* i3 version 4.14.1
* Kubuntu 18.04

The steps taken to try to reproduce were:
1. Using another st terminal instance, run the following command:
`st -e ~/Downloads/lf`
2. Step 1 was repeated 30 times

**Comment by alivefromupstairs** [comment]
I think I've narrowed down the variables to reproduce. [st-flexipatch](https://github.com/bakkeby/st-flexipatch) with `SCROLLBACK_PATCH` and `SCROLLBACK_MOUSE_PATCH` enabled. It is somehow harder to get incomplete UI with just those two patches enabled, but they're sufficient.

**Comment by avih** [comment]
For reference, the currently-recent mouse and mouse-altscreen patches were updated by me. Feel free to ping me if there are issues with these patches (or just fix them yourself if you find such issues).

That being said, at the moment I just don't see how any of those patches would affect rendering/layout.
