### ISSUE TITLE
Toggle columns mapping

### ISSUE THREAD

**Issue by ranebrown** [gokcehan/lf#289]
Is there a way to get a key mapping to work that will toggle the additional columns on/off? I have this which works to switch to single column mode but is there a way to use the same key to get the default view back? Thanks.

```
map ~ :{{
    set nopreview
    set ratios 1
    set info size:time
}}
```

**Comment by freed00m** [comment]
I wanted to make single preview toggleable, so you can get inspired from my snippet

There must be a simplier way, but I am learning LF as I go. 

```
# Hide previews
map zp no_preview

cmd yes_preview &{{
	lf -remote "send $id set preview"
	lf -remote "send $id map zp no_preview"
}}

cmd no_preview &{{
	lf -remote "send $id set nopreview"
	lf -remote "send $id map zp yes_preview"
}}
```

**Comment by ranebrown** [comment]
Thanks for the tip! This worked for me:
```
# toggle single column view
cmd no_preview :{{
    set nopreview
    set ratios 1
    set info size:time
    map ~ yes_preview
}}
cmd yes_preview :{{
    set ratios 1:2:3
    set preview
    set info
    map ~ no_preview
}}
map ~ no_preview
```
