### ISSUE TITLE
Neovim randomly opens in command or search mode

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#290]
About 50% of the times when I open a text file with `l`, neovim opens in search/command mode with a some very weird text in it. [These are just two examples](https://imgur.com/a/hK6rcuz).

This never happens when I open neovim directly from the command line.

**Comment by gokcehan** [comment]
@n0ibe There was a similar issue reported for neovim. Did you identify the issue somehow? Why did you close the issue?

**Comment by n0ibe** [comment]
@gokcehan I closed the issue because I later found out it wasn't `lf`'s problem. I tried several terminal based file managers (`lf`, `ranger`, `vifm`, `nnn`) and they all behaved the same way.

Turns out it's neovim's fault, and it's a [known bug](https://github.com/neovim/neovim/issues/11393).
