### ISSUE TITLE
macOS Color Tags

### ISSUE THREAD

**Issue by brandonkal** [gokcehan/lf#297]
Would it be possible to get macOS Finder color tags displayed inside the terminal lf listing? One of my favorite features of Finder is the Column view and lf elegantly brings that to the terminal.

It is possible to see color tags with this command:
```
xattr -p com.apple.metadata:_kMDItemUserTags file_or_folder.txt | xxd -r -p | plutil -convert json - -o -
```
Or by using something like https://github.com/jdberry/tag/

References for the color numbers are here:
https://eclecticlight.co/2017/12/27/xattr-com-apple-metadata_kmditemusertags-finder-tags/

**Comment by shabahengam** [comment]
I don't have macOS but I know lf uses `$LS_COLORS` variable(or `$LSCOLORS`).you can read [docs](https://godoc.org/github.com/gokcehan/lf#hdr-Colorschemes) here.
you just need to find out the color codes in macOS Finder and then set `$LSCOLORS`.
you can use this site too [LSCOLORS Generator](https://geoff.greer.fm/lscolors/)

**Comment by brandonkal** [comment]
I'm aware of LSCOLORS but that is limited to filetype and permissions only.

**Comment by shabahengam** [comment]
I don't think there is any other way to do that.

**Comment by gokcehan** [comment]
@brandonkal I don't have a macOS. What else do you need besides filetype, permission and extension to implement this behavior?

**Comment by brandonkal** [comment]
@gokcehan It is a finder metadata attribute on the file/folder.
The command above returns output like this: `["Red\n6","Green\n2"]`
Note the numbers represent the actual displayed color so it is possible to have something like "Important\n6".
```
none, 0
grey, 1
green, 2
purple, 3
blue, 4
yellow, 5
red, 6
orange, 7
```
It appears macOS sorts by number as the Finder displays the green dot above the red one. Calling that `tag` binary on a directory returns output for all files and folders:
```
Cloud                         	Green,Red
Code                           	Red
Desktop
Documents                      	Green
Downloads
```
Note there is a tab character just before the tags list which would make parsing easy.

**Comment by CatsDeservePets** [comment]
Hey @brandonkal! This is now possible using [addcustominfo](https://github.com/gokcehan/lf/blob/master/doc.md#addcustominfo).

**Comment by brandonkal** [comment]
Thank you for the heads up @CatsDeservePets !

Below is how I got this set up if anyone is interested.

### macOS Finder color tags in `lf` using `addcustominfo`

I got this working on macOS by using an `on-load` hook + `addcustominfo`.

#### 1) `~/.config/lf/lfrc`

```lf
set preview true
set previewer ~/.config/lf/preview.sh

# Draw borders between lf columns/panes.
set drawbox true

# Show macOS Finder tags (colors) in the info column via addcustominfo.
set info custom
cmd on-load &{{
    cmds=""

    for file in "$@"; do
        info="$($HOME/.config/lf/macos-tags.sh "$file")"

        if [ -n "$info" ]; then
            cmds="${cmds}addcustominfo \"${file}\" \"${info}\"; "
        else
            cmds="${cmds}addcustominfo \"${file}\" ''; "
        fi
    done

    if [ -n "$cmds" ]; then
        lf -remote "send $id :$cmds"
    fi
}}
```

#### 2) `~/.config/lf/macos-tags.sh`

```sh
#!/usr/bin/env sh

file="$1"

# Finder tags are stored in this extended attribute.
raw="$(xattr -px com.apple.metadata:_kMDItemUserTags -- "$file" 2>/dev/null)" || exit 0
[ -n "$raw" ] || exit 0



# Parse tags from plist binary -> JSON array (e.g. "Red\n6").
json="$(printf '%s' "$raw" | xxd -r -p 2>/dev/null | plutil -convert json - -o - 2>/dev/null)" || exit 0
[ -n "$json" ] || exit 0

# Convert Finder tag color numbers to colored circle emoji.
# 1=Gray 2=Green 3=Purple 4=Blue 5=Yellow 6=Red 7=Orange
icons="$(printf '%s' "$json" | jq -r '[
  .[]
  | (split("\n")[-1]) as $c
  | if $c == "1" then "⚪"
    elif $c == "2" then "🟢"
    elif $c == "3" then "🟣"
    elif $c == "4" then "🔵"
    elif $c == "5" then "🟡"
    elif $c == "6" then "🔴"
    elif $c == "7" then "🟠"
    else empty
    end
] | join(" ")' 2>/dev/null)"

printf '%s' "$icons"
```

Then make it executable:

```sh
chmod +x ~/.config/lf/macos-tags.sh
```

#### Notes

- `xattr -px` is important here (hex output), then decode with `xxd -r -p` before `plutil`.
- `set info custom` requires enough pane width, or custom info may not display.
- `set drawbox true` adds borders between lf columns.

**Comment by CatsDeservePets** [comment]
Really cool. Feel free to add it to the `tips` section of the wiki.
