### ISSUE TITLE
Unreliable selection of file after creating it

### ISSUE THREAD

**Issue by pglira** [gokcehan/lf#298]
I have this small script in my lfrc to create a new file and immediately select it afterwards. However, I don't know why, but the selection of the new file works only in approximately 50% of the cases. Is this an lf issue or is something wrong with my script?

```
cmd touch !{{
    file=$(echo $* | tr ' ' '\ ')
    touch "$file"
    lf -remote "send $id select \"$(pwd)//${file}\""
}}
```

**Comment by pglira** [comment]
I extended it to
```
cmd touch !{{
    file=$(echo $* | tr ' ' '\ ')
    touch "$file"
    lf -remote "send $id load" <-- new line
    lf -remote "send $id select \"$(pwd)//${file}\""
}}
```
but this also seems not to help. Still the created file is not reliably selected.

**Comment by gokcehan** [comment]
@pglira The use of `!` messes with the timing of remote commands in this case. Can you not change the command to `%` instead? It should be more appropriate for this case anyways.

**Comment by pglira** [comment]
It seems to work with %. Thank you.

**Comment by gokcehan** [comment]
For future reference, this turned out to be a bug and with the latest commit `select` should now work reliably in any type of shell commands and `load` is not necessary since it is already called after shell commands, so the example given in the original post should work without any modification.
