### ISSUE TITLE
all the executable is a rocket sign. that is weird

### ISSUE THREAD

**Issue by 66RING** [gokcehan/lf#299]
rocket off.
![2020-02-23-172924_443x328_scrot](https://user-images.githubusercontent.com/49358576/75109891-91bba900-5662-11ea-9972-f0bfd1ffa6bd.png)

rocket on.
![2020-02-23-172948_371x303_scrot](https://user-images.githubusercontent.com/49358576/75109897-93856c80-5662-11ea-9e2a-00f174464620.png)

due to this.
![2020-02-23-172843_366x260_scrot](https://user-images.githubusercontent.com/49358576/75109934-d8110800-5662-11ea-92af-3adbce230a8f.png)

I think this is a better way to display. because all the executable files is green, do not need a rocket sign to tell me.(this image come from ranger)
![2020-02-23-173648_398x190_scrot](https://user-images.githubusercontent.com/49358576/75109965-2faf7380-5663-11ea-8c86-718dd2f5947d.png)

thanks 
\ o /
|     |
 /  \

**Comment by gokcehan** [comment]
@66RING Not sure if you figured this out yourself and closed this afterwards but you should be able to delete `ex` line in `LF_ICONS` to get what you want.

**Comment by 66RING** [comment]
@gokcehan I had try this before but it didn't work. 
I delete `ex` line and than the icon turn into the `fi` line one. If I delete `ex` and `fi` line the icon just goes away. 

This problem only appears in excutable file, `chmod +x` things, and everything else is fine.

Now I am using the iconless mode and I think "Hum, that's not bad".
So I closed this issue.
