### ISSUE TITLE
Log files remain in /tmp if closed by window manager.

### ISSUE THREAD

**Issue by LukeSmithxyz** [gokcehan/lf#300]
If I close that instance of lf by pressing the shortcut bind within lf, it closes with no abnormal effects...

but if I close that with my window manager's typical shortcut for closing programs `super + q` as it happens, lf's log file remains in `/tmp` forever (well until `/tmp` cleanup).

You say in #65 that leftovers will remain in `/tmp` for instances closed by errors, but here it seems that any external closing does the same.

Not sure if this is a decided choice or what, but seems abnormal among programs.

I'm using dwm, if that's relevant.

**Comment by roket1428** [comment]
Already reported in #292.
