### ISSUE TITLE
Termbox is no longer maintained. tcell is a recommended replacement

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#302]
Hello @gokcehan . It has come to my knowledge that the go library termbox is no longer maintained, see https://github.com/nsf/termbox-go/commit/ed2200f31832eae5a7c3f22738f620fb9c5eda3a . After encountering https://github.com/nsf/termbox-go/issues/215 , I fixed the issue in https://github.com/nsf/termbox-go/pull/216 and there the author has stated that https://github.com/gdamore/tcell is a recommended replacement. 

I'm currently using my own fork of Lf with my own version of termbox that includes that patch. Im using tmux and I experience no issues. My fork of Lf is available here: https://github.com/doronbehar/lf/tree/doronbehar-termbox .

Would you be willing to consider switching to my fork of termbox until a replacement for it will be written? I can send a PR straight from https://github.com/doronbehar/lf/tree/doronbehar-termbox .

**Comment by gokcehan** [comment]
@doronbehar It is unfortunate termbox is not maintained anymore. I tried tcell at one point which also have a termbox compatibility layer but I remember some of the things were not working so I gave up without looking further into it. In the long term, we should switch to tcell, ideally using its own api. Meanwhile, it makes sense to maintain our own fork of termbox. If you're willing to maintain a termbox fork for lf, feel free to send a PR to change it. Thanks in advance.

**Comment by doronbehar** [comment]
> If you're willing to maintain a termbox fork for lf, feel free to send a PR to change it.

I wouldn't mind. It's just that I don't want that fork to be considered a permanent replacement. Not to mention security issues which I wouldn't dare take responsibility for. Please @gokcehan take this fork as a mere UX experience improvement for tmux users of Lf (https://github.com/nsf/termbox-go/issues/215).

**Comment by gokcehan** [comment]
@doronbehar I don't think there will be an issue, but if you're worried or don't want any responsibility, I can change lf to use `gokcehan/termbox-go` and you can send your tmux patch to that fork instead.

**Comment by doronbehar** [comment]
Well maybe it's not that worth your trouble. I'm sure you'll `@quote` me if needed for any issues related to termbox.

**Comment by flw-cn** [comment]
Support this idea. According to my research, issue #139 is also due to a flaw in termbox-go.
