### ISSUE TITLE
Yank path w/filename, filename, and file (As in Ranger)

### ISSUE THREAD

**Issue by pabloaguirrenck** [gokcehan/lf#303]
map y

map yy copy

map yp yank_path

map yn yank_name

map yd yank_dir

cmd yank_path ${{
    set -f
    readlink -f $f | xclip -selection clipboard
}}

cmd yank_name ${{
    set -f
     basename "$(readlink -f "$f")" | xclip -selection clipboard
}}

cmd yank_dir ${{
    set -f
    pwd -f $f | xclip -selection clipboard
}}

--------------------------------------------------------------------------------------------

Any suggestions for yank dir? pwd pipes current dir, not selected dir.

**Comment by shabahengam** [comment]
from [docs](https://godoc.org/github.com/gokcehan/lf)
`$f   current file`
`$fs  selected file(s) separated with 'filesep'`
`$fx  current file or selected file(s) if any`

so you can use something like this
`map yd ${{`
    `#Copy fullpath`
    `echo -n $fx | xclip -selection clipboard `
`}}`

**Comment by pabloaguirrenck** [comment]
@shabahengam thanks man. Works fine.

**Comment by roachsinai** [comment]
Hi, `lf` helps a lot for me, thanks!!!

And for yank path post at https://github.com/gokcehan/lf/wiki/Tips#yank-paths-into-your-clipboard works, but run a yank path command left a blank terminal as below:

```





hmanx ~/tt » 



```

The terminal buffer before run lf is:

```
hmanx ~/tt » ls
all.snippet  cuda_test         lines.txt              mcount          t1        ttcpp     tt.m4        tt.s       tt.web
alpha.c      eight_queens.py   lol_auto_chess.c       naval_fate.py   test      tt.go     tt.markdown  tt.sh      tt.zsh
a.out        git_stash         lol_auto_chess_dfs.py  program         test.txt  tt.hs     tt.md        ttt.c
beta.c       HelloWorld.class  lol_auto_chess.py      __pycache__     tt2.py    tt.html   tt.out       tt.tex
com          helloworld.cpp    m4                     resource        tt.c      tt.i      tt.py        ttt.ipynb
crash.c      HelloWorld.java   main.c                 rmm.zsh         ttc       tt.ipynb  tt.rb        tt.txt
crash.out    helloworld.out    makefile_example       setup_tutorial  tt.cpp    tt.json   tt.rkt       tt.vim
hmanx ~/tt » 



```

my lfrc is:

```
# default mapping is zh
map . set hidden!

# https://github.com/gokcehan/lf/wiki/Tips#yank-paths-into-your-clipboard
cmd yank-dirname $dirname -- "$f" | head -c-1 | xclip -i -selection clipboard
cmd yank-path $printf '%s' "$fx" | xclip -i -selection clipboard
cmd yank-basename $basename -a -- $fx | head -c-1 | xclip -i -selection clipboard

cmd yank-basename-without-extension ${{
    echo "$fx" |
        xargs -r -d '\n' basename -a |
        awk -e '{
            for (i=length($0); i > 0; i--) {
                if (substr($0, i, 1) == ".") {
                    if (i == 1) print $0
                    else print substr($0, 0, i-1)

                    break
                }
            }

            if (i == 0)
                print $0
        }' |
        if [ -n "$fs" ]; then cat; else tr -d '\n'; fi |
        xclip -i -selection clipboard
}}

map <space>
map <space>yd yank-dirname
map <space>yp yank-path
map <space>yb yank-basename
map <space>ye yank-basename-without-extension
```

**What expected**

Wish lf could restore terminal buffer.

Thanks in advanced!

**Comment by gokcehan** [comment]
@roachsinai That's probably #586 and not related to this.

**Comment by roachsinai** [comment]
@gokcehan got it, thanks for the quick reply!

**Comment by bushnerd** [comment]
How it is in Powershell, I try the code as follows
```
map y
map yy copy
map yn yank-basename
cmd yank-basename ${{ Split-Path -Leaf $env:f | Set-Clipboard }}
```
i use yn, but it tells "running shell: exit status 255

**Comment by badmagick329** [comment]
> How it is in Powershell, I try the code as follows
> 
> ```
> map y
> map yy copy
> map yn yank-basename
> cmd yank-basename ${{ Split-Path -Leaf $env:f | Set-Clipboard }}
> ```
> 
> i use yn, but it tells "running shell: exit status 255

Thanks this seemed to work for me. I think you might be missing this in your lfrc

```
set shell powershell
```
