### ISSUE TITLE
Make :rename accept multiple arguments as 1 file name

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#306]
I'm trying to create a mapping for `rename` which will include the original file name's in Lf's CLI. I.e, I want e.g to make the keys `ra` put the following in Lf's CLI:

```
:rename <current file name>
```

I'm currently using:

```
map ra ${{
	# get 'basename' of the selection
	filename="${f##*/}"
	# quote it so we won't deal with quotes in the lf -remote command
	filename="$(printf '%q' "$filename")"
	filename="${filename// /<space>}"
	lf -remote "send $id push :rename<space>$filename"
}}
```

So for example with a directory that `ls` shows as:

```
drwxrwxr-x+ 1 doron users 438 Mar 13 15:10 'Here'\''s a dir with "'
```

I get the following in the CMD when I press `ra`:

```
:rename Here\'s\ a\ dir\ with\ \"
```

Which is fine, but If I would like e.g to rename it so it'll be:

```
drwxrwxr-x+ 1 doron users 438 Mar 13 15:10 'Here'\''s a dir with " and other chars'
```

I need to type:

```
\ and\ other\ chars
```

I.e insert all of those backslashes - which is kind of tedious.

Ideally, I'd have been able to remove the `printf '%q'` quoting from that shell snippet so `map ra` will put in Lf's CLI:

```
:rename Here's a dir with "
```

But if I do that, and run the command as is, the file is renamed to:

```
drwxrwxr-x+ 1 doron users 438 Mar 13 15:10 "Here's"
```

It would have been nice if `:rename` would have assembled all arguments it gets and create 1 string out of it that will be used as the new file name.

**Comment by roket1428** [comment]
As far as I know, latest lf's `rename` command does exactly this.
And while you are writing functions/scripts to lf, prefer POSIX shell scripting as not everyone uses bash as default shell.

Also, I guess you borrowed that from one of my lf fucntions, `filename="${f##*/}"` wouldn't work on directory names that don't have a trailing back slash (`/`) at the end of their name.
I was using it because I didn't know `basename` command was POSIX-compliant.

So, my suggestion is, use POSIX-compliant things.
Have a nice day. :)

**Comment by doronbehar** [comment]
> As far as I know, latest lf's rename command does exactly this.

No it doesn't, see: https://asciinema.org/a/qUJf6JpRm1yEu0a9Ylx2F1ubQ

**Comment by roket1428** [comment]
> > As far as I know, latest lf's rename command does exactly this.
> 
> No it doesn't, see: https://asciinema.org/a/qUJf6JpRm1yEu0a9Ylx2F1ubQ

Oh, as I was using my own keybindings, I didn't realize that this behavior exist. It certainly is a bug though I just do `cc` and it doesn't do that. See [#279 (comment)](https://github.com/gokcehan/lf/issues/279#issuecomment-599029770) for all bindings that I've created.

**Comment by gokcehan** [comment]
Is the change mentioned in #279 enough to get rid of all custom rename shell commands?

**Comment by doronbehar** [comment]
The solutions in #279 don't suggest anything related to the idea presented here - I'm merely suggesting that `:rename` will assemble all the arguments it gets as 1 long file name - with spaces between every argument. I did not mean to suggest changing it's behavior, I was only trying to give some context to the origin of the idea - that it's uncomfortable for anyone, with or without a custom mapping for `:rename`, to give files names with spaces.

**Comment by gokcehan** [comment]
@doronbehar I may not have understood what you meant, but there could be cases where we want to take multiple arguments for a custom command, and merging arguments into a single argument would limit all custom commands to a single argument.
