### ISSUE TITLE
lf doesn't respect all properties of LS_COLORS

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#307]
AFAIK `lf` should decide how to colour files and folders according to the `LS_COLORS` environemt variable. I found this only works some of the time. For example, it works for folders and executables, but it doesn't work it [this situation](https://imgur.com/a/y2zpjc9).

As you can see comparing `ls` and `lf`, there are two problems:

1) the `README.md` and `setup.sh` are both colored in the `ls` output, but both of them are white in `lf`;

2) the line under the `README.md` file extends for the whole width of column instead of being confined to the name of the file.

This is the value of my `LS_COLORS`:
    
    export LS_COLORS='no=90:di=01;34:ex=01;32:ln=35:mh=31:*.mp3=33:*.md=04;93:*.ttf=95:*.otf=95:*.png=04;92:*.jpg=04;92'

**Comment by buzzcz** [comment]
Actually, for me, it doesn't even [respect the folders for me](https://imgur.com/a/ZTRwAhb).

I have not modified my `LS_COLORS`, those are provided either by Fedora or some other package:
```
rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
```

**Comment by gokcehan** [comment]
The issue described by @n0ibe is related to bright color codes (i.e. 90-97 range) which do not have an equivalent in termbox color codes.

@buzzcz I'm not sure what your issue is about. I can't reproduce it on my machine with the value you provide. What terminal are you using? Do you set `color256 option or not?

**Comment by shabahengam** [comment]
lf also doesn't support `target` value.for example if we have
`LINK target`
in our dircolors file,lf can't show the right color.this is the error in the log file:
`converting escape code: strconv.Atoi: parsing "target": invalid syntax`

**Comment by dufferzafar** [comment]
I have set my LS_COLORS variable using https://github.com/sharkdp/vivid

`vivid generate snazzy`

**Comment by buzzcz** [comment]
@gokcehan I use either gnome-terminal or tilix, both behave the same.
About the `color256 option`, do you mean if my TERM variable is set like this: `TERM=xterm-256color`? If so, then yes, it is set.
Should I open new issue or do you think it is related to this one?

**Comment by shabahengam** [comment]
@buzzcz from [documentation](https://godoc.org/github.com/gokcehan/lf)
`
You should also note that lf uses 8 color mode by default which uses sgr 3-bit color escapes (e.g. '\033[34m'). If you want to use 256 colors, you need to enable 'color256' option which then makes lf use sgr 8-bit color escapes (e.g. '\033[38;5;4m')
`

so check if you have `set color256` in your lfrc.
for more info check this issue #104

**Comment by buzzcz** [comment]
@gokcehan Ahh, that's it! Thank you very much for the solution.

**Comment by n0ibe** [comment]
@gokcehan what about the problem with underlined files?

**Comment by gokcehan** [comment]
I have now added support for the bright ansi escape codes (i.e. 90-97 and 100-107). Underline behavior is difficult to change with all the length calculations so I will simply leave it as it is.
