### ISSUE TITLE
Icons show weird glyph in ITerm  for Mac OSX

### ISSUE THREAD

**Issue by MrMic** [gokcehan/lf#309]
Hi,

- All are perfectly fine with Arch Linux Manjaro but, 
with my Mac OSX Mojave 10.14.6, the icons do not display correctly.
 I have ITerm2 with Ned Font. 
I tried with other fonts but it is not better ...
Do I miss something ? or is it a bug?
I set this option in the lfrc file.

Thank for the reply.
Rgds,

Michaël

**Comment by gokcehan** [comment]
@MrMic What icon settings you have in your lfrc file? How about `LF_ICONS` variable? Do you set it somewhere? Are you able to display icons properly where you set this variable?
