### ISSUE TITLE
Modify status line to show specific information

### ISSUE THREAD

**Issue by davoudarsalani** [gokcehan/lf#310]
Is there a way so I can edit the status line to show specific information as well, like the output of $(du -sh . | awk '{ print $1 }').
Currently I mapped it to <esc> like this:
map \<esc\> :{{
    echo $(du -sh . | awk '{ print $1 }')
}}
but it is temporary and I like it to be a permanent part of the status line.

**Comment by gokcehan** [comment]
@davoudarsalani Is there a typo in that mapping? Which key do you bind the command to?

There is currently no way to automatically display the output of a command in the statusline.

**Comment by davoudarsalani** [comment]
It is currently mapped to <esc> and works fine.

**Comment by shabahengam** [comment]
@davoudarsalani output of that command display in message line not statusline because statusline can not be changed during runtime.

@gokcehan  am I wrong about message line and statusline?
for that mapping use this
```
map t %{{
echo $(du -sh . | awk '{ print $1 }')
}}
```

**Comment by davoudarsalani** [comment]
Maybe I was wrong referring to it as status line. What I meant was the line at the bottom shown in Pic (1).
Currently this is the mapping I use:
map <esc> :{{
    %echo -e " \033[1;34mPWD\033[0m" $(du -sh . | awk '{ print $1 }')   $(\ls -lAFh | \grep '/$' | wc -l)  $(\ls -lAFh | \grep -v '^d' | sed '1d' | wc -l)
    clear
    unselect
    reload
}}
It works fine and shows what I want by pressing <esc> (Pic 2). But the point is it goes away as soon any key is pressed. 
So, what I am looking for is a way, for example through modifying the config file, for the desired output to be permanently visible on the line.

![1](https://user-images.githubusercontent.com/50229325/77096708-f3362400-6a24-11ea-8817-ffdf30bd874d.jpg)

![2](https://user-images.githubusercontent.com/50229325/77096723-f8936e80-6a24-11ea-81ea-750f9c50d0e3.jpg)

**Comment by gokcehan** [comment]
@shabahengam You're right, there is currently no option to customize the status line. Messages are simply written on the statusline. I haven't been calling them two separate names so far.

@davoudarsalani I think tmux support external commands. If you're using tmux, maybe you can display this information in tmux statusline as a workaround.

**Comment by 4volodin** [comment]
maybe somebody knows 
 there are fields (user and group) on macos
-rwxr-xr-x 1 user staff 1.3K 2021-04-09 23:01:31 +0400
on linux these fields are empty
-rw-r--r-- 384B 2021-07-05 21:30:44 +0400

**Comment by gokcehan** [comment]
@4volodin Are you sure you have the same version in both machines?

**Comment by davoudarsalani** [comment]
In newer version (currently `r24`), I've been able to show the disk usage information in `promptfmt`:
```
% {{
    lf -remote "set promptfmt '\033[0;49;34m %w/\033[0m\033[0;49;37m%f\033[0m $(du -sh . | awk '{ print $1 }')'"
}}
```

**Comment by 4volodin** [comment]
> @4volodin Are you sure you have the same version in both machines?

you are right, on Linux I had an old version

**Comment by camoz** [comment]
I'm not sure this is a good idea, for the reasons outlined in https://github.com/gokcehan/lf/issues/112#issuecomment-1311105498

If you need to browse your files and see disk usage for *every folder*, `ncdu` seems like the right tool for that.
