### ISSUE TITLE
Open lf in current session

### ISSUE THREAD

**Issue by blayz3r** [gokcehan/lf#318]
Is it possible for lf to open a file in an existing session e.g In Gvim below, opening a file creates a new instance
![image](https://user-images.githubusercontent.com/12205650/78506326-dd27a380-7746-11ea-9f25-0600da588d4f.png)

**Comment by blayz3r** [comment]
https://vi.stackexchange.com/questions/8197/open-text-file-in-an-existing-console-vim-window

**Comment by gokcehan** [comment]
@blayz3r In the example link you provided, instead of `filename`, you can use `$f` and it should work.

**Comment by gokcehan** [comment]
@blayz3r Sorry I didn't realize you already closed the issue.

**Comment by blayz3r** [comment]
> 
> 
> @blayz3r Sorry I didn't realize you already closed the issue.

thanks
