### ISSUE TITLE
Russian chars mess up formatting

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#32]
Like on screenshot. Had to cut a piece as there are some things I can't show, but should be visible what I mean.
<img width="642" alt="screen shot 2016-10-16 at 19 58 26" src="https://cloud.githubusercontent.com/assets/431488/19419700/409d7dd2-93dd-11e6-8479-322d387fee71.png">

May be related to #30. Perhaps termbox is thinking some of these chars are escape seqs or sth?

**Comment by gokcehan** [comment]
@KenjiTakahashi I'm guessing this is the same as #30 which is now fixed in the master. Can you copy those filenames here as strings so that I can try?

**Comment by KenjiTakahashi** [comment]
@gokcehan Sure.
```
Запуск и проблемы.txt
Список игр.txt
Читы.txt
```
I've also tested it now on current master and it seems to work fine. I'm closing this, feel free to reopen if you find anything more wrong.
