### ISSUE TITLE
Add sort by code point.

### ISSUE THREAD

**Issue by zeda-para-iba** [gokcehan/lf#320]
In natural unicode sorting, uppercase letters are sorted alongside lowercase letters.

I like to have my uppercase files sorted before lowercase ones so I have `README` and `Makefile` in the beginning of the directory list. And I think this applies for a lot of users.

By adding an option to sort by code point, without unicode natural sorting, this would suffice.

In the image, how a directory for a project is listed in `lf(1)`.
![lf](https://user-images.githubusercontent.com/63294608/78666363-a1f3b480-78ad-11ea-926a-e65e124fa408.png)

**Comment by gokcehan** [comment]
@zeda-para-iba I have checked the code and it looks like we lowercase the filename before using it in sorting. There should be an option to disable this behavior. It might also be possible to use the value of `ignorecase` for name and natural sorting but I'm still not sure if this is a good idea or not.

**Comment by zeda-para-iba** [comment]
Hmm, so a *foldsort* (or the like) option for whether or not fold uppercase letters with lowercase letters when sorting would suffice, just like the `-f` option in the `sort(1)` command.

**Comment by gokcehan** [comment]
@zeda-para-iba I have now changed `ignorecase` and `ignoredia` options to apply to sorting as well in addition to searching. So you can now `set noignorecase` to achieve what you want. We can separate options for searching and sorting later on if it is somehow necessary. Closing this issue now.
