### ISSUE TITLE
Add description of options in the documentation.

### ISSUE THREAD

**Issue by zeda-para-iba** [gokcehan/lf#321]
I think documentation problems are as serious as coding problems.  
`lf(1)` documentation only lists the options but do not describe most of them.  It is up to the user to test by trial-and-error to find out what each option is about.

I think that adding short descriptions for the options and/or adding a section describing the options and the format of their respective values would easily fix this.

In the image, how the documentation lists the options.
![lfdesc](https://user-images.githubusercontent.com/63294608/78667136-cbf9a680-78ae-11ea-8ca4-159224e324ed.png)

**Comment by gokcehan** [comment]
I have finally finished adding descriptions of commands and options to the documentation. I'm still trying to improve the documentation with a better organization but I think this issue is ready to be closed now.
