### ISSUE TITLE
Add option to choose what file types are hidden

### ISSUE THREAD

**Issue by cplaursen** [gokcehan/lf#327]
Currently the only files that are hidden are those prefixed by a dot.
It would be nice if the configuration allowed the user to specify other types to hide, such as temporary TeX files which clutter up directories. The option is available in ranger.

I would be happy to try to implement this if given the go-ahead.

**Comment by cplaursen** [comment]
@gokcehan globbing seems like the better option; would also be consistent with gitignore syntax which could aid in solving #199. However it seems harder to hide gitignore contents, as one would have to search the ancestors of the cwd for a git repository and then parse all relevant gitignore files.

I think the most intuitive way of specifying the files to hide would be as an array of strings. I imagine the config parser can cope with this, although I haven't looked into it much. Then it would just be a matter of replacing the isHidden function currently used with glob matching.

**Comment by gokcehan** [comment]
@adamtabrams I have looked at #330 and I'm not sure if it is a good idea to call an external process to check if a file should be hidden or not. I was more thinking of adding a simple option for this purpose (e.g. `set hiddenFiles .*:*.o:*.pyc` (`:` is still our string separator for options)).

**Comment by adamtabrams** [comment]
@gokcehan Hopefully you like #372 better.
