### ISSUE TITLE
Wrong GIF in Tutorial

### ISSUE THREAD

**Issue by manuelprinz** [gokcehan/lf#328]
The tutorial page shows the wrong GIF for `shell-pipe`. It is the same as for `shell` (the `mv` example.

**Comment by gokcehan** [comment]
@manuelprinz Example is the same but the prompt is displayed in the terminal in `$` whereas it is displayed in the status line in `%` which is the whole point of `%`, that it does not pause the ui when running a shell command.

**Comment by manuelprinz** [comment]
Thank you for explaining! I misunderstood. Closing.
