### ISSUE TITLE
Why are some folders highlighted?

### ISSUE THREAD

**Issue by Mati20187** [gokcehan/lf#331]
Hi, I've recently started using lf and found that some folders are highlighted with yellow. What does it mean?
![tmp](https://user-images.githubusercontent.com/31066931/79328196-2e812100-7f05-11ea-9628-268b9ca19286.png)
![dubble](https://user-images.githubusercontent.com/31066931/79328205-317c1180-7f05-11ea-89f3-d55e0c05059a.png)

**Comment by Provessor** [comment]
Files and directories are coloured depending on their attributes (lf should have the same colouring as GNU ls). In your case, `/tmp` is a sticky directory; see [here](https://unix.stackexchange.com/a/94505) if you want a more comprehensive answer on the colours.

**Comment by gokcehan** [comment]
Closing this issue. Feel free to leave comments.
