### ISSUE TITLE
use summarized size on directory

### ISSUE THREAD

**Issue by issadarkthing** [gokcehan/lf#332]
![image](https://user-images.githubusercontent.com/50593529/79576947-9185da00-80f6-11ea-8665-0d1c3eb5a54b.png)
it is more useful to show summarized file size `du -sh` rather than the size of directory itself which will only show 4KB max

**Comment by ivanp7** [comment]
It'll be extremely unpractical when handling deep directories with a lot of files, remote mounted subdirectories, etc. Latency problem.

**Comment by gokcehan** [comment]
Closing in favor of the duplicate #152.
