### ISSUE TITLE
lf shuts down on Control-C during shell commands

### ISSUE THREAD

**Issue by Randoragon** [gokcehan/lf#333]
# The Issue

I have a few mappings to shell commands. Sometimes I want to stop the running command and return to lf, so I press Control-C, and for some reason that shuts lf down completely, which I don't want.

## How To Replicate

You can try this during any shell command's execution, for example:

```
cmd wait $sleep 10
```

Open lf, type `:wait<enter>` and press Ctrl-C at any time before the command finishes. lf just closes.

## What I've tried

I've tried workarounds, like trapping SIGINT and running a custom function in its stead with `trap foo 2`, but to no avail.

## What I would expect to happen

I would like to be able to stop any shell command with Ctrl-C and return to lf safely.

## Information

LF Version | 14-1 (r14)
---: | :---
Build Date | Tue 14 Apr 2020 08:02:37 PM CEST
OS | Arch Linux 5.6.4-arch1-1
Terminal | termite
Shell | ZSH

[EDIT] Now also confirmed on the latest build from https://github.com/gokcehan/lf/commit/c49140ab364cdb2773e3593dea6cfc72da4f1bb2

**Comment by shabahengam** [comment]
what about other prefixes?
``` 
$  shell           shell command
%  shell-pipe      shell command running with the ui
!  shell-wait      shell command waiting for key press
&  shell-async     shell command running asynchronously
```
for example `cmd wait %sleep 5` doesn't shut down lf with Ctrl+C

**Comment by Randoragon** [comment]
Well yeah, but no prefix allows as much freedom in terms of scripting as `$`. Piped shell is both visually and functionally completely different, so it doesn't solve the problem.

**Comment by gokcehan** [comment]
This is a duplicate for #162. Closing in favor of the other issue.
