### ISSUE TITLE
Command not found: rename

### ISSUE THREAD

**Issue by HygorCosta** [gokcehan/lf#334]
Guys a appreciate so much your work in lf.

I think my question is stupid, but I tried and searched a lot and not found an answer.

When a run rename (:rename old_name new_name),  show: 'command not found: rename'.

Any help for what I can do?

**Comment by LordRusk** [comment]
Run just ':rename' and it will show a prompt for renaming. It doesn't work like 'mv item /new/dir/item', this is because ':rename' is supposed to be bound to a key.

if you really want it like that, you could bind shell to something like 'enter', then type something like 'mv item newnamefor-item'.

**Comment by shabahengam** [comment]
rename command added in [r13](https://github.com/gokcehan/lf/releases/tag/r13).check your lf version (`lf -version`)

**Comment by HygorCosta** [comment]
That is it !! My version is r8.
