### ISSUE TITLE
Unrepresentable unicode character in prompt

### ISSUE THREAD

**Issue by agostonbarna** [gokcehan/lf#336]
![image](https://user-images.githubusercontent.com/5561396/79698021-66ca8b80-8286-11ea-8631-8697c209d775.png)

## Steps to reproduce

* Create directory structure with more characters than the available space on the terminal screen and change to this directory, e.g.:
  ```
  mkdir -p /tmp/$(printf '%s/' {a..z}_test) && cd $_
  ```
* Start `lf`
* There is an unpresentable unicode character � just before the directory structure in the prompt.

## Additional info

lf: https://github.com/gokcehan/lf/releases/download/r14/lf-linux-amd64.tar.gz

~/.config/lf/lfrc
```
set promptfmt "\033[34;1m%w/\033[0m\033[1m%f\033[0m"
```
I could also reproduce this with the default config (no lfrc file).

OS: Arch Linux

**Comment by gokcehan** [comment]
@agostonbarna This is now fixed with https://github.com/gokcehan/lf/commit/f8daa60b310fb656f729b014f08652cef28cb7bf . Thanks for reporting.

**Comment by agostonbarna** [comment]
Thanks @gokcehan for the fix, looks good to me now.
