### ISSUE TITLE
What exactly is cp-p (from the wiki)? 

### ISSUE THREAD

**Issue by BachoSeven** [gokcehan/lf#337]
Hi, I have been trying to undestand where the commands `cp-p` and `mv-p` come from in [this](https://github.com/gokcehan/lf/wiki/Integrations#cp-p) section of the Wiki, but neither google nor github gave me any hints so far. Am I missing something obvious? Is this a common utility?

**Comment by shabahengam** [comment]
just click on each title to see the source.
cp-p: Unix cp (and mv), with progress
https://github.com/Naheel-Azawy/cp-p

**Comment by BachoSeven** [comment]
Thank you, hadn't noticed the link.
