### ISSUE TITLE
Neovim is open in other window

### ISSUE THREAD

**Issue by juacq97** [gokcehan/lf#339]
When I open a text file in lf with neovim it opens on another window instead of the lf window, and the desired behaviour is open neovin in the same window, replacing lf. My open command is

```
cmd open ${{
    case $(file --mime-type "$f" -b) in
        text/*) $EDITOR $f;;
	audio/mpeg) mpv $f;;
	video/*) setsid mpv $f > /dev/null 2 2>&1 & ;;
	image/*) rifle_sxiv.sh $f;;
        *) for f in $f; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac 
}}
```

If I change the "$" for an "&" (for a sync open) the lf terminal flickers once and  neovim is opened on another window either; and the rest of the GUI programs like mpv or sxiv hangs the terminal until the GUI window is closed. Any way to keep the async open but open neovim in the same window? Thanks!

**Comment by Monirzadeh** [comment]
what is content of $EDITOR

**Comment by Monirzadeh** [comment]
it happen to me too
after i type this command in lf
```
shell touch filename
```
after this lf open all my text file in new terminal

**Comment by juacq97** [comment]
I created a new lfrc (with the same cmd_open) and now works. If the file is empty it does not open, however

**Comment by shabahengam** [comment]
lf doesn't know how to open a file that has no type and there is nothing wrong with that,IMO.
`touch` command doesn't create a text file.it just create an empty file.

![lf](https://user-images.githubusercontent.com/53096747/81806534-d6ecca00-9531-11ea-9bce-3814372b225b.png)

**Comment by Monirzadeh** [comment]
> lf doesn't know how to open a file that has no type and there is nothing wrong with that,IMO.
> `touch` command doesn't create a text file.it just create an empty file.
> 
> ![lf](https://user-images.githubusercontent.com/53096747/81806534-d6ecca00-9531-11ea-9bce-3814372b225b.png)

i know that
the problem is if it open with vim, why that open in new window.

**Comment by gokcehan** [comment]
@Monirzadeh I think it calls `OPENER` instead of `EDITOR` when the file is empty (hence not a text file). File openers are sometimes configured to open in a new window. You may either change the configuration of your opener, or change the default case in your `open` command to open the file with `EDITOR` or so.
