### ISSUE TITLE
some extension system to be added to lf

### ISSUE THREAD

**Issue by usama-makhzoum** [gokcehan/lf#340]
hi all
i think that lf should have some simple extension or plugin system, and not just shell scripts. something that can use libraries like lua, scheme or even go.

i was discussing with a friend about the topic. at the end we thoughr that golang is good for it. although go is not common for such purpose.

thank you

**Comment by skuzzymiglet** [comment]
imo, this would complicate the design quite a lot. One thing with Go plugins is that they'd have to be recompiled into the program, invalidating the idea of single binary. Shell can do most things desirable for a file manager. What kind of feature are you thinking of, @usama-makhzoum?

**Comment by usama-makhzoum** [comment]
actually i am trying to lf with the other file managers, and i saw some features can't be implemented without using external apis (such as dropbox intergration, although can be implemented in FUSE for instance). i am thinking of a simple plugin system that can use these external functionality, but maybe there is some alternate ideas can more compatible with simple and commandline-oriented file manager like lf (other than shell scripts, of course)

so what do you think of a go REPL?

**Comment by usama-makhzoum** [comment]
closed it by mistake

**Comment by skuzzymiglet** [comment]
Would this REPL be for plugins? I don't think that would be efficient.
Any plugins could be file-based, and Go code coould just be installed
and the binary run by `lf`. Having a full plugin system would be really
bloated and the program would depend on more programs than it has to.
tbh, I think this should remain a non-feature

**Comment by usama-makhzoum** [comment]
@skuzzymiglet you are right. a full plugin system is just a headache and not very effective (at least in the current stage). but i'm thinking of some basic functionality in addition to shell scripts. shell simply knows nothing about data types (other than strings). in the other hand, implementing the right plugin system can reduce complexity later: we can move many feature from the core of lf or left them maintained outside lf itself.

i think this is not too bad to use: https://github.com/progrium/go-extpoints

**Comment by gokcehan** [comment]
@usama-makhzoum You can call any language you want in your shell script. That is the way of the shell. What do you have in mind?
