### ISSUE TITLE
is there a way to change default config location?

### ISSUE THREAD

**Issue by usama-makhzoum** [gokcehan/lf#342]
i have to lf source clones, your clone and an other to make some expirements and i want to separate each lfrc but i can't find the right option.

**Comment by OliverLew** [comment]
I found a work around, you can temporarily start lf with `XDG_CONFIG_HOME=<path> lf` after you put the config in `<path>/lf/lfrc`. But it might affect other programs which depend on `$XDG_CONFIG_HOME`. So it is better if lf supports custom config location directly.

**Comment by gokcehan** [comment]
@OliverLew It only changes the value of `XDG_CONFIG_HOME` for `lf` command when you call it like that so it should not be a problem.

**Comment by OliverLew** [comment]
> @OliverLew It only changes the value of `XDG_CONFIG_HOME` for `lf` command when you call it like that so it should not be a problem.

I was concerning about programs spawned from within `lf` that depend on this environment variable. I confirmed it today with `htop` (it uses `$XDG_CONFIG_HOME/htop/htoprc` if the legacy `~/.htoprc` is unavailable) that:
1. The spawned shell has the new `XDG_CONFIG_HOME` (I changed it to other locations). If I run `htop` in the shell which I can start with `w` key, `htop` will ignore `.config/htop/htoprc` which it should use if `XDG_CONFIG_HOME` has not been changed when starting `lf`.
2. Any spawned programs directly by keybindings are also affected, e.g. start `htop` with this key mapping
   ```
   map t $ htop
   ```

**Comment by gokcehan** [comment]
How about this:

    alias lfa='lf -command "source /path/to/first/config"'
    alias lfb='lf -command "source /path/to/second/config"'

**Comment by OliverLew** [comment]
> How about this:
> 
> ```
> alias lfa='lf -command "source /path/to/first/config"'
> alias lfb='lf -command "source /path/to/second/config"'
> ```

This works great! I just realized I was using similar work around in mutt, also :)

**Comment by gokcehan** [comment]
Closing this issue. Feel free to leave any further comments.
