### ISSUE TITLE
Icon display error

### ISSUE THREAD

**Issue by diandianti** [gokcehan/lf#344]
I set lfrc as fllow：
`set icons on`
but the lf shows error
![image](https://user-images.githubusercontent.com/32973377/80662468-e268db80-8ac3-11ea-861c-a96a9fe71e7e.png)

 my zsh is well work with icons
![image](https://user-images.githubusercontent.com/32973377/80583662-17811980-8a43-11ea-8d07-8093cfb98cae.png)

**Comment by Provessor** [comment]
@diandianti are you using one of the Nerd Fonts? I believe neither of those characters are part of the Nerd Nonts (they are listed under the [Miscellaneous Symbols and Pictographs](https://www.unicode.org/charts/PDF/U1F300.pdf) which the Nerd Fonts don't implement). If that's the case, for the closest result without changing fonts, set the `LF_ICONS` environment variable globally (for a POSIX sh compatible shell):
```
export LF_ICONS="\
di=:\
fi=:\
ln=:\
or=:\
"
```
Or start lf as:
```
LF_ICONS="\
di=:\
fi=:\
ln=:\
or=:\
" lf
```
A much more comprehensive list is on the [wiki](https://github.com/gokcehan/lf/wiki/Icons) which sets different icons for many file types.

**Comment by diandianti** [comment]
> @diandianti are you using one of the Nerd Fonts? I believe neither of those characters are part of the Nerd Nonts (they are listed under the [Miscellaneous Symbols and Pictographs](https://www.unicode.org/charts/PDF/U1F300.pdf) which the Nerd Fonts don't implement). If that's the case, for the closest result without changing fonts, set the `LF_ICONS` environment variable globally (for a POSIX sh compatible shell):
> 
> ```
> export LF_ICONS="\
> di=:\
> fi=:\
> ln=:\
> or=:\
> "
> ```
> 
> Or start lf as:
> 
> ```
> LF_ICONS="\
> di=:\
> fi=:\
> ln=:\
> or=:\
> " lf
> ```
> 
> A much more comprehensive list is on the [wiki](https://github.com/gokcehan/lf/wiki/Icons) which sets different icons for many file types.

Thank you for your answers，I use the [Nerd Font](https://github.com/ryanoasis/nerd-fonts) as my terminal font.
