### ISSUE TITLE
icons: file for folder

### ISSUE THREAD

**Issue by itmitica** [gokcehan/lf#345]
Hi.

I get file icon for folders.

lf v14
win10x64
macOS 10.15.4

![image](https://user-images.githubusercontent.com/1570477/80824463-286a9000-8be7-11ea-99d4-9490b8e46a1b.png)

![image](https://user-images.githubusercontent.com/1570477/80830761-396cce80-8bf2-11ea-8b05-7fd47cbeda03.png)

**Comment by Monirzadeh** [comment]
can you post your LF_ICON variable?

**Comment by itmitica** [comment]
`di=:fi=:ln=:or=:ex=:*.c=:*.cc=:*.clj=:*.coffee=:*.cpp=:*.css=:*.d=:*.dart=:*.erl=:*.exs=:*.fs=:*.go=:*.h=:*.hh=:*.hpp=:*.hs=:*.html=:*.java=:*.jl=:*.js=:*.json=:*.lua=:*.md=:*.php=:*.pl=:*.pro=:*.py=:*.rb=:*.rs=:*.scala=:*.ts=:*.vim=:*.cmd=:*.ps1=:*.sh=:*.bash=:*.zsh=:*.fish=:*.tar=:*.tgz=:*.arc=:*.arj=:*.taz=:*.lha=:*.lz4=:*.lzh=:*.lzma=:*.tlz=:*.txz=:*.tzo=:*.t7z=:*.zip=:*.z=:*.dz=:*.gz=:*.lrz=:*.lz=:*.lzo=:*.xz=:*.zst=:*.tzst=:*.bz2=:*.bz=:*.tbz=:*.tbz2=:*.tz=:*.deb=:*.rpm=:*.jar=:*.war=:*.ear=:*.sar=:*.rar=:*.alz=:*.ace=:*.zoo=:*.cpio=:*.7z=:*.rz=:*.cab=:*.wim=:*.swm=:*.dwm=:*.esd=:*.jpg=:*.jpeg=:*.mjpg=:*.mjpeg=:*.gif=:*.bmp=:*.pbm=:*.pgm=:*.ppm=:*.tga=:*.xbm=:*.xpm=:*.tif=:*.tiff=:*.png=:*.svg=:*.svgz=:*.mng=:*.pcx=:*.mov=:*.mpg=:*.mpeg=:*.m2v=:*.mkv=:*.webm=:*.ogm=:*.mp4=:*.m4v=:*.mp4v=:*.vob=:*.qt=:*.nuv=:*.wmv=:*.asf=:*.rm=:*.rmvb=:*.flc=:*.avi=:*.fli=:*.flv=:*.gl=:*.dl=:*.xcf=:*.xwd=:*.yuv=:*.cgm=:*.emf=:*.ogv=:*.ogx=:*.aac=:*.au=:*.flac=:*.m4a=:*.mid=:*.midi=:*.mka=:*.mp3=:*.mpc=:*.ogg=:*.ra=:*.wav=:*.oga=:*.opus=:*.spx=:*.xspf=:*.pdf=:*.nix=:`

**Comment by Monirzadeh** [comment]
add `tw=🤝:\` and check do tmp icon change?

**Comment by itmitica** [comment]
![image](https://user-images.githubusercontent.com/1570477/81163361-4cd3bd00-8f97-11ea-9337-7aa9a9727c68.png)
![image](https://user-images.githubusercontent.com/1570477/81163429-66750480-8f97-11ea-9ec0-b2ea575b949c.png)
![image](https://user-images.githubusercontent.com/1570477/81163504-8f959500-8f97-11ea-883e-35f2779a35a3.png)

**Comment by Monirzadeh** [comment]
ok please do this step some where on your system (Home)
```
mkdir newFolder
chmod 777 newFolder
```
check icon again and  folder icon change?

**Comment by itmitica** [comment]
![image](https://user-images.githubusercontent.com/1570477/81165019-ee5c0e00-8f99-11ea-94f4-9637aa51bf43.png)

**Comment by Monirzadeh** [comment]
Ok
it is a bug that i report that on #265. you can read more detailed there
 #257 PR change the icon mechanism.
@gokcehan  is it possible to merge just icon part of  #257 to solve this problem?
 side note: i can't reproduce that on my system (Linux) . it control with `tw=🤝` on my machine

**Comment by itmitica** [comment]
I've edited the wiki. The issues is solved by adding the `dir` icon for the following: tw, st, ow, dt.

**Comment by Monirzadeh** [comment]
but problem exist for files with execution permission?
for example 
```
chmod +x image.jpg
```

**Comment by itmitica** [comment]
![image](https://user-images.githubusercontent.com/1570477/81347492-f19fe880-90c4-11ea-8855-0db00e869742.png)
