### ISSUE TITLE
Incorrect displacement of date/size when either 'number' or 'relativenumber' enabled

### ISSUE THREAD

**Issue by ivanp7** [gokcehan/lf#346]
Parts of date/size are not fitting the panel
![image](https://user-images.githubusercontent.com/3432246/80914664-b1073e80-8d55-11ea-9221-2e6049ea9df5.png)

**Comment by gotroyb127** [comment]
To fix this only 2 lines should have to be changed:
````diff
@@ -344,9 +347,9 @@ func (win *win) printDir(dir *dir, selections map[string]int, saves map[string]b
 diff --git a/ui.go b/ui.go
index 722f2ab..0c28327 100644
--- a/ui.go
+++ b/ui.go

 		if len(info) > 0 && win.w-2 > 2*len(info) {
 			if win.w-2 > w+len(info) {
-				s = runeSliceWidthRange(s, 0, win.w-3-len(info))
+				s = runeSliceWidthRange(s, 0, win.w-3-len(info)-lnwidth)
 			} else {
-				s = runeSliceWidthRange(s, 0, win.w-4-len(info))
+				s = runeSliceWidthRange(s, 0, win.w-4-len(info)-lnwidth)
 				s = append(s, '~')
 			}
 			for _, r := range info {
````
I did that and then recompiled and reinstalled lf.

(Actually I also changed a a little more): 
````diff
diff --git a/ui.go b/ui.go
index 722f2ab..a93d70b 100644
--- a/ui.go
+++ b/ui.go
@@ -275,6 +275,9 @@ func (win *win) printDir(dir *dir, selections map[string]int, saves map[string]b
 
 	if gOpts.number || gOpts.relativenumber {
 		lnwidth = 1
+		if gOpts.number && gOpts.relativenumber {
+			lnwidth++
+		}
 		for j := 10; j < len(dir.files); j *= 10 {
 			lnwidth++
 		}
@@ -287,13 +290,18 @@ func (win *win) printDir(dir *dir, selections map[string]int, saves map[string]b
 		if lnwidth > 0 {
 			var ln string
 
-			if gOpts.number && (!gOpts.relativenumber || i == dir.pos) {
+			if gOpts.number && (!gOpts.relativenumber) {
 				ln = fmt.Sprintf(lnformat, i+1+beg)
 			} else if gOpts.relativenumber {
-				if i < dir.pos {
+				switch {
+				case i < dir.pos:
 					ln = fmt.Sprintf(lnformat, dir.pos-i)
-				} else {
+				case i > dir.pos:
 					ln = fmt.Sprintf(lnformat, i-dir.pos)
+				case gOpts.number:
+					ln = fmt.Sprintf(fmt.Sprintf("%%%d.d ", lnwidth-1), i+1+beg)
+				default:
+					ln = ""
 				}
 			}

````
With the second, when both relativenumber and number options are set, the number of the selected file/folder is shifted left by a space to be spotted more easily (to emulate vim's behavior).

_P.S. I am not yet familiar with many git/github capabilities, so I appologize for not making a pull request officially._

![shot_2020-05-30(21:58:32)w](https://user-images.githubusercontent.com/62418822/83337065-0b49df80-a2c1-11ea-9195-4b647c5addb1.png)
![shot_2020-05-30(21:58:48)w](https://user-images.githubusercontent.com/62418822/83337066-0d13a300-a2c1-11ea-876b-12a7394e6397.png)
![shot_2020-05-30(22:00:48)w](https://user-images.githubusercontent.com/62418822/83337067-0d13a300-a2c1-11ea-85f9-e97f18861b1e.png)
