### ISSUE TITLE
lf -remote used in a mapped command, has no effect on win10\cmd

### ISSUE THREAD

**Issue by itmitica** [gokcehan/lf#347]
Hi.

Win10\cmd. 
lfv14.

**Example**

I y(ank) a file. The file has now the visual decoration.

I open up a new console.
`lf -remote "send clear"` and the selection is cleared.

If I try to map the send command, it has no effect.
```
cmd clearme ${{
    lf -remote "send clear"
}}

map c
map cm clearme
```

**Comment by gokcehan** [comment]
@itmitica I can't reproduce this on my machine. Also there is already a builtin clear command. What exactly is your use case?

**Comment by gokcehan** [comment]
@itmitica Sorry, I just realized you report this on win10. I tried it on linux. I need to try this on windows. But still what is the use case here?

**Comment by navakelvin** [comment]
The send command works on windows? I mean, would you expect it to work?
