### ISSUE TITLE
A way to download the latest release version. Add to wiki?

### ISSUE THREAD

**Issue by liuyigh** [gokcehan/lf#350]
I just discovered you can download the latest release using this link:

`https://github.com/gokcehan/lf/releases/latest/download/lf-darwin-amd64.tar.gz`

So we can always use the same link, and only need to change the plarform (linux, amd64). We don't need to go to the release page to check whether r14 is the latest version, or copy the link in the assets list.

This will be very helpful for people who do not use `homebrew`.

**Comment by liuyigh** [comment]
Since nobody objected, I have updated wiki as I proposed.

**Comment by gokcehan** [comment]
@liuyigh I remember latest download was not available before in the github api. I'm glad to hear they finally added this. Thanks for updating the wiki.

**Comment by liuyigh** [comment]
I am glad that you like this idea. And having no version number in the filename makes it possible! Thanks again for such great software!
