### ISSUE TITLE
$fx is not working on windows.

### ISSUE THREAD

**Issue by ok97465** [gokcehan/lf#351]
First of all, thank you for your effort.

I tried to create a simple script using $fx on windows. But $fx is not working.
So I replaced $fx to %fx%. %fx% shows only one filename. I expected that %fx% shows selected filenames.

To help you understand, I'm attaching a simple screenshot.

![fx](https://user-images.githubusercontent.com/22970578/81702806-ba578000-94a6-11ea-9711-32872081f89c.gif)

**Comment by gokcehan** [comment]
@ok97465 This may be related to having newline as the default file seperator. Can you change the value of `filesep` to see if it works?

**Comment by ok97465** [comment]
It works. Thank you very much.
