### ISSUE TITLE
panic: runtime error: invalid memory address

### ISSUE THREAD

**Issue by crivaronicolini** [gokcehan/lf#353]
Hi, just downloaded on a fresh install of Ubuntu 20.04,
full error is 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x491f3e]

goroutine 1 [running]:
os.(*Process).signal(0x0, 0x60f300, 0x71b110, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0x60f300, 0x71b110, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/exec.go:131 +0x3f
os.(*Process).kill(0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/exec_posix.go:54 +0x43
os.(*Process).Kill(0x0, 0xd, 0x5dd67d)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/exec.go:116 +0x2b
main.(*callExpr).eval(0xc0000616e0, 0xc00016c280, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gokcehan/lf/eval.go:1231 +0xa251
main.(*app).loop(0xc00016c280)
	/home/travis/gopath/src/github.com/gokcehan/lf/app.go:295 +0x644
main.run()
	/home/travis/gopath/src/github.com/gokcehan/lf/client.go:44 +0x2c8
main.main()
	/home/travis/gopath/src/github.com/gokcehan/lf/main.go:186 +0x999

```
What can I do to get it working again?
Thanks

**Comment by sreejeet** [comment]
Please describe what you were doing when this happened. How can this be reproduced?

**Comment by crivaronicolini** [comment]
Sorry for lack of context. 
Downloaded for amd64. Extracted the file and ran ./lf .
The screen gets drawn but does not respond to keys, the last line displays a cursor that goes from left to right rapidly.
The error message appears when i close with ctrl-c.

I've tried downloading older versions and other architectures but had no luck.
It was working on Ubuntu 19.04 two weeks ago.
Thanks!

**Comment by shabahengam** [comment]
I can't reproduce it.

**Comment by crivaronicolini** [comment]
Thanks for commenting, the problem seems to be caused by the line `set shell zsh`, setting the shell to bash makes it work perfectly.

**Comment by shabahengam** [comment]
I have `set shell zsh` in my `lfrc` too, but still can't reproduce it.

**Comment by crivaronicolini** [comment]
Excuse the derp, I used `zsh` and then started using `fish` in my prior installation, when I upgraded I didn't bother to reinstall `zsh` so that whole error was simply `zsh` not being found. Thanks for responding anyway.
