### ISSUE TITLE
Rename tags to match expected format

### ISSUE THREAD

**Issue by Provessor** [gokcehan/lf#355]
Go modules only recognise tags of the form v1.14.0 as the semantic version not r14. Changing this could make it nicer for package maintainers (namely the debian package I am attempting to make) and for users getting the package with `go get ...`.

**Comment by gokcehan** [comment]
@Provessor Since lf is an application and not a library, we don't expect any go modules to import lf. So I don't see any reason our versioning to be recognized as a module version. Am I missing something? What do you need for the debian package?

**Comment by Provessor** [comment]
@gokcehan This is more of a QoL change to consider than something that is needed. The practical difference is that it can be left up to go to fetch the latest release when building locally instead of either cloning the current master or checking the releases.

Since I made this issue I have changed how I build the Debian package so this would not make a difference for me but it could still help future packagers.

**Comment by Provessor** [comment]
This isn't a real problem and I don't have anything else to say, it was just a suggestion so I'm closing this.
