### ISSUE TITLE
access prefix argument in custom commands?

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#356]
Is there any way to access the numerical prefix argument inside custom commands?

For eg.

you can press `5j` and lf will move 5 files down in the current view. 

I've got a fzf command bound to `gc`:

```bash
cmd fzf_cd ${{
    res="$(find -L . -mindepth 1 \( -type d -o \( -type l -a -exec [ -d {} ] ';' \) \) -print |
             fzf --no-multi)"
    [ -n "$res" ] && lf -remote "send $id select $res"
}}
```

and I'd like it so that when I press, for eg. `5gc` the command only offers directories
upto a max depth of 5. So I need to be able to access that number argument, `5`, inside
my command.

Does lf pass the argument to the command as an environment variable (eg. `$count`)? and if not, can it?

**Comment by gokcehan** [comment]
This is a duplicate for #62 which unfortunately is not implemented yet. Closing the issue in favor of the other one.
