### ISSUE TITLE
Implement asynchronous event loop and remote commands

### ISSUE THREAD

**Issue by gokcehan** [gokcehan/lf#36]
I have tried to do this 3 or 4 times before but gave up midway since things were getting too complicated but I think this is the only way forward so I'm pushing this. With commits 1e0b558344e111d925028edab4f97d52df816824 and 2f574962bc450339888200ea792895e78fb2077c main event loop in `App.handleInp` now works asynchronously. This is the beginning of implementing remote commands sent directly from the server.

I will try to elaborate the rationale a little bit.
1. Currently yanked/deleted items are not shown in the ui which can get confusing (mentioned in #13). Some measures have already been taken for this problem but if we want to get the ui involved we need a way to notify all clients of changes.
2. Currently there is no way to change the internals in a custom command. This works for most cases but sometimes it becomes limiting. For example it would be nice to be able to display a message for some commands (e.g. when the new filename exists in `rename` command example). This way we can truly say lf is scriptable in a language independent way.
3. Currently there are no conditionals in the evaluator. Remote commands can be used as a workaround for this without inventing a new syntax for control flow.
4. There are currently some subtle ui glitches (e.g. resize window while reading command in a prompt). This is still not fixed but asynchronous events may be useful for this purpose.
5. Asynchronous event loop should help implement non-blocking file copying.
6. Asynchronous event loop should help implement non-blocking file previewing (mentioned in #5).
7. It should now be very straightforward to implement periodic renews. I am not a fan of this myself but I would accept a PR for this with a sensible default in case someone gets interested. I guess I should remove it from non-features section in the readme.
8. It should make hacking lf much more fun with imaginative ways :)

First aim is to make a functional and stable implementation. I am not too happy with the type switch creeping in the codebase and directly passing `App` in `UI.readExpr` but the way prompting works make these necessary for now. Currently there is only a `ping` command implemented for testing. It can be used with OpenBSD netcat as follows:

```
echo "ping" | nc -U /tmp/lf.${USER}.sock
```

A `send` command is the next step to send arbitrary commands. This command may take an optional client id to send the command to that client only. We can pass current client id as an exported varible (e.g. `$id`) for use in custom commands. Maybe this id can also be used to seperate log files of each client.

**Comment by KenjiTakahashi** [comment]
I meant to go through this some days ago, finally read it out today. My 2 cents on some points.

Ad. 2. Would it make sense to also have an interactive prompt on this? E.g. ask for a new filename after a failed `rename`. I don't know myself ATM, so it's just a wild thought.
Ad. 3. I'm not sure what this means in practice. @gokcehan could you elaborate a bit on what this is meant to bring us?
Ad. 7. Like I mentioned somewhere earlier, I still plan on implementing event based renews. This is fairly low on my list, though, so I cannot really say when that could happen.

Generally, this sounds very nice :-). Somewhat in line with "push notifications" I briefly mentioned in #13.

**Comment by gokcehan** [comment]
@KenjiTakahashi In theory, you should be able to ask for a new filename by sending a `push` command if the name exists (e.g. `echo "send $id push :rename<space>" | nc -U /tmp/lf.${USER}.sock`). For the conditionals, I don't have a good example in mind but I thought it could be useful if/when we start passing more internals through environmental variables. I don't know, I'm still half regretful that I started this. Some nasty concurrency bugs are popping up that I can't get my head around. I hope we can come up with a working solution for #13 so I can feel better about this.

**Comment by gokcehan** [comment]
@KenjiTakahashi Ok so here's a somewhat interesting use case for conditionals. Let's say you want to adjust the number of columns on startup based on the width of the attached terminal. You may achive this with something like:

    ${{
        w=$(tput cols)
        if [ $w -lt 80 ]; then
            echo "send $id set ratios 1:2" | nc -U /tmp/lf.${USER}.sock
        elif [ $w -lt 120 ]; then
            echo "send $id set ratios 1:2:3" | nc -U /tmp/lf.${USER}.sock
        else
            echo "send $id set ratios 1:2:3:4" | nc -U /tmp/lf.${USER}.sock
        fi
    }}

At some point we can pass `$w` variable from lf and maybe values of other options too (e.g. `$lf_scrolloff` or `$lf_previewer`).

**Comment by KenjiTakahashi** [comment]
Right, now I can see what you meant. Thanks for clarifications.

**Comment by gokcehan** [comment]
Most things mentioned here are already implemented and others are discusses in their own issues. Closing this issue now.
