### ISSUE TITLE
Include git info?

### ISSUE THREAD

**Issue by pgierz** [gokcehan/lf#360]
Hello,

I'm new to go, so I am not sure if this is something that I'd need to program or if there is already some switch I'm not seeing...

I'd like to turn on the info for size/date. This works well with:

```
set info size:time
```
(or just `za` in if you don't override it)

Now, the question: Can `lf` detect if I'm in a git repository, and tell me a small info about modified/untracked/added files? That'd be useful...

Cheers
Paul

**Comment by gokcehan** [comment]
@pgierz It has been mentioned before in #83 but noone worked on it. I think it's best to implement this as a more general customization feature as mentioned in the other issue so users can come up with different use cases. Closing this in favor of the other issue.
