### ISSUE TITLE
Is it possible to open multiple marked files?

### ISSUE THREAD

**Issue by keystroke3** [gokcehan/lf#362]
I have been trying to make an opener script to work with Lf. It seems that the when I mark several files and tigger the open command, only highlighted file is opened. I want to know if you can mark several files to open with a script.

**Comment by zoj613** [comment]
same here, I dont see anything in the docs about this

**Comment by gokcehan** [comment]
@zoj613 You can use `fs` or `fx` variables instead of `f`.
