### ISSUE TITLE
LF_ICONS to work as LS_COLORS

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#364]
The LS_COLORS variable can be used to set colors for files using its name, not only its extension.
Example:
```
export LS_COLORS='*README=38;5;220;1'
```
it only works if single quotes are used around (not double quotes)

LF_ICONS apparently (please correct me) can set icons only based on file type (di, fi, ex...) or extension.
How I tried it:
```
export LF_ICONS='*README=📃:di=📂:tw=📂:ow=📂:ex=💲:ln=🔗:fi=📄:or=❌:mi=❌:bd=:so=🧦:do=🚪:cd=🔤:*.txt=📃:*.tab=🎼:*.zip=📦:*.rar=📦:*.7z=📦:*.tar.gz=📦:*.deb=📦:*.mp3=🎵:*.opus=🎵:*.ogg=🎵:*.m4a=🎵:*.flac=🎵:*.aac=🎵:*.wav=🎵:*.mkv=🎥:*.mp4=🎥:*.mov=🎥:*.avi=🎥:*.wmv=🎥:*.webm=🎥:*.mpeg=🎥:*.3gp=🎥:*.png=📷:*.ico=📷:*.jpg=📷:*.jpeg=📷 :*.gif=📷:*.bmp=📷:*.svg=💢:*.bib=🎓:*.tex=📜:*.md=📜:*.1=📜:*.pdf=📗:*.djvu=📗:*.epub=📗:*.nfo=📃:*.info=📃:*.log=🔎:*.gpg=🔒:*.c=💻:*.py=💻:*.pl=💻:*.h=💻:*.m=➗:*.r=📊:*.R=📊:*.rmd=📊:*.Rmd=📊:*.xcf=🦊:*.html=🌎:*.css=🎨:*.iso=📀:*.img=📀:*.z64=🎮:*.v64=🎮:*.n64=🎮:*.ged=👪:*.diff=➕:*.part=💔:*.torrent=🔽'
```

**Comment by gokcehan** [comment]
@lucas-mior I think the color example you provide do work in `ls` but not `lf`, am I right? `LF_ICONS` and `LS_COLORS` should behave identical in this regard.

**Comment by lucas-mior** [comment]
That's correct.

**Comment by gokcehan** [comment]
@lucas-mior We implemented this by checking if the color map contains they key `*.ext` where `ext` is the file extension. Otherwise we would need to go all over the colormap to see if it matches the pattern. So this is not implemented for performance reasons.
