### ISSUE TITLE
display owner of file in the bottom line

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#365]
I notice there is a line with info about the current file at the bottom like this:
```
drwxr-xr-x 4.0K Fri May 29 04:12:59 2020
```
It would be useful to also show the owner (and group) of the file, like ```ls -l``` does.

**Comment by gokcehan** [comment]
@lucas-mior I agree it would be nice, but golang does not provide owner and group with stat calls, most likely due to cross-platform incompatibility.

**Comment by kmarius** [comment]
With the packages `os/user` and `syscall` the following works on linux

	var owner string
	var group string
	if stat, ok := curr.Sys().(*syscall.Stat_t); ok {
		if u, err := user.LookupId(fmt.Sprint(stat.Uid)); err == nil {
			owner = u.Username
		}
		if g, err := user.LookupGroupId(fmt.Sprint(stat.Gid)); err == nil {
			group = g.Name
		}
	}
    ...

I don't know how file ownership works on windows though.

**Comment by gokcehan** [comment]
@kmarius Thanks for the patch. I have now added these to the statline. I have also added link counts to mimic `ls -l` behavior. On windows, these should show up as empty for now until we figure out how it works.

**Comment by 4volodin** [comment]
on ubuntu 20.04 owner isn't being displayed
although
on raspberry pi4 owner are being displayed with the same config
