### ISSUE TITLE
Add a command to create new files and directories

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#368]
It could be nice to have these commands built-in.  Graphical file managers, such as [Dolphin], have short accesses to create new files, directories and symlinks.

My use case is using lf as a project drawer with [connect.kak].

The behaviour would be create and select, as implemented in #370.

[Dolphin]: https://dolphin.kde.org
[connect.kak]: https://github.com/alexherbo2/connect.kak

**Comment by gokcehan** [comment]
@alexherbo2 Create and select should be possible with custom commands already. I don't see any reason we should add these commands as built-in.
