### ISSUE TITLE
don't pause for user input when subprocess outputs nothing

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#375]
I've got a bulkrename command like so:

```
cmd bulkrename !{{
    dir=$(dirname "$f")
    if [ "$fs" = "" ]; then
        # when no marked files exist, use all files in the current
        # directory.
        fs=$(ls -1 --group-directories-first --quoting-style=literal -- "$dir")
    fi

    bulkrename -s "$f" -c "$dir" - <<< "$fs"
}}
```

sometimes I run the command just so that I can quickly navigate around the files in the cwd in my editor of choice. because it's defined using `!` once the command is done lf then pauses for user input and says `Press any key to continue`. I'd like lf to not bother waiting for input when the process doesn't output anything.

There's no point in waiting for user input if there's nothing for the user to inspect... though I might be stepping a bit too far and presupposing the users intentions here.

**Comment by gokcehan** [comment]
@mohkale You can use `$` command instead for this purpose.

**Comment by mohkale** [comment]
I'd still like to see the output... when there's something to see. Doesn't the `$` command run the process and then immediately return to lf regardless of what happens with the subprocess.

To clarify, 
- process produces output -> wait until I'm done inspecting the output.
- process produces no output -> don't bother waiting, go straight to lf.

is the kind of behavior I'm looking for here.

**Comment by gokcehan** [comment]
@mohkale I see. Lack of an output in unix tools is the conventional way to say to the user that no errors have occurred. Don't you think it would be a little confusing if we automatically skip "no output"?

**Comment by mohkale** [comment]
Yes, I agree. maybe if there was a way to signal to lf to not stop.

I can't think of a good solution at the moment so I suggest we just leave the issue open until someone can suggest one :yum:.

**Comment by gokcehan** [comment]
@mohkale Regardless we want this behavior or not, I don't think it is possible to implement. `$` and `!` commands pause termbox and leave the terminal to the running command. lf is not aware how these commands are using the terminal so I don't think there is a way to see if they output anything or not.

**Comment by mohkale** [comment]
I've found a decent way to get the affect I wan't. binding `map I !true` takes you back to the the shell so that you can inspect the last processes output and then easily return to lf. This seems to be a good enough fix for now so I'll close this issue.
