### ISSUE TITLE
inspect remote options at runtime

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#376]
At the moment there's no way to check the current value of an option set in an lf remote. This makes defining commands which toggle between two (or more) states depend on you remapping the bindings for the command depending on which state is currently active. see #296 

There should be a way to make lf echo out the current value of options.

Such as: `lf -remote "send $id show ratios"`, to show the current value of the ratios option.

**Comment by gokcehan** [comment]
@mohkale I was more thinking of exporting the values of options as environment variables in shell commands (e.g. `$lf_hidden`, `$lf_ratios`) which should be easy to implement too.
