### ISSUE TITLE
manipulate cut-lists from commands

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#378]
I want to have a command that can cut files and then paste them as symlinks instead of moving them. Simply marking them may have unintended behaviour with other commands so I'd like it if lf also exposed the cut and copied files as shell variables. maybe `$fm` and `$fc`.

Then I could implement the command as:

```
cmd paste-symlinks ${{
    if [ -z "$fm" ]; then
        lf -remote "send $id echoerr \"no files in cut list\""
        exit 1
    fi

    for f in "$fm"; do
        ln -s "$f" ./
    done

    lf -remote "send $id :clear-cuts"
}}
```

which would also require the ability to clear cuts independently of copies and marks.

thoughts?

**Comment by gokcehan** [comment]
@mohkale Cut and copied files are stored in the server and can be read using `lf -remote 'load'`.

**Comment by mohkale** [comment]
Yes, that solves the issue completely. Thnx for your time.
