### ISSUE TITLE
question: Will you continue to use termbox-go?

### ISSUE THREAD

**Issue by ciami7** [gokcehan/lf#380]
Or switch to tcell ?

**Comment by gokcehan** [comment]
@ciami7 There is an open issue #302 and it is also mentioned in a few more issues as well. However, it requires rewriting our ui code so we will stick with termbox for the while. Why are you asking?

**Comment by ciami7** [comment]
i just wanted to know? It will be very nice if you move your repo from github to a good website.
like git.sr.ht or gitlab.com

**Comment by ciami7** [comment]
thanks
