### ISSUE TITLE
Is a buildin-console like ranger passible?

### ISSUE THREAD

**Issue by 66RING** [gokcehan/lf#383]
ranger has a pretty buildin-console which do not mess up terminal out side.

![2020-06-15-105706_374x305_scrot](https://user-images.githubusercontent.com/49358576/84613883-0e66e180-aef7-11ea-9e74-0ca4fbc5499a.png)

below is my lf command, it kind of mess up my terminal.

![2020-06-15-104955_318x161_scrot](https://user-images.githubusercontent.com/49358576/84613769-a6b09680-aef6-11ea-9357-55ac5c7b3aec.png)
![2020-06-15-105112_330x92_scrot](https://user-images.githubusercontent.com/49358576/84613770-a87a5a00-aef6-11ea-9ffd-e8e3227a72df.png)

**Comment by Mati20187** [comment]
Try this:
```
cmd mkdir $mkdir -p "$(echo $* | tr ' ' '\ ')"
map md push :mkdir<space>
```
In this case you can either type `:mkdir example` or press _md_ and you'll be prompted to enter the directory name. Also, you can create directories with spaces in the name without worrying about backslashes because it automatically replaces spaces with `\ `.
