### ISSUE TITLE
Symlinked text files are opened in another terminal window

### ISSUE THREAD

**Issue by Mati20187** [gokcehan/lf#384]
Hi, I use GNU Stow to manage my dotfiles. It basically stores all of them in one folder and creates symlinks in places where a particular config file should be.
Normally, lf opens text files in the same window using neovim (I have the EDITOR variable set to nvim in .bashrc). 
However, when I try to open a symlink to a text file, lf opens a new xfce4-terminal window, even though my default terminal emulator is st (echo $TERM returns st-256color), and opens nvim with the file there. I'm not gonna paste my config here because I tested it both with and without the config file and also on a virtual machine and the issue persists. 
Is there any way to make lf handle symlinks to text files as though they were normal text files?

**Comment by gokcehan** [comment]
@Mati20187 It seems that our example `open` command does not follow links by default. You can use something along the following to be able to do what you want:

    cmd open ${{
        test -L $f && f=$(readlink -f $f)
        case $(file --mime-type $f -b) in
            text/*) $EDITOR $fx;;
            *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
        esac
    }}
