### ISSUE TITLE
request: set file ordering like ls

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#387]
Basically title. I know we can set the file ordering as natural, based on file extensions, time, etc., but I'd be nice to have an option to mimic the ordering of `ls`, which can be customized in various ways.

**Comment by gokcehan** [comment]
@n0ibe Can you be more specific? Which options of `ls` are you looking for?

**Comment by n0ibe** [comment]
Two options really (I'm using `set sortby ext`):

1. hidden directories should be listed before visible directories. It already works for regular files, i.e. `.a.txt` is listed before `a.txt`, but `.a` is listed after `a` (where both `.a` and `a` are directories). I'd be nice to have consistent ordering across all filetypes;

2. sort uppercase before lowercase, i.e. `A` then `B` then `a` then `b`.

**Comment by gokcehan** [comment]
Second point also mentioned in #320.
