### ISSUE TITLE
status line is empty on startup

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#388]
I don't know if this is a bug or the intended behaviour, but the status line is always empty on startup, instead of displaying the information of the current file
![2020:06:17@14:18:29](https://user-images.githubusercontent.com/59321248/84897149-75c29400-b0a5-11ea-9b2d-d609e51ced5c.png)

**Comment by gokcehan** [comment]
@n0ibe It is left empty in case there is an error in the configuration file to not override the error message.

**Comment by n0ibe** [comment]
Would it be possible to always display the statusline on startup, and only override that if there are problem with the config file (basically changing the order of what gets printed first)?

I know this is probably a minor detail, but it feels weird having to scroll up and down on startup to show the file infos.

**Comment by gokcehan** [comment]
@n0ibe It may be possible but I'm not sure. We might need to dig through the code to find a suitable place for this. Marking the issue as enhancement.

**Comment by joelim-work** [comment]
Apparently this is fixed in #994 and can be closed.
