### ISSUE TITLE
bug: files on external drive are not updated

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#389]
Whenever I delete, paste, rename, etc. a file on my external drive (formatted in exfat), I need to quit lf and reopen it to see the changes.

For example, after renaming a file from `a` to `b`, I still see the file as `a`. If I quit lf and reopen it, the file is correctly displayed as `b`.

Same with deleting files from that drive (I still see them after deleting them), and pasting them from my local disk to the drive (I don't see them even if they're there).

**Comment by gokcehan** [comment]
@n0ibe We are using time stamps to detect if there is a change in a directory and reload if necessary. I think some external drives skip timestamp updates to reduce writes, or maybe it is related to the filesystem itself. Can you confirm timestamps change after the operations you mention? If not, I don't think we can do anything about it. Maybe there is a way to enable timestamp updates in your drive somewhere.

**Comment by n0ibe** [comment]
I must admit I'm not familiar with the concept of timestamps; how would I check if they are changing?

I don't know if ranger uses the timestamps method as well, but it shows changes immediately without any problem.

**Comment by gokcehan** [comment]
@n0ibe You can do stat calls (e.g. `stat foo.txt`) before and after these operations to see if access/modify/change times change or not. Also, do you have `period` option set?

**Comment by n0ibe** [comment]
@gokcehan Unfortunately timestamps do not change after modifying a file, so it's not an `lf` problem. I've been googling how to enable timestamps update on an external hard drive, but nothing comes up :(

**Comment by gokcehan** [comment]
@n0ibe Forgot to mention, you can always call `reload` (default `<c-r>`) instead of restarting `lf` which doesn't check timestamps and force reloads all directories. As far as I remember, `period` option calls periodic `load` commands which uses timestamps so I'm guessing it is not working.

**Comment by n0ibe** [comment]
@gokcehan I have `set period 1`. Reloading with `<c-r>` works.
