### ISSUE TITLE
Combine two functions in one mapping

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#397]
I'd like to map `<esc>` to both `unselect` and `clear`. I tried the following three

````
map <esc> unselect clear
map <esc> unselect; clear
map <esc> unselect && clear
````
but none of them worked. How can I do this?

**Comment by SayantanRC** [comment]
Try this
```
map <esc> :{{
  unselect
  clear
}}
```

**Comment by gokcehan** [comment]
@n0ibe You can also do it within a single line as in your second example but you need a `:` so the statements on the line are grouped into one (i.e. `map <esc> :unselect; clear`).
