### ISSUE TITLE
Does anyone has real image preview like `ranger`?

### ISSUE THREAD

**Issue by sleeperzjf** [gokcehan/lf#398]
I just can't find any way to do that.

**Comment by gokcehan** [comment]
@sleeperzjf Unfortunately no. This is a duplicate for #134. Closing this in favor of the other issue.

**Comment by sleeperzjf** [comment]
Okay, and is there any plan that introduces this feature into `lf`,
'cause not only is it cool, but also very useful. And I think many
people have the same opinion.

**Comment by gokcehan** [comment]
@sleeperzjf There are no plans for anything. People work on things when they feel like it. Image previews are a little tricky to implement. There has been a few attempts so far and the latest attempt is at the fork [here](https://gitlab.com/Provessor/lfp). You may check that out to see if it works.

**Comment by sleeperzjf** [comment]
OK, thanks for all your work.
