### ISSUE TITLE
How to quit `lf` and get into current directory?

### ISSUE THREAD

**Issue by sleeperzjf** [gokcehan/lf#399]
If I launch `lf` in folder `a`, and get into folder `b` in `lf`, when I quit `lf`, I 'm in folder `a` again, how can I quit `lf` and get into folder `b` directly.

**Comment by MahouShoujoMivutilde** [comment]
It's in the [tutorial](https://github.com/gokcehan/lf/wiki/Tutorial#working-directory).

**Comment by sleeperzjf** [comment]
Oh, sorry, didn't notice that, thanks!!
