### ISSUE TITLE
Using bat as PAGER

### ISSUE THREAD

**Issue by ggsalas** [gokcehan/lf#402]
Hi, I'm using bat as pager, I have this on `~/.zshrc`: ```export PAGER="bat --paging=always"```

My question is if there is a way to avoid print all the files that I have seen when I press `i` because after close *lf* I have all the files printed on my console.

Thanks

**Comment by ggsalas** [comment]
I have found a fix reading the documentation :)
```
set previewer ~/.config/lf/pv.sh
map i $~/.config/lf/pv.sh $f | less -R
```

Works would be good integrate with `bat` because I think has a better syntax

**Comment by gokcehan** [comment]
@ggsalas There might be related information about this in #234 . Closing this issue. Feel free to add information about this to our wiki pages.
