### ISSUE TITLE
BUG: using shell-async commands creates zombie processes

### ISSUE THREAD

**Issue by gotroyb127** [gokcehan/lf#408]
The issue I had was that I used the `shell-async` commands to execute shell commands that controled `lf`'s behaviour through `lf -remote "send $id ..."`, which don't have any output (to stdout or stderr). The problem is that these become \<defunct\> when completed.

screenshot from htop: (notice the list of the green `ksh` terminated processes)
![shot_2020-07-13(12:13:05)w](https://user-images.githubusercontent.com/62418822/87290533-c4c5e280-c506-11ea-8df8-5144565157d1.png)
 
According to 'https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed' and 'https://stackoverflow.com/questions/36050503/golang-child-processes-become-zombies' `lf` needs to wait for the processes it spawns.

Goroutins can be used so that there is no need to stop the execution of the main program. 

In any case, zombie processes are erased, after `lf`'s termination.
With the implementation provided by #407 we can also provide information about the processes that exited with an error.

**Comment by gokcehan** [comment]
@gotroyb127 I don't remember why this was implemented the way it currently is but I don't see any problems with this approach.

Also related discussion in #359
