### ISSUE TITLE
[Feature request] Ranger's unicode_ellipsis alternative

### ISSUE THREAD

**Issue by YerinAlexey** [gokcehan/lf#413]
Ranger has [`unicode_ellipsis`](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L130) setting to use `…` character instead of `~` when truncating file names. I'd be really happy to see it there

**Comment by gokcehan** [comment]
@YerinAlexey This should not be difficult to implement, though I'm not sure why they use a boolean option for this. How about making it a general option to set an arbitrary character (e.g. `set truncatechar …`)?

If anyone is interested in working on this, I think you just need to replace `~` characters in `win.printDir` in `ui.go` with an option value.

**Comment by YerinAlexey** [comment]
@gokcehan, thanks! I'll try to implement this
