### ISSUE TITLE
Segfault in readExpr

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#42]
Happened to me several times right after starting `lf`, then disappeared some time later... I *think* it might have been caused by a leftover socket created with older version (before the async stuff started) of `lf`, but I'm not sure.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7dfc1]

goroutine 9 [running]:
panic(0x16c660, 0xc42000c0d0)
       	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
fmt.Fprintln(0x0, 0x0, 0xc420029ee8, 0x1, 0x1, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7.1/libexec/src/fmt/print.go:248 +0x61
main.readExpr.func1(0x0, 0x0, 0xc42006eba0)
       	/Users/kenji/languages/.go/src/github.com/gokcehan/lf/client.go:64 +0xff
created by main.readExpr
       	/Users/kenji/languages/.go/src/github.com/gokcehan/lf/client.go:76 +0x71
```

That's more of a side note, but one thing we can certainly do is check `client.go:64` for errors (yes, `fmt` functions return errors, but people always forget about it ;-)).

**Comment by gokcehan** [comment]
As a workaround for people having the same issue, the following should work most of the time:

    killall lf; rm /tmp/lf.${USER}.sock

But this is certainly not acceptable especially for those people who aren't involved in the development. I hate to break the workflow of people. And `lf` crashes borks the terminal as well which is super annoying.

@KenjiTakahashi It would be great if `fmt` errors can be used to fix this. I will try to take a look at it in the weekend.

**Comment by KenjiTakahashi** [comment]
I don't think that `fmt` error check would fix that particular segfault. It was probably the `conn` itself being `nil`. But it could prevent many other errors (e.g. IPC related). Perhaps we could also check `if conn != nil` before trying to send to it, as it seems that it is not warranted in other way.

**Comment by gokcehan** [comment]
This has not been happening lately since we don't change server protocol often these days. Closing this issue. Feel free to report here if this happens again.
