### ISSUE TITLE
Double slash in root directory

### ISSUE THREAD

**Issue by YerinAlexey** [gokcehan/lf#421]
# Steps to reproduce
 - `cd /`

# Expected behaviour
I see one slash in the prompt line

# Actual behaviour
I see two slashes in the prompt line

**Comment by gokcehan** [comment]
@YerinAlexey I think double slash is technically ok but it is unintended. Also, it causes problems in windows. I will just fix this by removing the slash in `promptfmt`. I'm not sure why you decided to close this.
