### ISSUE TITLE
read -s still shows characters

### ISSUE THREAD

**Issue by mvrozanti** [gokcehan/lf#422]
I'm using `set shell zsh`

```
cmd example %{{ 
    read -s pass # this shouldn't echo back my password, but it does
}}
```

I'm only in need of using `read` in that script because there's no other way to use stdin interactively with some other programs. 

My real use case is I want to use `gocryptfs` to mount an encrypted filesystem. It normally asks for password interactively, but it seems that lf does not allow for this behavior at the moment.

**Comment by YerinAlexey** [comment]
Likely, it's not `lf` problem. Password is printed with `read -s pass` but it's hidden with `sudo`

**Comment by mvrozanti** [comment]
read -s does not work that way. It really seems like it's lf's problem. I shouldn't need to use sudo for this.

**Comment by YerinAlexey** [comment]
> Not sure if it's relevant but in my tests I used `stty -echo` inside `cmd example` and it returns `stty: 'standard input': Inappropriate ioctl for device`

This error explains everything

**Comment by mvrozanti** [comment]
how so?

**Comment by YerinAlexey** [comment]
> how so?

It shows that `lf` runs the script without a TTY. But TTY is required for disabling echoing input, colorizing output and so on.

Compared: Node's `child_process` (no TTY) and `lf` (no TTY either):
![image](https://user-images.githubusercontent.com/51704055/87860149-c565db00-c943-11ea-8452-3e163868a489.png)

The same error but with my locale (I'm too lazy to set `LANG=en_US.UTF-8`)

**Comment by mvrozanti** [comment]
is there a fix?

**Comment by YerinAlexey** [comment]
> Should lf create a TTY then?

Yes, but only if `shell-pipe` is used

**Comment by gokcehan** [comment]
@mvrozanti Can you use `$` command for this purpose? `%` command is mostly a hack and it only works for simple commands.

**Comment by mvrozanti** [comment]
I ended up using `%` just so I have a way to interact with `gocryptfs`. My initial attempts with `$` showed that neither `read` or `gocryptfs` were iteractable.

**Comment by gokcehan** [comment]
@mvrozanti I don't see how that happens. It should be a regular tty when you use `$` commands. Maybe the command returns quickly so you think it doesn't work. For example, the following example should ask you for a password:

    cmd ask-pass !{{
        echo -n "pass:"
        read -s pass
        echo "your password is $pass"
    }}

Maybe you can try `!` to see the output before the command works. I don't know anything about `gocryptfs`.

**Comment by YerinAlexey** [comment]
> That cmd ask-pass doesn't wait for input. Not sure if this is related to the shell I'm using. Tried with `sh` and `bash` as well with no success.
> 
> > Maybe the command returns quickly so you think it doesn't work.
> 
> When using `$`, it (gocryptfs) does return quickly and outputs the following:
> 
> ```
> Reading Password from stdin
> Got empty Password from stdin
> ```
> 
> But it shouldn't return quickly. It should wait for interactive input.

@mvrozanti this is why you should use `!` instead of `$` as @gokcehan said

**Comment by mvrozanti** [comment]
As I said, `!` and `$` produce equal behavior for that example script

**Comment by YerinAlexey** [comment]
> `!` and `$` produce equal behavior for that example script `ask-pass`

But `!` works fine with `read -s pass`

**Comment by mvrozanti** [comment]
@YerinAlexey what shell did you test it with? For zsh, bash, sh, it doesn't seem to be the case.

**Comment by YerinAlexey** [comment]
> what shell did you test it with?

ZSH

**Comment by mvrozanti** [comment]
Well, now I'm thoroughly confused. I'm going to test all of this again with a clean lfrc later.
