### ISSUE TITLE
Make variable containing files in the current directory in the order that they're being displayed

### ISSUE THREAD

**Issue by mvrozanti** [gokcehan/lf#423]
This would solve the following use case:

Suppose you open a picture and you want to go to the next in the order that `lf` is displaying. We currently aren't really able to do that. But if we have this variable it would be possible.

A less desirable alternative solution would be to make a variable that contains the current sort type.

**Comment by mvrozanti** [comment]
Something like https://github.com/gokcehan/lf/pull/424

**Comment by gokcehan** [comment]
@mvrozanti You can use `invert` selection and `$fs` and `$fx` should contain the files in the displayed order.
