### ISSUE TITLE
Space after shell prompts

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#425]
Would it be possible to put a space after the prompt of the various shell commands (`shell`, `shell-pipe`, etc...) ? I think `$ echo "foo"` looks a bit cleaner than `$echo "foo"`.

 I'm using `map <enter> push $<space>` for now, but I'd be nice to be able to customize the prompts directly.

**Comment by gokcehan** [comment]
@n0ibe Spacing in those prompts mimics `:`, `/`, and `?` which don't usually have spaces. Don't you think it would be weird if we put spaces?

**Comment by n0ibe** [comment]
> Spacing in those prompts mimics `:`, `/`, and `?` which don't usually have spaces

That's true, but I think they're different. `:` and `/` mimic vim's command mode and search mode, so it's normal not to put a space after those. However `$` and `%` are used as prompts for shell commands, and shell prompts usually have a space after them (I don't think I've ever seen someone not put a space before their prompt, but I might very well be wrong).

**Comment by alexherbo2** [comment]
In the shell and [Kakoune] command prompt, space at the start is used to not store the command in the history.  The prompts do not display the prefix key, but have a title, displaying `<title>:`, without a space.

[Kakoune]: https://kakoune.org

**Comment by jabbalaci** [comment]
I would also need a space after '`$`'. There should be a config. setting where the prompt could be customized.

**Comment by danielrode** [comment]
A setting for this would certainly be aesthetically appealing to me as well. It would be nice to be able to manually set these prompts to any string in the config file.
