### ISSUE TITLE
Making files executable

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#426]
I'm using the following command to make files executables
````
cmd made_executable %{{
    chmod +x "$fx"
    lf -remote "send $id load"
}}
````
the command works, but I think `lf` doesn't detect that the file changed because the file permissions don't change and the file isn't highlighted in green. I have to reload manually with `<c-r>` to see the changes.

If I call `stat` before and after chmodding the file I see that the `Change` time has changed, so `lf` should be able to detect it.

**Comment by gokcehan** [comment]
@n0ibe It seems that `chmod` doesn't change the directory file so `load` doesn't trigger a reload. In this case, you should be using `reload` instead of `load`.

**Comment by n0ibe** [comment]
@gokcehan that works even though it's a little bit annoying since reloading makes the UI "flash" for a fraction of a second.

Btw, I'm surrounding `$fx` in quotation marks so that the function works even if the file has spaces in its name. However that means that selecting a bunch of files and chmodding them doesn't work anymore. Is it possible to do both at the same time?

**Comment by gokcehan** [comment]
@n0ibe See the note about `ifs` at the end of "Shell Commands" in the documentation.

**Comment by n0ibe** [comment]
@gokcehan Thanks; I think we can close the issue.
