### ISSUE TITLE
Can't cleanly abort change of sorting order

### ISSUE THREAD

**Issue by igorhub** [gokcehan/lf#428]
1. Type `s` to change sorting order.
2. Type `esc` to abort.

Result: the sorting menu aborts as it should, but the status bar shows error message: "unknown mapping: \<esc>".

**Comment by YerinAlexey** [comment]
You can map `<esc>` to `unselect`, for example. That will fix that message

**Comment by igorhub** [comment]
Thanks, added that to my `lfrc`.

**Comment by gokcehan** [comment]
I think this is a duplicate for #361. Looking at the code now, I think we're missing an early return in `<esc>` processing. Closing this in favor of the other issue.
