### ISSUE TITLE
Using multi-step commands (mark-load in my case) in custom commands

### ISSUE THREAD

**Issue by igorhub** [gokcehan/lf#430]
I'm trying to emulate tabs with tmux. I want to rename the current "tab" (tmux window) every time I change directory. For this, I wrote the following code:

    cmd open
    cmd tmux-aware-updir :{{
        updir
        &tmux rename-window $(basename $PWD)
    }}
    cmd tmux-aware-downdir :{{
        open
        &tmux rename-window $(basename $PWD)
    }}
    cmd tmux-aware-mark-load :{{
        mark-load
        &tmux rename-window $(basename $PWD)
    }}

`tmux-aware-updir` and `tmux-aware-downdir` work as planned, but `tmux-aware-mark-load` does not: `&tmux rename-window $(basename $PWD)` is called right after I press `'`.

Is this a bug?
If not, how do I delay execution of `tmux rename-window` till `mark-load` finishes?

**Comment by YerinAlexey** [comment]
@igorhub `mark-load` is asynchronous so `&tmux rename-window $(basename $PWD)` is run before mark is actually loaded

**Comment by igorhub** [comment]
Yes. That's exactly my problem with it.

The question is: is it desirable behavior? If so, asynchronous commands are unusable inside other commands, unless there is a workaround.

**Comment by YerinAlexey** [comment]
> The question is: is it desirable behavior?

I think, yes

My idea about this is introducing a hook that is called when directory changes (command like `on-cd`). There're other use cases for it: for example, show git status and pull changes when you are in the repo. This shouldn't be hard to implement

**Comment by YerinAlexey** [comment]
There's a solution for changing tmux window title:
```
cmd on-cd &tmux rename-window $(basename $PWD)
```

**Comment by igorhub** [comment]
> I think, yes

If that's the case, this is counterintuitive and should probably be described in documentation, along with the list of asynchronous build-ins which you can't use for your own commands. Then again, I see no logical reason for it, other than something to do with implementation.


> There's a solution for changing tmux window title:
> 
> ```
> cmd on-cd &tmux rename-window $(basename $PWD)
> ```

Thank you, that solves my problem in a much cleaner way! I searched the docs for something like that, could not find anything.
