### ISSUE TITLE
Can't select lf as default filepicker in Waterfox (Firefox)

### ISSUE THREAD

**Issue by reg-iii** [gokcehan/lf#432]
Hi,

Any chance we could prevent Firefox's awful GTK-based file manager from popping up when we save files? This is different from [this issue](https://github.com/gokcehan/lf/issues/214), as creating a desktop entry only allows for us to use lf when opening files, rather than saving them.

On a fresh copy of Firefox or Waterfox, simply press ctrl+o or save a file to be met with an unusable fullscreen instance of GTK's file manager.

**Comment by gokcehan** [comment]
@reg-iii Does firefox/waterfox have a mechanism to change the default? I'm not sure if this is possible. @doronbehar may know better.

**Comment by doronbehar** [comment]
> This is different from [this issue](https://github.com/gokcehan/lf/issues/214).

Indeed this is a different request, and I don't think what you are after is possible, without patching Firefox.
