### ISSUE TITLE
Image preview in wayland

### ISSUE THREAD

**Issue by NullSense** [gokcehan/lf#437]
The `draw_img.sh` image preview script does not work on wayland. (xdotool is at least one limitation)

**Comment by gokcehan** [comment]
Related #134

**Comment by YerinAlexey** [comment]
@NullSense If you're using Sway, you can try [my preview script](https://github.com/YerinAlexey/sway-previews). It'll work exactly as `draw_img.sh` script

**Comment by gokcehan** [comment]
Image preview patch is now merged. Image previews in wayland may now be implemented with a supporting terminal (e.g. kitty). Example scripts were available [here](https://gist.github.com/Provessor/e4ee757e6c424083ca3c6441fe6ab9ac) though I'm not sure if they are up to date. Feel free to add examples to the [Previews](https://github.com/gokcehan/lf/wiki/Previews) wiki page if you get it working.

**Comment by NullSense** [comment]
So kitty has its own implementation of imager previews, what about terminals like Alacritty?

**Comment by gokcehan** [comment]
@NullSense The issue on our side was about enabling the use of terminal image preview methods in our preview scripts. If you can't already display images in your terminal, there is nothing we can do about it. As far as I know, ueberzug does not support wayland so people rely on terminal support for images on wayland and alacritty does not support image previews so it's not possible.
