### ISSUE TITLE
Grep-colorized output and ANSI escape sequences

### ISSUE THREAD

**Issue by LorenzoCaresio** [gokcehan/lf#440]
Hi folks, 
I'm currently facing some issues while trying to display some grep-colorized output in the previewer. 

**Long story short**:  when displaying some text that got through `grep --color=always` the displayed output is broken (probably due to some ANSI escape sequences incorrectly interpreted).

The following is the same command executed on bash:
![image](https://user-images.githubusercontent.com/16455422/89420927-afbe2700-d733-11ea-9bfb-7d2b59fbf663.png)

And this is what I get on LF:
![image](https://user-images.githubusercontent.com/16455422/89421443-56a2c300-d734-11ea-8e40-0c03a7d2742e.png)

- As suggested [here](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797), `[K` has to be related to an erase function to clear the current line.
- I'm currently running LF on Alacritty on Arch, but on a MacBook with macOs Catalina+Terminal the behavior is identical.
- It is definitely something grep-related since an awk-based solution is displayed properly.

**Comment by nvllsvm** [comment]
Reproduced:
**Previewer**: `cat`
**Test file**: [testfile.txt](https://github.com/gokcehan/lf/files/5732851/testfile.txt)
**Expected**:
![image](https://user-images.githubusercontent.com/6550543/102950738-3a13e700-4499-11eb-83f3-eae78732595d.png)
**Result**:
![image](https://user-images.githubusercontent.com/6550543/102950720-308a7f00-4499-11eb-9cdc-c899b12200e5.png)


---

**Version**: r18
**OS**: Arch Linux
**Terminal**: alacritty 0.6.0 (04cbf767)

**Comment by gokcehan** [comment]
I have now pushed a fix to ignore `ESC[K` escape codes.

**Comment by nvllsvm** [comment]
Confirmed, thank you!

**Comment by gokcehan** [comment]
Now available in r23.
