### ISSUE TITLE
Cannot map <c-h> and <c-l> to cmd-left and cmd-right

### ISSUE THREAD

**Issue by phongvcao** [gokcehan/lf#442]
Hi,

I have the following mappings in my `lfrc` but unfortunately they don't work:

```
cmap <c-l> cmd-right
cmap <c-h> cmd-left
```

After this, whenever I press `<c-h>` it acts like pressing `<Backspace>` (Remove previous char). If I press `<c-l>` well nothing happens.

**Comment by gokcehan** [comment]
@phongvcao `<c-h>` is a terminal shortcut to send `<bs>` characters. You can see the name of the key sent to the terminal by checking the error message when you press a key before you assign it to a command (i.e. `unknown mapping: <bs>`). In your case, you should be using:

    cmap <c-l> cmd-right
    cmap <bs> cmd-left

I can't reproduce any issues with `<c-l>` mapping.

**Comment by phongvcao** [comment]
Thanks. That worked.
