### ISSUE TITLE
fzf fails when calling from lf

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#444]
I'm on macOS using zsh.

The steps to reproduce are the following:

1. have an `FZF_DEFAULT_COMMAND`, doesn't really matter what's in it, I have

```
export FZF_DEFAULT_COMMAND='fd'
```
in my `.zshenv` file;

2. open [lf](https://github.com/gokcehan/lf) via `$TERMINAL -e lf`, for example `alacritty -e lf`;

3. call fzf via `$fzf`. I get the error

![2020-08-11@22:45:15](https://user-images.githubusercontent.com/59321248/89947272-7c443680-dc24-11ea-85f9-70c57f168ad8.png)

Steps 1. and 2. are important: if I don't have a `FZF_DEFAULT_COMMAND` set everything works fine, same if I call `lf` from the command line instead of through `alacritty -e lf`.

I'm not sure if the issue is with `lf` or `fzf` so I'm posting this on both repos.

**Comment by n0ibe** [comment]
As suggested by junegunn [here](https://github.com/junegunn/fzf/issues/2133#issuecomment-672781392), the problem is that `lf` sets `SHELL=lf` when I call it via `alacritty -e` (doesn't happen when I call it via command line), as I checked with `$ echo $SHELL | fzf`:

![2020-08-12@13:01:40](https://user-images.githubusercontent.com/59321248/90008011-fe237680-dc9b-11ea-9481-aeb78ddd4c3e.png)

This seems to contradict what's written in the [doc](https://godoc.org/github.com/gokcehan/lf):
>  The following default values are set to the environmental variables on unix when they are not set or empty: 
> $OPENER  open      # macos
> $OPENER  xdg-open  # others
> $EDITOR  vi
> $PAGER   less
> $SHELL   sh

Explicitely setting the shell via `set shell zsh` or `set shell sh` in my `lfrc` doesn't seem to solve the problem.

**Comment by gokcehan** [comment]
@n0ibe `alacritty -e lf` doesn't seem to set `SHELL=lf` on my linux machine. Are you on a different platform?

There is no mechanism to set `SHELL=lf` implemented in `lf`. This is likely something to do with `alacritty`. Maybe there is a way set a different shell or export it as a variable in `alacritty`.

**Comment by n0ibe** [comment]
> Are you on a different platform?

@gokcehan Yep, I'm on macOS. It's probably something in the new 0.5.0 release of alacritty, don't know what though. Maybe
> Fallback to program specified in $SHELL variable on Linux/BSD if it is present

but I'm not on Linux/BSD and even if I set the `SHELL` the result is the same.

Using `alacritty -e sh -c "lf"` seems to solve the issue for now.
