### ISSUE TITLE
cd outside of lf

### ISSUE THREAD

**Issue by soykai** [gokcehan/lf#446]
I always found it a little annoying when I'm navigating with lf through my directories and then find myself wanting to return to the command line but stay in the directory I was last in. I managed to do it by accident one time, but I wasn't able to reproduce it and can't find anything on it in the documentation.
Can anybody tell me how to access this feature? Or does it not exist?

**Comment by gokcehan** [comment]
@soykai There is a default `w` keybinding to spawn a new shell in the current directory, and there is a script to change directory to the last directory (see [wiki](https://github.com/gokcehan/lf/wiki/Tutorial#working-directory)). Are these what you're looking for?

**Comment by soykai** [comment]
@gokcehan Yesss sir. Thank you much! That's awesome.
