### ISSUE TITLE
Fetch current hover selection?

### ISSUE THREAD

**Issue by bryttanybryant** [gokcehan/lf#449]
Is there a way to fetch the current (hover) selection in lf via the remote option?

What I would like is something along these lines:
```
$ lf -remote 'send print_hover_selection' 
/home/foobar/main.c
```
Where I am just hovering over main.c in lf. Also, if I am hovering over a directory, then it should return the directory path.

I am mainly looking for access to the current hover selection path in lf, so any over way to obtain this information would also be acceptable.

**Comment by YerinAlexey** [comment]
I don't think this should be a feature because you can get this path by saving `$f` with `lf -remote` and `cat`ing it out:
```sh
lf -remote 'send $echo $f > /tmp/lftmp'
hover_path="$(cat /tmp/lftmp)"
rm /tmp/lftmp

echo "You're hovering over $hover_path"
```

**Comment by bryttanybryant** [comment]
This is exactly what I was looking for. Thanks!
