### ISSUE TITLE
unicode character display error in windows10 powershell or windows terminal

### ISSUE THREAD

**Issue by zerobikappa** [gokcehan/lf#451]
If using `Powershell` or `Windows Terminal` to run `lf`, the console would insert whitespace between every unicode character.
For example, "テストフォルダ1" would be shown as "テ  ス  ト  フ  ォ  ル  ダ  1".
Windows cmd does not have this problem.
Is this `lf`'s issue or shall I report to microsoft?

**Comment by zerobikappa** [comment]
The files can be shown correctly when not using `lf`.
While using `lf`, only `cmd` with codepage 936 or 932 can have correct output.
`cmd` with `chcp 65001` would have this error, and `powershell` and `windows terminal` have the same issue no matter using which codepage.

**Comment by gokcehan** [comment]
@zerobikappa It seems that this issue is related to termbox (our terminal ui library), which is not maintained anymore. There is an ongoing PR #439 to replace termbox with tcell, which doesn't seem to have this problem.

**Comment by gokcehan** [comment]
@zerobikappa I have now pushed a new release r17 with the new tcell terminal library. Closing this issue. Thanks for reporting.
