### ISSUE TITLE
set file selection (like toggle)

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#454]
With `save` we can save the copied/cut file list but there doesn't seem to be an intuitive way of setting the toggled files. There's `:toggle` to toggle selection state of the current file, but I'd like to write a command to select all files in the current directory.

**Comment by gokcehan** [comment]
@mohkale `:toggle` can now take optional filenames as arguments. Can you not use something like `for f in *; do lf -remote "send $id toggle $f"; done`? You can also use `invert` command to implement a select all operation (e.g. `cmd select-all :unselect; invert`).

**Comment by mohkale** [comment]
Hmmmm... it doesn't seem to be working.

```
cmd select-files ${{
    lf -remote "$id" toggle "$f"
}}
```

If I map that to a key or run `:select-files` nothing seems to be happening. If I run `:toggle "$f"` that works, but it doesn't seem to work through remote.

**Comment by mohkale** [comment]
And [done](https://github.com/gokcehan/lf/wiki/Tips#select-all-files-or-directories-in-the-current-directory). Thnx for your help.
