### ISSUE TITLE
Why does this program wants to use the network ?

### ISSUE THREAD

**Issue by spapas** [gokcehan/lf#456]
Hello, I tried running lf.exe on my windows machine but it displayed the usual windows firewall popup that it wants to use the network etc (similar to this https://i.stack.imgur.com/a45bg.png - notice this screenshot for a random program). I think that this popup is displayed when a program tries to open a listening network socket so as to act as a server.

Could you please clarify why does lf.exe need be used as a network server? 

Thank you

**Comment by shabahengam** [comment]
check the [FAQ](https://github.com/gokcehan/lf/wiki/FAQ)
```lf uses a server/client architecture to share file selection among multiple instances.
lf launches a server process in the background when you run it the first time.
Server listens and records file selections so that you can copy files in one instance and paste in another.
```

**Comment by gokcehan** [comment]
@spapas We are using a server/client architecture to share the copy/cut files between multiple `lf` instances, and also implement remote commands so you can send commands back to `lf` in your shell commands. On unix, we are using unix socket files for this interprocess communication. Windows doesn't have an equivalent so we're using TCP sockets. Feel free to have a look at our [client.go](https://github.com/gokcehan/lf/blob/master/client.go) and [server.go](https://github.com/gokcehan/lf/blob/master/server.go) code to see what is being done.

I'm not too happy about this either. And it doesn't seem like a good idea to do this on public networks in terms of security, so windows is kind of right to warn you. There are plans to move copy/cut file selection from server to local files as discussed in #177. After this maybe we can add an option to disable server altogether for people who are not interested in multiple client use cases, though this would also mean remote commands will not be available either.

**Comment by spapas** [comment]
Thank you very much for the answers, using TCP sockets for IPC makes sense.

However,  from a peek at the source code I saw that your listen to all interfaces (bind to 0.0.0.0) unless I am mistaken (I am not familiar with the go programming language but I saw that by default it listens to :12345). 

That's probably why the Windows firewall asked me if I wanted to allow connections. Wouldn't it be possible to listen only to 127.0.0.1 to avoid the warning?

**Comment by gokcehan** [comment]
@spapas Oh, that would be great if it works. I had no idea. Thanks for the heads up. I will check this out next time I boot my windows. Marking the issue as a bug to catch my attention.

**Comment by spapas** [comment]
Excellent! Let's hope it works :)

**Comment by gokcehan** [comment]
@spapas This indeed seems to work. I have removed the old permission from the firewall settings, and with this change it doesn't ask for permission anymore. Thanks again for this idea.

**Comment by spapas** [comment]
You are welcome I'm glad it works!
