### ISSUE TITLE
(feature): ui recenter view

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#457]
I'm used to hitting `zt`, `zz` and `zb` in vim to recenter the current layout and I'd like `lf` to have that feature as well.

For example with a file list like this:

```
 d
 e
 f
 g
>h
 i
```

recenter-top will realign `lf` to show:

```
>h
 i
 l
 m
 n
```
rectenter-bottom will show:

```
 d
 e
 f
 g
>h
```

and recenter-middle will show:

```
 e
 f
 g
>h
 i
 j
 k
```

**Comment by mohkale** [comment]
now that I'm here. I'd also like to add the vim like `H`, `L` and `M` commands.

**Comment by joelim-work** [comment]
> now that I'm here. I'd also like to add the vim like `H`, `L` and `M` commands.

This was added in 01fe12b, so this issue can be closed.
