### ISSUE TITLE
LS_COLORS isn't applied in latest version

### ISSUE THREAD

**Issue by haomingw** [gokcehan/lf#460]
![lf](https://user-images.githubusercontent.com/31854632/92233475-a3eb8f00-eeb0-11ea-9849-9bb5abc89c4f.png)

I recently upgraded go to 1.15.1 and also updated lf. For my color theme in terminal, folders are blue and files are white, as you can see in the picture, lf applied the same color theme before. After the update, in `lf` all becomes white. I've read the docs https://godoc.org/github.com/gokcehan/lf#hdr-Colorschemes and my LS_COLORS is well set.

OS: Ubuntu 20.04
Default terminal

**Comment by gokcehan** [comment]
@haomingw Is [this](https://github.com/gokcehan/lf/pull/439#issuecomment-684879707) similar to what you experience? If so there is a solution [here](https://github.com/gokcehan/lf/pull/439#issuecomment-685054042).

**Comment by haomingw** [comment]
Yes it works. Thanks for your quick reply!

**Comment by gokcehan** [comment]
@haomingw No problem. Thanks for reporting.
