### ISSUE TITLE
High cpu usage running external commands

### ISSUE THREAD

**Issue by Naheel-Azawy** [gokcehan/lf#461]
I suspect something weird is going between the channels after the latest changes?

Anyway, I leave you with this video. Notice the CPU usage on the right after running `less` while on master. The same applies for any program. `less` is just an example.

https://youtu.be/3xsRSBLD6bc

**Comment by gokcehan** [comment]
@Naheel-Azawy Looks like this was introduced with the "fix" in #459 so it's part of that issue.

**Comment by Provessor** [comment]
@gokcehan `tcell.Screen.PollEvent()` returns nil immediately if `tcell.Screen.Fini()` has been called so its constantly looping in `ui.PollEvent()` and the `newUI()` goroutine.

**Comment by gokcehan** [comment]
@Provessor I now understand why a separate goroutine was needed. Looks like it was indeed the proper approach for this. I have now pushed your fix to master (moved error check to before an event is sent). Everything should be ok now. Closing both issues.

**Comment by Naheel-Azawy** [comment]
Nice! Thank you @Provessor and @gokcehan.
