### ISSUE TITLE
fzf commands stopped working

### ISSUE THREAD

**Issue by uzhne** [gokcehan/lf#464]
After 24f01f4988cfd96364a135c33bfeb9672a32794d all my commands that use fzf crash lf with `Failed to read /dev/tty`

Simplest case I could find is invoking `$true | fzf` from the prompt.

**Comment by uzhne** [comment]
`Failed to read /dev/tty` might be a message from fzf which is not always present. What happens is lf gets suspended and then when I run `fg` it resumes with `running shell: exit status 128` error in the status bar.

**Comment by uzhne** [comment]
Sorry, I just realized I could do a better job of stripping down my environment. Turns out running bash as an interactive shell was partially at fault. I want my `.bashrc` sourced, so I put `set shellopts '-i'` in my `lfrc`. Running fzf with a blank `lfrc` doesn't crash anymore, but gives a blank screen until I give fzf some keyboard input (e.g. start moving around with arrow keys.)

**Comment by gokcehan** [comment]
@uzhne I can't reproduce this. You need to be more clear about the steps to reproduce the problem.
