### ISSUE TITLE
`$[variable]` does not work on Windows

### ISSUE THREAD

**Issue by lucypero** [gokcehan/lf#466]
For example, `:cd $f ` outputs:

```cd: chdir C:\Users\Admin\AppData\Local\$: The system cannot find the file specified.```

**Comment by gokcehan** [comment]
@lucypero On windows `cmd.exe`, environmental variables are used as `%f%`. Documentation should be updated soon to make this more clear.

**Comment by lucypero** [comment]
That doesn't work either. `:cd %f%` outputs:

```cd: chdir C:\Users\Admin\AppData\Local\%: The system cannot find the file specified.  ```

**Comment by gokcehan** [comment]
@lucypero Sorry, I didn't realize you were trying this with `:cd` command, which is not a shell command so it doesn't work. You need to be using remote commads for this purpose, though your example doesn't make much sense to me. What's the point of such a command? Can't you just use `:open` instead of `:cd %f%`?

**Comment by lucypero** [comment]
`:open` doesn't do what I want. I just want to `cd` to the selected folder and return to `cmd`

**Comment by gokcehan** [comment]
@lucypero What do you mean by selected folder and returning to cmd? If you describe what you're trying in more detail, I can try to come up with an example command.

**Comment by lucypero** [comment]
I want to set the `pwd` to the selected folder in `lf` and return to the shell. As in, quit `lf`

**Comment by gokcehan** [comment]
@lucypero So then why does `:open; quit` not work? `:open` changes directory to the the selected directory (i.e. `$f`) when it's a directory.

**Comment by lucypero** [comment]
No, it doesn't work. That does not change the working directory.

**Comment by gokcehan** [comment]
@lucypero Have you seen the related section in the [tutorial](https://github.com/gokcehan/lf/wiki/Tutorial#working-directory)?

**Comment by lucypero** [comment]
No, I haven't. Now it makes sense. `lfcd.cmd` works well. Thank you.
