### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by doa379** [gokcehan/lf#470]
Interesting project. Can we get tabs (gn)? Would save running additional instances of the program.

**Comment by mohkale** [comment]
This has been asked and answered. See the [FAQ](https://github.com/gokcehan/lf/wiki/FAQ#how-is-lf-different-than-ranger) and also issue #153.

Long story short, people are used to having ways to spawn and tile terminals using their window manager (or terminal multiplexer) of choice. Re implementing a copy of such a feature would've added too much complexity for too little gain. Just create a new terminal and spawn lf in it. That way you also benefit from the same bindings to move between lf tabs that you do move between any other windows.

I suggest trying out tmux or screen and acclimating yourself to lf's client server approach. IMO it's noticeably better than a single instance with multiple tabs.

**Comment by doa379** [comment]
Which people are you referring to?

**Comment by mohkale** [comment]
Hmmm... bad wording on my part. Apologies. I meant developers commonly have their own workflow for this sort of thing. That's partially opinionated so it's probably not a good answer for this question. Issue #153 gives a much better description of why `lf` doesn't have tabs. Please read that instead.

**Comment by aleksfadini** [comment]
> This has been asked and answered. See the [FAQ](https://github.com/gokcehan/lf/wiki/FAQ#how-is-lf-different-than-ranger) and also issue #153.
> 
> Long story short, people are used to having ways to spawn and tile terminals using their window manager (or terminal multiplexer) of choice. Re implementing a copy of such a feature would've added too much complexity for too little gain. Just create a new terminal and spawn lf in it. That way you also benefit from the same bindings to move between lf tabs that you do move between any other windows.
> 
> I suggest trying out tmux or screen and acclimating yourself to lf's client server approach. IMO it's noticeably better than a single instance with multiple tabs.

Some tab functions cannot be replicated in tmux or tile windows.
Example:
```
In ranger, I can have:
 tab 1 opened on folder A,
 tab 2 opened on folder B, 
 tab 3 opened on folder C.

on tab 1, I can select file X from folder A and yank it
on tab 2, I can paste file X on folder B (this would not be possible on a separate instance of lf, it's possible on a ranger tab),
on tab 3, I can paste file X on folder C (this would not be possible on a separate instance of lf, it's possible on a ranger tab)
```

Imagine similar instances on more complicated workflows (ex: every 20 minues a new file appears in folder A, and I would like to tank it t folder B and C, a seamless workflow with tabs, much more convoluted with new instances).

I think failure to imagine these cases is leading lf to resist a feature that would be useful, and pushing away some ranger users like me, who might otherwise switch to a faster file manager, if they do not lose essential functions.
