### ISSUE TITLE
question: Is there a way i can output the last-dir-path to STDOUT

### ISSUE THREAD

**Issue by qlcom** [gokcehan/lf#472]

**Comment by Provessor** [comment]
How about:
```sh
lfcat () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        cat "$tmp"
        rm -f "$tmp"
    fi
}
```

**Comment by qlcom** [comment]
no. i want direct output to `stdout`. no temp file.

**Comment by Provessor** [comment]
@qlcom you can't view the path this way but it does work in a script
```sh
lf -last-dir-path="/dev/stdout" "$@"
```

**Comment by qlcom** [comment]
can't it have a option to just print it to `stdout`, like how `fzf` prints it's selection to `stdout`

**Comment by Provessor** [comment]
@qlcom it could but it doesn't at the moment.

You probably want to change this into a feature request and try to convince someone to do it.

**Comment by qlcom** [comment]
how can this happen? i don't understand. how can the author didn't thought about this? this is not how unix programs works.

**Comment by gokcehan** [comment]
@qlcom The reason this is missing is that `lf` allows shell commands to use stdout while running. If you were to use `lf` in a pipe or subprocess, and run a shell command while it is running, things can get ugly. So I'm not sure if this is a good idea, though there are ways to do this as discussed above if you insist on doing this. `fzf` is a great tool that has proved itself useful with the simple unix IO model, though there are many programs for which this model falls short. Most editors for example don't implement this, and I don't think it makes them less unixy. Not everything is meant to be used in pipes or subprocesses.

In any case, I'm not strictly against adding such an option, though I think we should figure out a way to prevent the use of shell commands with such an option. If you like to see this feature, feel free to reopen this issue to track it, and I can mark it as enhancement. It's probably a good idea to drop the angry customer attitude though.

**Comment by qlcom** [comment]
> It's probably a good idea to drop the angry customer attitude though.

yeah, i was a little angry.

Thank you for your answer.

**Comment by gokcehan** [comment]
Yet another workaround is to have a command like the following:

    map q :{{
        $printf $PWD
        quit
    }}

**Comment by Provessor** [comment]
@gokcehan a note if you decide to work on this: my option in https://github.com/gokcehan/lf/issues/472#issuecomment-694247467 would work as expected if the screen was closed before writing the directory path.
