### ISSUE TITLE
push sometimes skips characters

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#474]
I have a command in my config setup like this:

```
map -  :push :touch<space>

cmd touch %{{
    file="$@"

    if [ -n "$file" ]; then
        directory=$(dirname "$file")
        mkdir -p "$directory"
        touch "$file"
        lf -remote "send $id load"$'\n'"send $id select \"$file\""
    fi
}}
```

I've noticed that sometimes when I run the binding for `:touch`, `-`, the first character of the command doesn't get inserted. I.E. `lf` shows `:ouch` instead of `:touch`. I'm having a hard time reproducing it intentionally, but it's happened enough times that I think it warrants a new issue.

Has anyone else seen something like this?

**Comment by gokcehan** [comment]
@mohkale This is likely the same issue in #445 which is fixed recently in master but not r16. Can you confirm you are not using the latest master version?

**Comment by mohkale** [comment]
@gokcehan I tried upgrading to master, but I'll wait until the color issues (#473) are worked out before using it to make sure this is no longer an issue.

**Comment by mohkale** [comment]
Haven't encountered this issue so far. Safe to say this issue can be closed.
