### ISSUE TITLE
hiddenfiles doesn't hide all hidden files at startup

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#476]
I have this in my config:

```
set hiddenfiles .*:__pycache__:*.pyc:*.o:node_modules
```

If you:
- go to a directory 
- run `mkdir node_modules __pycache__ foo bar baz.o .bag` 
- start `lf`. 

`__pycache__`, `node_modules`, `baz.o` are not hidden. `.bar` is the only hidden entry in the directory. 

If you then run `:reload` then those directories are also hidden.

The output of my `lf -version` is empty, but I'm pretty sure my current build is from commit [1460f49](https://github.com/gokcehan/lf/commit/1460f49b3e158ec74bf7ec5388667c830581f4fc).

The output of `uname -a` for me is: `Linux mk-desktop 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux`

**Comment by gokcehan** [comment]
@mohkale I have now pushed a fix for this. We know check the value of `hiddenfiles` for directory updates. Thanks for reporting.
