### ISSUE TITLE
[ BUG] First directory is shown empty until reload

### ISSUE THREAD

**Issue by BachoSeven** [gokcehan/lf#478]
Upon entering `lf`, the first directory is shown as empty(when it is not), also after moving around; the only way to show the files is to `:reload`, i.e. `<c-r>`.
This behaviour is not consistent, meaning it happens most of the time, so perhaps it has something to do with asynchronous loading of files(?)
I suspect it could be related to the recent changes of lazy drawing in the ui (https://github.com/gokcehan/lf/commit/50dd374f77049c167952ca917148bd357f5731e8).

Edit: I noticed some even weirder behaviour by spamming `<c-r>` while on (not inside) any directory: it also makes the files inside it disappear, almost as if I were toggling them
to be hidden(but again not consistently).

**Comment by gokcehan** [comment]
@BachoSeven It seems that I forgot to initialize `hiddenfiles` for loading placeholder directories in 88749a3da1a28351b60fef78c4aa146809f403fd as part of the fix for #476. This should now be fixed with the latest commit. Thanks for reporting.

**Comment by BachoSeven** [comment]
The same issue appeared again with the latest commits. It might have something to do with `[d46ccfc](https://github.com/gokcehan/lf/commit/d46ccfc8054cd57441ba0a2d4c1519fe84dd9f72)`, since it's the exact same line of code which fixed the issue last time.

**Comment by gokcehan** [comment]
@BachoSeven My bad, sorry. It should now be fixed with the latest commit. Thanks for the heads up.
