### ISSUE TITLE
Make `put` command configurable

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#48]
I'd like to mimic the behavior of *ranger* in case a file with same name as the file being pasted exists. I.e. to rename the yanked file (even repeatedly) and then paste it.

It sounds like everybody could want to have a different behavior, so I'm proposing making the "paste" command configurable in the same way as the "open-file" command is (i.e. using `cmd open-file ...`).

**Comment by gokcehan** [comment]
This is also needed for windows support. As a workaround for now, I think you can create a custom command with the direct server communication trick and use it instead of the default paste, something along the line (not tested):

    cmd paste-custom ${{
        resp=$(echo 'load' | nc -U /tmp/lf.${USER}.sock)
        mode=$(echo $resp | cut -d' ' -f1)
        list=$(echo $resp | cut -d' ' -f2-)
        if [ $mode == 'copy' ]; then
            IFS=':'; cp -r $list $(pwd) # or whatever
            echo "copy these files: $list"
        elif [ $mode == 'move' ]; then
            IFS=':'; mv $list $(pwd) # or whatever
        fi
    }}

    map p
    map p paste-custom

**Comment by gokcehan** [comment]
This is now possible and examples are added to the documentation and tips wiki page. Closing this issue now.
