### ISSUE TITLE
Icons are '?' Marks Despite LF_ICONS being set

### ISSUE THREAD

**Issue by Mertzenich** [gokcehan/lf#481]
![pic-selected-201008-0923-01](https://user-images.githubusercontent.com/62816361/95471753-e38e1680-0947-11eb-8cd9-3e28720a7acb.png)

As you can see, despite $LF_ICONS being set the icons in lf are '?' marks.

**Comment by gokcehan** [comment]
@Mertzenich Can you paste the value of `$LF_ICONS` variable here so I can try it myself?
