### ISSUE TITLE
'open' command won't open 'text/plain'

### ISSUE THREAD

**Issue by fedoranvar** [gokcehan/lf#483]
When I'm trying to open text/plain file (mpv.conf)
![image](https://user-images.githubusercontent.com/52028706/95646177-39e18d80-0adf-11eb-9b48-10fb9b77d5d4.png)

 it opens it with xdg default application.
But if I'll comment line for opening '*' applications

![image](https://user-images.githubusercontent.com/52028706/95646131-d8212380-0ade-11eb-8c9f-dfb859d2423d.png)

 and will try to open mpv.conf, it will show an error in terminal

![image](https://user-images.githubusercontent.com/52028706/95646164-22a2a000-0adf-11eb-93f1-2d217c7826bc.png)

tried to rename file - same result.
lfrc - is a text/plain file but LF normally handles it.
So it's something wrong with file itself (mpv.conf) ?

**Comment by gokcehan** [comment]
@fedoranvar I can't really test this myself since you add them here as screenshots but are you not missing a `;` at the end of video line?

**Comment by fedoranvar** [comment]
@gokcehan indeed. It's solved the case.Thank you very much.
