### ISSUE TITLE
Run lf from a keybinding causes issues with icons and colors

### ISSUE THREAD

**Issue by juacq97** [gokcehan/lf#484]
When I run lf inside a terminal, I can see all the icons, the diferent colors and everything

![image](https://user-images.githubusercontent.com/7623047/95662639-98196b00-0af5-11eb-9087-2b8ae6988e98.png)
 
But when I run lf from a keybinding, I can't see some icons and colors:

![image](https://user-images.githubusercontent.com/7623047/95662650-b8e1c080-0af5-11eb-95c7-1ff84b866d65.png)

I tried many ways to launch lf: `st -e lf`; `st -e zsh -c lf` even launch a wrap script:

```bash
#! /usr/bin/zsh
source ~/.config/lf/LF_ICONS
lf
```

It works perfectly when launched from the terminal. I use `sxhkd` to manage my keybindings. Any idea of how I can solve this? Thanks!

**Comment by gokcehan** [comment]
@juacq97 You might have some related settings in your shell configuration file for when the shell is launched as interactive.

**Comment by StarTroop** [comment]
I'm not very familiar with zsh or all the possible locations to place environment variables, but back when I was using lightdm to log into my session, variables in .bashrc were not read by lf when launched from my i3 shortcut, but it worked when variables were placed in .profile. Now that I don't use any display manager, .bashrc works fine. 
So, I'm not sure exactly where would be most appropriate to place your variables to be used by lf, but I'm certain some experimenting would figure that out.
