### ISSUE TITLE
Zombie process when terminal window is closed

### ISSUE THREAD

**Issue by aduros** [gokcehan/lf#485]
When I close an xterm window running lf, the lf client process (not just the -server) stays running and only responds to kill -9. Quitting lf by using :quit doesn't have this problem.

Thanks :) Let me know if I can provide any more info to repro.

**Comment by gokcehan** [comment]
@aduros Thanks for reporting. I can reproduce this on my machine. This was first fixed in #305. It looks like it was regressed somewhere between r16 and r17, most likely due to tcell port.

**Comment by gokcehan** [comment]
@aduros This should now work as expected in master. Closing this issue. Feel free to leave further comments if the issue persists.
