### ISSUE TITLE
Problem when shutdown and multiple lf process stay active

### ISSUE THREAD

**Issue by Cyberdr3am** [gokcehan/lf#488]
Hi,

With the last release of lf my computer take very to turn off.
I post it here because the systemd log show me a problem with lf

oct. 18 02:52:44 cyberdr3am-pc systemd[1]: Stopped Session 2 of user cyberdr3am.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Failed with result 'timeout'.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43796 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43785 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43784 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43783 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43782 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43781 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43780 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43779 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43778 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33023 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33022 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33021 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33020 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33018 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33017 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33016 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27583 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27582 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27580 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27576 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27574 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27573 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27572 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27571 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 43777 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 33015 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Killing process 27570 (lf) with signal SIGKILL.
oct. 18 02:52:44 cyberdr3am-pc systemd[1]: session-2.scope: Stopping timed out. Killing.

I don't know why i have got this problem because i close lf all the time after using it

**Comment by Cyberdr3am** [comment]
I can't edit my first post.

If the problem is the same as https://github.com/gokcehan/lf/issues/485 please close this issues.

Thx

**Comment by gokcehan** [comment]
@Cyberdr3am It may or may not be the same issue. When you say you close lf all the time, do you close normally with `quit` or close the terminal instead?

**Comment by Cyberdr3am** [comment]
I start lf with
"st -e lf" on i3
To exit lf i use
"[con_id="__focused__" instance="^(?!dropdown_).*$"] kill" or just kill

I don't have any problem before r17

**Comment by gokcehan** [comment]
@Cyberdr3am Then it's likely the same issue. I have now pushed a fix for this. Closing this issue.
