### ISSUE TITLE
Periodic refresh does not work with sshfs mounting

### ISSUE THREAD

**Issue by hajdamak** [gokcehan/lf#489]
Mounting/unmounting FUSE drive using sshfs does not refresh content of the mounted directory in lf even if `set period 1` is set.
Refreshing works for regular operations like creating files or deleting them.

- lf r16
- Latest Arch

**Comment by gokcehan** [comment]
@hajdamak Option `period` simply calls `load` commands periodically, and `load` command checks modification times of directories to determine if directory should be refreshed or not. Can you make sure directory modification time is updated with your sshfs? There might be some related `mount` options about this.
