### ISSUE TITLE
opening Sc-im files in LF

### ISSUE THREAD

**Issue by Combowombo** [gokcehan/lf#494]
I use Sc-im as my spreadsheets editor and I'm trying to get lf to open .sc files with skim as default. Here's what I have in my lfrc so far, but it doesn't seem to work. I'm on MacOS

cmd open ${{
    case $(file --mime-type $f -b) in
        *.sc) scim $f & ;;
        text/*) $EDITOR $fx;;
        video/*) open -a mpv $f & ;;
        *) open $f & ;;
   esac
}}

**Comment by gokcehan** [comment]
@Combowombo `.sc` is not a mimetype so it doesn't work. And I don't think there is a mimetype for sc files. You can try matching for the file extension first as such:

```
cmd open ${{
    case $f in
        *.sc) scim $f & ;;
    esac
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        video/*) open -a mpv $f & ;;
        *) open $f & ;;
    esac
}}
```
