### ISSUE TITLE
Certain unicode characters are displayed improperly on lf.

### ISSUE THREAD

**Issue by crocket** [gokcehan/lf#496]
Create a file named `Iván Pérez Domı́nguez - 2018 - Extensible and Robust Functional Reactive Programming.pdf`

You may see `Ivan Perez Dominguez - 2018 - Extensible and Robust Functional Reactive Programming.pdf` instead on lf.

**Comment by gokcehan** [comment]
@crocket Thanks for reporting the issue. I have now pushed a fix for this. Closing this issue. Feel free to report if you still encounter this problem.

**Comment by crocket** [comment]
I tested the lastest commit. It seems fixed.

**Comment by gokcehan** [comment]
@crocket I had to use a different fix for this issue because of #565. The original example in your report still works for me. Feel free to report here again if you notice anything not working with the most recent change in master.
