### ISSUE TITLE
installed from aur and missing /etc/lf config files

### ISSUE THREAD

**Issue by Walkability** [gokcehan/lf#497]
docs say there should be /etc/lf/ config files, but they are not there. Is there somewhere else they may be?

**Comment by gokcehan** [comment]
@Walkability Doc meant configuration files can be put in those locations. 2 of the 3 aur packages seem to copy the file to `/usr/share/doc/lfrc.example`. If not you can copy the example from the repo `etc/lfrc.example` to one of the paths specified in the documentation.
