### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#498]
```
$ lf ~/doc/piecework/
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.(*dir).sel(0xc000126780, 0x0, 0x0, 0x27)
        /home/user/.cache/yay/lf-git/src/lf/nav.go:230 +0x1ba
main.(*app).loop(0xc000168200)
        /home/user/.cache/yay/lf-git/src/lf/app.go:259 +0x851
main.run()
        /home/user/.cache/yay/lf-git/src/lf/client.go:44 +0x356
main.main()
        /home/user/.cache/yay/lf-git/src/lf/main.go:186 +0xb8e
$ 
```
No ideas what's going on. I've then run it again (with exactly the same argument and in the same environment) and it works.

**Comment by mohkale** [comment]
Can confirm, I've also encountered this issue more than once.

**Comment by gokcehan** [comment]
@dumblob @mohkale What are the steps to reproduce this?

**Comment by mohkale** [comment]
@gokcehan I'm not sure. It seems to happen sponetaneously without any real reason. I try starting lf and it crashes. Then I try again in the same shell and it works. When I get a chance I'll try to find some concrete reproduction steps.

**Comment by dumblob** [comment]
@gokcehan same for me - I couldn't find any reproduces. It feels quite random. I won't have time to investigate as of now :cry:.

**Comment by shabahengam** [comment]
to reproduce the issue just open a directory and then press `Shift+G` immediately.
this directory shouldn't be opened before.I mean the directory contents shouldn't be cached before opening.
also if the directory contains a lot of files/dirs then it will be easier to reproduce the issue.

**Comment by gokcehan** [comment]
@shabahengam Thanks for the tip. I was able to reproduce it by adding `push G` in lfrc.

@dumblob @mohkale I have now pushed a fix for the crash. Thanks for reporting.
