### ISSUE TITLE
Custom Open with WSL-OPEN

### ISSUE THREAD

**Issue by tgaldi** [gokcehan/lf#500]
I'm modified my `lfrc` to use a custom open command: `cmd open $wsl-open "'$f'"`

https://github.com/4U6U57/wsl-open

I'm receiving an error that the path does not exist, for example with: `'/mnt/w/Test Folder/test.txt'`

Using wsl-open directly works: `wsl-open '/mnt/w/Test Folder/test.txt'`

![image](https://user-images.githubusercontent.com/17083706/98280769-dfb2db80-1f69-11eb-9299-778ad9ac0f98.png)

I'm new to this environment so I apologize if this is the wrong place to ask, but is something special happening in `lf` when using the opener that prevents the path from working with wsl-open?

Thanks.

**Comment by gokcehan** [comment]
@tgaldi It seems like you are making a quotation error. Why do you have both single and double quotes?

Also I don't know about `wsl-open` but if you are on Windows, note that your `shell` might be set to `cmd` so you might need to use something like `cmd open $wsl-open %f%`.

**Comment by tgaldi** [comment]
@gokcehan I put both so that the path would be surrounded by single quotes. This fixes issues with a directory with a space in it.

I'm using `wsl-open` because it converts a linux path to a windows path, so `/mnt/c` is converted to `C:/`
It then calls the proper windows shell to open the directory/file.

**Comment by gokcehan** [comment]
@tgaldi One of the quotes should be enough to escape spaces. When you use both single and double quotes, single quotes are considered part of the filename since every character is allowed in filenames on unix systems. Unless there is something specific about `wsl-open` that I don't know, you should try removing single quotes from your command.

**Comment by tgaldi** [comment]
Hmm ok maybe I'll need to ask on its git page. I tried with one set of quotes but its the same issue. Thanks for responding though!

![image](https://user-images.githubusercontent.com/17083706/98420625-98a21480-2055-11eb-86d2-064a8c2934db.png)
