### ISSUE TITLE
Time format in info

### ISSUE THREAD

**Issue by kikniknik** [gokcehan/lf#507]
When time is included in `info` option, "Jan _2 15:04" format is always used.

Wouldn't it be nicer if "Jan _2 15:04" format is used for recent dates (less than 6 months ago) and "Jan _2 2006" for the older ones, like `ls` does?

**Comment by gokcehan** [comment]
@kikniknik It sounds like a neat idea. Dates should be aligned properly, so we need two spaces before `2006` which already seems to be the case in `ls`.

**Comment by gokcehan** [comment]
@kikniknik I have now pushed a change as such. Thank you for the idea.
