### ISSUE TITLE
Adding shell-wait to a custom command.

### ISSUE THREAD

**Issue by nativepapaya** [gokcehan/lf#510]
I am trying to create a command that prints out the contents of a tar file by taking the existing extract command and just modifying it. It works but the information does not remain on screen, so I am trying to include a shell-wait option but it is not working. I thought I could just add ! within the nested command but it seems it is taken the ! literally and the shell is looking for a command literally named `!tar`. What's strange is that something like `map U !du -sh` works without issue.

That sort of leads to another question I had. Is it possible to execute custom commands with a shell-wait option? Like say `!extract`

![image](https://user-images.githubusercontent.com/72029903/100256875-4dbc4400-2f13-11eb-9678-b92ee284fda7.png)

**Comment by kmarius** [comment]
Everything inside `${{ ...}}` is executed by the shell. The `!` prefix is handled by `lf` so adding it inside does not make sense. You would have to change `${{` to `!{{` to achieve what you want. The better option would probably be keeping the `$` and piping into a pager, e.g. `tar -jtvf $f | less`.

**Comment by nativepapaya** [comment]
Thank you for the less suggestion. Much nicer than using shell-wait.
