### ISSUE TITLE
Wrong colors when using 24bit values in LS_COLORS

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#511]
If I set some filetype in LS_COLORS to use 24bit colors, those are not well reproduced in lf. For example, consider the following:
```
$ echo $LS_COLORS
di=1;38;2;69;133;136
```
which colors directories in `#458588`. ls respects that color, however the directories in lf are colored in a different shade of blue, specifically `#5f8787`.
![2020-Nov-28@15:48:55](https://user-images.githubusercontent.com/59321248/100518372-75204480-3191-11eb-882b-dead2dd345f5.png)

I'd expect this shouldn't be an issue now that lf supports 24bit colors

**Comment by MahouShoujoMivutilde** [comment]
From the man page

```
Second,  you  can  set the values of environmental variables mentioned above for
       fine grained customization. This is useful to change colors used  for  different
       file types and extensions. '$LS_COLORS' is more powerful than '$LSCOLORS' and it
       can be used even when GNU programs are not installed on the system. You can com‐
       bine  this  second method with the first method for best results. lf can also be
       configured to ignore your terminal theme and output colors  "as  they  were  in‐
       tended" by translating all numbered colors into a 24-bit output that matches the
       description;  this  can  be  enabled  by  setting   the   environment   variable
       '$TCELL_TRUECOLOR' to "on" (or any text except ""/nothing or "disable")
```

Launch lf with `env TCELL_TRUECOLOR=on lf`, then it will work as expected.

<details>
  <summary>e.g. with your example LS_COLORS</summary>
  
![29-11-2020-15_12_21](https://user-images.githubusercontent.com/14999778/100541537-a2cec180-3255-11eb-9480-2b16ee805617.png)
  
</details>


https://gitlab.com/Provessor/lfp/-/issues/14

**Comment by noib3** [comment]
@MahouShoujoMivutilde yes, that works. However, since terminal color are now ignored this means the colors in `promptfmt` have to be specified as rgb values, instead of just saying "blue" and letting the terminal handle what blue should look like.

This makes switching between multiple terminal themes annoying. I'd be nice to have the best of both words: letting "blue" be handled by the terminal, while also reproducing rgb colors correctly.

**Comment by MahouShoujoMivutilde** [comment]
Indeed, it would be.

Also, while you can fix promptfmt yourself, cut/copy/select colors are wrong color as well.

<details>
  <summary>right is the one with TCELL_TRUECOLOR=on</summary>

![29-11-2020-15_41_47](https://user-images.githubusercontent.com/14999778/100542288-f0e5c400-3259-11eb-822f-1baf99aa3981.jpg)
  
</details>

<details>
  <summary>lfp on tcell v2 works, however</summary>

  ![](https://user-images.githubusercontent.com/14999778/100542435-d95b0b00-325a-11eb-8c03-527a97f18f78.jpg)
  
</details>

So i guess it will be fixed, when lf will switch to tcell v2.

**Comment by gokcehan** [comment]
I have imported tcell/v2 patch from lfp a while ago. A new release r18 is now available with the patch.
