### ISSUE TITLE
Support for overwriting properties in LS_COLORS

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#513]
If `LS_COLORS` contains overwriting properties for the same file, ls handles the output correctly but lf doesn't. For example, let's say I set `LS_COLORS` to highlight all markdown files in yellow, with `README.md` also underlined:
```bash
LS_COLORS= "*.md=0;38;2;215;153;33:*README.md=4;38;2;215;153;33"
```
Then ls outputs
![2020-Nov-29@12:24:09](https://user-images.githubusercontent.com/59321248/100540551-41e7bf00-323e-11eb-9b60-aa801b7b499c.png)
but lf doesn't seem to care about a particular specification for `README.md` over the one for all other markdown files, and it outputs
![2020-Nov-29@12:24:29](https://user-images.githubusercontent.com/59321248/100540577-65ab0500-323e-11eb-860d-47577dc1cf78.png)

**Comment by gokcehan** [comment]
The behavior was changed at some point and I can' reproduce this issue anymore. Closing this issue. Feel free to repen if the issue persists.
