### ISSUE TITLE
[Question] How to display keyboard command cheat sheet?

### ISSUE THREAD

**Issue by Darthagnon** [gokcehan/lf#515]
New user here, on Windows, and trying to figure out how to use lf.

I saw in the Readme screenshots (e.g. below) that it is possible to display some form of cheat sheet showing mapped keyboard commands in the terminal. How do I enable this?

![screenshot](https://camo.githubusercontent.com/a786b5141d2a31b3e4b2f1e2719e0ed053e69c73fcc7a23d092c161ab3cc1fdd/687474703a2f2f692e696d6775722e636f6d2f44615455656e752e706e67)

### Couple other questions

How do I implement [the command scripts from the usage instructions](https://github.com/gokcehan/lf/wiki/Tips#show-progress-for-file-copying)? I'm guessing I need rsync in my PATH, but do I save the command as a BAT file in my PATH, too, or is there some config file or option in lf that I have to use?

Is it possible to change drives in lf? or do I need to quit every time and ```cd /d D:\```?

**Comment by gokcehan** [comment]
@Darthagnon Key mappings are displayed automatically when there are multiple matches. In the screenshot, one presses `g` to display those keybindings.

Using rsync copy for progress tip is pretty outdated. Progress during file copying is already shown in the builtin file copying. You would need to create a separate bat file on windows. I have added some configuration example files for windows to the repository.

You should be able to change drives with the builtin `cd` command.
