### ISSUE TITLE
delete (d) does nothing

### ISSUE THREAD

**Issue by masics** [gokcehan/lf#518]
When I press a 'd' button, the red mark appears near the file but the file stays. What exactly needs to be done to delete files?

**Comment by shabahengam** [comment]
`d` is for cut files(you can paste files with `p`)
if you want to delete a file use `delete` command or put something like this in your `lfrc`
```
# unmap default
map d
# cut / delete 
map dd cut
map dD delete
```
now when you press `d` you can choose what do you want to do with the file(cut or delete)
