### ISSUE TITLE
Can we start lfcd by default .

### ISSUE THREAD

**Issue by shahid777-py** [gokcehan/lf#520]
i wanna hit `q`  and enter into `(cd  $(pwd) )`  into directory . i  can only do it with `lfcd() in zsh`  but not with a keybind like `lf` usually initialize. for example  `super + r --> lf in sxhkd`, can i get `lfcd()` with a keybind in anyway . like `st -e "lfcd"  ` something like that.

**Comment by YerinAlexey** [comment]
You can use `st -e zsh -c lfcd`

**Comment by shahid777-py** [comment]
> You can use `st -e zsh -c lfcd`

It's bot working though, i dont't  know why.

**Comment by aduros** [comment]
The way I did this was to set an environment variable before starting the terminal, then check for that environment variable in zshrc.

keybind:
```shell
# Keybind from i3
_START_LFCD=1 xterm

# Or even fancier: start in the directory of the currently focused
# window using xcwd
cd "`xcwd`" && _START_LFCD=1 xterm
```

zshrc:
```shell
# This should be near the top of zshrc to display lf as soon as possible
# without loading the rest of the stuff in zshrc.
if [ "$_START_LFCD" ]; then
    unset _START_LFCD
    lfcd
fi
```

Then when you quit lf you should be back in the shell at the last lf
directory.

**Comment by shahid777-py** [comment]
> The way I did this was to set an environment variable before starting the terminal, then check for that environment variable in zshrc.
> 
> keybind:
> 
> ```shell
> # Keybind from i3
> _START_LFCD=1 xterm
> 
> # Or even fancier: start in the directory of the currently focused
> # window using xcwd
> cd "`xcwd`" && _START_LFCD=1 xterm
> ```
> 
> zshrc:
> 
> ```shell
> # This should be near the top of zshrc to display lf as soon as possible
> # without loading the rest of the stuff in zshrc.
> if [ "$_START_LFCD" ]; then
>     unset _START_LFCD
>     lfcd
> fi
> ```
> 
> Then when you quit lf you should be back in the shell at the last lf
> directory.

Where to puth these .

**Comment by shahid777-py** [comment]
> > The way I did this was to set an environment variable before starting the terminal, then check for that environment variable in zshrc.
> > keybind:
> > ```shell
> > # Keybind from i3
> > _START_LFCD=1 xterm
> > 
> > # Or even fancier: start in the directory of the currently focused
> > # window using xcwd
> > cd "`xcwd`" && _START_LFCD=1 xterm
> > ```
> > 
> > 
> > zshrc:
> > ```shell
> > # This should be near the top of zshrc to display lf as soon as possible
> > # without loading the rest of the stuff in zshrc.
> > if [ "$_START_LFCD" ]; then
> >     unset _START_LFCD
> >     lfcd
> > fi
> > ```
> > 
> > 
> > Then when you quit lf you should be back in the shell at the last lf
> > directory.
> 
> Where to puth these .

how can i use this keybind with other like sxhkd

**Comment by tenklo** [comment]
Had the same issue, I came up with a different solution. 
Basically I squeezed the lfcd function into a single line.

    #!/bin/sh`

    $TERMINAL -t "lf" -e bash -c 'tmp="$(mktemp)" && command lf -last-dir-path="$tmp" "$@" && test -f "$tmp" && dir="$(command cat "$tmp")" && rm -f "$tmp" && test -d "$dir" && cd "$dir" && exec $SHELL'

**Comment by shahid777-py** [comment]
> Had the same issue, I came up with a different solution.
> Basically I squeezed the lfcd function into a single line.
> 
> ```
> #!/bin/sh`
> 
> $TERMINAL -t "lf" -e bash -c 'tmp="$(mktemp)" && command lf -last-dir-path="$tmp" "$@" && test -f "$tmp" && dir="$(command cat "$tmp")" && rm -f "$tmp" && test -d "$dir" && cd "$dir" && exec $SHELL'
> ```

Nice Can u see any perfomance difference.

**Comment by shahid777-py** [comment]
> Had the same issue, I came up with a different solution.
> Basically I squeezed the lfcd function into a single line.
> 
> ```
> #!/bin/sh`
> 
> $TERMINAL -t "lf" -e bash -c 'tmp="$(mktemp)" && command lf -last-dir-path="$tmp" "$@" && test -f "$tmp" && dir="$(command cat "$tmp")" && rm -f "$tmp" && test -d "$dir" && cd "$dir" && exec $SHELL'
> ```

i tried it , is there any issue will occur if i use any different shell than bash in your script , i tried all shells it seems its working fine , and it exiting to my zsh.
