### ISSUE TITLE
No colors on macOS

### ISSUE THREAD

**Issue by yanzhang0219** [gokcehan/lf#526]
Hello,
macOS version 11.0.1
lf version: build the latest master using `go` command
Terminal I use: Alacritty, the latest build, alacritty 0.7.0-dev (4de1048)

Just now I updated lf and got an abnormal colorscheme. Before this, I was running lf on version r17 and its colors are normal.

Only a single color here
![image](https://user-images.githubusercontent.com/11582667/102173807-c8acb680-3e50-11eb-91ec-bd27e156eb31.png)

`LSCOLORS` is
![image](https://user-images.githubusercontent.com/11582667/102173829-d5c9a580-3e50-11eb-85fb-62826b7dfe9b.png)

Thank you.

**Comment by gokcehan** [comment]
@yanzhang0219 We had recently switched to tcell version 2 and it looks like I forgot to check BSD style LSCOLORS. I have now pushed a new commit to fix the issue. Hopefully everything is ok now. Thanks for reporting.

**Comment by yanzhang0219** [comment]
Perfect working confirmed. Thank you.
