### ISSUE TITLE
promptfmt %w expansion, but without trailing slash

### ISSUE THREAD

**Issue by aduros** [gokcehan/lf#528]
Would it be possible to get a promptfmt expansion that expands to the current directory exactly like %w, but doesn't include the trailing / character at the end? I'm trying to make lf's prompt match my shell prompt and that slash is triggering my OCD 😅

Thanks and I hope it's not too nit picky!

**Comment by gokcehan** [comment]
@aduros This was the case a while back ago but we have changed it because it was showing double `//` in the root folder. There is probably a way to make it work. I might consider merging such a patch if someone implements it.
