### ISSUE TITLE
How to run a command before lf exits?

### ISSUE THREAD

**Issue by aduros** [gokcehan/lf#529]
I made a quick lf command that mounts the selected zip using `archivemount` at a temporary directory and cds into it. So it's possible to copy/paste/view files inside of zips directly in lf, awesome! However, I don't know the best way to cleanly unmount the temporary directory. It would be nice if there was a special on-exit callback (similar to on-cd) that gets called by lf right before it closes. Then that could be used to unmount all zips that were previously mounted.

I think it may be possible to handle the cleanup outside of lf by wrapping it in a script:

```sh
lf_then_unmount () {
    lf "$@"
    # Cleanup logic here?
}
```

That would be a little more fiddly when dealing with multiple instances of lf though. Not to mention it wouldn't work when running lf directly.

**Comment by gokcehan** [comment]
@aduros I think I have seen someone implementing something like this in the integrations wiki page.

**Comment by aduros** [comment]
Perfect, thanks!

I extended it a bit with `trap` to cleanup even if the terminal window is closed.
