### ISSUE TITLE
-hidden option yields error: `Flag provided but not defined: -hidden`

### ISSUE THREAD

**Issue by irstacks** [gokcehan/lf#53]
Running on darwin from build.

**Comment by gokcehan** [comment]
@irstacks `hidden` is not a command line option but a regular runtime option. You can use it inside `lf` by typing something like `:set hidden` or put it in your configuration file. See the documentation for more info.

Closing this issue now. Feel free to write here if you still have problems with this.

**Comment by irstacks** [comment]
Got it. Thanks for your time!
