### ISSUE TITLE
TCELL_TRUECOLOR still required to get proper colors inside neovim terminal

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#533]
I'm using the vim-floaterm plugin by voldikss, and if I don't set the `TCELL_TRUECOLOR` env variable to 1 then the colors of files and directories are off.

`TCELL_TRUECOLOR` set to 1:
![2020-Dec-22@20:13:59](https://user-images.githubusercontent.com/59321248/102924707-5f512700-4492-11eb-9e82-73ae5c22b759.png)

`TCELL_TRUECOLOR` unset:
![2020-Dec-22@20:14:31](https://user-images.githubusercontent.com/59321248/102924724-6a0bbc00-4492-11eb-8eba-0faeec54f65d.png)

**Comment by gokcehan** [comment]
@noib3 I can't reproduce it on my machine. What is the value of `LS_COLORS`? Also what terminal are you using?

**Comment by noib3** [comment]
Turns out I wasn't setting the `g:terminal_color_` variables inside neovim. My bad.
