### ISSUE TITLE
Feature Request: softwrap: wrap lines that are too long to fit on the screen

### ISSUE THREAD

**Issue by danrobi11** [gokcehan/lf#534]
Cant read all the text in preview, lines are too long. If I zoom out it becomes too small, can barely read.
I havent found anything related to a wrap lines option. Is there any?
Thank you for lf.

**Comment by gokcehan** [comment]
@danrobi11 I'm afraid there is no such option. Preview window is meant to preview things. You can launch the file with your pager if you intend to read the content.

**Comment by danrobi11** [comment]
@gokcehan fair enough.

**Comment by gokcehan** [comment]
@danrobi11 I have thought about this again. I think such an option might be useful for some users. I would probably not use it myself so don't expect me to work on this anytime soon. If anyone bothers to implement such an option I might consider pulling to the base. If you are still interested in this, feel free to reopen the issue and someone might get interested in it.

Also related to this, maybe we should add a truncate characters to the end of lines for such long lines to avoid confusion (e.g. `~`). We already have an option `truncatechar` for filenames so I think we can use the value of this option in the preview pane as well.

**Comment by danrobi11** [comment]
@gokcehan Ok. Unfortunately, I've no coding skills.

**Comment by joelim-work** [comment]
With custom `previewer` scripts, this should be possible by using `fold` to wrap the file contents:

```shell
#!/bin/sh

fold -s -w $(($2 - 2)) "$1"
```
