### ISSUE TITLE
Integration with zoxide

### ISSUE THREAD

**Issue by yassinebridi** [gokcehan/lf#540]
[Zoxide](https://github.com/ajeetdsouza/zoxide) is an alternative to z.lua, autojump.
To just print the directory you want:
```bash
zq some_dir
```
or the expanded version
```bash
zoxide query "$@" some_dir
```

This is the closest i got it to work with lf:
```bash
cmd jump ${{
    printf "directory: "
    read -e dr
    dir=$(zoxide query "$@" $dr)
    lf -remote "send $id cd \"$dir\""
}}
map jp :jump
```
But this push you to a new window, instead of just the command prompt.
I tried to use just user input like this:
```bash
cmd jump ${{
    dir=$(zoxide query "$@" $1)
    lf -remote "send $id cd \"$dir\""
}}
map jp push :jump<space>
```
but it doesn't seem to do anything.

**Comment by kmarius** [comment]
The second command fails because `zoxide query "$@" "$1"` expands to `zoxide query somedir somedir`. You need to remove one of them.

**Comment by yassinebridi** [comment]
You are are right.
I got it working now, with a 2 liner
```
cmd az %lf -remote "send $id cd '$(zoxide query $1)'"
map a push :az<space>
```

**Comment by duganchen** [comment]
This should be fairly comparable to the zoxide plugins for other file managers:

`cmd z %lf -remote "send $id cd '$(zoxide query $1)'"

cmd zi ${{
    res="$(zoxide query -i "$1")"
    lf -remote "send $id cd \"$res\""
}}`
