### ISSUE TITLE
bug in LF_COLORS/LF_ICONS: a file named `di` is treated as a directory

### ISSUE THREAD

**Issue by gotroyb127** [gokcehan/lf#543]
Related 99d6b7fd449fd4c2b6aff989674a6bdd78a8eb5f.

After updating to current `master` branch, I noticed that a folder named `st` of mine
is displayed with the color and icon set with the pair `:st=...:` of LF_COLORS and LF_ICONS.
It is easy enough to verify that also a file named `di` is considered a directory, another named `ln` is displayed as a link, etc.

A quick fix I currently use:
````diff
diff --git a/colors.go b/colors.go
index 0efd156..a9ae138 100644
--- a/colors.go
+++ b/colors.go
@@ -233,14 +233,6 @@ func (sm styleMap) get(f *file) tcell.Style {
 		}
 	}
 
-	if val, ok := sm[f.Name()]; ok {
-		return val
-	}
-
-	if val, ok := sm[f.Name()]; ok {
-		return val
-	}
-
 	if val, ok := sm[filepath.Base(f.Name())+".*"]; ok {
 		return val
 	}
@@ -286,5 +278,9 @@ func (sm styleMap) get(f *file) tcell.Style {
 		return val
 	}
 
+	if val, ok := sm[f.Name()]; ok {
+		return val
+	}
+
 	return tcell.StyleDefault
 }
diff --git a/icons.go b/icons.go
index 2cb2d61..ee7fd85 100644
--- a/icons.go
+++ b/icons.go
@@ -74,10 +74,6 @@ func (im iconMap) get(f *file) string {
 		}
 	}
 
-	if val, ok := im[f.Name()]; ok {
-		return val
-	}
-
 	if val, ok := im[filepath.Base(f.Name())+".*"]; ok {
 		return val
 	}
@@ -123,5 +119,9 @@ func (im iconMap) get(f *file) string {
 		return val
 	}
 
+	if val, ok := im[f.Name()]; ok {
+		return val
+	}
+
 	return " "
 }

````
 (also in the above diff there is a block twice in a row which probably shouldn't be there)

Thank you.

**Comment by gokcehan** [comment]
@gotroyb127 We are matching from the most specific to least specific, so I have moved base and extensions matches after type as well. The current order is:

    1. Full Path (e.g. '~/.config/lf/lfrc')
    2. Dir Name  (e.g. '.git/') (only matches dirs with a trailing slash at the end)
    3. File Type (e.g. 'ln') (except 'fi')
    4. File Name (e.g. '.git')
    5. Base Name (e.g. 'README.*')
    6. Extension (e.g. '*.txt')
    7. Default   (i.e. 'fi')

Let's see if this will be any better.

Double same conditional was indeed unintended. Thanks for the heads up.

**Comment by gotroyb127** [comment]
Unfortunately, the issue persists, that is even when a file does not has the
characteristics of a type, e.g. `di`, but has it's name, it is considered to be of
that type.

As of now, the cause of the problem is that a file named, for example, `di` may
not match the corresponding type (it may not be a directory), though immediately
after that it matches `di` because its name is `di`.

Personally I see two possible ways of overcoming it:
1. We check `File Type` matching just before `File Name` and that one
as the last. (as in the diff above).
2. Otherwise, I think it is necessary to add a suffix to the filename (similar to
what `/` does with `Dir Name`) which may be `*`. In this way, with `LF_COLORS='di=35:di*=37'`
a file of type `di` matches the `35` and a file without type `di` but with name `di` matches `37`.
This should work both when the file is a directory and when it's not.

**Comment by gokcehan** [comment]
@gotroyb127 I'm not sure how the first suggestion would work with base/extension matching moved after type as well. Second suggestions seems like an interesting alternative. Let's try it for a while.
