### ISSUE TITLE
File names are not propery escaped.

### ISSUE THREAD

**Issue by FoundOne** [gokcehan/lf#547]
I can't perform any action on a file name containing spaces or any other special characters. I usually just do something like `$nvim "$f"` in order to open it, but the issue is that it does not work on the lf commands.

**Comment by gokcehan** [comment]
@FoundOne What do you mean by lf commands?

**Comment by FoundOne** [comment]
I meant  the integrated ones. Those who start with a colon, but after some testing I found out that I'm wrong. It's caused by my opener script. I'm sorry. It's my fault.

**Comment by gokcehan** [comment]
@FoundOne It's no problem. I'm closing the issue then.
