### ISSUE TITLE
About when to show the info columns (size when icons on, specifically)

### ISSUE THREAD

**Issue by OliverLew** [gokcehan/lf#548]
since "size" info column is only 4 characters wide, if you enable icons and only have about 9 columns for one pane, the sizes are still shown, resulting in the files to have only one character plus a `~` sign. It's hard to tell what files they are. This should be quite common since this happens for "80 columns terminal" + "1:2:3 ratios" + "set icons".

For me at least 4 characters of the file name is an acceptable lower limit. 

Reference:
> ```
>     info           []string  (default '')
> 
> List of information shown for directory items at the right side of pane.
> Currently supported information types are 'size', 'time', 'atime', and
> 'ctime'. Information is only shown when the pane width is more than twice
> the width of information.
> ```

![Screenshot_2021-01-02_22-20-56](https://user-images.githubusercontent.com/12032219/103459251-ddda7e00-4d48-11eb-89d8-3dd7f572f50e.png)

**Comment by gokcehan** [comment]
@OliverLew `icon` is added much later than the heuristic used to show `info`. I also realized enabling `number` makes things even worse. I have now changed the calculation to take icon and number options into account so it should behave more sensible now. Thanks for reporting.

**Comment by OliverLew** [comment]
That fixed it, thanks!
