### ISSUE TITLE
On terminal resize, new width previewer argument isn't updated

### ISSUE THREAD

**Issue by rafi** [gokcehan/lf#553]
When resizing terminal, the new width previewer argument isn't updated.

**Reproduce**
1. Create previewer script using [bat] and/or [chafa]:
```sh
#!/usr/bin/env bash
# previewer
FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"

WIDTH="$(( $WIDTH - 3))"

case "$(file -b --mime-type "${FILE}")" in
  image/*) chafa -s "${WIDTH}x" "${FILE}";;
  *) bat --paging=never --tabs=2 --wrap=auto --terminal-width "${WIDTH}" --line-range :"${HEIGHT}";;
esac
```
2. Run `lf`
3. Preview source-code with long-lines or wide image
4. Resize terminal
5. `lf` won't update width until <kbd>ctrl</kbd>+<kbd>r</kbd> is pressed for reload

[bat]: https://github.com/sharkdp/bat
[chafa]: https://github.com/hpjansson/chafa

**Comment by neeshy** [comment]
I can't reproduce this. Looking at your script, it seems like you're not exiting with a non-zero exit code. You need to do this, otherwise lf will cache the result of the preview. Using something like:
```sh
case "$(file -b --mime-type "${FILE}")" in
  image/*) chafa -s "${WIDTH}x" "${FILE}"; exit 1;;
  *) bat --paging=never --tabs=2 --wrap=auto --terminal-width "${WIDTH}" --line-range :"${HEIGHT}";;
esac
```
would work.

**Comment by rafi** [comment]
@neeshy thank you for clarifying the caching behavior. It works as expected when exiting with non-zero code.
