### ISSUE TITLE
The first keystroke after execution of a shell command has no response

### ISSUE THREAD

**Issue by yanzhang0219** [gokcehan/lf#555]
Hi,

After running any shell command with prefix `$` or `%`, the first keystroke does nothing. For example, in lf, I type `$ls`, and then I press `j` to move the selection downward, however, it does not work, and if I press `j` again, it works.

Is this behavior expected, or an issue?

Some necessary info:
macOS version: Big Sur 11.1 (the lastest)
lf version: the latest master (built from source)
shell: zsh 5.8
terminal: iTerm2

Thank you very much. 

Update:
Tested this on other terminals like Alacritty, kitty and Terminal.app, and I got the same issue.

**Comment by windowswithoutborders** [comment]
Experiencing the same issue. Also running macOS 11.1, and have never experienced this on arch linux. Regardless of the terminal I use (I use alacritty but this persists in the default mac terminal), if I enter lf and from there navigate to and open a document, say a text file that goes into another terminal based program, like a previewer, or an editor like nvim, the program will not take input until I make one initial key input, and from there the program will respond from there on out as usual. Worth noting there are no issues when opening a terminal based program from the command line. This is especially a nuisance with a program like nvim where I already know the sequence of inputs I want to put as soon as I enter a file, but of course the first input will never be accepted and it will derail my nvim workflow unless I'm mindful of it.

This occurs even without an lfrc file as well so it's not something related to my lf settings as far as I can tell. Appreciate any help. Thanks.

**Comment by grozan** [comment]
The same problem exists with Catalina as well, with `lf` installed with `brew`

Simple way to reproduce it for me

```
cmd dummy ${{
    r=$(echo -e "foo\nbar" | fzf)
    lf -remote "send $id echo $r"
}}
map Z :dummy
```

when fzf opens I see the 2 items. The first character I type, no matter which one, does nothing. It's only with the 2nd character onwards that I can start filtering the entries. Very annoying. Hopefully it can be fixed.

Thanks

**Comment by yanzhang0219** [comment]
Not sure whether this issue is related to the other issue I posted (https://github.com/gokcehan/lf/issues/554)

**Comment by gokcehan** [comment]
The issue is likely related to #554 which in turn is related to #480 and we are tracking the issue in the latter.

**Comment by gokcehan** [comment]
Feel free to reopen if the issue persists in version r23.

**Comment by yanzhang0219** [comment]
Thank you. I just now tested it and I confirm this bug is fixed. 👍
