### ISSUE TITLE
Parent dir column duplicating the current one when $PWD is appended by '/'

### ISSUE THREAD

**Issue by OliverLew** [gokcehan/lf#558]
Update: more accurate issue description.

The parent folder pane, if available, will be the same as current folder pane, if current `$PWD` is current directory appended by a slash, i.e., `PWD=$(pwd)/`.

I can reproduce it with current lf v26 with:
```
alias lf="PWD=\$(pwd)/ lf"
```

**Comment by gokcehan** [comment]
@OliverLew Is there a use case for setting `PWD` manually with a trailing slash?

**Comment by OliverLew** [comment]
@gokcehan I didn't set this pwd intentionally. Had this for a long time only figured out the exact case and reproduce yesterday. But I haven't figured out why this trailing slash is there, maybe due to my shell setup somewhere or something terminal emulator does, it's there by default when I start the terminal emulator unless I cd explicitly.

I just think what lf does here is unexpected behavior and if it's related to the trailing slash it should be fixed.
