### ISSUE TITLE
[Question] Display different icons for different filenames instead of filetypes

### ISSUE THREAD

**Issue by niceloaf** [gokcehan/lf#559]
Hello I was wondering how can I assign a specific icon for a specific filename? For example I want to assign a different icon to a file named 'EXAMPLE'.

**Comment by gokcehan** [comment]
@niceloaf We're still experimenting with color/icon configuration in master. If you are on master, the current way is to append `*` to the name if it's a file (i.e. `...:EXAMPLE*=E:...`), or append `/` if it's a dir (i.e. `...:EXAMPLE/=E:...`).

**Comment by niceloaf** [comment]
Well that explain a lot. Thanks!
