### ISSUE TITLE
ranger keybings for lf

### ISSUE THREAD

**Issue by westofer** [gokcehan/lf#563]
ranger-like keybings for lf, thought I should share: https://github.com/westofer/lf-ranger-keybingings
should this be in the wiki?

**Comment by gokcehan** [comment]
@westofer Sure, you can put them in the wiki. There is already a [Ranger](https://github.com/gokcehan/lf/wiki/Ranger) page for such things.

With a quick glance, I see you have things like:

    map du push :shell-wait<enter>du<space>--max-depth=1<space>-h<space>--apparent-size<enter>

And it can be simplified to:

    map du !du --max-depth=1 -h --apparent-size

**Comment by westofer** [comment]
thanks, will simplify things!

**Comment by joshcho** [comment]
How would you have :q be bound to :quit? It seems like an obvious thing to include by default.

**Comment by westofer** [comment]
@joshcho 

```
cmd q push quit

```

there could be more efficient ways that I am not aware off

**Comment by gokcehan** [comment]
@joshcho I think there is an extra `push` in @westofer 's example so it should instead be:

```
cmd q quit
```
