### ISSUE TITLE
Make search cyclic?

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#57]
I.e. go back to top with  next `n`, after reaching bottom. That's how it usually works (in vim, ranger, etc.).

**Comment by gokcehan** [comment]
@KenjiTakahashi that would be nice. We can add an option for it (it's called `wrapscan` in vim but `wrapsearch` or `searchwrap` would also be ok I think), or just make it the default behavior without an option. I'm fine with both. We should also consider whether it would be nice to have a message in the statusbar when wrapping occurs as in vim (e.g. search hit BOTTOM..). I find it helpful in vim but for lf it means blocking the file info.

**Comment by gokcehan** [comment]
Statusline is always utilized in lf so I guess it is better to leave "search hit BOTTOM" message out. Now that we have this working and `wrapscan` option is added, I'm closing this issue. Feel free to comment here if you like to add something.
