### ISSUE TITLE
Mouse selections are no longer possible

### ISSUE THREAD

**Issue by Limero** [gokcehan/lf#570]
I occasionally use my mouse to select and copy the name of files in lf and that is not possible since https://github.com/gokcehan/lf/commit/a13c14fb079b8062137cc7414b8d79c77aea1378

Trying to do a selection on text now does nothing. Is there any way to restore the previous behavior?

**Comment by gokcehan** [comment]
@Limero My terminal uses `shift` key to send mouse events to the terminal instead of the application. But I think maybe we should have an option `mouse` to enable/disable mouse events much like vim so shift key wouldn't be necessary by default.

**Comment by Limero** [comment]
Using shift works the way I want it to, thanks!

I agree with the option to disable mouse support, but I also like the potential of full mouse support in lf. With drag-to-select support like in vim, so mouse support can be enabled and selections be handled by the application instead.

**Comment by gokcehan** [comment]
@Limero I have now added a `mouse` option which is disabled by default.

As I said in #268 I'm not against more complicated mouse events but they may not be easy to implement and personally I'm not very interested in it myself.

**Comment by Limero** [comment]
> @Limero I have now added a `mouse` option which is disabled by default.
> 
> As I said in #268 I'm not against more complicated mouse events but they may not be easy to implement and personally I'm not very interested in it myself.

I think this is the best solution until someone works on better mouse support, so good call!

**Comment by BachoSeven** [comment]
@gokcehan I was able to test mouse mappings in the last release and they were working fine, but now that I updated to `r20` it looks like they don't anymore: I have set
```
map <m-down> down # Mouse mappings
map <m-up> up
```
in my `lfrc`, but now when I  scroll up and down using the mouse I get these errors, respectively
```
unknown mapping: <c-e>
```
and
```
unknown mapping: <c-y>
```
