### ISSUE TITLE
Feature request: Tree view

### ISSUE THREAD

**Issue by pkillnine** [gokcehan/lf#575]
I would like a file manager that is like the `tree` command except interactive. I found one today called `broot`, however it looks like the interface is a bit clunky. It would be neat to have lf support this tree-style view.

**Comment by gokcehan** [comment]
@pkillnine Try `ranger` with the `flat` option to see if it feels "clunky" as well.

**Comment by pkillnine** [comment]
How do I do that?

**Comment by gokcehan** [comment]
@pkillnine You know `ranger` is a file manager and it has a command named `flat` which we're still lacking. It's not exactly tree view but I think it's close in some ways. See the documentation for how the `flat` command works.
