### ISSUE TITLE
use lf's preview cache but still call for previewer

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#584]
Hello there,
I'm using a preview script for video files which both 
- displays an image (using `ueberzug`)
- outputs text (using `mediainfo`).

I made it so that it stores the output of `mediainfo` in a cache file, so that it doesn't need to recall the program every time
the previewer is called**¹**, instead it will just `cat` the contents of the `mediainfo` command out if the cache file exists.

As it turns out, it is pretty slow to do that (although still much faster than calling `mediainfo` every time).

Is it possible to make `lf` to use its cache (which makes looking into an previous looked file pretty smooth)
but still call the previewer (possibily with an extra argument so that text isn't output again), so that ueberzug can draw the image again?

Thanks.

**1** Of course, the previewer is only called again because it exits with an error code which is handled in the script.

**Comment by lucas-mior** [comment]
Just for clarification / extending the discussion:
What is really annoying is the flickering (the short "loading..." that shows up in the preview pane).
If instead the preview pane were only updated when the preview is ready (no "loading" screen),
I think the experience could be much better.
As an example, `fzf`does that (I tested it using the same script).
I don't mind `cat`'s slowness that much.

**Comment by gokcehan** [comment]
@lucas-mior I don't think it's possible. I'm not sure I understand what you're exactly trying to do though.

**Comment by lucas-mior** [comment]
Nevermind, I think I can llive with that hahaha.
