### ISSUE TITLE
"initializing screen: inappropriate ioctl for device" - ZSH keybinding stopped working.

### ISSUE THREAD

**Issue by alexeygumirov** [gokcehan/lf#585]
After recent update my ZSH widget stopped working from the key binding.
`ZSH` version `5.8`.
`LF` version is `21`.
OS - Manjaro,
OS kernel 5.11.1-1-MANJARO

When I press my keys (Ctrl+f), I got the following error:
```
 2021/03/02 14:37:36 initializing screen: inappropriate ioctl for device
```

Interestingly, I can launch `lf` normally with the command or even by calling the widget from the command line.

My **zsh** config for `lf` widget:
```
function _zle_lf() {
    lf .
}
zle -N _zle_lf
bindkey -M vicmd '^f' _zle_lf
bindkey -M viins '^f' _zle_lf
```

my `lfrc`:
```
set shell sh

set shellopts '-eu'

set ifs "\n"
set scrolloff 10

map <enter> shell

map x $$f
map X !$f

map o &mimeopen $f
map O $mimeopen --ask $f

cmd open ${{
    set -f
    case $f in
        *.docx|*.doc) lowriter $f;;
        *.drawio)
            drawio $f
            exit
            ;;
    esac
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        # image/*) fstone $fx;;
        video/*) mpv --force-window $fx >/dev/null 2> /dev/null &;;
        audio/*) deadbeef $fx >/dev/null 2> /dev/null &;;
        application/pdf) zathura --fork $f;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}

cmd trash ${{
    files=$(printf "$fx" | tr '\n' ';')
    while [ "$files" ]
    do
        file=${files%%;*}
        trash-put "$(basename "$file")"
        if [ "$files" = "$file" ]
        then
            files=''
        else
            files="${files#*;}"
        fi
    done
}}

cmd extract ${{
    set -f
    case $f in
        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
        *.tar.gz|*.tgz) tar xzvf $f;;
        *.tar.xz|*.txz) tar xJvf $f;;
        *.zip) unzip $f;;
        *.rar) unrar x $f;;
        *.7z) 7z x $f;;
    esac
}}

# compress current file or selected files with tar and gunzip
cmd tar ${{
    set -f
    mkdir $1
    cp -r $fx $1
    tar czf $1.tar.gz $1
    rm -rf $1
}}

# compress current file or selected files with zip
cmd zip ${{
    set -f
    mkdir $1
    cp -r $fx $1
    zip -r $1.zip $1
    rm -rf $1
}}

# { My  config

set hidden
set ratios 2:3:5
# set color256
set dircounts
set drawbox
set icons
set incsearch
set number
set previewer ~/.scripts/lf-preview
set preview
map i $~/.scripts/lf-preview "$f"
```

## Update

I checked `LF` version `20` and it works fine. I assume latest improvements regarding `stty` do cause some problems with `zsh`.

**Comment by gokcehan** [comment]
@alexeygumirov This only seems to fail with vi keybinding mode. `stty` change is not likely related as it only runs after `shell-wait` commands but this happens without running a shell command. But there has also been changes in tcell to use stdin instead of `/dev/tty` which is likely the cause. There might be some workarounds like changing the zsh binding mode or tty configuration before running lf somehow and restore them afterwards. We have been using such a workaround in `fish` which might be useful.

**Comment by alexeygumirov** [comment]
I rolled back to `LF` version `20` for now.
Could you please share which particular `tty` configuration parameters did you change for `fish`?
I would not like to change from VIM mode in my terminal. :)

**Comment by gokcehan** [comment]
@alexeygumirov For fish, I have been using this:

    bind \co 'set old_tty (stty -g); stty sane; lfcd; stty $old_tty; commandline -f repaint'

**Comment by alexeygumirov** [comment]
Thanks. This works for ZSH for now. But clear screen from errors after each run is not so convenient. So, I am just keeping it with and use `accept-line` instead.
Here is workaround for ZSH (thanks to @gokcehan for his workaround for `fish`):

```
function _zle_lf() {
    stty sane
    lf .
    zle accept-line
}
zle -N _zle_lf
bindkey -M vicmd '^f' _zle_lf
bindkey -M viins '^f' _zle_lf

**Comment by alexeygumirov** [comment]
Tried it, but did not work for me.

**Comment by brunoqkz** [comment]
I'm having the same problem. For now, I'm using this workaround:

```bash
[ "$(command -v lf)" ] && bindkey -s '\el' '^Ulfcd^M'
```

**Comment by alexeygumirov** [comment]
As a temporary solution I had to remove bindings for the `vim ins` mode and use simple binding like:
```
bindkey -s '\C-f' 'lf .\n'
```
