### ISSUE TITLE
Question: Shortcuts file

### ISSUE THREAD

**Issue by Kemmojo** [gokcehan/lf#589]
Hi.
Other then going for a complicated zsh scripty solution, i just wanted to ask if there is currently any way implemented to **load/source an external file**? ( shortcutsrc ) And use whats in there like it is in the **lfrc**.

**Following scenario:**
I have a bookmarks file containing things like this:

```bash
# Shortcut           Path                                                       Comment
cfa	             ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc		# aliases used by zsh (and potentially other shells)
cfp	             ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile
```

And a _script_ which gets started every time i _boot up my machine_, which takes the _files content and converts_ them to, for instance _zsh aliases_ and puts them into a _aliasrc file_, which is then _loaded by .zshrc_.

**Aliases would look like this:**

```bash
alias cfa="$EDITOR $HOME/.config}/shell/aliasrc"
```

So, my question would be, if there is some kind of method to "source" a "aliasrc" in lfs lfrc?

If my explanation is a little unclear, follow those links:
1. Bookmark file: [File](https://github.com/LukeSmithxyz/voidrice/blob/87c295003995ffdb071551ce0fe56307aadfdda8/.config/shell/bm-files#L14)
2. Source script that converts things: [Source](https://github.com/LukeSmithxyz/voidrice/blob/87c295003995ffdb071551ce0fe56307aadfdda8/.config/shell/profile#L143)
3. What the script does: [Script](https://github.com/LukeSmithxyz/voidrice/blob/87c295003995ffdb071551ce0fe56307aadfdda8/.local/bin/shortcuts#L33)
4. Output in `$HOME/.config/shell/shortcutsrc` ( example above )
5. Load aliasrc: into zsh for usage: [shortcuts](https://github.com/LukeSmithxyz/voidrice/blob/87c295003995ffdb071551ce0fe56307aadfdda8/.config/zsh/.zshrc#L16)

Thanks in advance and thanks for reading. 😄

**Comment by gokcehan** [comment]
@Kemmojo There is a `source` command in case you haven't seen it, though it only works with lfrc syntax and I'm not sure if that's what you want.

**Comment by Kemmojo** [comment]
Oh boy, yes, i totally missed that.
Now the bookmarks also get converted into lfrc readable format and put into a shortcuts files, which is then beeing sourced by lfrc.
And it works like a charm.

Thanks again, [that made my day](https://memegenerator.net/img/instances/64833240/made-my-day-you-have.jpg). :)
