### ISSUE TITLE
No option to change drive on Windows

### ISSUE THREAD

**Issue by jdfa** [gokcehan/lf#590]
Hi,

It is possible to inspect file system only on drive, which was used to start application. Nothing is shown in list of parent items when I am standing on. Here I am standing on root of D: drive and can't switch to C: drive:

![image](https://user-images.githubusercontent.com/14260814/111086968-c0374b00-8527-11eb-8948-6ac7971a6205.png)

To inspect content on other drive I am forced to rerun application from other location.

I was also looking for some complex solution with custom commands but didn't succeed with that.

**Comment by gokcehan** [comment]
@jdfa You can switch to different volumes with the builtin `cd` command. The trick is either to escape `\` in the volume name by doubling it as `\\` or simply use quotes as such:

    cd C:\\
    cd 'C:\'

You can also assign keybindings for these:

    map gc cd 'C:\'
    map gd cd 'D:\'

I think maybe we should add these keybindings to the example configuration file.

**Comment by jdfa** [comment]
@gokcehan 

Oh, I see. It works for me. 

Not sure is it applicable for Linux OS but I feel that visualization of existing drives can be nice improvement for Windows.
In case of some dynamic drive it will require two commands to change location since at first it will be needed to request existing drives and then change location. This might be the case for external hard drives or flash drives.

**Comment by gokcehan** [comment]
@jdfa That would be nice but I doubt it's possible. Windows does not have a single root filesystem so `C:\` is indeed a root folder and it does not have a parent folder to show in the left column. This is similar to how it works in `cmd` and `powershell` as well. For example, you can not go up a folder with `cd ..` if you are in a root folder `C:\`. I would be interested if someone comes up with an easy way to add something like this. In the meantime, as a workaround, it might be possible to come up with a custom command to list all volumes and prompt for a letter to change into.
