### ISSUE TITLE
Is it possible to open a currently selected file with vim?

### ISSUE THREAD

**Issue by elbek** [gokcehan/lf#593]
Once I select the file is there a command where I can run the vim (or any editor) by passing the currently selected file?

**Comment by kdkasad** [comment]
This is explained in both the wiki and the man page. Here's an example:
https://github.com/gokcehan/lf/blob/master/etc/lfrc.example#L34

**Comment by OliverLew** [comment]
`e` by default open the current (not selected tho) in default `$EDITOR`

https://github.com/gokcehan/lf/blob/06bf58851b209516cc87a4947a696c7f82b22ccb/lf.1#L170-L177

I remapped it like this so the selected files will be opened if there is any (works fine so far):

```
map e $$EDITOR $fx
```

**Comment by elbek** [comment]
Do we know where the editor variable is set?

**Comment by kdkasad** [comment]
> Do we know where the editor variable is set?

It can be set anywhere. If you use bash, then probably in `~/.bashrc`.
