### ISSUE TITLE
How to debug image previews not working

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#594]
version: r21
os: NixOS 20.09
terminal: alacritty 0.5.0
ueberzug version: 18.1.9

I followed the steps exactly as reported in the [wiki](https://github.com/gokcehan/lf/wiki/Previews#with-%C3%9Cberzug) page for image previews but I can't get them to work. I tried all of the alternative scripts reported in that page like lfimg and stpv, and none of them seem to work.

Since I'm not familiar with how ueberzug image previews work under the hood, how can I debug it? I get no errors when I launch lf via the wrapper script, but when I try to preview an image the preview pane is totally blank

**Comment by OliverLew** [comment]
Maybe try the shell script from [ueberzug](https://github.com/seebye/ueberzug#examples) first to check if `ueberzug` works at all?

**Comment by noib3** [comment]
I tried running that script and it works without problems.

**Comment by gokcehan** [comment]
@noib3 You may try checking the log file to see if there is an error. For example, a common error is forgetting to set the executable bit on the previewer script.

**Comment by noib3** [comment]
@gokcehan actually it's working now (not sure how, haven't changed anything since the last time I tested it), but if I use the `drawbox` option sometimes the images overflow one cell and cover the border, is there a fix for that?

Also, what should I put in the previewer script to get image previews for pdf files? The previewer in the wiki only shows how to create previews for image and video files.

**Comment by gokcehan** [comment]
@noib3 I think maybe drawbox issue can be considered as a bug. Preview parameters should take into account the value of `drawbox` option to set their values. I would accept a patch for that. It might be better to open a separate issue for more visibility.

There are example scripts as external repository links in the wiki page and some of them have pdf previewing.

**Comment by noib3** [comment]
@gokcehan I just opened a new issue here https://github.com/gokcehan/lf/issues/602.
