### ISSUE TITLE
Shell exit status 130

### ISSUE THREAD

**Issue by roachsinai** [gokcehan/lf#595]
I'v add a function to use fzf to select a file/directory:

```
cmd fzf ${{
    res="$(ls -t | fzf +s --cycle)"
    if [ -d "$res" ]; then
        cmd_="cd"
    else
        cmd_="select"
    fi
    lf -remote "send $id $cmd_ \"$res\""
}}
map <space>e fzf
```

and when I press `<space>e` in lf then press <esc> directly, I got a warning: `warning shell exit status 130` and at a post https://developpaper.com/shell-exit-status-code-and-its-application/ show 130 means `The command is terminated by Ctrl + C`.

So I got this warning caused by I press <esc> for fzf in lf?

If so, is there a way to supress it?

Thanks again!

**Comment by gokcehan** [comment]
@roachsinai We report errors from commands in Go side, and any non-zero return code is considered an error there. You should be able to suppress it by appending `|| true` or `|| quit` somewhere in your command so that it would return 0 instead.

There are some examples in #441

**Comment by roachsinai** [comment]
That works! Thanks @gokcehan !
