### ISSUE TITLE
ueberzug-go

### ISSUE THREAD

**Issue by rsteube** [gokcehan/lf#596]
Stumbled onto https://gitlab.com/diamondburned/ueberzug-go which seems to work quite fine:

https://github.com/gokcehan/lf/compare/master...rsteube:ueberzug-go

![lf-test](https://user-images.githubusercontent.com/9090290/112772081-2bf0dc00-902f-11eb-8b0e-c4c634f474e6.jpg)

**Comment by gokcehan** [comment]
@rsteube That seems cool but we already have a way to work with ueberzug as an external tool so I don't think this would bring much to the table. It would be nice to get rid of wrapper scripts for ueberzug but this doesn't seem like a cleaner alternative either. Readme literally says it's an "half-assed port" and the commit history suggest that it was hacked together for a few weeks last year and abandoned later on. So I don't think it is a good idea to add this as a dependency.

Feel free to add a link to your fork somewhere in our wiki pages if you are interested in keeping it maintained. I'm sorry to say I'm usually biased against image previewers in terminal in general. I think terminal specific solutions (e.g. kitty, terminology, iterm2) are cleaner than ueberzug for lf but they don't require any integration in our side anyways.

**Comment by rsteube** [comment]
Nah that's fine, just felt it might be nice to get rid of the shell scripts and wanted to let you know about it.
