### ISSUE TITLE
missing new line after 'Press any key to continue'

### ISSUE THREAD

**Issue by gotroyb127** [gokcehan/lf#598]
When a command executed via the `shell-wait` command exits, `lf` prints
`Press any key to continue` but no newline is printed. So after that any
output to the terminal starts after the last `Press any key to continue`.

To confirm that this is weird, you can run two times `!exit`. This way you will
end up with `Press any key to continuePress any key to continue` and any output
following to the terminal following that.

When trying to overcome it, I came up with a quick and dirty solution shown in
the diff below.

````diff
diff --git a/ui.go b/ui.go
index e94ffdb..3d9f318 100644
--- a/ui.go
+++ b/ui.go
@@ -1153,13 +1153,13 @@ func (ui *ui) resume() error {
 }
 
 func anyKey() {
+	fmt.Println("Press any key to continue")
 	oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
 	if err != nil {
 		panic(err)
 	}
 	defer term.Restore(int(os.Stdin.Fd()), oldState)
 
-	fmt.Print("Press any key to continue")
 	b := make([]byte, 1)
 	os.Stdin.Read(b)
 }
````
What seems unusual to me is that a newline after the message is not displayed
as I expected.

Also, due to recent changes in the `anykey` function, we may be interested in
creating a new option (maybe with a name like `waitmsg`) to set the wait message string.
If you think it could be useful, I can offer an implementation and a PR.

**Comment by gokcehan** [comment]
@gotroyb127 You are right. It seems that we're missing the newlines with the new `anykey` function in `r20 -> r21` transition.

I would prefer to keep the cursor on the same line after the prompt if it's ok for you. I had implemented the vim behavior before and I think it's less confusing. So how about the following?

```
diff --git a/ui.go b/ui.go
index e94ffdb..8d18e2c 100644
--- a/ui.go
+++ b/ui.go
@@ -1153,13 +1153,15 @@ func (ui *ui) resume() error {
 }
 
 func anyKey() {
+	fmt.Print("\n")
+	fmt.Print("Press any key to continue")
+	defer fmt.Print("\n")
 	oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
 	if err != nil {
 		panic(err)
 	}
 	defer term.Restore(int(os.Stdin.Fd()), oldState)
 
-	fmt.Print("Press any key to continue")
 	b := make([]byte, 1)
 	os.Stdin.Read(b)
 }
```

I think printing newlines in raw mode does not behave well without line discipline since carriage returns are not performed.

I would accept a PR for `waitmsg` if you're interested. Maybe you can send it along the patch for the newline.

**Comment by gotroyb127** [comment]
I guess this has been closed now.

Also, I forgot to mention that the patch you posted above prints also a newline before the 'Press any key to continue' message, but I considered that it was not intended.

Thank you.

**Comment by gokcehan** [comment]
@gotroyb127 Printing a newline before the message mimics the vim behavior but this is also fine no worries. Also I think users can add newlines themselves with the new `waitmsg` option anyways.
