### ISSUE TITLE
force `find` after `cmd-enter`

### ISSUE THREAD

**Issue by gotroyb127** [gokcehan/lf#599]
Currently, when `findlen` is set large enough or `0`, executing the `find` command prompts for the
string to search. In case when there are more than one matches, pressing `<enter>` (or any key
mapped to `cmd-enter` clears the search, it seams reasonable to end the search and
select the first match. Although what happens is that the input field clears and it still prompts for a
pattern.

My attempt to takle this was the following patch, but it seems rather hacky.
````diff
diff --git a/eval.go b/eval.go
index e83aa3b..796b9fa 100644
--- a/eval.go
+++ b/eval.go
@@ -1231,8 +1231,6 @@ func (e *callExpr) eval(app *app, args []string) {
 		app.ui.menuBuf = nil
 		app.ui.menuSelected = -2
 
-		app.ui.cmdAccLeft = nil
-		app.ui.cmdAccRight = nil
 		app.ui.cmdTmp = nil
 
 		switch app.ui.cmdPrefix {
@@ -1356,9 +1354,16 @@ func (e *callExpr) eval(app *app, args []string) {
 				app.ui.loadFile(app.nav, true)
 				app.ui.loadFileInfo(app.nav)
 			}
+		case "find: ", "find-back: ":
+			oldlen := gOpts.findlen
+			gOpts.findlen = len(s)
+			insert(app, "")
+			gOpts.findlen = oldlen
 		default:
 			log.Printf("entering unknown execution prefix: %q", app.ui.cmdPrefix)
 		}
+		app.ui.cmdAccLeft = nil
+		app.ui.cmdAccRight = nil
 	case "cmd-history-next":
 		if app.ui.cmdPrefix == "" || app.ui.cmdPrefix == ">" {
 			return
````

**Comment by gokcehan** [comment]
@gotroyb127 I don't use `findlen` myself. I have now tried it and `<enter>` behavior seems strange indeed. I don't remember if we had a reason to implement it as such. You can send this as a PR if it changes the behavior as you say.
