### ISSUE TITLE
Bug: The timefmt is incorrectly parsed if containing spaces

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#60]
Not sure when it was introduced, because I used a different time string until now, but the following statement in `lfrc` produces an error `command not found: -0700`:
~~~~
set timefmt "2006-01-02 15:04:05.000000000 -0700"
~~~~
While this works:
~~~~
set timefmt "2006-01-02^15:04:05.000000000^-0700"
~~~~

**Comment by gokcehan** [comment]
@dumblob Looks like I have only added `'` last time so just use `set timefmt '2006-01-02 15:04:05.000000000 -0700'` for now.

**Comment by gokcehan** [comment]
I have implemented double quotes as well. This should now work as intended. Closing this issue now.

**Comment by dumblob** [comment]
Ok, thanks.
