### ISSUE TITLE
Can't open text files

### ISSUE THREAD

**Issue by RossKM** [gokcehan/lf#600]
I can't open text files, upon pressing right arrow to open I receive 'error code 127'.

I can open other files such as pdf and doc.

**Comment by gokcehan** [comment]
@RossKM You should be able to see your log file for the error description. You can use the following mapping to show the log file:

```
map ` $less /tmp/lf.${USER}.${id}.log
```

It's possible that you're missing an installed program used by your default opener. Try opening the file from the command line to see if it works.

**Comment by RossKM** [comment]
> @RossKM You should be able to see your log file for the error description. You can use the following mapping to show the log file:
> 
> ```
> map ` $less /tmp/lf.${USER}.${id}.log
> ```
> 
> It's possible that you're missing an installed program used by your default opener. Try opening the file from the command line to see if it works.

so I examined the logs and I have noticed these entries, I believe it the problem stems here. I am unsure what dependency it is referencing.


> 2021/04/04 23:25:09 shell: ${{ case $(file --mime-type $f -b) in ... }} -- []
> 2021/04/04` 23:25:09 error: running shell: exit status 127
> 2021/04/04 23:25:09 Got EventError: 'read /dev/stdin: resource temporarily unavailable' at 2021-04-04 23:25:09.61718821 +0100 BST m=+3.927126685

**Comment by gokcehan** [comment]
@RossKM So I think you have a custom `open` command defined. It is possible that you have an error in the command. Make sure everything in the command is installed and working.

**Comment by RossKM** [comment]
> @RossKM So I think you have a custom `open` command defined. It is possible that you have an error in the command. Make sure everything in the command is installed and working.

my `$EDITOR output is vim. When I install Nano to test it, txt files open in nano without a problem. So it appears to be an issue with vim.

When I use Nano, the log still shows the same lines as before just without the 

> 2021/04/04` 23:25:09 error: running shell: exit status 127

line.

**Comment by RossKM** [comment]
I discovered a fix.

To fix this issue, I backed up /usr/bin/nano to another folder, deleted the original file and then made a system link that links nano to /usr/bin/vim folder. It redirects the call to open with nano to vim and opens in vim.

ie:

`cd /usr/bin`
`sudo cp nano ~/utils/nanobackup`
`sudo rm nano`
`sudo ln -s vim nano`
