### ISSUE TITLE
Preserve root folder when opening a file in the editor

### ISSUE THREAD

**Issue by luisdavim** [gokcehan/lf#601]
Is there a way to preserve the root folder when editing a file? What I mean is to launch the editor from the folder `ls` was originally launched from and passing the relative path to the editor.
This would be useful when working with certain language servers that don't play nice when the editor isn't launched from the project's root folder...

**Comment by gokcehan** [comment]
@luisdavim I don't think there is currently an easy way to do this. Maybe we can add an environment variable to denote the initial directory in which `lf` is launched (e.g. `OLDPWD`) so the following can work:

    map e $cd $OLDPWD && $EDITOR $fx

File variables are already full path so I think this should work.

This might also be an easier way to implement canceling directory change within `lfcd` function as discussed in #140.

**Comment by luisdavim** [comment]
Sounds good. I think that would work. Thanks.

**Comment by gokcehan** [comment]
@luisdavim I have added `OLDPWD` which is included in the new r22 release.
