### ISSUE TITLE
Add floating terminals *a la neovim*

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#603]
I have no idea how hard this is to implement but it would be really cool to be able to execute ui-blocking shell commands (i.e. the `$`-prefixed ones) inside floating terminals, instead of the current behaviour where they take over the entire screen.

For example, this is what the same command looks like in lf (top) and in a floating terminal inside neovim (bottom):

![2021-04-04@21:06:57](https://user-images.githubusercontent.com/59321248/113519055-3b6da900-958a-11eb-9b95-13e36477c07c.png)
![2021-04-04@21:07:33](https://user-images.githubusercontent.com/59321248/113519061-40325d00-958a-11eb-81dc-54b2a945bc48.png)

**Comment by gokcehan** [comment]
@noib3 I think that would be pretty difficult to implement. You would essentially need to embed a terminal emulator inside lf. I don't know any terminal emulator libraries written in Go, and even if there was a library I don't think there is much benefit in doing this. A much easier solution would be to use something tmux splits for command executions.
