### ISSUE TITLE
Pass preview pane geometry as argument to preview cleaner

### ISSUE THREAD

**Issue by phillbush** [gokcehan/lf#606]
I use w3m as image drawer for file preview. And it needs the geometry (position and size) of the preview pane in order to clean the image that was drawn. But it is not possible, as the cleaner program only gets as argument the path to the current file.

Can the next release of lf pass to the cleaner program the same arguments passed to the previewer program? (i.e., filepath width height x-pos y-pos)

**Comment by gokcehan** [comment]
@phillbush I would accept a patch for this. I just made a new release already but we can aim for the next release if we get a patch.

**Comment by phillbush** [comment]
done with #945
