### ISSUE TITLE
[feature] Update terminal title based on cwd

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#614]
Atm we have an on-cd cmd and the tips section has an [example](https://github.com/gokcehan/lf/wiki/Tips#show-current-directory-in-window-title) that lets us update the terminal title based on the cwd... which is epic :-). However there's no way to clear the title or restore it to its original value when you exit lf.

It'd be nice if lf set and restored the title itself (maybe adding an option for that in the config file). Alternatively we could add an on-exit cmd which users can use to clear the title themselves. 

Thoughts?

**Comment by gokcehan** [comment]
@mohkale This was discussed in #262 and #544 and I think my previous stance still holds. I don't really want to maintain a low level terminal handling behavior in `lf` especially when it's not portable. You might be able to run a command after exit with something like:

   lf; printf "\033]0; original title\007"

You could make this an alias or add it to any wrapper script.

**Comment by mohkale** [comment]
@gokcehan

I'd rather have something in my config over relying on wrappers or aliases. Multiple wrappers don't really mix well (at the moment I have the lfcd wrapper setup as well).

What're your thoughts on the `on-exit` command suggestion?

**Comment by gokcehan** [comment]
@mohkale I guess that might be acceptable as I can't think of any complications. I think it might be better to call it `on-quit` though.

**Comment by mohkale** [comment]
@gokcehan 

Roger. I'll send a PR when I get a chance :smile:.

**Comment by gokcehan** [comment]
This is added to the master branch a while ago which will likely be available in the next release (e.g. r27).

**Comment by mohkale** [comment]
Ah, my bad, I totally forgot about this. Thanks for the great work :-).
