### ISSUE TITLE
Crash with directory preview and hidden files

### ISSUE THREAD

**Issue by kmarius** [gokcehan/lf#615]
I get this panic on `r22` and `master` on linux:

    drwxr-xr-x 4 marius users  8panic: runtime error: index out of range [1] with length 1
                                                                                      goroutine 1 [running]:
                                                                                                            main.(*dir).name(...)
                                                                                                                                        /home/travis/gopath/src/github.com/gokcehan/lf/nav.go:246
                                            main.(*app).loop(0xc00030a080)
                                                                                /home/travis/gopath/src/github.com/gokcehan/lf/app.go:295 +0x157c
                                                                                                                                                 main.run()
        /home/travis/gopath/src/github.com/gokcehan/lf/client.go:50 +0x30d
                                                                          main.main()
                                                                                        /home/travis/gopath/src/github.com/gokcehan/lf/main.go:286 +0xa25

This happened when switching from `hidden` to `nohidden` and then selecting (with the cursor, not actually selecting) a directory that contains hidden files. The number of visible files in the preview pane changed so that the previously correct index is then out of bounds. I can reproduce it with a clean config with the following steps

    mkdir -p a/b/{.c,d}
    lf -config /dev/null a
    :set hidden (zh)
    :updir (h)
    :set nohidden (zh)
    :open (l)

**Comment by gokcehan** [comment]
@kmarius Thank you very much for the detailed report. I have now pushed a fix to avoid such crashes.
