### ISSUE TITLE
w3m image support?

### ISSUE THREAD

**Issue by array-in-a-matrix** [gokcehan/lf#617]
In ranger you can view images in the terminal with w3m is this possible in lf?

**Comment by gokcehan** [comment]
@array-in-a-matrix There are some instructions in the [Previews](https://github.com/gokcehan/lf/wiki/Previews) wiki page though I don't know if it works as I haven't tried it myself.

**Comment by XPhyro** [comment]
You can check out [lfimg](https://github.com/cirala/lfimg). Works pretty well in my experience. Though, notice that it uses Überzug and not w3m.

**Comment by array-in-a-matrix** [comment]
thank you guys!
