### ISSUE TITLE
Selecting a Range

### ISSUE THREAD

**Issue by lucas979797** [gokcehan/lf#619]
Is it possible to select all files and directories between two points, similar to how with a regular GUI file browser you can hold shift to select all files between the first selected file and second? 
Currently the only way I can select a bunch of files is by just repeatedly hitting `<space>` to select a file/directory and move to the next item, but I'm not able to find anything about selecting multiple files at once in the tutorial or documentation. A *select all in current directory* would also be useful to know.

**Comment by gokcehan** [comment]
@lucas979797 There is `invert` command (default `v`) to invert selection in the current directory. If you use it with an empty selection, it selects all files.

You can also use `toggle` with count (i.e. `10<space>`). Also see `glob-select` and `glob-unselect` commands.

**Comment by lucas979797** [comment]
@gokcehan thanks for your response. Invert is a good idea for selecting all. I didn't know about using `toggle` with a count as well. Good tip.
