### ISSUE TITLE
Passing arguments to a command

### ISSUE THREAD

**Issue by lucas979797** [gokcehan/lf#620]
I'm having problems passing an argument to a command. What I have so far, having followed the example in the documentation on `rename` is:
```
cmd mkd %mkdir "$1"
map nd push :mkd<space>
```
However, when I invoke the command with `nd`, and then type a name, lf reports `mkdir: .: No such file or directory` on the bottom line. I've also tried with `"$@"` and for some reason that gives a load of white space with a caret on the bottom line.

Any ideas where I could be going wrong? I'm using the fish shell if that helps at all.

**Comment by kmarius** [comment]
Try `argv[1]` instead of `"$1"` and make sure you are running a recent version of `fish`. Some older versions don't support passing variables the way `lf` does.

**Comment by lucas979797** [comment]
@kmarius thanks for the help, that was pretty much it. I should have known it was a fish specific thing.

The specific sequences I used in the end were:
```
# new directory
cmd mkd %mkdir $argv[1]
map nd push :mkd<space>


# new file
cmd newfile $nano $argv[1]
map nf push :newfile<space>
```
