### ISSUE TITLE
[feature] warn about nested lf instance

### ISSUE THREAD

**Issue by sigasigasiga** [gokcehan/lf#625]
# description
it'd be nice if `lf` would warn you if it is running in its nested instance (like `ranger` does). imagine this scenario:
* open `lf`
* open shell inside current `lf` instance (`$$SHELL`)
* accidentally forget that you've opened shell inside `lf` instance
* open new `lf` instance in shell that is running inside previous `lf` instance

to make things easier to understand, here's a possible process tree:
```
\_ -fish
|   \_ lf
|       \_ fish
|           \_ lf
```

i think users should be still able to launch nested instances (it could be convenient in some cases) but they should be warned just in case they forgot about previous opened instances.

# implementation
i can think of two ways this could be implemented:
* ranger-like implementation
  on startup export some environment variable and if it already exists then output a warning ([snippet with ranger implementation](https://github.com/ranger/ranger/blob/277e1db745a817f522278487b97f1518b54d668e/ranger/core/main.py#L185-L187)).

  notes:
  * don't know if this method would work on windows though
  * may not always work on unix systems if shell doesn't export all environment variables before fork (like `sudo` does for example)

* `/proc` traversing implementation
  the only way to get another process' PPID is to get it in procfs. in case of linux it is lying inside `/proc/<pid>/stat` file (don't know about other unix systems though).

  notes:
  * this method obviously won't work on windows (not sure if we can get info about process' parent process at all)
  * this method may be not that portable across all unix systems (i'm not in the mood to dig up POSIX specification today :( )
  * it may be tricky to identify if a process is `lf`

**Comment by sigasigasiga** [comment]
btw i'm new to golang but i think i could implement this if we make a decision about implementation

**Comment by kmarius** [comment]
The environment variable you describe already exists, it is called `LF_LEVEL`. You can mimic `ranger`s behavior by adding 

    &{{ [ $LF_LEVEL -eq 1 ] || lf -remote "send $id echo Warning: You're in a nested lf instance"; }}`

to your `lfrc`. Note that this variable is exported to any spawned process so you will get the warning if you run `lf` in a terminal started from `lf` even though it is not actually nested.

**Comment by gokcehan** [comment]
@sigasigasiga Do you think this is enough for your needs? It is not automatic but maybe it is better this way to be configurable. You could also consider adding the following to your `~/.bashrc` to remind you that the shell is spawned inside `lf`:

```
[ -n "$LF_LEVEL" ] && PS1="$PS1""(lf level: $LF_LEVEL) "
```

@kmarius Thanks for coming up with a solution. It seems rather useful so maybe you can also consider adding it as a tip in the wiki page. By the way, I think in this case `%` command can also work similarly:

```
%[ $LF_LEVEL -eq 1 ] || echo "Warning: You're in a nested lf instance"
```

**Comment by sigasigasiga** [comment]
yeah, that's a great solution, thank you.
don't know if i should close this issue because you seem to be deciding if this solution should be added to wiki (btw, i think you should also consider adding it to the `lfrc` example), so i leave ticket closure up to you guys

**Comment by kmarius** [comment]
I have added it to the Tips wiki but I don't think it belongs in `lfrc.example`, mainly because it is just supposed to show people how to get started with configuring `lf`.

**Comment by gokcehan** [comment]
@sigasigasiga I wouldn't mind including it in the example config as it seems useful but @kmarius is also right as it's just an example to get started so I think wiki is fine for now. Thank you both for discussion. Closing this issue now. Feel free to leave further comments if you have.
