### ISSUE TITLE
folder a does not show files after deleting empty folder b and renaming a to b

### ISSUE THREAD

**Issue by oliverisler** [gokcehan/lf#627]
hi,

i guess i have found a minor issue. 

1) take a folder x with sub folders a and b, a containing files. my left windows shows x, middle shows a / b (selection e.g. on a) and my right window shows the files.

x/a/files
x/b/empty

2) when i delete folder b and then rename a to b, the files (in new b, former a) are not visible. I have to reload/refresh b to see the files.

x/b/files

p.s. i love lf !

OLi

**Comment by gokcehan** [comment]
@oliverisler Thanks for the report. I'm aware of that one. It's a side effect of storing the cache using path names as the key and renaming a file not updating the modification times. Unfortunately, I can't think of a good solution for that. Let's keep this issue open as a reference. Maybe a good idea pops up at some point.

**Comment by oliverisler** [comment]
hi gokcehan,

... no worries, just wanted to "give back" as i am using lf very heavily.
keep up the good work!

OLi

**Comment by sigasigasiga** [comment]
@gokcehan i think you may use `dev` and `ino` (see `man 2 stat`) as keys. probably wont work on windows but should be pretty reliable

**Comment by gokcehan** [comment]
@sigasigasiga I guess that would be the proper approach, thanks. But it seems that neither `dev` nor `ino` are directly visible in [fs.FileInfo](https://golang.org/pkg/io/fs/#FileInfo) and they are hidden behind `Sys()` as `interface{}`. I'm usually inclined to avoid such non-portable uses as I'm not able to test it on different machines myself. In this case, it seems that this is the approach they use for unix systems except for plan9 (i.e. `sameFile` function in [types_unix.go](https://golang.org/src/os/types_unix.go)) but the windows version seems quite complicated (i.e. `sameFile` function in [types_windows.go](https://golang.org/src/os/types_windows.go)).

**Comment by gokcehan** [comment]
@sigasigasiga Also, I realized now that this may not even work in our case. When you delete an old file that inode number is available to new files. Consider the following case:

```
gokcehan@this ~/asd> touch foo
gokcehan@this ~/asd> ls -i
542245 foo
gokcehan@this ~/asd> rm foo
gokcehan@this ~/asd> touch bar
gokcehan@this ~/asd> ls -i
542245 bar
```

In this case `foo` and `bar` would try share the same cache.

**Comment by sigasigasiga** [comment]
somehow i forgot to answer lol.

another way is to use something like `inotify` in linux to monitor changes in folders. there are some libraries that do this in a portable manner https://github.com/fsnotify/fsnotify

but on the other hand cache management could be tricky to implement and makes you dependent on an another third-party library which is not always a good thing

**Comment by sigasigasiga** [comment]
if you think that monitoring filesystem isn't worth it then maybe you should consider removing cache at all? **IMHO**, caching is a good thing but only if it behaves correctly

**Comment by gokcehan** [comment]
@sigasigasiga That library has been discussed before but I'm often hesitant to add new dependencies. My general consensus is that if things can be implemented portably in a straightforward fashion, then it would have been included in the standard library. This is not always the case, but I find it a useful heuristic.

Caching works 99% of the time so I would not want to remove it altogether. But I'm open to include an option for it (e.g. `nocache`). Some people may find such an option useful for true image previews.
