### ISSUE TITLE
Debian/Ubuntu link community package is dead

### ISSUE THREAD

**Issue by ChickenKiddie** [gokcehan/lf#628]
https://software.opensuse.org//download.html?project=home%3AProvessor&package=lf

**Comment by gokcehan** [comment]
@ChickenKiddie I have removed it now, thanks. Actually, I have recently added the repology badge to the wiki page so maybe maintaining each package manually is not necessary anymore. Some of them are not in repology badge (e.g. fedora and mageia) but they seem to be outdated anyways.
