### ISSUE TITLE
Can we somehow get find to work as ranger's find?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#629]
Is  there any known way to change find function work like ranger's. For example I might have Documents and Desktop folder, so I can just press f and then write do and it sends me inside Document folder.

Right now with LF when I use f and write d it just goes to Desktop but doesnt enter nor let me write more nor automatically go inside a folder. Wondering if this is doable? It's weird that it just lets me find the alphabet one and stops there.

I am getting load of goosebumps after changing from ranger to lf.
No more crashing or ui becoming funky and way more stable and faster. So if its not doable I am still very okay and darn happy that this tool exists.

**Comment by gokcehan** [comment]
@thepenguinthatwants There are currently two options options to customize finding, `findlen` is to match more than one character (set 0 to read until there is only a single match as in ranger), and `anchorfind` is to match starting from an arbitrary position. See 'Searching Files' in the documentation for more information. I'm not aware any method to automatically open the matched directory.

**Comment by thepenguinthatwants** [comment]
Hi,
Thanks that works good enough.
I finally added lfrc to config and it seems okay. 
`set findlen 2`
