### ISSUE TITLE
Is there a way to paste files creating duplicates automatically?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#630]
In ranger there has being ability to copy files and paste. If there is same named files it will automatically create a file with underscore at the end of file name. 

Is there any known way to achieve this?

**Comment by gokcehan** [comment]
@thepenguinthatwants That should already be the case with the default `paste` operation, although we use a suffix different than `ranger` to be compatible with GNU cp instead. See "File Operations" in the documentation for more information.
