### ISSUE TITLE
Any way to map J and K to move in to the half page down?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#632]
Hi,
In ranger I've managed to move half page down using J or K

is this somehow manageable using lf?

```
map J  move down=0.5  pages=True
map K  move up=0.5    pages=True
```

Tho relativenumber is crazily awesome sometimes its nice to just quickly drop to the middle of the screen when navigating.

**Comment by gokcehan** [comment]
```
map J half-down
map K half-up
```
