### ISSUE TITLE
Setting automatic file opener for .bashrc type of files?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#634]
Hi,
For now when I open files txt and .pdf type of files gets opened easily. But when I tried to open .bashrc lf just got totally stuck.
Any way to debug that? Tho its probably also quite hard to define as its not *.txt type of file.

I've set it up to look like this right now.

```
cmd open ${{
    case $(file --mime-type "$f" -b) in
	image/vnd.djvu|application/pdf|application/octet-stream) setsid -f zathura "$fx" >/dev/null 2>&1 ;;
        text/*) $EDITOR "$fx";;
	image/x-xcf|image/svg+xml) setsid -f gimp $f >/dev/null 2>&1 ;;
	image/*) "$f" | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|tif\)\(_large\)*$" | vimiv "$f" 2>/dev/null ;;
	audio/*) mpv --audio-display=no "$f";;
	video/*) setsid -f mpv "$fx" -quiet >/dev/null 2>&1 ;;
	application/pdf|application/vnd*|application/epub*) setsid -f zathura "$fx" >/dev/null 2>&1 ;;
        *) for f in "$fx"; do setsid -f $OPENER "$f" >/dev/null 2>&1; done;;
   esac
}}
```

**Comment by gokcehan** [comment]
@thepenguinthatwants You probably have a symbolic link for your `~/.bashrc`. You can use the following to follow links:

```
cmd open ${{
    test -L $f && f=$(readlink -f $f)
    case $(file --mime-type "$f" -b) in
	image/vnd.djvu|application/pdf|application/octet-stream) setsid -f zathura "$fx" >/dev/null 2>&1 ;;
        text/*) $EDITOR "$fx";;
	image/x-xcf|image/svg+xml) setsid -f gimp $f >/dev/null 2>&1 ;;
	image/*) "$f" | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|tif\)\(_large\)*$" | vimiv "$f" 2>/dev/null ;;
	audio/*) mpv --audio-display=no "$f";;
	video/*) setsid -f mpv "$fx" -quiet >/dev/null 2>&1 ;;
	application/pdf|application/vnd*|application/epub*) setsid -f zathura "$fx" >/dev/null 2>&1 ;;
        *) for f in "$fx"; do setsid -f $OPENER "$f" >/dev/null 2>&1; done;;
   esac
}}
```

**Comment by thepenguinthatwants** [comment]
Wow u r smart, this was solved instantly.

**Comment by gokcehan** [comment]
@thepenguinthatwants Thanks but this was actually asked a while ago and that's how I guessed. I was meant to put the line in the examples and I forgot but now I did.

**Comment by thepenguinthatwants** [comment]
There is something strange when opening a empty txt file, it doenst know which software to use. But if the txt file has some text then it uses correct one "vim"

**Comment by gokcehan** [comment]
@thepenguinthatwants Empty files are not automatically considered text files and their type is `inode/x-empty`. You may add this to your open command if you want to open empty files with your editor.
