### ISSUE TITLE
Image preview using lfimg but also having lfcd?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#635]
Hi,
From wiki of previews https://github.com/gokcehan/lf/wiki/Previews I've gotten lfimg to work.
But then comes the problem.
I've mapped lf as alias for lfcd, how can I run lfimg and lfcd same time?

**Comment by XPhyro** [comment]
lfimg provides a binary named `lfrun`. You can just replace `lf` with `lfrun` and it should work. The resulting shell function is something like this:
```
lfcd() {
    tmp="$(mktemp)"
    lfrun -last-dir-path="$tmp" "$@" # this is where you swap in lfrun
    [ -f "$tmp" ] && {
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$PWD" ] && cd "$dir"
    }
}
```
