### ISSUE TITLE
lf -remote should take arguments separately

### ISSUE THREAD

**Issue by soystemd** [gokcehan/lf#636]
Currently the way to send commands to lf is to clump them in one argument:
`lf -remote 'send ....'`

This makes it really difficult / impossible to make distinction between different
arguments that are sent.

Say I want to remotely select a file whose name contains a quote / doublequote
and it resides in a shell variable:

```
$ file="$(command_that_gets_file_name)"
$ echo "$file"
Don't Need Love.mp3
# remotely select it:
$ lf -remote "send $id select '$file'"
```

It won't work because the quote character in `$file` is interpreted specially.

It's also impossible to directly send commands with their own set of
arguments, if the arguments contain any whitespace character:

```
cmd="$@"
lf -remote "send $id \$$*" # won't work if any arguments contain whitespace
```

Arguments should really be interpreted as actual separate shell arguments:

`lf -remote send $id <command> <arg1> <arg2> ...`

This also makes it possible to use in conjunction with xargs(1).

**Comment by gokcehan** [comment]
@soystemd Currently we write the command as a single line string to the unix socket which is then split into multiple arguments on the server side. If we take remote commands as multiple arguments, I think we would still need to join them before sending it through the socket which might add another level of quoting semantics to the pipeline. I can't really comment on whether the proposal is better or not but we also need to discuss whether or not it is feasible to implement somehow. By the way, there are some examples in the our wiki page which use escaped double quotes for the examples you provided which might work better (e.g. ` lf -remote "send $id select \"$*\""`)
