### ISSUE TITLE
Autocompletion for bash commands?  (open_with)

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#637]
I've gotten this on my lfrc, and wondered if its possible to find programs by pressing tab instead of writing whole name of programs?

```
cmd open_with $$1 $f
map o push :open_with<space>
```

**Comment by gokcehan** [comment]
```
map o push $<space>$f<home>
```

**Comment by gokcehan** [comment]
@thepenguinthatwants This is not strictly what you asked for but I think it works similar enough. Is this an acceptable solution? Shall we close the issue?

**Comment by thepenguinthatwants** [comment]
This didn't work the way as I intended but I guess its not doable "easily" at least. So yeh this issue can be closed.
