### ISSUE TITLE
Ability to see free disk  space like in ranger?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#638]
Hi,
Is there a way to modify gui more? After using ranger for so many years I felt more comfy to check free space size from it than to separately use df -h.

**Comment by se7en-x230** [comment]
I use gdu and map it to 
`map di gdu`

**Comment by thepenguinthatwants** [comment]
This is bit different than seeing it straight when opening lf. Gdu also feels quite overwhelming tool as it indexes before showing results

**Comment by se7en-x230** [comment]
Well 
`! du -sh ` if that helps

**Comment by gokcehan** [comment]
@thepenguinthatwants Free space is something that may not be constantly required to see so it may feel like cluttering the screen for some users. Ideally, we should have an option to customize the status line first (e.g. `statfmt`) similar to what we have as `promptfmt` so users would have a chance to enable/disable this possible field. Personally, I haven't needed to see the free space in `lf` so far as I have my free space shown in my i3status already. You may consider a similar approach as a workaround if this is something you would rather see all the time and keybindings are not enough for your purpose.

**Comment by thepenguinthatwants** [comment]
Actually idea for having ability to customize promptfmt would be super neat.
