### ISSUE TITLE
Tagging an entry doesn't update the rightmost panel

### ISSUE THREAD

**Issue by lenormf** [gokcehan/lf#64]
Hi,

Upon marking an entry, the cursor jumps to the next entry in the main column, and the panel on the right isn't updated when the entry is a directory (it's supposed to list the files in the directory, which right after the one that was marked).

Thanks.

**Comment by KenjiTakahashi** [comment]
True, same thing happens for file previews.

**Comment by KenjiTakahashi** [comment]
Why close ;-)?

**Comment by lenormf** [comment]
Hit the wrong button in a hurry!

**Comment by gokcehan** [comment]
And also if you change a file with a shell command (e.g. vim) old file preview persists afterwards.

I haven't got a chance to clean things up yet when we added preview buffering. I will try to do these as soon as possible.

**Comment by gokcehan** [comment]
Everything should work as intended now. I'm closing this issue but feel free to report here if there is still anything funky.
