### ISSUE TITLE
How do people usually manage with external drives and mounting?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#640]
I usually just open pcmanfm (as it uses gvfs) and then navigate in lf to usb location. 
After when I've done file copying or pasting. I just do

`udiskie-umount --detach -a`

To be sure that its not busy and being able to unmount.

Wondering what solutions people are usually using with external drives.

**Comment by se7en-x230** [comment]
I run a mount/unmount script via !script-name.sh

**Comment by thepenguinthatwants** [comment]
Want to elaborate more about your script?

**Comment by se7en-x230** [comment]
you can add the command you usually run and bind it to a key.
                   
let's say you use sshfs :

 `cmd sshfs-shop ${{
  sshfs someone@something.net:/ ~/Mount/ 
}}

map M sshfs-shop
 `
 Add something like that for your service to your lfrc.
