### ISSUE TITLE
cjk text refresh residue

### ISSUE THREAD

**Issue by hxse** [gokcehan/lf#644]
dir 1:
![image](https://user-images.githubusercontent.com/22582226/120833896-e99acc80-c594-11eb-9e38-fddbf28a751a.png)

dir 2:
![image](https://user-images.githubusercontent.com/22582226/120834340-75145d80-c595-11eb-9f00-ecc04f34ff1b.png)

dir 2 to dir1:
![image](https://user-images.githubusercontent.com/22582226/120834556-c1f83400-c595-11eb-82f5-29d155316f6c.png)

When switching from the dir 2 to the dir 1, the english text refresh normal, but the cjk text residue.

**Comment by gokcehan** [comment]
@hxse Thanks for reporting. Is this specific to windows terminal or you can reproduce it on different terminals as well? This may likely be terminal or a tcell issue. Also can you copy the names of those files here as text so maybe we can try reproducing?

**Comment by hxse** [comment]
I only know that Windows is like this because I only have Windows.
Test text: 
新建文件
新建文本文档
文件文件夹
测试文档

**Comment by mshungo** [comment]
I had a similar problem with Japanese fonts. When LF displays the Japanese file, the rendering was weird and finally the console crashed. However, when I turned on "legacy console" in the command prompt options, it rendered fine.

Unfortunately I no longer get to choose my favorite font in legacy console, but for the moment it works fine.

**Comment by gokcehan** [comment]
@mshungo Thanks for the workaround. It's unfortunate that I don't know how to solve some of these terminal issues. I have now created a [Troubleshoot](https://github.com/gokcehan/lf/wiki/Troubleshoot) wiki page so such workarounds would not be buried in the issues. I have tried adding this to the page. Feel free to add more information there if you like.

**Comment by zcysxy** [comment]
Emmm this is a really annoying bug. Is there any way to prevent the preview of CJK? by configuring the previewer or something.

**Comment by SpicyChickenFLY** [comment]
Hi, @hxse, I found that you have closed this issue. Is there any idea for a solution for this?

**Comment by gokcehan** [comment]
We can reopen this issue to track it but I don't think there is much we can do about this on our side. From what I understand from discussions, I suspect this is a tcell issue as it uses a different API for unix and windows. I found https://github.com/junegunn/fzf/issues/2715 reported in fzf repository which might be related to this issue. Unfortunately, I haven't found anything related reported in tcell repository. If anyone wants to see this issue fixed, it might be a good idea to reproduce this issue with a toy example for tcell and report the bug. If the issue is solved, we can simply bump our tcell version in lf to include the fix on our side.

**Comment by SpicyChickenFLY** [comment]
@gokcehan  yeah, I agree with you, and I found a related issue in [microsoft/terminal#12479](https://github.com/microsoft/terminal/issues/12479) and it is now assigned to a contributor of that repo. Maybe we will get a conclusion soon XD.

**Comment by ayuayue** [comment]
you can reset key l && h,and use reload command;
I use powershell in windows11. and now it's very nice.
eg:
```
# lfrc

map l 
map h

map l :open; reload
map h :updir; reload

```

**Comment by ayuayue** [comment]
and set j,k to redraw
```
# lfrc
map k
map j

map k :up; redraw
map j :down; redraw
```

**Comment by CAESIUS-TIM** [comment]
> and set j,k to redraw
> 
> ```
> # lfrc
> map k
> map j
> 
> map k :up; redraw
> map j :down; redraw
> ```

In WindowsTerminal with pwsh7, without these maps, chinese characters can be rendered sometimes, and even cannot highlight text preview properly.
After setting, chinese characters completely disappear.
I have given up WindowsTerminal. Instead, [WindTerm](https://github.com/kingToolbox/WindTerm) can render chinese chars (but sometimes misses the first char) and true color.
