### ISSUE TITLE
How to easily compress folder and files without the full path?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#646]
Hi,
I've being trying to figure how to easily compress files and folders without full paths.

```
cmd targz %tar cvzf "$f.tar.gz" "$f"
map xg targz
```
The problem with this approach is that it takes the whole path from /home/user/folder/file instead of just folder/file.

**Comment by gokcehan** [comment]
@thepenguinthatwants Maybe `basename` could work:

```
cmd targz %tar cvzf "$(basename "$f").tar.gz" "$(basename $f)"
map xg targz
```
