### ISSUE TITLE
Windows packaging via Chocolatey?

### ISSUE THREAD

**Issue by ratijas** [gokcehan/lf#649]
Feature request to officially push Windows binaries to Chocolatey registry. It is already there<sup>[1]</sup>, but it is currently missing some features.

Stuff from etc would be appreciated:
- PowerShell autocompletion,
- `lfcd` script.

Currently, `lf` installation from chocolatey looks like this:

```
PS C:\ProgramData\chocolatey\lib\lf> tree /F
C:.
│   lf-windows-amd64_x64.zip.txt
│   lf.nupkg
│   lf.nuspec
│
├───legal
│       LICENSE.txt
│       VERIFICATION.txt
│
└───tools
        chocolateyInstall.ps1
        lf.exe
```

[1]: https://community.chocolatey.org/packages/lf

**Comment by ratijas** [comment]
On a second thought, things like `lfcd` and autocompletion would really fit into PS Gallery, aka PowerShell Gallery of packages.

https://www.powershellgallery.com/packages

**Comment by gokcehan** [comment]
@ratijas Thanks for the suggestion. We can leave this issue open for visibility and discussion.
