### ISSUE TITLE
dircounts are always visible when pane ratio is set to 1:2:2

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#652]
I don't know if this is the intended behaviour, but when I set `dircounts` to true and `ratios` to `1:2:2`, the dircounts on the first pane are always visible, even if there is no space for them.

This is different when `dircounts` is left to its default value, in that case the dircounts on the first pane are only visible if there is enough space.

These two screenshots should show what I mean. Both of them have dircounts set to true, but the `ratios` setting is left unchaned in the first screenshot and to `1:2:2` in the second one:

![2021-06-17@23:03:03](https://user-images.githubusercontent.com/59321248/122472918-798f3c00-cfc1-11eb-8e03-e5a2c7219973.png)
![2021-06-17@23:03:10](https://user-images.githubusercontent.com/59321248/122472935-7dbb5980-cfc1-11eb-9b27-3ce6da43df59.png)

as you can see, the dircounts on the first pane are hidden in the first screenshot (which I believe is the correct behaviour since there is not enough space for them) but shown in the second one.

**Comment by gokcehan** [comment]
@noib3 I think this is currently the intended behavior. The current heuristic is to show the info when it is less than half the width of the pane. Size info is 4 cell wide so it is shown for panes wider than 8. When you change `ratios`, you also modify the width of the pane.
