### ISSUE TITLE
--: line 2: /home/user/test.file: Permission denied (error key remove)

### ISSUE THREAD

**Issue by chetnuy** [gokcehan/lf#653]
Hello
quite recently, an error started to appear when deleting file ~/test.file  via key binding **X** and **x** 
I see this error:
**--: line 2: /home/user/test.file: Permission denied**

The same thing appears when running from root

Section in lfrc:
```
cmd trash %set -f; mv $fx ~/.trash
cmd delete ${{
    set -f
    printf "$fx\n"
    printf "delete?[y/n]"
    read ans
    [ $ans = "y" ] && rm -rf $fx
}}
```

OS: Archlinux
Package: aur/lf-bin 23-1 aur/lf 23-1

**Comment by gokcehan** [comment]
@chetnuy When you say recently, is this something that started happening when you upgraded `lf`? I can't reproduce this on my machine. Can you try this with an empty configuration file with only the section you posted? Also does this work with the builtin `delete` command?

**Comment by chetnuy** [comment]
I completely updated the system three days ago

Current lfrc:
```
set shell sh

map x $$ f
map X! $ f

cmd trash% set -f; mv $ fx ~ / .trash
cmd delete $ {{
     set -f
     printf "$ fx \ n"
     printf "delete? [y / n]"
     read ans
     [$ ans = "y"] && rm -rf $ fx
}}
```

And when I press the key  **X** or **x** on I get the error in console:
**--: line 1: /home/user/test.file: Permission denied**

Removing via **!rm -rf test.file** works

**Comment by gokcehan** [comment]
@chetnuy There are now multiple whitespace errors in your `delete` command.

**Comment by chetnuy** [comment]
@gokcehan 
Sorry, display problems. Here is the exact file
https://raw.githubusercontent.com/chetnuy/lf/main/lfrc

Tried using bash instead zsh console.Same error.

**Comment by kmarius** [comment]
@chetnuy The commands bound to `x` and `X` both execute the file, not delete it, but the file is not executable. Try `map x delete`.

**Comment by chetnuy** [comment]
@kmarius Ok, thank you. Close this issue.
