### ISSUE TITLE
lf becomes unresponsive after a graphical shell command

### ISSUE THREAD

**Issue by SPFabGerman** [gokcehan/lf#654]
I have a command in my `lfrc` file like this:
```
cmd img_view ${{
	sxiv "$f"
	echo "done"
}}
```
(Simply running `$sxiv $f` inside lf also works and has the same effect.)

Sometimes when I run this command on an image file and quit sxiv afterwards lf completetly freezes (and I only see a blank terminal screen in most cases). I would say this happens about 10-50% of the time. (Sometimes it happens more frequently and sometimes less frequently. I don't know why.)

The wierd thing is, when I switch the `echo` to a `notify-send` this does not happen anymore. (I use dunst, if that is relevant.) (Removing the `echo` command makes no difference.)
The same goes for, when I switch the `$` to a `!` or `%`: the freeze simply does not happen now.
There are some other wierd niche cases, when this also does not happen, e.g. when I have window swallowing activated in my window manager.

This doesn't seem to be related to sxiv, since I get a simmilar behaviour when replacing `sxiv` to `zathura` and viewing pdf files. The problem seems to happen with all graphical programs.
When this happens the shell already exited and is no longer alive. (I used htop to check this.) So the issue seems to come from what lf does after a shell command.
Remote commands send via `lf -remote` also do nothing. This indicates to me, that lf is somehow stuck and frozen and not simply "invisible".

**Comment by kmarius** [comment]
Sounds like #621. The problem is (likely) `lf` getting resized while reinitializing.
