### ISSUE TITLE
bash history

### ISSUE THREAD

**Issue by kexul** [gokcehan/lf#656]
Hi, Can I get bash history when running command from lf using 'Up' key in keyboard?

**Comment by XPhyro** [comment]
I don't think lf provides this feature. As a workaround, you can try syncing your bash history (after some processing) to `~/.local/share/lf/history` or run the command in a subshell. By default, lf provides the following binding `map w $$SHELL`. You can press `w` to drop into a subshell, use bash features to run the command and press `<c-d>` to return back to lf.

**Comment by kexul** [comment]
Thanks @XPhyro , it sounds good!
