### ISSUE TITLE
Built-in command/keybind for $mkdir and $touch

### ISSUE THREAD

**Issue by JimPix1** [gokcehan/lf#658]
I think a built in keybind or command for mkdir and touch would be handy instead of having to do $mkdir [name] or $touch [name]

**Comment by kmarius** [comment]
If you add `map M push $mkdir<space>` to your config and press `M`, the command line will contain `$mkdir ` and you can then type `[name]`. Is that what you are looking for?

**Comment by JimPix1** [comment]
That's exactly what I want, I didn't know ``push`` existed, thanks!
