### ISSUE TITLE
Any way to get ui indication showing linked files

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#660]
Hi,
There are sometimes symlinked files and folders and it would be nice to see somekind of indication that its a symlink.
Is there a way to get it shown?

**Comment by kmarius** [comment]
Currently the only indication are different colorization of symlinks in the directory view and, for the currently selected file, the link target shown in the bar at the bottom. I like personally like how `ranger` also shows arrows in the directory view, i.e. 

    Data                                     -> 4    
    Documents                               -> 23    
    Downloads                                -> 1    
    Sync                                       12 
    ...

**Comment by thepenguinthatwants** [comment]
I dont even see the color indicator. Should it be activated by some settings?

**Comment by kmarius** [comment]
@thepenguinthatwants It is configured by the `LS_COLORS` environment variable and should be active by default, assuming your terminal emulator supports colors. `LS_COLORS="ln=01;31" lf` shows symlinks as bold red for me.

**Comment by thepenguinthatwants** [comment]
Weird I can't see such on my alacritty terminal nor st.

**Comment by gokcehan** [comment]
@thepenguinthatwants You can also add an icon for symlinks in addition to colors.

**Comment by thepenguinthatwants** [comment]
> @thepenguinthatwants You can also add an icon for symlinks in addition to colors.

Can you give example of setting different icons for symlinks?

**Comment by gokcehan** [comment]
@thepenguinthatwants It has the same syntax as colors. See the documentation for more information.

**Comment by thepenguinthatwants** [comment]
I dont seem to find such in documentations. I think u mean as https://github.com/gokcehan/lf/wiki/Icons wiki?
