### ISSUE TITLE
can not compile "lf" without connect internet

### ISSUE THREAD

**Issue by wan2355** [gokcehan/lf#661]
I like to compile "lf" without internet connection.

I git clone "lf" github by another PC, and copy the github directory to the PC without internet connection.  
Move to "lf"  directory and type following command, and the error came up. 

$ env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w" github.com/gokcehan/lf
or 
$ env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w

go: github.com/gdamore/tcell/v2@v2.3.1: Get "https://proxy.golang.org/github.com/gdamore/tcell/v2/@v/v2.3.1.mod": proxyconnect tcp: dial tcp hogehoge:8080: i/o timeout

I download v.2.3.1.mod at another PC and copy this file under "lf" github directory at the PC without internet connection.
But I have same error.

Where should I place "v.2.3.1.mod" to compile "lf"
or
How do I compile "lf" ?

**Comment by gokcehan** [comment]
@wan2355 I don't know if this is possible. It does not seem to be related to `lf` though so maybe you should ask it in some Go community instead. I'm sure how this might be useful as well. You should be able to compile the program on the machine you clone the source and then move the resulting binary to the other machine without the internet connection.
