### ISSUE TITLE
Instructions for Linux beginners (Suggested addition to documentation)

### ISSUE THREAD

**Issue by Yekutiel** [gokcehan/lf#662]
I suggest you add the following...

### Instructions for Linux beginners

These instructions will work for most "regular" computers.

1. Download [lf-linux-amd64.tar.gz](https://github.com/gokcehan/lf/releases/download/r24/lf-linux-amd64.tar.gz).
2. Uncompress the tar file so that you end up with the file `lf`.
3. Move `lf` to `/usr/bin`.
4. Open a terminal 
5. Type `lf`.
6. Press the `Enter` key.
6. That's it!

**Note:** [kitty](https://github.com/kovidgoyal/kitty) is a very popular terminal for many good reasons.

**Comment by gokcehan** [comment]
@Yekutiel Thanks, in fact we have such beginner instructions in the [Tutorial](https://github.com/gokcehan/lf/wiki/Tutorial) wiki page.

**Comment by Yekutiel** [comment]
> @Yekutiel Thanks, in fact we have such beginner instructions in the [Tutorial](https://github.com/gokcehan/lf/wiki/Tutorial) wiki page.

I've got zero patience with ignorant indie FOSS developers therefore  I'll be **extremely** blunt: I suppose if you want Linux beginners to install lf my instructions are vastly superior the ones on [Tutorial](https://github.com/gokcehan/lf/wiki/Tutorial) wiki page. On the other hand, I suppose if you would like to remain in "techie ghetto" then your "simple instructions" will suffice to prevent myriad beginners from installing lf. It's your choice.

Oh. And. By the way. Your crazy looking image...
![1835672](https://user-images.githubusercontent.com/16394972/125088759-97ad0100-e082-11eb-9756-00c77485af2c.jpeg)


might seem cool to you, but ummm, er, well, it makes you seem like a lunatic.

I'm not going to invest my time learning an application that, frankly, seems like its being helmed by a madman.
