### ISSUE TITLE
Do you have any suggestions for improving the documentation?  If so, please create an issue. (Suggested addition to documentation)

### ISSUE THREAD

**Issue by Yekutiel** [gokcehan/lf#663]
I suggest you add the following to the documentation.

###  Do you have any suggestions for improving the documentation? 

If you have any suggestions for improving the documentation please create a new issue with your suggestions.

**Comment by gokcehan** [comment]
@Yekutiel I think this should implicitly assumed already. Do you have any suggestions for improving the documentation?

**Comment by Yekutiel** [comment]
LOL. It should **not** be implicitly assumed. I already made suggestions for improving the documentation which you seem to have ignored.
