### ISSUE TITLE
Icons aren't displaying

### ISSUE THREAD

**Issue by Barbarossa93** [gokcehan/lf#664]
Sorry for yet another "icons are borked" issue, I really tried digging aroound and couldnt find the solution. For some reason, the icons refuse to display within lf but work perfectly fine outside of lf. I'm using [cozette](https://github.com/slavfox/Cozette) icons which are intended to replace some of the nerd font icons with bitmap versions, so perhaps there's some property to it that doesn't work well with lf? I've tried running with `LC_ALL=en_US.UTF-8 lf` to no avail.

Icons in `.zshrc`:
![1625178566](https://user-images.githubusercontent.com/57952969/124196435-69d02700-da9a-11eb-9181-ef0b1cca5f97.png)

Icons in lf:
![1625178587](https://user-images.githubusercontent.com/57952969/124196452-76547f80-da9a-11eb-8660-2d908edc6e9c.png)

**Comment by Barbarossa93** [comment]
To verify its not a problem with my terminal, I tried running lf in alacritty. Icons appear, but they aren't at all the ones configured in the environment variable. They look like they're the default icons.

**Comment by gokcehan** [comment]
@Barbarossa93 You are not supposed to have any indentation when setting `LF_ICONS`.

**Comment by Barbarossa93** [comment]
Hey, thanks for the response! To clarify, there should be no tabbed space in front of each line?

**Comment by gokcehan** [comment]
@Barbarossa93 Tab or space, there should be no identation. You can try it out yourself.

**Comment by Barbarossa93** [comment]
Wow, that was it. Thank you so much!
