### ISSUE TITLE
lf crashes if I open file in neovim from lf

### ISSUE THREAD

**Issue by darrSonik** [gokcehan/lf#665]
My default editor is neovim. If I open a text of source file in `nvim` from lf, it just freezes. `nvim` opens alright but behaves bizzarely, `lf` doesn't respond even if I quit `nvim`, whole terminal window stays messed up until I force quit `lf`.

Is there any work to fix this?

The open command is attached below:
![open function](https://user-images.githubusercontent.com/34137568/124259427-4ff11b80-db50-11eb-8369-abdb23d05dc7.png)

**Comment by kmarius** [comment]
You are running nvim in the background, the command should just be `nvim $fx`.
