### ISSUE TITLE
tweak header 'prompt'

### ISSUE THREAD

**Issue by nsklaus** [gokcehan/lf#666]
is it possible currently to tweak the header 'prompt' ?
i'm refering to the "user@machine" part of the header, before the path (see screenshot).
as examples of tweaks i'm thinking about: i'd like to make it look different.
either display different values, or avoid displaying it completely, leaving only the current path to be shown. 
it'd be nice if there could be a place in lfrc where to specify what this 'prompt' should display.

![lfpic](https://user-images.githubusercontent.com/6810861/124293686-33a4ad00-db57-11eb-80e0-50bd9dd54195.jpg)

**Comment by shabahengam** [comment]
check `promptfmt` option.more info [here](https://pkg.go.dev/github.com/gokcehan/lf?utm_source=godoc) & and [here](https://github.com/gokcehan/lf/issues/50#issuecomment-367721160)

**Comment by nsklaus** [comment]
@shabahengam 
works well, thank you for the reply!
