### ISSUE TITLE
`lf -remote load` no longer lists cut/copy buffer

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#670]
`lf -remote load` used to list the cut/copied files which you could use for example [here](https://github.com/gokcehan/lf/wiki/Tips#add-to-cutcopied-files).

This no longer seems to work, with lf saying `listen: unexpected command: load`. Is there an alternative approach now?

**Comment by mohkale** [comment]
Looks like the buffer has been moved to the file-system (see `$XDG_DATA_HOME/lf/files`). You can modify it and then call load to re-sync the buffers.

**Comment by fredcallaway** [comment]
The default location is `~/.local/share/lf/files` if you don't have $XDG_DATA_HOME defined.
