### ISSUE TITLE
Lowering priority of executable icon

### ISSUE THREAD

**Issue by nabakolu** [gokcehan/lf#671]
The way lf handles icons for executable files is really unintuitive, as all executable files get the executable icon (rocket by default) assigned, regardless of filetype. For example this means, that an executable .sh file would not get the appropriate icon for .sh files.
A better way to do it, would be to only assign an executable icon, if the file does not match the crieteria of any other icon.
So that the executable .sh file would get an icon for .sh files, while an executable file with no mathcing icon would get the executable icon.  

A way to accomplish this would be like this:
```
diff --git a/icons.go b/icons.go
index a4122f8..a6ed8bf 100644
--- a/icons.go
+++ b/icons.go
@@ -101,8 +101,6 @@ func (im iconMap) get(f *file) string {
 		key = "su"
 	case f.Mode()&os.ModeSetgid != 0:
 		key = "sg"
-	case f.Mode()&0111 != 0:
-		key = "ex"
 	}
 
 	if val, ok := im[key]; ok {
@@ -121,6 +119,10 @@ func (im iconMap) get(f *file) string {
 		return val
 	}
 
+	if val, ok := im["ex"]; ok && f.Mode()&0111 != 0 {
+		return val
+	}
+
 	if val, ok := im["fi"]; ok {
 		return val
 	}


```

where the checking if a file is executable is performed after the checking for specfic file names and extensions.

**Comment by gokcehan** [comment]
@nabakolu Thanks for reporting. We have changed the priorities a few times already and every time there's a change a unintuitive case is reported. I think the latest discussion related to this was in #505 and #506 . We may need to go over the discussion there to decide if this would be a better approach or not.
