### ISSUE TITLE
lf does not open correct location when opening from other programs

### ISSUE THREAD

**Issue by DusanLesan** [gokcehan/lf#676]
For a while now i have problem with opening files from vs code or slack. They are offering a option to see some file in the file manager but when I  pick that option, path opened is not exactly right.

When I try to open file `~/.config/lf/lfrc` from the vs code, the lf is opened at `~/.config/` with the focus on the first item.
When I try to open `lf ~/.config/lf/lfrc` it works ok. `xdg-open ~/.config/lf/` opens right as well.
A have also noticed that dbus event is also getting right path when trying to open file

Is this known behavior for lf to miss the correct path? Can I do something to make it right? Can I make dbus to open lf without creating always active processes listening for events?

**Comment by kmarius** [comment]
Can you show us the command line arguments that `vscode` gives to `lf`? You can see them with `top` or `htop`.

**Comment by DusanLesan** [comment]
> Can you show us the command line arguments that `vscode` gives to `lf`? You can see them with `top` or `htop`.

I am seeing this: 
![image](https://user-images.githubusercontent.com/20520590/127996240-a0114ba0-1311-4398-87c5-160abdc4f60a.png)

**Comment by kmarius** [comment]
It looks like this is actually the intendet behaviour (on `vscode` side). Opening the directory in a file manager makes more sense than openen the file. `vscode` doesn't know that `lf` can also select the file. I don't know if this behaviour can be changed.

**Comment by DusanLesan** [comment]
So it looks like code, slack and skype are all using `lf .` But they are not opening the directory containing my file. In the example from the description, notice how it is opening `~/.config/` when I tried to open `~/.config/lf/lfrc`. I would expect it to open at `~/.config/lf/` if it only targeted the directory. Like the starting point is not right. Are thunar or such file managers using dbus to open correctly? Could I set up lf to use dbus?

**Comment by kmarius** [comment]
Ah, I missed that in your first post. In that case you would have to first find out how `lf` is being launched. Are you using a `.desktop` file? Have you configured *anything* regarding `lf` in `vscode`?

**Comment by DusanLesan** [comment]
I have defaults in mimeapps.list file where the inode/directory=lf.desktop
Desktop file was made automatically on install where Exec=lf. I was trying with %u and %f in exec too but that made no difference. I do not have access to edit what command code is running when I select option "Open Containing Folder" for selected file. My code settings file contains only several unrelated entries. They also do not have a option to create my own entry in the context menu without creating extensions.

**Comment by DusanLesan** [comment]
@kmarius Also it may be helpful to see in the image that xdg-open was called first

**Comment by kmarius** [comment]
@DusanLesan Why didn't you tell us that you had [already opened an issue?](https://github.com/microsoft/vscode/issues/127818) Anyway, I observed the same behaviour with `thunar` so I don't think we can do anything about it here.

**Comment by DusanLesan** [comment]
@kmarius Sorry, it did not seam relevant to me as I have seen this behavior in multiple other programs later. I have installed thunar to verify and it is working ok. With the focus on selected file

**Comment by kmarius** [comment]
Ok, I have to retract what I said earlier. Thunar does indeed select the file correctly, but only if there is already another instance running. Apparently the communication over dbus does not work with the first instance. `Lf` does not offer a dbus interface, so the interesting question would be  if and how it works in other file managers (ranger, vifm, ...) or if one could make a wrapper that calls `lf -remote`.

**Comment by DusanLesan** [comment]
Ranger behaves the same.
Closing code leaves no processes mentioning electron
Even if I run `pkill Thunar`, It will open correctly for me
No matter what is my default file manager, these apps always open thunar. I guess these apps call dbus and if nothing responds they use `xdg-open .` as a fallback

**Comment by kmarius** [comment]
I found https://github.com/dirk-olmes/dbus-file-manager/blob/master/expose-filemanager.py and put together

```
#!/usr/bin/env python

import dbus.service
from gi.repository import GLib

from dbus import SessionBus
from dbus.mainloop.glib import DBusGMainLoop

import os
import re


class LfFileManager(object):
    def ShowItems(self, items):
        for item in items:
            item = re.sub("file://", "", item)
            os.system("foot lf '{}' &".format(item))


class ExposedFileManager(dbus.service.Object):
    BUS_NAME = 'org.freedesktop.FileManager1'
    INTERFACE = 'org.freedesktop.FileManager1'

    def __init__(self, connection, object_path):
        bus_name = dbus.service.BusName(self.BUS_NAME, connection)
        dbus.service.Object.__init__(self, bus_name, object_path)
        self.file_manager = LfFileManager()

    @dbus.service.method(dbus_interface=INTERFACE, in_signature='ass', out_signature='')
    def ShowItems(self, items, startup_id):
        self.file_manager.ShowItems(items)
        return None


if __name__ == '__main__':
    DBusGMainLoop(set_as_default=True)

    bus = SessionBus()

    object_path = '/org/freedesktop/FileManager1'
    filemanager = ExposedFileManager(bus, object_path)

    loop = GLib.MainLoop()
    loop.run()
```

It works for me, but it likely does not adhere to the specification and might interfere with any other file managers running. The file name is also not escaped (must not contain `'`) and the terminal (`foot` in my case) should be changed.

**Comment by DusanLesan** [comment]
Works for me too. You could edit it so it reads system variable to get terminal

**Comment by kmarius** [comment]
> Works for me too. You could edit it so it reads system variable to get terminal

Unfortunately this is futile because we don't know which flags are needed to run the command. Maybe some opener should run it, but I *really don't* want to deal with `xdg-open`.
