### ISSUE TITLE
[Windows] Doesn't react on keyboard input after running any shell command with shell-wait

### ISSUE THREAD

**Issue by jdfa** [gokcehan/lf#677]
This issue appeared for me after upgrade to version 0.23, also reproduced on 0.24. 
When I run any shell command with `shell-wait` - I am getting some results and string "Press any key to continue". 
After pressing it - main view is rendered, but keys are not working. I can only end `lf` task to proceed working in terminal.

**Comment by gokcehan** [comment]
@jdfa We bumped our tcell version in r23 which is probably related to this issue.

**Comment by gokcehan** [comment]
I have pushed a new release r26 with the fix today. Closing this issue now. Feel free to report back here if the issue persists for some reason.
