### ISSUE TITLE
[QUESTION] Is it possible to preview images in WezTerm on MacOS?

### ISSUE THREAD

**Issue by is0n** [gokcehan/lf#678]
I imagine this is possible as [WezTerm](https://github.com/wez/wezterm) supports [image previews](https://wezfurlong.org/wezterm/imgcat.html), however, I haven't seen any mention of this in the wiki.

**Comment by idr4n** [comment]
I'm wondering this as well. I tried `wezterm imgcat $file` which is the command to preview images in WezTerm but it didn't work. I wonder if there is a way as WezTerm seems to do a good job in displaying images.

**Comment by latipun7** [comment]
As mentioned by @gokcehan in https://github.com/gokcehan/lf/issues/675#issuecomment-890354915

> Long answer, we interpret escape codes ourselves for the previews instead of pushing them directly to the terminal. Currently we only have standard color escape codes and other things are ignored.

As I understand, WezTerm `imgcat` is converting image to iTerm2 Graphics Protocol which WezTerm could interpret that and display as image. While displayed in `lf`, unknown escape codes are ignored so the image is not displayed inside `lf`.

> At some point, I thought about pushing unknown escape codes directly to the terminal so things like sixels might work.

I really want this to be implemented so maybe `lf` can display images based on terminal capabilities.

**Comment by joelim-work** [comment]
Sixel support was officially added in dd82949, so this should be possible so long as you install a tool like [`chafa`](https://github.com/hpjansson/chafa) to convert the images to Sixel format. This is now documented in the [wiki](https://github.com/gokcehan/lf/wiki/Previews#with-sixel).
