### ISSUE TITLE
[Question] How can I access an argument passed to a custom command?

### ISSUE THREAD

**Issue by mroavi** [gokcehan/lf#680]
I know that you can use `$` to access arguments passed to a *shell* command, e.g.
```
cmd mkdir %mkdir "$1"
```

Is it also possible to access arguments passed to *custom* commands? E.g.:
```
cmd myecho echo <ARG1>
```

I couldn't find this info anywhere in the docs.

**Comment by kmarius** [comment]
Unfortunately this is not possible. The closest you can get to it is using shell commands and calling back with `lf -remote`.

**Comment by mroavi** [comment]
Thanks.
