### ISSUE TITLE
Fedora repositories link return Error 404: Not Found

### ISSUE THREAD

**Issue by the-cli** [gokcehan/lf#689]
Hi, has anyone found a way to install lf through package manager? The link provided on https://github.com/gokcehan/lf/wiki/Packages is broken.

**Comment by the-cli** [comment]
if i install using go get from this instruction 
`env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w" github.com/gokcehan/lf`
say if you release a newer version in future. I can run 
`go get -u github.com/gokcehan/lf` again to receive the latest update? 

Apologize for the amateur question, very new to this language.

**Comment by gokcehan** [comment]
@the-cli I think yes, but I'm not 100% sure to be honest. It might depend on what version of Go you have installed as they keep changing these things in the language. Also I think from Go 1.17 onwards they deprecated `go get` in favor of `go install` as mentioned [here](https://golang.org/doc/go-get-install-deprecation).
