### ISSUE TITLE
Last commit changed the chdir behavior

### ISSUE THREAD

**Issue by jakubreron** [gokcehan/lf#690]
![image](https://user-images.githubusercontent.com/25802053/130793233-2a986022-74aa-46ad-9455-a5fed352993f.png)

I get `/home/user/my_custom_path`
instead of `my_custom_path`

After the [last commit](https://github.com/gokcehan/lf/commit/05a48ea315fc4a1aafca22361da401219a21579f) it started working like this, I don't remember that the `/home/user` prefix was there before

here is the script:
```sh
map J $lf -remote "send $id cd $(cut -d'	' -f2 ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | sed 's/\${.*\://;s/\-\$HOME/~/;s/$HOME/~/;s/}//' | fzf | rev | cut -d' ' -f1 | rev  )"
```

How can I restore the previous behavior?

**Comment by gokcehan** [comment]
@jakubreron This was not intentional. A simpler example to reproduce the issue is to use the default `gh` binding (i.e. `map gh cd ~`) which should simply switch to the home directory but it does not.

@SPFabGerman Can you look into this issue?

**Comment by gokcehan** [comment]
cc #685

**Comment by SPFabGerman** [comment]
That is really interesting. The issue comes from the check in line eval.go in line 1176. (`if !filepath.IsAbs(path) {`) For some reasons `~` or any path that starts with `~` is not interpreted as a absoulte path, causing the wrong if branch to be used.
Im fixing this right now.

**Comment by gokcehan** [comment]
@SPFabGerman Thanks for the fixes.
