### ISSUE TITLE
featues: --chosefile, --choosedir, --show-only-dirs, show_selection_in_titlebar 

### ISSUE THREAD

**Issue by user-b** [gokcehan/lf#692]
Any chances these features of ranger could be added to lf? Calling ranger with `--choosedir --show-only-dirs` allows to use ranger as a dir picker, to save files from the web for example. Lf shines for its speed so it would be much better than ranger for this. `set show_selection_in_titlebar false`  just hides the file name from the path shown at the top.

Thanks.

**Comment by gokcehan** [comment]
@user-b I think `--show-only-dirs` is recently merged in #669 with the option name `dironly` which can be used from the command line with something like `lf -command 'set dironly'`.  It is currently available in master and should be included in r25 release in the future. And if I'm not mistaken `--chosedir` is implemented with the argument `-last-dir-path` so your suggestion should already be possible.

**Comment by user-b** [comment]
Thanks, I misunderstood `-last-dir-path` and wasn't aware of #669. It's or it's planed to be possible to hide the file name from the title bar when using lf as usual, without `-last-dir-path`  and/or `dironly`?

**Comment by gokcehan** [comment]
@user-b What do you mean by title bar?

**Comment by user-b** [comment]
I borrowed that from ranger:

```
# Add the highlighted file to the path in the titlebar
set show_selection_in_titlebar false
```

My personal/particular usecase for this is, to use ranger/lf with only one column (plus  the preview). For this  that "title bar" must show the current dir (not the selected one) because of not having another column showing that information. The selected file is highlighted anyway..

In other words, that means turning this:
/home/me/current_dir/**selected file**

Into this: 
/home/me/**current_dir** 

Don't know how you call that, it's the path on top, over the columns/file previews.

**Comment by gokcehan** [comment]
@user-b I see, we call it prompt in lf and there is a `promptfmt` option to customize it as you like.

**Comment by user-b** [comment]
Nicely done, thank you! Dropping ranger, never though this could ever happen.
