### ISSUE TITLE
Run a very long command 

### ISSUE THREAD

**Issue by kexul** [gokcehan/lf#693]
Hi, when running a very long command, there won't be a new line, then I would not know what I typed, is there any solution for this?

**Comment by slavistan** [comment]
Could you be a little more precise? I've had trouble here and there with narrow terminals and wide lines and I've may be able to help you. Is your command long or the output of the command? Or something else?

**Comment by kexul** [comment]
> Could you be a little more precise? I've had trouble here and there with narrow terminals and wide lines and I've may be able to help you. Is your command long or the output of the command? Or something else?

Thank you，it is my command too long.

**Comment by slavistan** [comment]
Alright, which command? Please post an example here.

lf gives you one command line, that's true, but I question the necessity to manually type out long commands. If you provide even more context we'll find a way.

**Comment by kexul** [comment]
Wow! I just upgrade my lf to the latest version and found out it could move the line to the left side when the command is longer than the screen, so my problem no longer exists. Thanks for your reply so far!
