### ISSUE TITLE
Size not refreshed

### ISSUE THREAD

**Issue by desbma** [gokcehan/lf#696]
When showing a directory with `lf`, and copying a big file into this directory either from another shell, or from an async `lf` command, the new file shows up, but its size (enabled with `set info "size"` in `~/.config/lf/lfrc`) is not updated to the final size once the copy is finished.

Running `set period 1`, `load`, or changing directory still shows the outdated file size. The only way to make it show the right size is to restart lf.

By the way, this a great project, I recently switched from ranger, and I love it so far :+1:

**Comment by shabahengam** [comment]
you should use `reload` command. press `Ctrl+r` or put something like this in your lfrc, so you can press `r` for reloading.
```
map r reload
```
from docs:
```
load 
Synchronize the terminal and redraw the screen.

reload                   (default '<c-r>')
Load modified files and directories. This command is automatically called when required.

```

**Comment by desbma** [comment]
Thanks that fixed it, although it's a bit confusing because one might expect `load` does more than `reload`.

**Comment by gokcehan** [comment]
@shabahengam Explanations are below the command so the documentation should actually read as follows:

```
load
Load modified files and directories. This command is automatically called when required.

reload                   (default '<c-r>')
Flush the cache and reload all files and directories.
```

@desbma `load` command works with directory modification times to skip redundant readings of directories which often works well but sometimes fails as in your case. `reload` command is essentially a force `load` to flush the cache for such cases. Unfortunately, I'm not good at naming things :)

**Comment by shabahengam** [comment]
@gokcehan Oops.Sorry.Deleted my comment about docs to avoid confusion.
