### ISSUE TITLE
Symlinks from wiki

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#700]
I use a highly modified lfrc but I can not get symlinks creation work.
If I understand the code correct it creates a file in .local/share/lf/files and temporarily adds the path to this file.
The file will not be created AND if I manually create it it will stay empty.

I have bound yy to cp and x to mv that should not be a problem. 
Any ideas?

**Comment by gokcehan** [comment]
@se7en-x230 What version are you using? Use of files for copy and paste is added in r23.

I have tried the example in the wiki and it seems to work fine in my machine. There might be something related to this in your configuration file. Maybe you might try with a configuration file to locate the issue.
