### ISSUE TITLE
Icons aren't being displayed at all despite setting icons to true

### ISSUE THREAD

**Issue by MuizU** [gokcehan/lf#702]
These are my current settings
```
set shell zsh
set shellopts '-euy'
set ifs "\n"
set filesep "\n"  # default already
set icons true
set scrolloff 10
set color256 true
set ifs "\n"
set period 1
set promptfmt "\033[34;1m%w/\033[0m\033[1m%f\033[0m"
set ratios 1:2:3
```

My screen however looks like this.
![Screenshot_20211002_185640](https://user-images.githubusercontent.com/35157872/135718404-cb1a3e5e-fb74-49e1-bb0f-3bdd4f6a559b.png)

This is all happening despite me installing FiraCode Nerdfont. Icons appear in my terminal (kitty). It just doesn't appear in lf.

**Comment by gokcehan** [comment]
@MuizU I can display icons with your configuration file. What's the value of `$LF_ICONS` variable?

Can you update to the latest version if you're not already using it? `color256` option is removed a while ago.

Also boolean options does not use `true/false` to set. Please see syntax section in the documentation.

**Comment by ppk-gh** [comment]
Same issue here, icons appear once I run `set icons on` within LF itself however.

**Comment by gokcehan** [comment]
@ppk-gh You probably have an error in your lfrc then. Also see #758

**Comment by ppk-gh** [comment]
Yep, an add-on was pointing to its own config file which didn't have them enabled.
