### ISSUE TITLE
How to combine `lf` and `fzf` like ranger’s fzf integration ?

### ISSUE THREAD

**Issue by akharrou** [gokcehan/lf#705]
Here's ranger's fzf integration: https://github.com/ranger/ranger/wiki/Custom-Commands#fzf-integration

I want to be able to press a keyboard shortcut and have an fzf prompt come up that shows me all the files and directories under the currently selected file/folder in `lf`, then after i fuzzy search and select the thing i want, i would like lf to jump to that file/directory.

is that possible ? and if so, how so ?
this would be a wonderful and productivity boosting integration IMO, something worthy of putting in the docs too as an example integration.

**Comment by fzhzhen1987** [comment]
ranger fzf_select in lf 

`cmd fzf_select ${{
    res="$(find -L . \( -path '*/\.*' -o -fstype 'dev' -o -fstype 'proc' \) -prune -o -print 2> /dev/null | sed 1d | cut -b3- | fzf +m)"
    if [ -d "$res" ] ; then
        cmd="cd"
    elif [ -f "$res" ] ; then
        cmd="select"
    else
        exit 0
    fi
    lf -remote "send $id $cmd \"$res\""
}}`

**Comment by timoleistner** [comment]
```
cmd fzf_search ${{
    res="$( \
        RG_PREFIX="rg --column --line-number --no-heading --color=always \
            --smart-case "
        FZF_DEFAULT_COMMAND="$RG_PREFIX ''" \
            fzf --bind "change:reload:$RG_PREFIX {q} || true" \
            --ansi --layout=reverse --header 'Search in files' \
            | cut -d':' -f1
    )"
    [ ! -z "$res" ] && lf -remote "send $id select \"$res\""
}}

cmd fzf_infile ${{
    res="$(fd --type f | fzf --reverse --header='Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
    if [ -d "$res" ] ; then
        cmd="cd"
    elif [ -f "$res" ] ; then
        cmd="select"
    else
        exit 0
    fi
    lf -remote "send $id $cmd \"$res\""
}}

map <c-t> :fzf_infile
map <c-f> :fzf_search
```
