### ISSUE TITLE
Using charmbracelet/glow as a previewer for .md

### ISSUE THREAD

**Issue by elmarsto** [gokcehan/lf#706]
Hi all,

I'm *this* close to nerdvana and I need your help.

basically, https://github.com/charmbracelet/glow works great as an .md previewer. The problem is that, when used as a previewer for .md files in `lf`, the preview comes out with no colors.

`bat` worked great after I `unset COLORTERM`, but messing with COLORTERM and TERM has not produced a change. 

Has anyone else here gotten glow to work as a previewer? 

It works rather well as `glow -p` for an .md *opener*, so I can live with B&W previews if I have to

**Comment by emilBeBri** [comment]
elmarsto could you share your lfrc file and/or pv.sh file to show me how to accomplish this? thank you!
