### ISSUE TITLE
Support platform specific configurations

### ISSUE THREAD

**Issue by LinArcX** [gokcehan/lf#707]
In c programming language, we can use conditional macro to write code for different platforms and operating systems:

```
#ifdef WIN32
   // code for Windows systems
#else
   // code for other systems
#endif
```

Right now, if a LF user is working on both windows and linux, he/she should create different config files for each OS. I think it's a good idea to provide a way to handle this situation.

**Comment by gokcehan** [comment]
@LinArcX This might be useful but our config syntax is too basic for such things. It might be possible to utilize `source` for this purpose.

**Comment by Konfekt** [comment]
https://github.com/gokcehan/lf/wiki/Tips#configuration-dependent-on-os talks about MacOS and Linux, but Windows would also be interesting. How does source work?

**Comment by Konfekt** [comment]
I could only come up with the work around

```
${{
    cd $HOME || lf -remote "send $id source ~/.config/lf/win32.lfrc" && exit
                lf -remote "send $id source ~/.config/lf/unix.lfrc"
}}
```
