### ISSUE TITLE
LF crashes if I switch between terminal and come back to LF

### ISSUE THREAD

**Issue by LinArcX** [gokcehan/lf#709]
OS: windows
Shells: cmd, powershell, yori

In all mentioned shells, if you open `lf` and hit `w` and type exit to come back to `lf`, it will freeze.

I didn't have this issue on my linux machine(with bash)

**Comment by gokcehan** [comment]
@LinArcX There was such a bug in windows which was fixed in r26. Can you confirm you are using the latest version?
