### ISSUE TITLE
New eval command to set ui message

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#71]
Several of my own blocking commands (`$` or `${{ }}`) have error branches which tell the user what went wrong. Currently the only way to do that is to simply write to `stdout` or `stderr`. This works, but is inconsistent with the `lf` interface.

Could you please add a dead simple command (to be used with `lf -remote`) which sets the `app.ui.message` string? There might also be some regex check, whether the string won't do any harm to the terminal (to stay consistent with `lf` messages, I would suggest allowing just ASCII printable characters `^[[:print:]]*$` - the asterisk would allow "erasure" of the current content).

Setting a message might be useful also for other cases, not only error messages.

**Comment by gokcehan** [comment]
You can set a message with `lf -remote "send $id echo 'this message is shown in the status line'`.

`echo` command itself was bugged a while ago and doesn't show any messages when it is run from inside lf. I think it is immediately overridden after it is executed. I shall clean the code to fix it again.

**Comment by dumblob** [comment]
Sorry for the fuss, I didn't look carefully enough. Though the regex sanitization might still be worth adding (in case it wouldn't match the string, some other error string like `send echo: argument not satisfying regex ^[[:print:]]*$` would be used).

**Comment by gokcehan** [comment]
I have added `shell-pipe` commands (`%`) a while ago, which makes displaying output in the statline even easier. Closing this issue now.
