### ISSUE TITLE
r26, Windows, multiline shell command does not work

### ISSUE THREAD

**Issue by dejeppo** [gokcehan/lf#710]
lf: r26
OS: Windows
Shell: cmd
 
works:
`cmd name $command`

works:
`cmd name ${{command}}`

 does not work:
```
cmd name ${{
  command
  command
}}
```

**Comment by gokcehan** [comment]
@dejeppo This is a known issue that I don't know how to fix. You can create separate script files and call them in a single line in windows as mentioned in `etc/lfrc.cmd.example` and `etc/lfrc.ps1.example`.

**Comment by dejeppo** [comment]
ok thanks
