### ISSUE TITLE
Paste-overwrite doesn't work anymore

### ISSUE THREAD

**Issue by itsdeadguy** [gokcehan/lf#715]
Hello, i'm not sure how long this has been going on now, but i've noticed it only recently.

This paste-overwrite command (don't remember where it came from, the wiki maybe?, i've had it for quite some time) no longer works.

```
cmd paste-overwrite %{{
    load=$(lf -remote 'load')
    mode=$(echo "$load" | sed -n '1p')
    list=$(echo "$load" | sed '1d')
    if [ $mode = 'copy' ]; then
        cp -r $list .
    elif [ $mode = 'move' ]; then
        mv $list .
    fi
    lf -remote 'send load'
    lf -remote 'send clear'
}}
map po paste-overwrite
```

I've also tried the solution proposed in #561 but it was also a no go (yes, rsync is installed). Am I doing something wrong?

lf version r26 on Void Linux

**Comment by se7en-x230** [comment]
Works her. 
Have you "unmaped" p and assigned normal paste to something like "pp"?

**Comment by kmarius** [comment]
The remote command `lf -remote load` doesn't exist anymore, instead the file list is written to `~/.local/share/lf/files`. Try replacing the lines 

```
load=...
mode=...
list=...
```

with

```
mode=$(head -1 ~/.local/share/lf/files)
list=$(sed 1d ~/.local/share/lf/files)
```

_Somebody_ should probably change that in the wiki where necessary.

**Comment by itsdeadguy** [comment]
@kmarius thank you very much, that did the trick. I'm gonna go ahead and close this.
