### ISSUE TITLE
Error when copying files in mounted NTFS partition

### ISSUE THREAD

**Issue by amineden** [gokcehan/lf#716]
similar to issue [415](https://github.com/gokcehan/lf/issues/415), I have shared partitions with my windows installation, they are mounted manually using `/etc/fstab`, whne trying to copy files to the partitions I get this message: `[3] copy: chmod /home/user/folder/file: operation not permitted` (there's a symbolic link to /run/media where the partitions are mounted, copying at the original location doesn't work either)
this is my `ftsab`

```
# <file system> <dir> <type> <options> <dump> <pass>
UUID=2B6989F276F031DA	/run/media/amine/C		ntfs	rw,user,exec,umask=000	          0	  0
UUID=72E0CB18E0CAE189	/run/media/amine/D		ntfs	rw,user,exec,umask=000	          0	  0
UUID=FAE4C346E4C303BB	/run/media/amine/E		ntfs	rw,user,exec,umask=000	          0	  0
```

moving, deleting renaming files works normally

**Comment by gokcehan** [comment]
@amineden Can you copy files normally from shell using `cp`?

**Comment by mimshipio** [comment]
Try following [this guide](https://wiki.archlinux.org/title/NTFS-3G#Linux_compatible_permissions)
