### ISSUE TITLE
Open multiple files with the same instance

### ISSUE THREAD

**Issue by sucrecacao** [gokcehan/lf#719]
Hello,

Don't know if it's a bug or a feature request, but here is my trouble:

Selecting 3 mp3 with `lf` ( pressing `space` three time) and opening them ( pressing `l` ) it open 3 instance of `mpv` like if I did:
```
mpv file1.mp3
mpv file2.mp3
mpv file3.mp3
```

But what I would expect, is to have a behaviour similar to ranger, opening the three mp3s in the same mpv instance:
```
mpv file1.mp3 file2.mp3 file3.mp3
```

Is there a way to hack the default opening command to achieve this behavior?

bests,

**Comment by BachoSeven** [comment]
Just create a custom command, this should work:
```
cmd open_bulk ${{
    lf -remote "send $id open $fx"
}}

map L open_bulk
```

**Comment by kmarius** [comment]
If you use the `open` command form the example `lfrc` then the line 

      *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;

runs the opener on each file. Try replacing it with 

      *) setsid $OPENER $fx >/dev/null 2>/dev/null &;;

(and similarly if you use a command from the wiki). This obviously won't work if you try to open e.g. videos and text files at the same time.

**Comment by ralphee** [comment]
> Just create a custom command, this should work:
> 
> ```
> cmd open_bulk ${{
>     lf -remote "send $id open $fx"
> }}
> 
> map L open_bulk
> ```
> 
> Edit: of course, if you wanted to you could just map this to `l`, overriding the default behaviour.
> 
> Also, have a look at [this](https://github.com/gokcehan/lf/blob/5d02b557d3ea694d8a51cc3918ab5ffda33387d9/etc/lfrc.example#L34) if you want to tweak the `open` function for specific filetypes/extensions, since the default is to just call `xdg-open`.

unfortunately this does not work for me (trying to open multiple files in mpv or sxiv)

**Comment by mnabila** [comment]
@sucrecacao Have you found this solution?

**Comment by mnabila** [comment]
@sucrecacao  Have you found a solution for this issue ?

**Comment by sucrecacao** [comment]
@mnabila no, not yet

**Comment by BachoSeven** [comment]
@sucrecacao Did you try the aforementioned solutions?

**Comment by sucrecacao** [comment]
@BachoSeven

Yes but didn't worked as intended

 @mnabila, @BachoSeven 

Made it work with the following snippet:
```
cmd open ${{

    # what to do with simlinks?
    # test -L $f && f=$(readlink -f $f)
    image_acc=""
    audio_acc=""
    video_acc=""
    set $fx
    while [ $# -gt 0 ]; do
      case $(file --mime-type $1 -b) in
           text/*) $EDITOR $1;;
           */json) $EDITOR $1;;
           image/*)
             image_acc="$image_acc $1";;
           audio/*)
             audio_acc="$audio_acc $1";;
           video/*)
             video_acc="$video_acc $1";;
           *) xdg-open $1;;
      esac
      shift
    done
    # sxiv $( echo $image_acc)
    test -n $image_acc && (eval "sxiv $image_acc" &)
    test -n $video_acc && (eval "mpv --no-terminal  $video_acc" &)
    test -n $audio_acc && (eval "mpv --no-terminal  $audio_acc" &)

}}
```

**Comment by mnabila** [comment]
@sucrecacao i was try this solution but not working on my device, 

ps: can i see your full configuration ?

**Comment by mnabila** [comment]
I have found the solution for my lf

handle multiple file

```
IFS="";eval "program_name $(echo $fx | awk '{ printf "\"%s\" ", $0 }')"
```


example implementation
```
# file opener
cmd open ${{
    case $(file --mime-type "$f" -bL) in
        video/*) IFS="";eval "mpv $(echo $fx | awk '{ printf "\"%s\" ", $0 }')"  &>/dev/null &;;
        *) xdg-open "$f" &>/dev/null & ;;
    esac
}}
```


cc @sucrecacao @BachoSeven

**Comment by sucrecacao** [comment]
> @sucrecacao i was try this solution but not working on my device,
> 
> ps: can i see your full configuration ?

That should be enought, maybe you already have a `open` cmd defined. Also, you should have mpv and sxiv installed, and bulk open only work for audio, video and image.

To make it work select multiple files with space and then type `:open<return>`

**Comment by BachoSeven** [comment]
> 

Congrats on figuring it out!

MAybe this can be closed now

**Comment by sucrecacao** [comment]
sure, also want to link this config:
https://github.com/LukeSmithxyz/voidrice/blob/ed9a67ed6dbd408032f51f34a471362264c47e1c/.config/lf/lfrc#L16
