### ISSUE TITLE
Cycle through completion candidates by hitting the tab key repeatedly

### ISSUE THREAD

**Issue by lenormf** [gokcehan/lf#72]
Hi,

Right now, we have to keep typing to get as close as possible to the one candidate we want, which could be improved if the current text was cycling through all the available candidates when hitting `tab`.

Thanks.

**Comment by gokcehan** [comment]
It could be nice since we already show all possible matches we could highlight the current selection in the ui and maybe provide keybindings to move up/down/left/right. I would probably prefer the current method though so it would be nice to add this as an option (e.g. `completeopt` in vim).

**Comment by tarasyarema** [comment]
I'm having a look at this right now, and I guess there should be some refactor in terms of how the `ui.menuBuf` https://github.com/gokcehan/lf/blob/e36b1b048469a3388ee9e1f1a438cfe9c9ba42d2/ui.go#L751 is printed.
Now it's printed line by line, so there's no track of the elements of the menu buffer. 

The first thing that comes into my mind is storing the elements of the menu buffer in a list, in the ui struct. So this way the implementation of the tabbing would be easier. Plus it could be implemented a simple filter for when you begin writing.

**Comment by gokcehan** [comment]
@tarasyarema Note that `ui.menuBuf` is also used for other displays like keybindings and bookmarks in which cyclic completion is not applicable. Maybe we add a field like `ui.menuInd` to hold the current index in the list and pass this variable to `listMatches` along with the list of matches to build a `bytes.Buffer` but this time with the `ui.menuInd` reverse highlighted. Each subsequent `cmd-complete` should increase `ui.menuInd` somehow.

Don't let me misguide you though. It's difficult to tell how to make this work without trying it out myself. If you can come with a working solution in any way you can send a PR and we can discuss it further.

**Comment by tarasyarema** [comment]
@gokcehan I created a pull request (#482) implementing what you said, seems like it works.

Here's a quick demo:
![lf cycling](https://i.imgur.com/OgcTc5w.gif)

**Comment by tarasyarema** [comment]
Created a pull request #482 implementing this feature.

Here's a quick demo:
![Cycle demo](https://i.imgur.com/nwhRr4q.gif)
