### ISSUE TITLE
how do I read user input from status line

### ISSUE THREAD

**Issue by smartding** [gokcehan/lf#720]
Sorry if this is a simple question.

I want to write a command to get user confirmation before actually deleting any file.

```
cmd delete ${{
    lf -remote "send $id echo are you sure to delete?"
    <how do I read user input (y/n) into variable "ans"?>
    [ "$ans" = "n" ] || rm -rf -- $fx
}}
```

**Comment by kmarius** [comment]
A command run with `%` can take input from (and send output to) `lf`

    cmd delete %{{
        echo "are you sure to delete? "
        read ans
        ...
    }}

You will have to press enter, `bash`s `read -n 1` option doesn't seem to work. (Personally, I would also switch the last line to `[ "$ans" = y ] && rm -rf -- $fx`).

**Comment by smartding** [comment]
Cool, thanks
