### ISSUE TITLE
Use XDG_RUNTIME_DIR on Linux for runtime files instead of /tmp

### ISSUE THREAD

**Issue by desbma** [gokcehan/lf#722]
On Linux, `lf`currently uses `/tmp` to store runtime files (logs & sockets).

The usual convention is to use a directory under $XDG_RUNTIME_DIR environment variable, which is usually something like `/run/user/{UID}/lf`. See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for more context and full specifications.

This is a user specific directory, so it solves races and conflicts between users.

**Comment by gokcehan** [comment]
@desbma We are currently using [os.TempDir](https://pkg.go.dev/os#TempDir) provided by Go which seems to return `/tmp` on linux. I don't know their rationale for this choice. I did not see any function returning `/run/user/{UID}` in `os` package either. There is [os.UserCacheDir](https://pkg.go.dev/os#UserCacheDir) returning `$HOME/.cache` by default but I don't think this directory is cleaned up after a restart. I'm open to changing this as long as we don't need to hardcode the directory ourselves and it is provided by Go somehow. In the meantime, we already add usernames to runtime files to avoid conflicts. Documentation also mentions that you can override the directory by setting `$TMPDIR` on linux. I hope that helps.

**Comment by desbma** [comment]
Go has a `xdg` package for that : https://github.com/adrg/xdg
