### ISSUE TITLE
-version prints nothing

### ISSUE THREAD

**Issue by c02y** [gokcehan/lf#723]
Whether I install lf from my ArchLinux repo or using `go install`

`lf -version` prints nothing.

**Comment by mbpowers** [comment]
I use arch and am getting the correct behavior:
```bash
[user@arch ~]$ lf -version
24.r10.g85aa3b9
```
If you do `yay -Q lf-git` it should show you the version you downloaded (if you aren'y using yay as your AUR helper, replace yay with whatever AUR helper you are using). 
What is your set up?

**Comment by c02y** [comment]
Now, lf from ArchLinux prints the right version(Don't know why), but `go install` still prints nothing.

**Comment by kmarius** [comment]
The version information is injected by the build script, see for example https://github.com/gokcehan/lf/blob/master/gen/build.sh. You will have to `git clone` und run that script to include version information. I think the next version of go will make it possible to embed vcs info into the binary for this very reason.
