### ISSUE TITLE
No bindings from lfrc loaded when using sudo

### ISSUE THREAD

**Issue by mbpowers** [gokcehan/lf#724]
When using `sudo lf` to work within directories that require permissions none of my bindings are loaded from my config. 

Is this intentional because it is somehow unsafe to use lf with sudo or is this a bug? If it is unwise be using `sudo lf`, is there a preferred way to work on files that require permissions within lf?

**Comment by kmarius** [comment]
If you run lf with `sudo` it will read the config from `/root/.config/lf/lfrc`. If you were to link the config to yours or pass it via a command line flag, then that would be considered a risk. Otherwise I don't see a problem.

**Comment by mbpowers** [comment]
That makes a lot of sense that sudo wouldn't read my user config now that you pointed it out lol... thanks! From your last answer I would assume it would be, but would it be unsafe to symlink my user config to the root config?

**Comment by kmarius** [comment]
Symlinking your the root config to yours would give an attacker another way to escalate previleges (by adding commands to your `lfrc` with your normal user previleges). Note that many common `sudoers` configs (yours, and mine too) are not secure against this: an attacker could modify `PATH`, hijack `sudo` and steal your password. Ultimately it is up to you, but for me symlinking goes one step too far.

**Comment by se7en-x230** [comment]
Why not use
cmd mkfiles ${{
  printf "File Name: "
  read ans
  sudo touch $ans
}}
cmd mkfiles ${{
  printf "File Name: "
  read ans
  sudo touch $ans
}}

cmd sudoedit ${{
  sudoedit $f
}}

**Comment by mbpowers** [comment]
Thank you for the advice @kmarius and inspiration for commands @se7en-x230. Here are my commands, they try to not use sudo unless necessary.

`cmd mkdir ${{ printf "Folder Name: "; read ans; mkdir $ans 2> /dev/null || sudo mkdir $ans }}`

`cmd touch ${{ printf "File Name: "; read ans; touch $ans 2> /dev/null || sudo touch $ans }}`

```
cmd delete ${{
	clear; tput cup $(($(tput lines)/3)); tput bold
	set -f
	printf "%s\n\t" "$fx"
	printf "permanently delete?[y/N]"
	read ans
	[ $ans = "y" ] && rm -rf -- $fx || sudo rm -rf -- $fx && exit
    lf -remote "send $id echomsg 'File(s) deleted permanently.'"
}}
```

It would be cool if the yanked/cut files selected with d/y were accessible through variables (unless they are hiding somewhere I missed) so that I could add similar functionality for pasting in protected directories as this was the main functionality I was looking for. Sudo lf works well enough though.
