### ISSUE TITLE
Environmental variable to show selected file without full path

### ISSUE THREAD

**Issue by mimshipio** [gokcehan/lf#727]
I'd like to have a function for bulkrenaming without having the fullpath. It makes more complicated vim macros or regex manipulation more difficult having the file path printed.
Is it possible to change the function mentioned on the wiki to do this?

**Comment by se7en-x230** [comment]
I use vimv for bulk renaming 

` cmd rename-batch ${{
      $printf '%s' "$(basename -a -- $fx)" |  vimv
`

**Comment by lmburns** [comment]
There's also [`mmv`](https://github.com/itchyny/mmv), [`massren`](https://github.com/laurent22/massren) , and [`f2`](https://github.com/ayoisaiah/f2). I'm unsure if any of these would help
