### ISSUE TITLE
How to delete a selection of files (like issue #45)

### ISSUE THREAD

**Issue by hakova** [gokcehan/lf#728]
Hi there,

Thank you for this great file manager. I really like to use it for my daily driver but probably due to my lack understanding, I just cannot make it the way I want it to work for acting on a selection of files. A good example is deleting a selection of files. I have the following configuration in my lfrc:
`# define a custom 'delete' command`
`cmd delete ${{`
`set -f`
`printf "$fx\n"`
`printf "delete?[y/n]"`
`read ans`
`[ $ans = "y" ] && rm -rf $fx`
`}}`
`# use '<delete>' key for either 'trash' or 'delete' command`
`map <delete> trash`
`map <f-8> delete`
When I select a number of files with the space key and then hit "d", the selection of files have a red flair as expected. However, when I hit the F8 button, the prompt is asking me whether to delete only the file that is highlighted, which is not necessarily in the selected file list; it doesn't get that I want to delete the files in the selection, not the one that is highlighted. What am I missing?

**Comment by kmarius** [comment]
By default `d` is mapped to `cut` which will mark the selection with the red marker. It is meant to be used with `paste` to move files. `$fx` refers to the current selection (pink marker); you need to simply select files with `<space>` and press `<delete>` or `<f-8>`.

**Comment by hakova** [comment]
Duh! Thank you very much for explaining it clearly and quickly. I am sorry for my confusion.
