### ISSUE TITLE
How to have separate cmds for opening a directory and a file

### ISSUE THREAD

**Issue by dslgr** [gokcehan/lf#730]
Hi,
Is there a way to have separate cmds for opening a directory and a file? I would like to map l for opening directories but use enter for opening files. In particular to avoid accidentally opening files. I understand how to create cmds and map cmds but I'm unsure what cmds to create for this setup. 

Thanks!

**Comment by gokcehan** [comment]
@dslgr If I'm not mistaken, you might be able to remove `open` command so it won't act on files but only directories:

```
cmd open
```

Then, you can bind a command to `<enter>` key to open files:

```
map <enter> &xdg-open $f
```

You may also want to check whether `$f` is a file or directory in the command to avoid running the command with directories.

**Comment by dslgr** [comment]
I'm using powershell, so I'll see what I can do to adapt that. Thanks!
