### ISSUE TITLE
Icons and integrated fzf not working when caling lf using dwm but works when calling from terminal

### ISSUE THREAD

**Issue by yogeshdcool** [gokcehan/lf#732]
OS:Archlinux
WM:dwm
terminal:alacritty
lf version:r25

Icons and fzf are workinh when executing the command lf in the terminal but not working when using the keybind I set for lf,What should I do for getting it work when called using keybinding?

edit:sorry for my english

**Comment by gokcehan** [comment]
@yogeshdcool This is most likely an environmental variable issue. If you are setting the variables in your shell configuration file, it may not be sourced when you are using a keybinding. I'm not familiar with dwm, but it might be possible to change the binding to run `lf` inside a shell (e.g. `sh -c lf` instead of `lf`). Feel free to post your command here so people may come up with a solution.

**Comment by slavistan** [comment]
@yogeshdcool Presumably your LF_ICONS are defined in your zshrc or bashrc, which dwm won't pick up on. You can export LF_ICONS in your *~/.profile* instead (although I personally don't like to pollute my environment like that). If you provide us with some more details we'll find a more elaborate solution.

**Comment by LemmonPa** [comment]
hey i have the same problem running `echo ${LF_ICONS:+icons loaded}` outputs `icons loaded` and when I echo `$LF_ICONS` all the icons are fully visible. I'm exporting lf icons from `~/.config/shell/profile`.  as mentioned above trying to add `set icons` to `~/.config/lf/lfrc` results in icon being shown as question mark. all the icons are working properly in any other interface like dwm, zsh and st.

**Comment by gokcehan** [comment]
FYI, I have added support for colors/icons file for configuration a while ago in 17453f10f570150e86de333754b992097f29dd90 which will likely be available in the next release (i.e. `r27`) so you won't have to use environment variables for configuration anymore.

**Comment by LemmonPa** [comment]
i see. my bad. thanks for information. great work.
