### ISSUE TITLE
Show numbers only in the selected pane.

### ISSUE THREAD

**Issue by nikinbaidar** [gokcehan/lf#733]
`set number; set relativenumber` shows the numbers on the left side of all the panes. Is there a way I can get the numbers to just show up in the pane/column that I'm currently in. The interface would look much leaner that way.

**Comment by gokcehan** [comment]
@nikinbaidarr We still lack a configuration mechanism to show `info` on specific panes (#296). If we add that at some point, we may also tie this to the same mechanism.

**Comment by nikinbaidarr** [comment]
> @nikinbaidarr We still lack a configuration mechanism to show `info` on specific panes (#296). If we add that at some point, we may also tie this to the same mechanism.

Yes I think that'd be nice. One more thing though, I have `chmod $1 "$fx"` in my config but changing the permission set on a file does not reflect immediately, I have to reload everytime. Is there something I'm missing here? Everything else about lf is so much better compared to ranger.

**Comment by slavistan** [comment]
>I have `chmod $1 "$fx"` in my config but changing the permission set on a file does not reflect immediately, I have to reload everytime.
@nikinbaidarr Chaning file permissions does not modify the directory's timestamp so lf won't pick up on it. You'll have to reload lf manually. Here's how to make it work for multiple files and arbitrary filenames:

```
set shell zsh
set filesep '\0'

cmd chmod ${{
	chmod "$1" "${(s/\0/)fx}" &&
		lf -remote "send $id :reload"
}}
```
Zsh is used to split $fx at the nullbyte into multiple arguments. I'm sure this can also be done in bash or even posix.

**Comment by joelim-work** [comment]
Closing in favor of #1751, which describes the issue better.
