### ISSUE TITLE
Render error? Index out of range after delete files.

### ISSUE THREAD

**Issue by 66RING** [gokcehan/lf#736]
I use this script to delete multiple files. 

```
cmd delete ${{
	echo $fx
    if [ $# -lt 2 ]; then
        ans="N"
    else
        ans=$2
    fi
    [ $ans = "y" ] || [ $ans = "Y" ] && rm -rf -- $fx
}}

map DD push :delete<space>?[y/N]<space>
```

And then get this error.

![image](https://user-images.githubusercontent.com/49358576/148892168-41eb1406-8eff-4ee3-9e7a-207df3111bea.png)

lf.log as below:

```
2022/01/11 14:20:55 hi!
2022/01/11 14:20:55 loading files: []
2022/01/11 14:20:55 reading file: /home/ring/.config/lf/lfrc
2022/01/11 14:20:55 loading files: []
2022/01/11 14:21:01 pushing keys :delete<space>?[y/N]<space>
2022/01/11 14:21:02 command: delete ?[y/N] y
2022/01/11 14:21:02 shell: ${{ echo $fx ... }} -- [?[y/N] y]
2022/01/11 14:21:02 recv: load
2022/01/11 14:21:02 Got EventError: 'read /dev/tty: i/o timeout' at 2022-01-11 14:21:02.731972788 +0800 CST m=+7.256545176
```
![lf](https://user-images.githubusercontent.com/49358576/148893134-6120e9ae-ceb5-4b38-b870-2ccb51f45fc7.gif)

**Comment by 66RING** [comment]
environment:
OS: archlinux 5.10.83-lts
go: 1.17.4 linux/amd64
lf: `git pull` and `go build` from source

**Comment by 66RING** [comment]
My bad. Kind of previewer error. I'll check it out.

```
set previewer /home/ring/.config/lf/scope.sh
```

**Comment by 66RING** [comment]
But it used to work. weird.😅

**Comment by 66RING** [comment]
Hi @gokcehan 
I found a solution finally which is do not exit 1 in [previewer script](https://github.com/gokcehan/lf/wiki/Ranger) and it look good for now.

![image](https://user-images.githubusercontent.com/49358576/150570761-7434c772-b66b-4fac-ae90-bc06d9f57968.png)

I thought it has a data race in `dir.ind`. But I have no idea with lf thread model. 

![image](https://user-images.githubusercontent.com/49358576/150571753-2e192a77-2675-4ba9-9578-4963d26286d1.png)

**Comment by gokcehan** [comment]
@66RING That line has just been merged in #729 and apparently there is a bug. We should not crash due to any return value in a previewer script. I'm marking this issue as a bug. Thanks for reporting.

cc @lucas-mior

**Comment by gokcehan** [comment]
I have reverted `dirtyfiles` patch in #729 for now so this crash should not happen in the latest commit.

**Comment by 66RING** [comment]
LGTM. close

**Comment by lucas-mior** [comment]
A somewhat convoluted solution:
```
diff --git a/nav.go b/nav.go
index 5dee4dd..8e05730 100644
--- a/nav.go
+++ b/nav.go
@@ -538,7 +538,7 @@ func (nav *nav) previewLoop(ui *ui) {
                }
                dir := nav.currDir()
                if clear && len(gOpts.previewer) != 0 && len(gOpts.cleaner) != 0 && nav.volatilePreview {
-                       if forceClear || !isDirty(dir.files[dir.ind], dir.path, dir.dirtyfiles) {
+                       if forceClear || len(dir.files) > 0 && !isDirty(dir.files[dir.ind], dir.path, dir.dirtyfiles) {
                                cmd := exec.Command(gOpts.cleaner, prev)
                                if err := cmd.Run(); err != nil {
                                        log.Printf("cleaning preview: %s", err)
```
Might work on something cleaner when I have time.

@gokcehan do you want me to redo the PR?

**Comment by gokcehan** [comment]
@lucas-mior Sorry for removing the patch. There could be a way to fix this crash but reading this part of the code, I felt like there is too much accumulated complexity already. For example, isn't `forceClear` a mechanism to override the `dirtyfiles` mechanism introduced to override another `cleaner` mechanism which is already an optional mechanism used alongside another optional mechanism `previewer` which runs optionally depending on the return code? Personally, I can't wrap my head around this logic. That's why I thought we should take a step back and think of a simpler approach. At this point I don't think adding a new option is the right approach so I think we should have some discussion before another patch. #584 is not a very clear issue and #626 have an alternative proposal already.

**Comment by lucas-mior** [comment]
I agree with you that it is way too complex. Don't mind about removing the patch :)
