### ISSUE TITLE
W10 with WSL2- list directory not working, permission denied

### ISSUE THREAD

**Issue by kalekume** [gokcehan/lf#741]
lf does not list any directories if in between there are some inaccessible files or folders. In the below example I'm trying to list files of my C drive using WSL2 on windows 10:

![permissiondenied](https://user-images.githubusercontent.com/63711967/151157578-0bccf569-787b-4230-8d99-7da565f3cdc4.png)

ls -l /mnt/c

drwxrwxrwx 1 myuser myuser 4096 Nov 22 14:07    build
-????????? ? ?       ?          ?            ?  hiberfil.sys
dr-xr-xr-x 1 myuser myuser 4096 May  4  2021    inetpub
drwxrwxrwx 1 myuser myuser 4096 Feb  1  2021    logs
-????????? ? ?       ?          ?            ?  pagefile.sys
-????????? ? ?       ?          ?            ?  swapfile.sys

**Comment by gokcehan** [comment]
@kalekume Looks like we return early from directory reading with a partial list and show `permission denied` error in the ui when there's an error with an lstat call for a file in the directory. We might be able to do a better job for this case.

**Comment by gokcehan** [comment]
I have now changed the behavior to skip files with stat errors instead and log the error.
