### ISSUE TITLE
Temporary Marks

### ISSUE THREAD

**Issue by laktak** [gokcehan/lf#743]
Would it be possible to implement marks that are temporary/local to the instance like `'`?

Use case:
- When working in a directory A you want to copy a file from B. You mark A, search for the file and copy it, then use the mark to go back to A and paste.
- When sorting files (pictures, documents etc.) from directory A to directories X, Y and Z. You mark all directories you need and quickly jump between them to copy/paste.

I know that I can do this in tmux with multiple instances. I find opening a new window and toggling between them is more work than setting a mark. Also I usually have several windows and sessions open already so I'd prefer to stay in one window for this task.

Using marks for this already works 'kind of' but the drawback is that you overwrite the marks in another instance and they have to be cleared manually.

**Comment by gokcehan** [comment]
@laktak Thanks for the proposal. I suppose we could use a lowercase/uppercase strategy for temporary and permanent marks as in vim, although I think in vim they are both permanent but one is local to the buffer and the other is global across files. This might have the disadvantage of requiring shift keys for permanent marks which may not be desirable for some users. Alternatively, this feature might also be implemented with some additional options or commands. Do you have any suggestion for how this could be implemented?

**Comment by laktak** [comment]
I think it would be enough to have a handful of temporary marks.

The easiest solution that would not have a great impact for existing users IMO
is to make the marks 0-9 temporary (although vim's 0-9 marks work differently they can't be set directly either).

If it should be configurable I would just let the user specify which should be temporary marks (e.g. `set tempmarks "asdf"` to define `a`, `s`, `d` and `f` to be temporary).

**Comment by gokcehan** [comment]
@laktak Adding it with such an option does not seem to have any drawbacks. We could also consider leaving the option default empty to make this a non-breaking optional feature.

Just to set the expectations right, I rarely have any time working on new features, so if anyone is interested in this feature consider making a PR.

**Comment by laktak** [comment]
@gokcehan I'm interested ;-) so I submitted a PR.
