### ISSUE TITLE
Question: chown tty when running as other user?

### ISSUE THREAD

**Issue by Adamkadaban** [gokcehan/lf#746]
I'd like to run lf as a different user.

I tried aliasing lf as `/bin/su -c "/bin/lf" - <user>`, but I get the error:
`initializing screen: open /dev/tty: no such device or address`

**Comment by gokcehan** [comment]
@Adamkadaban I'm not sure why this happens. Does `sudo` work?

**Comment by gokcehan** [comment]
@Adamkadaban Note that we delegate the management of `/dev/tty` to our tui library tcell so it is likely that we don't have a possible fix for this issue in our side. However, we can leave this issue open for a while in case someone already has a workaround for this use.
