### ISSUE TITLE
-remote commands don't work

### ISSUE THREAD

**Issue by brwnig** [gokcehan/lf#756]
whether from the lf command line, from "lfrc" or from the terminal, commands of the form bellow don't seem to work:

> lf -remote "send 1001 echomsg "

there is a "lf -server" instance running and a "/tmp/lf.tc.sock" file, but this seems to be always empty.

i was trying to get this command to work:

```
cmd fd ${{
  pick=$( realpath  ` fd -L|fzf `  )
  [ -d "$pick" ] && cmd="cd" || cmd="select"
  lf -remote "send $id $cmd \"$pick\""
}}
map a fd
```

(to be thorough: i'm running  tinycore linux, which means "lf" is a squashfs TCZ file that gets mounted to /usr/local/bin/lf, which is somewhat different than how other linuxes run. also, i call "lf" from a script that uses "exec /usr/local/bin/lf".)

**Comment by MahouShoujoMivutilde** [comment]
Your command works fine for me.

What you might want to check is lf logs after you run the command:

e.g. 
```
map ` $less /tmp/lf.${USER}.${id}.log

```
And press \` after you run the command, maybe it will have something useful.

**Comment by brwnig** [comment]
@MahouShoujoMivutilde 

the problem seem to be broader. no "-remote" command works...

however, i did try what you suggested:

/tmp/lf.tc.1000.log says:
2022/02/11 18:16:08 shell: ${{ less /tmp/lf.${USER}.${id}.log }} -- []

/tmp.lf.tc.server.log says:
2022/02/11 18:16:06 listen: send

the command i showed does work (i added a line ">~/test" and the file was created in my homedir).

what fails is the line that was supposed to call ":cd" and change the directory:
> lf -remote "send $id $cmd \"$pick\""

**Comment by gokcehan** [comment]
@brwnig What version are you using?

**Comment by brwnig** [comment]
> @brwnig What version are you using?

> lf -version
r15

**Comment by gokcehan** [comment]
@brwnig Is 15 your lucky number or are you really one of old users? Our latest release is r26. Don't you think it is time to upgrade? We have a good amount of features and fixes in the newer releases.

**Comment by brwnig** [comment]
haha! sorry. i only realized how far behind i am when you asked. tinycore packages aren't exactly "bleeding edge" and i'm still kind of a noob when it comes to compiling.

i've tried to compile lf but golang says "x509: certificate signed by unknown authority".

**Comment by brwnig** [comment]
well, i ran the pre-built binary. "lf -version" is now "r26". however, the command still fails.

the log for "lf -remote" just says "send", but the log for the client reports an error:

`2022/02/28 14:03:27 Got EventError: 'read /dev/tty: i/o timeout' at 2022-02-28 14:03:27.006092677 -0300 -03 m=+30.147466803`

**Comment by gokcehan** [comment]
@brwnig Unfortunately, I still can't reproduce the bug. Your command seems to work for me.

That error message in the log file is probably not related to this issue.

In your original report, you mention the command:

```
lf -remote "send 1001 echomsg "
```

There are two issues with this example. First, `1001` may not be the id of the client. In r26, we are using the process id of the client as the id. You can see it with something like `!echo $id` and then use it in your example. Second, it does not actually print anything as `echomsg` does not have an argument. So you may try something like `echomsg hello` instead. I hope these can help you identify the issue.

**Comment by brwnig** [comment]
regarding the `1001`: i also tried with `$id` and i did verify that the id belonged to the instance i was testing.
regarding the lack of arguments in `echomsg`, i did try it with and argument and i did try other commands

both `lf -remote "send $id echo hello"` and `lf -remote "send 1349 echo hello"` fail.

but i guess since the error message says something about /dev/tty and i/o error it must be some misconfiguration on my system and not some general bug in lf. probably something related to this obscure concept of a tty timeout ([https://stackoverflow.com/questions/6713668/how-i-can-read-tty-file-with-timeout](https://stackoverflow.com/questions/6713668/how-i-can-read-tty-file-with-timeout))

thanks anyway.
