### ISSUE TITLE
Opener when using PowerShell (Core)

### ISSUE THREAD

**Issue by seantwie03** [gokcehan/lf#760]
Hello,

I am trying to use PowerShell (Core) with LF. After changing the shell to 'pwsh' I had to overwrite all the default bindings like it mentions in etc/lfrc.ps1.example. Everything seemed to work well except OPENER. 

It took quite a while, but finally I stumbled upon this which seems to work: 

    cmd open &pwsh -Command Invoke-Item `"$Env:f`" 

    The backticks around the quotes are a hack to allow opening files with spaces in the name.

I'd like to submit a PR mentioning this to etc/lfrc.ps1.example but  before I do, is there a better/easier way to accomplish this?

**Comment by gokcehan** [comment]
@seantwie03 With both `pwsh` and `powershell` as `shell` value, the current `cmd open &start $Env:f` command in `etc/lfrc.ps1.example` seems to work for me. Can you give more details about what does not work for you?

**Comment by seantwie03** [comment]
That works and is much simpler. Thank you. I've submitted a PR that adds that line to `etc/lfrc.ps1.example`

**Comment by gokcehan** [comment]
@seantwie03 Sorry, I thought it was already in the example config file.
