### ISSUE TITLE
Provide a help bar

### ISSUE THREAD

**Issue by roipoussiere** [gokcehan/lf#766]
I'm new to lf and although I find it very powerful I still have some troubles to remember the shortcuts.

It could be interesting a provide a help bar that lists some common shortcuts.

For instance, the `nano` program displays this bar on the bottom (here in french):
![image](https://user-images.githubusercontent.com/1665542/154940378-7cc0ef9b-ac31-422b-9dd4-7de130dd99f1.png)

Some thoughts about this:
- the help bar should be created dynamically according to actual shortcuts defined in the config file;
- the list shortcuts displayed in the help bar could be defined in the config file, so the user can customize it according to its needs;
- the help bar could be activated or deactivated with a shortcut;
- the default state of the bar could be also defined in the config file.

**Comment by se7en-x230** [comment]
When I started I had the same problem.
But I think the interface is clear and clean as it is and should not add another bar.

What I did in the beginning was adding an external script which greps my lfrc for the mappings and pipe the output into dmenu.
 
 `grep -v "^#" ~/.config/lf-ueberzug/lfrc-ueberzug |grep -v "unmap" | grep map | awk '{printf("%-6s %s %s %s %s %s %s %s %s\n", $2, $4, $5, $6, $7, $8, $9, $10, $11, $12);}' | sort | dmenu -i -l 20 -p "lf keybindings"`
 
 
![image](https://user-images.githubusercontent.com/69777713/154945727-95139b77-9e60-47e6-a22c-b5c967e518a0.png)

**Comment by roipoussiere** [comment]
The doc command displays the full documentation in fullscreen.
I'm talking about a light help bar that stays visible while using lf.
