### ISSUE TITLE
Pressing Ctrl + H key triggers backspace

### ISSUE THREAD

**Issue by Dhamma-valence** [gokcehan/lf#767]
I'm trying to map `hidden!` to ctrl + h so that I can toggle hidden files on and off as there is quite a lot to scroll through without. 

Unfortunately, unlike most of the other mappings which seem to work fine, specifically `ctrl + h`, and in the lfrc `map <c-h> set hidden!` (the set term may not be necessary), the output is `unknown mapping: <backspace>`, when it should at least say `unknown mapping: <c-h>`.

**Comment by Dhamma-valence** [comment]
I believe that this is actually caused by my terminal, Alacritty, confusing `ctrl + h` and `ctrl + backspace` and believing they are the same. As an aside, I adore `lf` and very much appreciate all of the work you've put into it!

**Comment by gokcehan** [comment]
@Dhamma-valence Note, this may not be specific to alacritty as most terminals map `<c-h>` to `<backspace>` for historical reasons.

**Comment by CatsDeservePets** [comment]
This is fixed now:
- https://github.com/gokcehan/lf/pull/2496
