### ISSUE TITLE
Question: kill asynchronous shell commands

### ISSUE THREAD

**Issue by NikitaIvanovV** [gokcehan/lf#770]
Asynchronous command started with `&` seem to stay alive even if `lf` is exited. Is it really the case and is there a way to change this behavior for a particular command?

**Comment by NikitaIvanovV** [comment]
I use [stpv](https://github.com/Naheel-Azawy/stpv) for previews and I noticed that it doesn't do any cleanup when lf is exited: https://github.com/Naheel-Azawy/stpv/issues/20.

What about adding another type of command (beside `$`, `!`, `%` and `&`) to start and async process and kill it when exiting? Or an option to register functions called on exit (similar to `atexit`)? I actually like the latter more.

**Comment by gokcehan** [comment]
@NikitaIvanovV We have a special command `on-cd`  to run when a directory is changed. I guess we could add something like `on-quit` to run a command before exit.

**Comment by NikitaIvanovV** [comment]
It would be great!

**Comment by gokcehan** [comment]
@NikitaIvanovV I have pushed a commit to run `on-quit` command when it is defined. Feel free to say if it is working as expected.

Let's keep this issue open until I add this to the documentation. I will probably make a new section with these special commands (e.g. `open`, `on-cd`, `pre-cd`, and `on-quit`).

**Comment by NikitaIvanovV** [comment]
It does work as expected. Thanks!
