### ISSUE TITLE
lf freezing on AIX

### ISSUE THREAD

**Issue by arozehnal** [gokcehan/lf#771]
I have successfully compiled lf for AIX.
 I can run lf, a basic operations work fine.
 Going to the shell (key '$') also works, the shell command goes to run but after the command is finished
 lf prints a message "running shell: exit status 127  "  and stop responding to any key.
 
I didn't use any custom config at startup.
In the log this  message  appears :
Got EventError: 'EOF' at 2022-03-01 21:29:17.479283 +0100 CET m=+55275527.869296001

Any suggestion?

**Comment by gokcehan** [comment]
@arozehnal Any non-zero return code of shell commands are printed as such messages in lf. How do you finish the command? I suspect the issue is related to lf and the command sharing the same input/output. We have had similar issues about this before in other platforms as well.

**Comment by arozehnal** [comment]
The message "running shell: exit status 127 " appears when I use ArcTel as a client SSH program.
ArcTel (see [[https://www.fbl.cz/arctel_01_home.html](url)](https://www.fbl.cz/arctel_01_home.html) ) is  similar to Putty.
 
 If I use Putty, I get the same state...
 
 start lf, going to the shell (key '$'), confirm the cmd execution (e.g. simple *NIX command or own shell script) by pressing Enter, the Putty session stops responding completely.
 Cmd doesn't quit by itself, Putty doesn't respond to any key. The only option is to force quit Putty by cross in the main bar of the Putty window.

**Comment by gokcehan** [comment]
@arozehnal Unfortunately, there's nothing much I can further say about this issue as I don't have access to an AIX system. If you want to investigate this further, I suggest you try [mouse.go](https://github.com/gdamore/tcell/blob/master/_demos/mouse.go) demo in tcell repo to see if Suspend/Resume works properly or not.
