### ISSUE TITLE
Moving files between drives updates file timestamp

### ISSUE THREAD

**Issue by jfdelaquis** [gokcehan/lf#779]
When moving files between different drives mounted on the same machine using the default cut (`d`) / paste (`p`) command, the timestamps of the files which were moved are updated to the time the file was fully moved.
If a file is moved anywhere within the same drive, timestamps are kept as expected.

Testing the same scenario using the normal `mv` command in a shell, the behavior is that timestamps are kept even if files are moved between drives (tested where both drives are using an ext4 filesystem).

How can timestamps of files be preserved when moving them between drives using lf?

**Comment by gokcehan** [comment]
@jfdelaquis Builtin move command fallbacks to copy-and-then-delete when drives are different and the copy command does not preserve timestamps. I guess you can simply use a custom `paste` command using `cp` and `mv` if you want this behavior.

**Comment by jfdelaquis** [comment]
Thanks for the feedback @gokcehan.
My bad, I just saw the dedicated section (file operations) in the manual to get started implementing something for this behavior.
