### ISSUE TITLE
spawn when opening (feature request)

### ISSUE THREAD

**Issue by dkwo** [gokcehan/lf#780]
When opening a file with external program, would it be possible to spawn it?
What I mean is that, after say zathura is opened by lf (with its own process etc), one can still go ahead and use lf,
and not have a stuck terminal, which is only released after zathura is closed.

I apologize if this is already an option that I missed.

**Comment by gokcehan** [comment]
@dkwo I think you can use `&` commands for this as such:

```
&zathura $f
```

See `shell-async` and "Asynchronous Shell Commands" section in the doc for more info.

**Comment by dkwo** [comment]
Thank you!
