### ISSUE TITLE
[Bug] Windows process doesn't terminate on exit.

### ISSUE THREAD

**Issue by imranZERO** [gokcehan/lf#781]
Whenever I close `lf.exe` by pressing `q` it seemingly closes the program and gets me back into the shell but the underlying process hangs around in the background. You can't even see it in Task Manager. But it can be confirmed if you try to delete the executable.

![image](https://user-images.githubusercontent.com/67048153/158035300-9690605e-998b-467c-be5f-bb64a967d0f0.png)

Then you have to close it through `taskkill` or [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).

![image](https://user-images.githubusercontent.com/67048153/158035198-b5af19db-6af0-47d9-9462-3b8849e11ad7.png)

**Comment by gokcehan** [comment]
@imranZERO The default behavior is to automatically spawn a server with the first program launch which is used for remote commands. There are a number of things you can do to avoid this:

- You can use `-single` flag to avoid spawning a server but then you won't be able to use remote commands.
- You can run `lf -remote quit` to quit the server after you finish but this requires manual effort.
- You can use `autoquit` option to quit server after the last client finishes but then it will need to spawn again next time you launch which can take some time especially on windows.
- Or you can simply leave the server as it is.
