### ISSUE TITLE
How to use `if` `else` in lfrc

### ISSUE THREAD

**Issue by hanleylee** [gokcehan/lf#782]
I want to map some custom command depend on it is inside tmux environment or not. For example:

```shell
if [[ -n $TMUX ]]; then
    map ...
else
    map ...
fi
```

But I encounter this error: `command not found: fi`

Please tell me how to use `if else` inside `lfrc` file

**Comment by gokcehan** [comment]
@hanleylee You can only use it inside shell commands. See the documentatin for more information.

**Comment by hanleylee** [comment]
All right. I know I can use `if else` inside shell function. It will be convenient for me if the lf can support `if else` on the top level of `lfrc`! I want that feature!😄
