### ISSUE TITLE
Trouble with executable file icons

### ISSUE THREAD

**Issue by InternetDr3am** [gokcehan/lf#784]
Just a few minor icon problems:

1. I can't assign icons to folder names, something I used to be able to do with the [devicons](https://github.com/alexanderjeurissen/ranger_devicons) which was a big part of the aesthetic appeal of using Ranger:
![screenshot2](https://user-images.githubusercontent.com/65509715/158297986-8dcd2647-8828-4dd2-a6fc-fc7284e1bd44.png)
My devicon's config (with all the emojis):
[devicons.txt](https://github.com/gokcehan/lf/files/8249839/devicons.txt)

2. It'd be much better if I could disable one icon for all executable files (listed as "ex" in LF_ICONS). I'd much rather see the icon for the file extension of a given file. Most of the files on my computer are executable (plz don't ask lol) so I don't get to see my files' extensions' icons most of the time.

**Comment by gokcehan** [comment]
@InternetDr3am Have you seen [Icons](https://github.com/gokcehan/lf/wiki/Icons) wiki page for the configuration? Also note, I have recently added support for colors/icons file which is currently in master and it will likely be available in the next release (e.g. r27).

Executables are already the latest in the matching order so I'm not sure if there's anything else we can do about it.
