### ISSUE TITLE
Can environment variables be used to set paths in lfrc?

### ISSUE THREAD

**Issue by climbTheStairs** [gokcehan/lf#786]
Some settings, such as `previewer` and `cleaner` in lfrc are the paths to scripts that are run.

[This example is in the documentation:](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Previewing_Files)

```
set previewer ~/.config/lf/pv.sh
```

I have moved my user config directory a couple of times in the past; while for most programs, it is as simple as resetting the [XDG environment variables](https://wiki.archlinux.org/title/XDG_Base_Directory) and moving the files, for `lf`, this would also require editing the `lfrc` file.

Is it possible to do something like this, instead?

```
set previewer $XDG_CONFIG_HOME/lf/pv.sh
```

If it isn't, could this feature be implemented?  Since tildes (`~`) are already expanded into the home directory, I imagine it wouldn't take much to also expand environment variables.

**Comment by gokcehan** [comment]
@climbTheStairs I think this is possible with remote commands, probably with something like:

```
&lf -remote "send $id set previewer \"$XDG_CONFIG_HOME/lf/pv.sh\""
```

Expanding it inside the config would be problematic since `$` is used for shell commands.
