### ISSUE TITLE
How to unmark all marked items in the current column?

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#79]
I wonder if there is any way (disregarding how complicated - may include shell scripting etc.) to unmark all marked items (disregarding whether yanked or space-marked or ...) at once in the current column with a key shortcut?

The `clear` command unmarks just the marked-for-deletion/move files, but I'm seeking for a solution to unmark all.

**Comment by gokcehan** [comment]
As you say, `clear` command clears yanked/deleted items from the server. Marking is different though. Currently there is no way to unmark all items and we should have one.

Marking in lf is implemented in such a way that you can mark items from different folders, not only the current one. On the other hand, ranger and most other file managers only allow yanking/deleting from the current folder. The former approach is more flexible but if you mark an item and change directory to somewhere else, you may forget that you have marked that item before and there is no such indication in the ui if you're at a distant path. This flexibility is rarely needed so I was thinking maybe we should adopt the latter approach as well in lf. Also at some point, we have received a patch for an `invert` command to invert the marked selection and naturally this works for only the current directory. Therefore things might be more consistent if we only allow marking in the current directory.

Any ideas about such a change?

**Comment by dumblob** [comment]
>Any ideas about such a change?

Well, I already used the marking in different folders at the same time and I found it quite useful. What about just adding a dead-simple "addressing scheme" to operations making use of marking and unmarking? It could be a first argument of `toggle` `invert` `unmark` `mark` etc. (the last two do not exist, but they might once) like `current_column|visible_columns|all_mark_lists_in_the_session|all_mark_lists_in_all_sessions` (but shorter :wink:).

**Comment by gokcehan** [comment]
Are `visible_columns` and `all_mark_lists_in_all_sessions` really necessary? Also I'm not sure if there is a common addressing scheme between these commands. For example what should it mean to `invert all_mark_lists_in_the_sessions`, or the difference between `toggle current_column` and `invert current_column`?

**Comment by dumblob** [comment]
>Are `visible_columns` and `all_mark_lists_in_all_sessions` really necessary?

It was just a proposal. Now when thinking about it in more depth, the lowest granularity (one column) is probably enough as even on setups with very wide screens and tiny fonts, the maximum number of columns could be about 15, which is still manageable with "unmark the current column" when it comes to "burst unmarking with `visible_columns`".

The `all_mark_lists_in_all_sessions` could be though useful at the end of complex file work in more clients at the same time. And actually if the marks sharing from https://github.com/gokcehan/lf/issues/80 will be implemented (either as an option or as a default), then it's an equivalent operation to `all_mark_lists_in_the_session`.

> For example what should it mean to invert `all_mark_lists_in_the_sessions`?

>or the difference between `toggle current_column` and `invert current_column`?

No difference according to what I wrote. It seems, that the fundamental difference between `toggle`operating on single items and `invert` operating on whole lists and `mark` `unmark` operating on both single items and lists (either existing or e.g. columns) is intriguing.

Any good ideas how to unify them or their interfaces? I'll think of it.

**Comment by gokcehan** [comment]
At some point, I have added `unmark` command which clears all marks. Almost all our commands work on all marks except for `invert` which only makes sense in the column context. Therefore it does not seem wise to add unmarking for the column which should be rarely needed anyways. Closing this issue. Feel free to leave comments if you have any.
