### ISSUE TITLE
Path on Windows

### ISSUE THREAD

**Issue by pixelblender** [gokcehan/lf#790]
Hi,

Thank you for this awesome project! According to your integration page QuickLook on Windows works but I can't make it work.

On my end Quick Looks is installed in C:\Users\pixelblender\AppData\Local\Programs\QuickLook\QuickLook.exe

From lf cmd, I tried:
- :map <space> C:\\Users\\pixelblender\\AppData\\Local\\Programs\\QuickLook\\QuickLook.exe %f%
  it says "command not found"
- :map <space> C:/Users/pixelblender/AppData/Local/Programs/QuickLook/QuickLook.exe %f%
  same "command not found"
- :map <space> %LOCALAPPDATA%/Programs/QuickLook/QuickLook.exe %f%
  silent and doesn't do anything

Maybe I'm missing something obvious?

Thank you!

**Comment by gokcehan** [comment]
@pixelblender I haven't tried quicklook myself but maybe the following could work:

```
map <space> $C:\Users\pixelblender\AppData\Local\Programs\QuickLook\QuickLook.exe %f%
```

**Comment by pixelblender** [comment]
it's working perfectly. thank you!
