### ISSUE TITLE
slow in autocompletion when pressing <tab>

### ISSUE THREAD

**Issue by syheliel** [gokcehan/lf#794]
I'm using WSL (ubuntu 18.04). When I type some command by `!`, like `!cat`, I have to wait for a long time to autocomplete the command by <Tab>.

I can't tell the lf version,since `lf -version` returns nothing.

**Comment by gokcehan** [comment]
@syheliel I think this issue is not specific to `lf` but wsl in general. See https://github.com/microsoft/WSL/issues/4234
