### ISSUE TITLE
[Question] How disable annoying colors in some specific directories?

### ISSUE THREAD

**Issue by LinArcX** [gokcehan/lf#795]
I have two NTFS partitions and mounted them at system startup. Here is the content of `/etc/fstab` file:

```
UUID=ae33b954-6477-40af-b185-21105ef058c1 / ext4 defaults 0 1
tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0

/dev/sda5	/mnt/D	ntfs-3g uid=linarcx,gid-users	0 0
/dev/sda6	/mnt/E	ntfs-3g	uid=linarcx,gid-users	0 0
```

But if i view these directories with LF, i will see something like this:
![Screenshot from 2022-04-02 10-23-57](https://user-images.githubusercontent.com/10884422/161369145-9b351f89-41f0-4927-8ab9-b53577b4b15f.png)

The colors are very annoying and i can't see anything!

I don't know why this happening. (because of mounting options perhaps?!)

But in any case, i always want to see all different directories the same color, like this:

![Screenshot from 2022-04-02 10-26-01](https://user-images.githubusercontent.com/10884422/161369083-f081d489-4335-4051-b0e0-cc8f68f21037.png)

Is there any option or settings for it?

**Comment by gokcehan** [comment]
@LinArcX We removed reverse color defaults quite a while ago. Make sure you are using the latest version.

**Comment by LinArcX** [comment]
I'm using the latest release version: r26

BTW, thank you.

**Comment by gokcehan** [comment]
@LinArcX Sorry, then `lf` probably reads those colors from `LS_COLORS`. Can you try `LS_COLORS= lf` to see if it works. If so, see 'Colors' section in the documentation. Note, colors file is only available in master and not r26.

**Comment by LinArcX** [comment]
Yes, setting `LS_COLORS= lf` works for me. Thank you.
