### ISSUE TITLE
creating archive "parameter not set"

### ISSUE THREAD

**Issue by mqrris** [gokcehan/lf#797]
OS: OpenBSD GENERIC.MP#232 amd64
lf version: 22

**Issue**: Unable to create a `tar.gz` archive
Error: `running shell exit status 2`
Shell output: `--: 4: 1: parameter not set`

lfrc: 
```
set shell dash

# compress current file or selected files with tar and gunzip
cmd tar ${{
 set -f
 mkdir $1
 cp -r $fx $1
 tar czf $1.tar.gz $1
 rm -rf $1
}}

map A tar
```

**Comment by gokcehan** [comment]
@mqrris You need to call that command with an argument (i.e. `$1`) like `:tar asd` which would then create the file `asd.tar.gz`.

**Comment by mqrris** [comment]
Ahh.. Right.. Thank you!

**Comment by mqrris** [comment]
And another thing, when I do `:tar asd` the screen freezes, and selection is still there, what is  the right syntax to map something like this: `map A push :tar<space> :unselect :redraw` ?

**Comment by gokcehan** [comment]
@mqrris I'm not sure what you mean by screen freeze. There was a time shell commands were not working properly in OpenBSD. You can try updating to the current version to see if the issue is fixed.

**Comment by mqrris** [comment]
Yeah, updating to the latest version solved the screen freezing issue, thanks!

**Comment by mqrris** [comment]
What is the type of a color format do I need to insert into LS_COLORS variable? `export LS_COLORS="*.jpg=???"`
I'd like to convert hex values into this format.
