### ISSUE TITLE
Set bold font instead of a block selection

### ISSUE THREAD

**Issue by mqrris** [gokcehan/lf#799]
I'd like to remove background and set a bold font instead. Is it possible? 
If there's a variable that could overwrite a background color, I will set it to my terminal's color. 
And what about foreground color?

**Comment by joelim-work** [comment]
If you are referring to how the style the cursor, then yes this should be possible by setting the `cursoractivefmt` option (also related are the `cursorparentfmt` and `cursorpreviewfmt` options). The default value for `cursoractivefmt` is `"\033[7m"` which means reversed colors.

These configurations just use terminal escape sequences, so for a bold font use `"\033[1m"`, and for a red foreground use `"\033[31m"`.
