### ISSUE TITLE
change the default text editor upon opening a .txt file

### ISSUE THREAD

**Issue by chbo70** [gokcehan/lf#802]
Hii, so i recently downloaded lf and set it up on my main PC and laptop. Now i see that i can change the default app on my laptop by simply changing the property on dolphin, however on my PC it didn't work. 
Note that i use manjaro on my laptop and normal Arch on my PC :)

I tried to find a command but i was not successful, hope someon can help^^

**Comment by joelim-work** [comment]
I think it is better to have this discussion in #890, I will close this issue as a duplicate.
