### ISSUE TITLE
lf icons won't work

### ISSUE THREAD

**Issue by kars0n777** [gokcehan/lf#804]
this happens on st and alacritty
i use the jetbrains mono nerd font theme
icons were working before then an update made the icons a letter instead
[what the icons look like](https://user-images.githubusercontent.com/79391709/162015277-ec5ed3c4-5302-4b20-892b-87c4c3cca1c2.png)

the icons work with `exa` which shows icons on my terminal as well, but lf seems to be not using them. 

my config is located [here](https://github.com/kars0n777/dotfiles/blob/main/config/lf/lfrc)

**Comment by LinArcX** [comment]
I have the same issue.

Even i tried to copy [icons.example](https://github.com/gokcehan/lf/blob/master/etc/icons.example) into:
1. `~/.config/lf`
2. `/etc/lf/`

But still can't see the icons.

**Comment by ItsRogueRen** [comment]
> I have the same issue.
> 
> Even i tried to copy [icons.example](https://github.com/gokcehan/lf/blob/master/etc/icons.example) into:
> 
>     1. `~/.config/lf`
> 
>     2. `/etc/lf/`
> 
> 
> But still can't see the icons.

Just tried this myself on Pop!_OS 21.10 w/ KDE Plasma and had the same result

**Comment by Player01osu** [comment]
Had the same issue, copied icons into env variable LF_ICONS and worked again.

using zsh, alacritty, and jetbrains mono nerd

**Comment by ItsRogueRen** [comment]
found a solution, which is that `icons.example` needed to be renamed to just `icons`

**Comment by aatmasaat** [comment]
> found a solution, which is that `icons.example` needed to be renamed to just `icons`

I copied the `colors` and `icons` files into my lf directory and have set icons to true, still I just see `[]` instead of icons, am I doing something wrong? Have not tried the `LF_ICONS` envrionment variable method as that has been removed from the wiki and currently there is no guide on how to enable the icons.

**Comment by mroavi** [comment]
The file should be named `icons` and it should be located inside one of these directories:

| OS      | system-wide             | user-specific                    |
|---------|-------------------------|----------------------------------|
| Unix    | /etc/lf/           | ~/.config/lf/               |
| Windows | C:\ProgramData\lf\ | C:\Users\<user>\AppData\Local\lf\ |

Remember to add `set icons` in your lfrc config file.

**Comment by mahmoudajawad** [comment]
@mroavi, I think this is not intuitive to everyone, so, I used your data to add this section to the installation tutorial: https://github.com/gokcehan/lf/wiki/Tutorial#colors-and-icons

**Comment by aatmasaat** [comment]
aahh, the reason why icons feature was not working was because I was using r26 version and icons support was added in r27 release.

I've icons and colors file in `~/.config/lf` directory and have `set icons` and `set colors` in my lfrc but I'm still getting `unknown option: colors` error

**Comment by joelim-work** [comment]
Judging from the direction of the comments here, I think this is no longer an issue - will close. Please reopen if further discussion is required.
