### ISSUE TITLE
Going back to last dir.

### ISSUE THREAD

**Issue by navneetankur** [gokcehan/lf#811]
Like the back button in GUI file managers. Is there a way to go back to the last dir?
It is especially useful when we go to a bookmarked dir, and then want to go back.

**Comment by shabahengam** [comment]
```
jump-next                (default ']')
jump-prev                (default '[')
```
read more about this at  https://github.com/gokcehan/lf/pull/755

we also have `'` that holds the previous directory after a 'mark-load', 'cd', or 'select' command. 
``
mark-load      (modal)   (default "'")
``

**Comment by navneetankur** [comment]
Thanks.
