### ISSUE TITLE
read: operation timed out

### ISSUE THREAD

**Issue by imceZZ** [gokcehan/lf#812]
when I execute this command: env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w" github.com/gokcehan/lf 

I get this result:
go get: module github.com/gdamore/tcell/v2/terminfo/a/alacritty: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/a/alacritty/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/b/beterm: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/b/beterm/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/g: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/g/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/h: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/h/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/l/linux: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/l/linux/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/v/vt400: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/v/vt400/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/w/wy60: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/w/wy60/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/x/xfce: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/x/xfce/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module github.com/gdamore/tcell/v2/terminfo/x/xterm_kitty: Get "https://goproxy.cn/github.com/gdamore/tcell/v2/terminfo/x/xterm_kitty/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out
go get: module golang.org/x/term: Get "https://goproxy.cn/golang.org/x/term/@v/list": read tcp 172.20.10.12:63082->79.133.176.212:443: read: operation timed out

**Comment by joelim-work** [comment]
@imceZZ This is just an internet connection issue which prevented you from downloading the dependencies, please try again.

BTW that command for installing `lf` is out of date, please refer to https://github.com/gokcehan/lf#installation for the current recommendations.
