### ISSUE TITLE
Question: How to delete files?

### ISSUE THREAD

**Issue by hervyqa** [gokcehan/lf#814]
I read in the documentation, `delete` there is no shortcut.  It only has `cmd-delete`, it uses `<c-d>` and `<delete>`.  But isn't `<c-d>` already used for `half-down`?

Currently i delete file with `:delete`.

**Comment by ailac22** [comment]
Yes, I also think a default shortcut would be nice, and there's no risk given that a y/N prompt is offered.

**Comment by hervyqa** [comment]
@ailac22 thanks for your reply. I just realized what `<cmd>` is for. it's true that having a shortcut for del is a bit risky.
