### ISSUE TITLE
Add special on-load command

### ISSUE THREAD

**Issue by SeerLite** [gokcehan/lf#816]
Same as `on-cd` but executed everytime the `load` command is called.

My use-case is I want to show the number of hidden files in the prompt (actually in the status line but I found no `statuslinefmt` (#310? #112?) so I settled for the prompt). It works relatively fine with `on-cd` but it breaks if a file is created while lf is open or if the file is created _via_ lf.

And thanks again for making the best file manager <3 Out of all software I use daily I'd say lf is the only one that gets the least in my way and does exactly what I expect it to.

**Comment by joelim-work** [comment]
I think the closest thing we have is `on-select` which will trigger if the currently selected file changes.

But if you just wanted to show the number of hidden files in the status bar, you can use `%h` in the `rulerfmt` option. Someone else requested the same thing in #1287 which is now supported.
