### ISSUE TITLE
File structure of complex setup

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#818]
I have a very customized llfrc setup.
It grew over time and works very well as my only file manager on the system.
But where I struggle in a new setup is to get Ueberzug,, lfcd, color, dircolor and icons to work.
As icons go in.my .profile and lfcd can't even remember how to get that to work.

I saw now you have a /etc/ folder with dircolor, icons ...
Does this mean you can place all lfcd Ueberzug icons and dircolor in your .config/lf  ?
That would be awesome, instead of editing files all over the place.

If not what is the structure to make all of that migrate to another system.

**Comment by joelim-work** [comment]
I think this is no longer an issue, config files are now available for colors and icons (`~/.config/lf/colors` and `~/.config/lf/icons` respectively), which should simplify the setup.

For `lfcd`, you just have to ensure it is included in your `.bashrc` file, either by copying the contents of `lfcd.sh` into your `.bashrc` or by using the `source` command. This is explained in the comments: https://github.com/gokcehan/lf/blob/dddf437c42a5e61afefaae6bb39f0c484cd2f0e0/etc/lfcd.sh#L3-L4
