### ISSUE TITLE
Question: Built-in prompt

### ISSUE THREAD

**Issue by YanDoroshenko** [gokcehan/lf#819]
Hello,
I'm trying to implement a command that takes user input. Is there a way to do that "internally" (like the `/` command does), without throwing the user out to a bare terminal with `read`?
Thank you.

**Comment by Itsnexn** [comment]
Hey,

I'm kind of new to `lf` and I was checking issues to find something but I think this is how you should do it...
![image](https://user-images.githubusercontent.com/72174296/179390219-65a8300c-8956-49cd-b32d-aae98978310e.png)
and it should look something like this:
![image](https://user-images.githubusercontent.com/72174296/179390276-b5c855d4-879e-4238-8aef-224a2aa85c82.png)
and you can write anything you want and it will pipe into the stdin of that command
![image](https://user-images.githubusercontent.com/72174296/179390285-b2d307f7-da64-46cb-986e-16542c07f14d.png)

**Comment by pc00per** [comment]
@Itsnexn How do you escape out of the questionaire ? For delete, I could just `j,k` out or hit escape to cancel the input. But can't with this method.

**Comment by Itsnexn** [comment]
@pc00per currently I have limited time and I couldn't find the built-in delete command in the source code.

but I believe that is because the read command only reads one character from the stdin.

>```
>       -n nchars	return after reading NCHARS characters rather than waiting
>    		for a newline, but honor a delimiter if fewer than
>```
> from `read --help` 

something like:
```bash
read -n 1 ans
```
and using a simple if statement checks for the "y" answer to delete the file. otherwise, it just does nothing.

**Comment by Itsnexn** [comment]
@YanDoroshenko Hey I believe we covered everything here. if you found your answer please close this issue.

**Comment by YanDoroshenko** [comment]
Yeah, thanks everyone, somehow I managed to miss the entire thread.
