### ISSUE TITLE
-selection-path switch not functional

### ISSUE THREAD

**Issue by occivink** [gokcehan/lf#82]
Unless I misunderstand its purpose, if I start `lf -selection-path /tmp/whatever`, mark some files and exit, there is no such file created.

**Comment by gokcehan** [comment]
@occivink Somehow I couldn't reproduce your problem. It should create a file if it doesn't exist and write the names of marked files or the name of current file if no file is marked. Can you check if you have an error message in the log file if you have it? (note that log file is removed on successful exit so it may or may not be useful here) Also if you're a vim user, can you try the example vim script provided in the etc folder. It should demonstrate the proper use of this flag. For reference, this behavior itself is implemented [here](https://github.com/gokcehan/lf/blob/3eca9059bf0aff6b5def66039492904d9c21814a/eval.go#L240).

**Comment by occivink** [comment]
I can't see anything in the log and the vim plugin doesn't seem to work, I'll try to debug is some time.

**Comment by occivink** [comment]
Ok looking at the implementation I now see that it was a misunderstanding on my part. What I imagined is that after marking the files, I would just normally exit with `q` and the marked files would be written to the file.
I think  the fact that the last file that you "open" to trigger this behavior doesn't get written is a little suspicious.

**Comment by gokcehan** [comment]
Hmm, shall we do the same for `quit` then?

**Comment by occivink** [comment]
I'd say yes, but I imagine that other users may  want to exit without touching these files (like esc would in a GUI), so I'm not sure.

**Comment by gokcehan** [comment]
How about

> path to the file to write selected files on open (to use as open file dialog)

instead of

> path to the file to write selected files on exit (to use as open file dialog)

Does that sound more or less confusing?

**Comment by occivink** [comment]
I think that's an improvement, yes.

**Comment by gokcehan** [comment]
@occivink As you say, it is better to have a way to cancel this (e.g. you start lf in vim but then give up opening a new file). So `open` and `exit` should not behave the same.
