### ISSUE TITLE
lf does not exit when pressing "w"

### ISSUE THREAD

**Issue by DusanLesan** [gokcehan/lf#823]
I have issue with the command that is mapped by default to "w" key (I could not find 'w' in the [doc](https://pkg.go.dev/github.com/gokcehan/lf)).

**STR**:
- Open terminal
- Start `lf`
- Navigate to any other dir
- Press `w` key
- Enter `exit` command

**Expected Result**: terminal should close itseflf
**Actual Result**: `exit` command closes the active terminal and returns to lf. 
After pressing `w`, the lf server is still active even with `set autoquit true`

This is very confusing in ssh. If I open lf several times and then exit in current dir with `w`, I need to type `exit` bunch of times to close the ssh session. 
If this is expected behavior, how do I really cd and close lf process (if possible keeping ability to use previous commands from that shell session (currently, if I exit lf, I cannot get to above commands with up arrow and I get history entries from previous session))?

**Comment by SeekingBlues** [comment]
`w` does not quit `lf`. It spawn a subshell as documented below, so you should return to `lf` after you exit from the shell:
https://github.com/gokcehan/lf/blob/2104a501aad1f2f46d118623402205a24c122fff/doc.go#L192

**Comment by DusanLesan** [comment]
@SeekingBlues  Thanks. The behavior makes sense now. Do you know how to merge lfcd into my image preview wrapper?
```
set -e

cleanup() {
	exec 3>&-
	rm "$FIFO_UEBERZUG"
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf "$@"
else
	[ ! -d "/tmp/lf" ] && mkdir -p "/tmp/lf"
	export FIFO_UEBERZUG="/tmp/lf/ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup HUP INT QUIT TERM PWR EXIT
	lf "$@" 3>&-
fi
```

**Comment by DusanLesan** [comment]
I have found a solution to make a external keybinding trigger lfcd in my rc file using a env variable.
```
lfcd () {
	tmp="$(mktemp -uq)"
	trap 'rm -f $tmp >/dev/null 2>&1' HUP INT QUIT TERM PWR EXIT
	lfrun -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
		dir="$(cat "$tmp")"
		[ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
	fi
}

if [ "$_START_LFCD" ]; then
	unset _START_LFCD
	lfcd
fi
```
So  I can start a wrapped lf like: `_START_LFCD=1 alacritty`
This is good enough for me. I will close the issue, but anybody that knows better solution, please let me know.
