### ISSUE TITLE
Integration with z.lua ? 

### ISSUE THREAD

**Issue by SamDc73** [gokcehan/lf#828]
for z.lua integration with ranger there is [this](https://github.com/skywind3000/z.lua/blob/master/ranger_zlua.py) extension to achieve that, is there any similar project to achieve that in lf  ?

**Comment by zhengpd** [comment]
You could try this cmd:

```sh
cmd zl ${{
result="$(read '?Dir: ' input && $ZLUA_ROOT/z.lua -I -e $input)"
[[ -z '' ]] && read '?No directory. Press Enter to continue' || lf -remote "send ${id} cd '${result}'"
}}
```

**Comment by SamDc73** [comment]
I'm having this error message :
`--: line 3: read: `?Dir: ': not a valid identifier`

**Comment by zhengpd** [comment]
@SamDc73 You might be using bash. Try `read -p 'Dir: '`. The `read '?Dir: '` syntax works with zsh.

**Comment by zpyg** [comment]
It works
```
cmd z-jump ${{
  z_exe="$HOME/.local/share/zinit/plugins/skywind3000---z.lua/z.lua"
  lf -remote "send ${id} cd '$($z_exe -I -e $1)'"
}}
map Z push :z-jump<space>
```
