### ISSUE TITLE
simplify code

### ISSUE THREAD

**Issue by horriblename** [gokcehan/lf#845]
Correct me if I'm wrong but the following code does the same as `ui.screen.Clear()` right?

``` go
func (ui *ui) draw(nav *nav) {
	st := tcell.StyleDefault

	wtot, htot := ui.screen.Size()
	for i := 0; i < wtot; i++ {
		for j := 0; j < htot; j++ {
			ui.screen.SetContent(i, j, ' ', nil, st)
		}
	}
```
From the docs:
> Clear erases the screen.  The contents of any screen buffers will also be cleared.  This has the logical effect of filling the screen with spaces, using the global default style\.

**Comment by joelim-work** [comment]
Thanks @horriblename, I have submitted #1169 to solve this.

**Comment by joelim-work** [comment]
Okay, so while `ui.screen.Clear()` works fine for Unix terminals, it unfortunately causes slowness on Windows, see the comments in #1169  for more details. I'm not sure if this issue worth keeping open, but anyway I think the best we can really do is to leave a comment in the source code to explain why the screen is manually cleared in the current way.
