### ISSUE TITLE
Help page does not open if PAGER is set to "less -R"

### ISSUE THREAD

**Issue by tucuxi** [gokcehan/lf#848]
On Linux, lf fails to display the doc page if PAGER is set to `less -R`. The following output is generated.

lnside lf: `running shell: exit status 127`

In the terminal window:
`--: line 2: less -R: command not found`

This issue also affects other commands that use the PAGER environment variable.

**Comment by SeekingBlues** [comment]
You probably have `IFS` set to `\n` in lfrc. This will prevent the shell from splitting `$PAGER` on spaces, which would cause it to interpret `less -R` as the name of the command.

**Comment by tucuxi** [comment]
You are correct. `LFS` was set to `\n'. Closing this issue as resolved.

**Comment by ilyagr** [comment]
One solution I found is to set PAGER to `"less\n-R"` (with a newline instead of a space). I am not sure whether this is considered crazy.
