### ISSUE TITLE
how to create mapping for returning to the last visited dir

### ISSUE THREAD

**Issue by peku-jamf** [gokcehan/lf#851]
Hey,

I'm often using my 'go' shortcut to get the most visited dirs using
`map go :fasd_dir`

my problem is when I need to get back to the last visited dir I have no options but manual

is there any possibility to add a mapping to go to the last visited dir?
Similar to "cd -" in shell.

I've tried quite a lot of ways to achieve that but none of them worked.
Is it possible to save the current visited dir somehow using 'pre-cd' function perhaps?

Thanks for ideas.

**Comment by kmarius** [comment]
Does 'jump-prev' (default `]`) do what you want?

**Comment by peku-jamf** [comment]
amazing, thanks for the hint!
