### ISSUE TITLE
no script nfcd for nushell

### ISSUE THREAD

**Issue by tourmaline3333** [gokcehan/lf#856]
I use lf nushell on windows.
I searched Issues and Discussions.and I googled ,but no information.

plz help me.
thank you.

**Comment by kepet19** [comment]
Hello I came here looking for lfcd for nushell. 
I did not find it. I made my own, be aware I just started scripting in nushell yesterday.

Also be aware that it is changing directories every time you leave **lf**. That is the last thing that is missing.


Shell `: vim $nu.config-path` for opening the config file
Filename `config.nu`
```nu
let-env config = {

  keybindings: [
    {
      name: lfcd
      modifier: control
      keycode: char_o
      mode: [vi_insert, vi_normal, emacs]
      event: {
        send: executehostcommand
        cmd: "lfcd"
      }
    }
  ]

}
```

Shell: `: vim $nu.env-path` for opening the env file
Filename `env.nu`
```nu
export def-env lfcd [...args: any] {
    let tmp = ([$env.TEMP, $"lfcd-(random chars -l 5).tmp"] | path join)
    lf -last-dir-path $"($tmp)" $args
    let dir = (open $tmp)
    rm $tmp
    cd $dir
}

```

**Comment by gokcehan** [comment]
@kepet19 Thanks for coming up with a solution. Feel free to also add this somewhere appropriate in the wiki pages if you like so it won't get lost here. Closing this issue.
