### ISSUE TITLE
I can't tag a file path that contains colon.

### ISSUE THREAD

**Issue by amano-kenji** [gokcehan/lf#857]
For example, try to tag `/home/user/abc:abc.txt` or `/home/user/dir:1/file.txt` by pressing `t` on it. You can't.

I just read `~/.local/share/lf/tags`, and colon is used as a separator in that file. Perhaps, tags file should become a JSON file?

Or, the parser should use the last colon as the separator between a tag and a file path?

**Comment by amano-kenji** [comment]
https://github.com/gokcehan/lf/blob/36a7a18316580864f2f2ebd79e9ddae4858f6b60/nav.go#L1670 causes the issue.

**Comment by gokcehan** [comment]
@amano-kenji Sorry for late reply. Thanks for reporting and locating the issue. I have now pushed a fix to handle colons in paths for tags.

**Comment by amano-kenji** [comment]
I tested the latest commit. The issue is fixed.
