### ISSUE TITLE
Copy with preserved timestanp

### ISSUE THREAD

**Issue by manu0600** [gokcehan/lf#869]
Hello,

Is it possible to change the behavior of the "copy" function to preserve timestamps and attributes ? (creation date, modification date, permissions, etc). When I use `rsync -aAX file1 newlocation/file1` instead of `cp file1 newlocation/file1`, everything is preserved. I'm not sure where to change this in lf while preserving the nice looking progress percentage.

thank you

**Comment by lahwaacz** [comment]
There is an example for showing progress: https://github.com/gokcehan/lf/wiki/Tips#show-progress-for-file-copying
