### ISSUE TITLE
[Help Wanted] Integrating QuickLook on Windows

### ISSUE THREAD

**Issue by TiberiusDreadnought** [gokcehan/lf#870]
### Expected Behavior

Pressing the assigned key should open a preview of the selected item in QuickLook.

### Actual Behavior

Pressing spacebar on an image file, text file, etc. prompts the dialog box:

```
QuickLook is already running.
QuickLook enables quick previewing of certain type of files by pressing the spacebar while it is highlighted.
```

### Steps to Reproduce Problem

1. Add the following in the configuration file for lf (C:\Users\<user>\AppData\Local\lf\lfrc):
  ```
  map <space> $C:/Users/<user>/AppData/Local/Programs/QuickLook/QuickLook.exe %f%
  ```
2. Save the file, and restart lf (if running). QuickLook should also be running.
3. Move selection to any file supported by QuickLook. Press spacebar.

### Notes

- Made sure that QuickLook is working by using it on the same files through other file managers (Files, Double Commander).
- Tried using Ctrl-g as the map for QuickLook instead of spacebar (`<c-g>` instead of `space`).
  - Additionally, used `<space>` to select a file, and then pressed `<c-g>`

### Specifications

- `lf --version`: r26
- QuickLook version: 3.7.1
- Installed with chocolatey on Windows 10

**Comment by lab-do** [comment]
You have to change `%f%` to `$Env:f` if you are using Poweshell on Windows

**Comment by TiberiusDreadnought** [comment]
The above solution works.
