### ISSUE TITLE
Improved command editing experience

### ISSUE THREAD

**Issue by jdfa** [gokcehan/lf#876]
I feel that command input is not really user-friendly. For instance, it doesn't allow marking and jumping between words.
Those features are really essential to input commands conveniently. 
Same improvements can be also applied to rename command input and any other input request handler.

**Comment by UnrealView** [comment]
I agree, currently editing experience is very poor.
It should be great if the input bar can handle some common action in text editor like:
- `ctrl-left/right arrow` to navigate word by word
- `ctrl-shift-left/right arrow` to select word by word
- `ctrl-delete/backspace` to delete word by word
- ...

These example is common for Windows but maybe it can be configurable.

**Comment by ilyagr** [comment]
> name command input and any other input request handler.

What does this mean?

> It should be great if the input bar can handle some common action in text editor like

- Making `<c-left>` and `<c-right>` work is doable. I may or may not do it :). Currently, you can use `<a-f>` and `<a-b>` or `cmap` something else (but not ctrl-arrows, those are not yet supported).
- Creating a notion of selection in the command-line would be a pretty big change. The command line does support emacs-style kill and yank if that helps.
- You can use `<c-w>`  to delete a word and there are other useful commands in the docs. Unfortunately, it seems to be difficult to reliably bind `<c-backspace>` in a terminal app.

**Comment by joelim-work** [comment]
Mapping `<c-left>` and `<c-right>` is supported as of #1248

On my terminal <kbd>backspace</kbd> is mapped to `<backspace2>`, and <kbd>ctrl</kbd>+<kbd>backspace</kbd> is mapped to `<backspace>`, and the following works for me:

```
cmap <c-left> cmd-word-back
cmap <c-right> cmd-word
cmap <backspace> cmd-delete-unix-word
cmap <c-delete> cmd-delete-word
```

Note that `cmap` mappings apply for both editing commands, and when user input is requested (e.g. `rename: ` and `filter: `).

Regarding text selection, `lf` command line editing is based off GNU Readline, so I'm not sure whether it's worth implementing or whether it's in the correct spirit to do so.
