### ISSUE TITLE
Show if file is symlink

### ISSUE THREAD

**Issue by grammoboy2** [gokcehan/lf#877]
In Ranger symlinks (linux) are displayed with a '->' sign. 
I do miss that feature in Lf and I think it is a useful, if not important one for a filemanager. 

edit: in nnn it's displayed with a '@' sign.

**Comment by Tony-Sol** [comment]
Try to set icons option to "on" and specify icon for `ln` file type.
It's gonna be something like this
<img width="1286" alt="Снимок экрана 2022-07-22 в 21 29 37" src="https://user-images.githubusercontent.com/33671815/180501697-0eab6c0d-2fe6-46a4-8486-a603de6fb033.png">
with example icons config from https://raw.githubusercontent.com/gokcehan/lf/master/etc/icons.example (Nerd Font required)

**Comment by lahwaacz** [comment]
Or you can add something like `ln 01;38;5;37` to `~/.config/lf/colors` to highlight links with a different color.
