### ISSUE TITLE
Open lf in given directory

### ISSUE THREAD

**Issue by TeddyDD** [gokcehan/lf#88]
Something like `lf [params] directory` would be useful. It would allow to implement simple "new tab" behaviour (open new client in current directory)

**Comment by occivink** [comment]
Dupe of #63 I believe :)

**Comment by TeddyDD** [comment]
Whoops, my bad

**Comment by TeddyDD** [comment]
Whoops, my bad

**Comment by gokcehan** [comment]
@TeddyDD @occivink This is now possible with the latest commit.
