### ISSUE TITLE
How to repeat shell command

### ISSUE THREAD

**Issue by lefuturiste** [gokcehan/lf#885]
Let's say I have a situation where I want to apply to a number of files a specific shell command. But I cannot just use find and then xargs that, I need to manually select each file where I want my command to be applied.

Well... I could create a specific mapping for that but it's only for this specific moment, I won't need to use it later so it kinda too much work and I'm lazy.

How can I for example use a mapping to repeat the last shell command on the selected file?

**Comment by jdfa** [comment]
You can call previous executed command for this. From docs: 
cmd-history-prev         (default '<c-p>')

**Comment by joelim-work** [comment]
I have discovered that you can also script this:

```
map . :read; cmd-history-prev; cmd-enter
```

I will add this to the Tips section for the wiki, thanks for the idea!
