### ISSUE TITLE
proposal: vim syntax for lfrc

### ISSUE THREAD

**Issue by nnzv** [gokcehan/lf#888]
### Why?

End-users could easily differentiate stuff:

```
# Is this a comment?
set shellopts '-eu'
```
```sh
# This is a comment!
set shellopts '-eu'
```

**Comment by kmarius** [comment]
There is https://github.com/camnw/lf-vim. It could use some updates such as missing config options that were added in the past year.

**Comment by andis-sprinkis** [comment]
> There is https://github.com/camnw/lf-vim. It could use some updates such as missing config options that were added in the past year.

I have updated the above mentioned plugin, which seems to be unmaintained, with the r32 keywords:
https://github.com/andis-sprinkis/lf-vim
