### ISSUE TITLE
suggestion: use all terminal columns

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#898]
Currently, lf only uses all terminal columns for the top and bottom infos.
In the directory files section, it starts printing them one cell after the margin,
and on the right side, it stops one cell before the last.

![image](https://user-images.githubusercontent.com/49657055/182895958-27adf143-757a-4045-b80e-8827e3d6f2ac.png)

Could it be done, that lf doesn't "waste" that space?

**Comment by joelim-work** [comment]
The cell at the start (just before the icon) is actually used for displaying tags. Press <kbd>t</kbd> with the default configuration and see what happens.

The cell at the end (just after the file info or dircount) is not used, but one could argue that it makes the cursor look balanced if there is a space on both sides (most of the time anyway). This is a matter of personal preference though - I think it's in the best interests to keep the existing behaviour unless there are a large number of users complaining about this.
