### ISSUE TITLE
colour of pane borders

### ISSUE THREAD

**Issue by gsaple** [gokcehan/lf#902]
Hi  there,
 Just a  tutorial question. I probably miss it somewhere. :sweat_smile: 
How can I change the colour of the pane borders after I enter `:set drawbox` ?

**Comment by gsaple** [comment]
just to be more precise, what I really meant is after I put `set drawbox` in lfrc

**Comment by ytian81** [comment]
also interested in changing the color of if's pane border. 

According to the following code, it doesn't seem we can configure this yet.

https://github.com/gokcehan/lf/blob/b0cb9268d802ef22f1dd646274a6ee1213570a7a/ui.go#L806
