### ISSUE TITLE
dircolors values always have higher priority than filetype colors

### ISSUE THREAD

**Issue by Cavernosa** [gokcehan/lf#903]
The DIRCOLORS colors (exec, link, dir, etc.) always have higher priority than the more specific filetype colors (mp4, aac, png, etc.) which is bad.
Example: In a directory full of videos, some of them have the executable flag, others do not, so some of them will be green and others will be purple.

This could be extra confusing in directories where you have mixed file formats, you could have `mp4`s, `txt`s, `wav`s etc. all share the same green color instead of the assigned file format color, just because they're executable.
This also makes `set icons` with the file flag letters kinda useless.

Just like ranger, lf should make file formats have higher priority than the dircolors file flags.
Another approach could be a hierarchy in the colors config file, later assignments have higher priority than earlier assignments. So the user could tweak it to however they want.

Edit: it's actually documented in lf:
>Note that lf first tries matching file names and then falls back to file
types. The full order of matchings from most specific to least are as
follows:
>
>    1. Full Path (e.g. '~/.config/lf/lfrc')
>    2. Dir Name  (e.g. '.git/') (only matches dirs with a trailing slash at the end)
>    3. File Type (e.g. 'ln') (except 'fi')
>    4. File Name (e.g. 'README*')
>    5. File Name (e.g. '*README')
>    6. Base Name (e.g. 'README.*')
>    7. Extension (e.g. '*.txt')
>    8. Default   (i.e. 'fi')

Reading the first phrase, this seems like it was not intentional. It says it tries matching file names before file types, but the point 3 in the list shows a file type matching before file names. :thinking: 
Anyway, so what i'm proposing is something like this:
>    1. Full Path (e.g. '~/.config/lf/lfrc')
>    2. Dir Name  (e.g. '.git/') (only matches dirs with a trailing slash at the end)
>    3. File Name (e.g. 'README*')
>    4. File Name (e.g. '*README')
>    5. Base Name (e.g. 'README.*')
>    6. Extension (e.g. '*.txt')
>    7. File Type (e.g. 'ln') (except 'fi')
>    8. Default   (i.e. 'fi')

Hard-switching the hierarchy in the code shouldn't be hard. In fact, from what i see, the revelant code seems to be very simple, just moving some `if`s around is enough:
https://github.com/gokcehan/lf/blob/b0cb9268d802ef22f1dd646274a6ee1213570a7a/colors.go#L264-L331

**Comment by lahwaacz** [comment]
This is a feature of dircolors. Ranger does not use dircolors at all, so it cannot be compared. You should fix your file permissions if you don't like the green color.

**Comment by Cavernosa** [comment]
> This is a feature of dircolors. Ranger does not use dircolors at all, so it cannot be compared.

Ranger does use dircolors, executable text files are green, for example (since they don't have any color assigned), but executable videos will always be purple. Directories are blue just like dircolors, links are cyan, just like dircolors, etc. So it is comparable.

Ranger implements what i said, file extension specific colors have higher priority than dircolors. This is very useful as i can look at the color and instantly know if it's a video, archive or audio, or a executable without having to look at the filename.

>You should fix your file permissions if you don't like the green color. Or remove the EXEC color from your dircolors to avoid highlighting executable files.

That is not helpful at all, I never said i don't like the green color. I don't want to remove the `EXEC` color, because *it is useful*, but let's be honest, i also don't want it on every file in my system. Making everything that's a executable take the green color is comparable to not using per file type colors at all (and just using dircolors like `ls`)

And as i said, one could theoretically implement something that is fine to both dircolors lovers and per file type colors lovers, tho that would probably be harder than just hard-switching the priority in the code, and its hard to imagine that anyone sane actually finds this dircolors wonkyness useful

**Comment by lahwaacz** [comment]
Ranger _does not_ use dircolors, this issue is still open: https://github.com/ranger/ranger/issues/169  However the behavior resembles dircolors, it is implemented differently and cannot be configured via dircolors.

>  i also don't want it on every file in my computer.

Why do you have the executable bit on _every_ file in your computer? Fix your permissions!

> Making everything that's a executable take the green color is comparable to not using per file type colors at all (and just using dircolors like ls)

Exactly, that's the point. I said that this is a _feature_.

**Comment by Cavernosa** [comment]
> Exactly, that's the point. I said that this is a _feature_.

Uh...
If it's a feature it's an awful feature for 99.9% of users. Nobody cares if their videos or images are executable.
I have not found any place where it explicitly mentions this is an intended feature, and i do not see any record of you contributing to this repo, care to explain?

> Why do you have the executable bit on every file in your computer? Fix your permissions!

...That was a hyperbole. But it's not far from truth when i `sudo mount` my NTFS partition, literally `touch a` creates a with 0777 permissions, certainly not my fault.
I could write paragraphs on this executable debate but no, i'm tired and it's not the point of the issue.

Sorry, but you look really stubborn or trolling me and i feel like I already made my point clear, i'm not going to continue discussing with you.

**Comment by lahwaacz** [comment]
As explained in the [colors section of the documentation](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Colors), lf implements the behavior of GNU dircolors. The configuration format and behavior is exactly the same as for GNU programs such as `ls`. That's why I said it's a _feature_, one that is implied by a compatibility with GNU dircolors.

> Although it's not far from truth when i `sudo mount` an NTFS partition, in which literally every file has 0777 permissions, now should i stop using NTFS?

You might want to read up on the `fmask` mount option for NTFS-3G: https://unix.stackexchange.com/q/396904

**Comment by Cavernosa** [comment]
>As explained in the [colors section of the documentation](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Colors), lf implements the behavior of GNU dircolors. The configuration format and behavior is exactly the same as for GNU programs such as ls. That's why I said it's a feature, one that is implied by a compatibility with GNU dircolors.

Ok, I thought you meant that file type colors (a.k.a. `ls` colors) overriding file extension colors was a feature. That's why i said it's an horrible feature.
Idk if you read my edit so, the only paragraph saying anything related to my issue is this one:
> Note that lf first tries matching file names and then falls back to file types. The full order of matchings from most specific to least are as follows:
>1. Full Path (e.g. '~/.config/lf/lfrc')
>2. Dir Name (e.g. '.git/') (only matches dirs with a trailing slash at the end)
>3. File Type (e.g. 'ln') (except 'fi')
>4. File Name (e.g. 'README*')
>5. File Name (e.g. '*README')
>6. Base Name (e.g. 'README.*')
>7. Extension (e.g. '*.txt')
>8. Default (i.e. 'fi')

Which contradicts on itself

Thx for the stack exchange link.

**Comment by lahwaacz** [comment]
The order was most recently changed in https://github.com/gokcehan/lf/commit/bfa527fcea1f678a02446e03794d5a78a09857cc so the contradiction is in the introductory sentence.

We could argue about the order for any given extension. If you configure a color for shell scripts based on extension, such as `*.sh`, `*.zsh`, `*.csh`, etc., then you'd want to highlight which scripts have the executable bit and which don't, so the file type has to be matched before the extension. To avoid the bikeshedding, it makes sense to keep the same behavior as GNU dircolors.
