### ISSUE TITLE
how to use highlight/bat as the previewer?

### ISSUE THREAD

**Issue by shusheaan** [gokcehan/lf#904]
I'm trying to just add a bit syntax coloring in lf by just using highlight/bat as the previewer instead of writing a full blown script. How can I do that? Simply adding 'previewer /usr/bin/highlight' seems not right.

**Comment by lahwaacz** [comment]
The [documentation](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Previewing_Files) has an example script using `highlight`. To use bat instead, change the highlight command to something like `bat --paging=never --style=numbers --terminal-width $(($2-5)) -f "$1"`.

**Comment by shusheaan** [comment]
Thx, so I tried it but it's now working - I added set previewer ~/.config/lf/pv.sh in lfrc and the content of pv.sh is just 

#!/bin/sh
case "$1" in
    *) highlight -O ansi "$1" || true;;
esac

but the lf preview window is not showing anything. I also tried the version in the documentation and the version without "|| true", same nothing.

Any idea why? I'm sure I have highlight installed and I'm using zsh in /usr/bin/zsh.

**Comment by lahwaacz** [comment]
Did you make the script executable?

**Comment by shusheaan** [comment]
yes I did, not working.
Another weird thing after this is that if I open some file in lf. Previously without previewer it would be opened in vim. Now it creates a new window and run gvim. I have gvim installed but I always use vim in terminal - gvim is just for the clipboard function. I would assume this weird behaviour is related to the preview setup as if I disable the preview line in lfrc it's normal.

**Comment by shusheaan** [comment]
please let me know if you need more info. Basically the system is plain arch + i3, very minimal nothing fancy

**Comment by shusheaan** [comment]
https://github.com/shusheaan/gral/blob/main/lf.conf this is my full lfrc

**Comment by monoelh** [comment]
@lahwaacz comment

> The [documentation](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Previewing_Files) has an example script using `highlight`. To use bat instead, change the highlight command to something like `bat --paging=never --style=numbers --terminal-width $(($2-5)) -f "$1"`.

This worked for me. The command is actually 'batcat' and not only bat. Here is my lfrc:
`set previewer /etc/lf/pv.sh
cmd open $rifle $fx`

and the pv.sh I modified from the docs and the comment:
`#!/bin/sh

case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    *.pdf) pdftotext "$1" -;;
    *) batcat --paging=never --style=numbers --terminal-width $(($2-5)) -f "$1" || true;;
    #*) highlight -O ansi "$1" || true;;
esac`

It's slower than highlight though.

**Comment by lahwaacz** [comment]
> The command is actually `batcat` and not only `bat`.

That's the case only on Debian and Ubuntu. See https://github.com/sharkdp/bat

**Comment by monoelh** [comment]
Yes, sorry you are totally right. I'm on Ubuntu 22.04. on WSL2.

**Comment by shusheaan** [comment]
> @shusheaan your config does not use the correct `set` syntax. Turning an option on is done with e.g. `set hidden` not `set hidden true`. See #758. Maybe this is causing something to break.

@p-ouellette I just corrected them and now it WORKS. I'm so happy this is finally done and I appreciate your help very much. Cheeeeers

**Comment by cyqsimon** [comment]
Came across this issue and ended up with this script, inspired by @monoelh's:
`preview.sh`:
```bash
#!/usr/bin/env bash

MIME=$(mimetype --all --brief "$1")
#echo "$MIME"

case "$MIME" in
    # .pdf
    *application/pdf*)
        pdftotext "$1" -
        ;;
    # .7z
    *application/x-7z-compressed*)
        7z l "$1"
        ;;
    # .tar .tar.Z
    *application/x-tar*)
        tar -tvf "$1"
        ;;
    # .tar.*
    *application/x-compressed-tar*|*application/x-*-compressed-tar*)
        tar -tvf "$1"
        ;;
    # .rar
    *application/vnd.rar*)
        unrar l "$1"
        ;;
    # .zip
    *application/zip*)
        unzip -l "$1"
        ;;
    # any plain text file that doesn't have a specific handler
    *text/plain*)
        # return false to always repaint, in case terminal size changes
        bat --force-colorization --paging=never --style=changes,numbers \
            --terminal-width $(($2 - 3)) "$1" && false
        ;;
    *)
        echo "unknown format"
        ;;
esac
```

I used MIME type instead of file extension so hopefully this will make handler selection more accurate.

This also has the unintended side effect that files like `.pptx` which are secretly just zip files also get "unzipped". The usefulness of this "bug/feature" is questionable but I suppose it's better than nothing?
