### ISSUE TITLE
sudo cp file/folder

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#910]
I fail to get a command of sudo cp -r working.
Nicest solution would be to yank a file and past it with sudo 

Any nicer suggestions?

This is working but I have to mark the file with space and can't use yank

`# {{{ <<<<<<<<<<<<<<<<<<<<<<<<< sudo paste "ps" <<<<<<<<<<<<<<<<<<<<<<<<<<
cmd sudocp ${{
    sudo cp -r "$fx" .
}}
##-------------------
map ps sudocp Paste file with sudo
#-------------------

`

**Comment by lahwaacz** [comment]
https://github.com/gokcehan/lf/wiki/Tips contains several examples of a custom `paste` command.

**Comment by se7en-x230** [comment]
Thanks I read that before.
I manage to sudo cp a selected $fs item 
but not a yanked (I guess $@)

**Comment by lahwaacz** [comment]
Search for the tips handling `~/.local/share/lf/files`

**Comment by se7en-x230** [comment]
Thanks I give up. "$fs" is not really what I want but whatever.
"$@" asks for passwd but doesn't take it and asks again and again ...

**Comment by se7en-x230** [comment]
Thanks
