### ISSUE TITLE
lf stay working in background

### ISSUE THREAD

**Issue by OssNasr** [gokcehan/lf#912]
Im using **lf** in **voidlinux** musl base system, and after i press **q**, i still see **lf** in top, and if i issue another **lf** command and quit, i see two instances of **lf** working in background

![2](https://user-images.githubusercontent.com/43766296/185488108-f86f921c-5f14-45e5-96f7-56cb8eb7709a.png)

**Comment by lahwaacz** [comment]
lf runs a server process that is kept running when a client quits. Search for the `autoquit` option in the documentation: https://pkg.go.dev/github.com/gokcehan/lf#section-documentation

**Comment by OssNasr** [comment]
Ok, but im not running a server though, im logging in  my machine on tty.

I mean, im using it as a main system from tty.

**Comment by rafcon-dev** [comment]
That's not what he meant. When you open lf, lf starts two things, a "server" process, and the "gui" that you see. The gui that you see comunicates with the server. This is to enable several instances of lf to comunicate between each other, to past files from one to another for example (so each gui effectively comunicates with the server that passes responses between the guis)

**Comment by OssNasr** [comment]
Thanks for your explanation, it's clear for me now, and yes, i thought it might be reasonable for "autoquit" to be enabled by default, but you persuade me already about the server to be communicating with other instances of lf, its like a replacement for tabs i guess, its something like a taste for the developer... And it might be better than tabs too.

Thanks :)

**Comment by rafcon-dev** [comment]
Yeah, I for example like to have two guis inside tmux side by side, so as to mimic a two pane manager like midnight commander for example. You're welcome!

**Comment by pc00per** [comment]
Infact I started liking the server way. Caz tabs are limited to a single client.

**Comment by joelim-work** [comment]
@OssNasr If you want to use `lf` without starting a server, you can use the `-single` option. Although note that in this case you can't use some features that depend on the server such as `lf -remote` commands.
