### ISSUE TITLE
Different Icons for Specific Folders

### ISSUE THREAD

**Issue by DaitiDay** [gokcehan/lf#913]
As for the title, is it possible/will it be possible to assign specific icons to specific folders/files given the name of the folder/file?
For example adding `git=GIT_ICON:\` to `LF_ICONS` in order to get the proper icon for the folder/file named "git", while all the other folders/files keep the default icon.

**Comment by lahwaacz** [comment]
Directories have to be specified either as absolute paths or with a trailing slash. See the documentation: https://pkg.go.dev/github.com/gokcehan/lf#hdr-Colors

**Comment by DaitiDay** [comment]
Yeah I know that, I should be more specific. What I would want is to have all folders/files named "git" to have the icon GIT_ICON, but without having to keep the `LF_ICON` list updated with every single folder/file just like in ranger for example.

**Comment by lahwaacz** [comment]
> Yeah I know that, I should have been more specific. What I would want is to have all folders/files named "git" to have the icon GIT_ICON, but without having to keep the `LF_ICON` list updated with every single folder/file just like in ranger for example.

Clearly you don't know that you can add the trailing slash to the name: `git/=whatever_icon`

**Comment by DaitiDay** [comment]
And clearly you don't know what good manners are :/ This said, that solved my problem, thank you.

**Comment by se7en-x230** [comment]
> And clearly you don't know what good manners are :/ This said, that solved my problem, thank you.

Help without going through riddles ... :) 
May I ask how?
