### ISSUE TITLE
Select item on mouse click

### ISSUE THREAD

**Issue by DeeGeeMan** [gokcehan/lf#919]
Is there a way to select a file or directory with the mouse similar to ranger?

`map <m-1> ???`

**Comment by ilyagr** [comment]
Looking at https://github.com/gokcehan/lf/issues/268#issuecomment-762506668 and [the code], it looks like the answer is no. The location of the mouse isn't being checked anywhere.

[the code]: https://github.com/gokcehan/lf/blob/a13c14fb079b8062137cc7414b8d79c77aea1378/ui.go#L1021

**Comment by p-ouellette** [comment]
#963 is not in a released version yet. Did you build from the latest code?
