### ISSUE TITLE
IO caching optimizations and asynchronous updates

### ISSUE THREAD

**Issue by gokcehan** [gokcehan/lf#92]
One of the main selling points of `lf` is speed, yet most of the time it is not fast enough due to IO bottlenecks. There seems to be two different issues. First, we are not caching the dir and read it again for almost all operations (even a simple `top` command assigned to `gg` reads the dir again). Second, preview updates are blocking and prevents snappy movement for crowded directories and long running preview commands. I will be focusing on these two issues in the upcoming days and try to track the progress here.

Mentioned in #87.

**Comment by avently** [comment]
I use lf on a daily basis and now with all commits from the issue it works fantastic!
It loads asynchronously directories with thousands of objects so quick. And uses cache. And it doesn't block a ui while I am scrolling. Good job, @gokcehan!

**Comment by gokcehan** [comment]
@avently Thank you for the kind words. I agree things are getting fancy :)

For future reference, I have two things in mind left on this issue. First `reload` event should keep the position in the current directory much like `redraw`. Second, I hope to experiment with detecting file and directory changes using modification times and renew the content automatically when necessary.

**Comment by gokcehan** [comment]
Modified files and directories are now automatically detected and reloaded asynchronously. Closing this issue now. Feel free to report any problems.
