### ISSUE TITLE
Is there a way to toggle preview

### ISSUE THREAD

**Issue by jfrascon** [gokcehan/lf#927]
I've been trying to implement some kind of toggle preview, like the behavior you can find in ranger (zi keybind), but I haven't had any success so far. 
As a previewer I'm using ctpv, which is easy to configure and display all the content I'm interested on, but as far as I know in lf, either you have preview enabled all the time or you have the feature disabled.
Am I missing something? (perhaps some kind of easy script or something to automate this)

Thank you in advance!

**Comment by lahwaacz** [comment]
See https://github.com/gokcehan/lf/issues/289

**Comment by jfrascon** [comment]
Thank you!
Sorry,  I do not why, I missed this closed issue (#289) when I was looking in the repo if anybody else has just asked this.
Thank you very much!

**Comment by lahwaacz** [comment]
Please close the issue if it's resolved.
