### ISSUE TITLE
Is there a way to change icons colors only?

### ISSUE THREAD

**Issue by G2G2G2G** [gokcehan/lf#928]
like this
![1](https://user-images.githubusercontent.com/50514477/189027063-7b600157-129b-4c08-8e16-715be0fd1b68.jpg)
(nnn file manager)

also this is 30000000000x better (I did the math) than the nerdfont this wiki recommends for font patching
https://github.com/sebastiencs/icons-in-terminal

~~Also while we do that can we support more colors? The package you import in this script https://github.com/gokcehan/lf/blob/master/colors.go has tons of them as seen here:~~
~~https://github.com/gdamore/tcell/blob/master/color.go~~

~~can we perhaps just search the massive struct in that color.go of tcell and use those words instead of your hard coded bash ones that run through a switch? Line 845 has easy names.~~

~~Most terminals these days support many colors https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html~~

~~or do I not understand your switch statement? IDK wtf is going on after the 40s, does it support RGB in the second if statement of the 48 case or something?~~

### lmao
wow ok, I figured it out
foreground RGB:
38;2;10;206;255
background:
48;2;128;32;122

why is this not mentioned anywhere?
anyway back to original, can we color icons separately?

Please add this to the etc/color.example so dummies like me can see how stuff works, these are the languages logo colors
```
# code
*.go    38;2;121;212;253
*.php   38;2;120;124;181
*.js    38;2;255;217;58
*.html  38;2;241;100;40
*.css   38;2;46;170;222
*.md    0;31
*.json  38;2;155;155;155
*.py    38;2;255;212;59
*.xml   38;2;145;167;141
*.log   0;37
*.txt   0;37


*.pdf   0;31
```

**Comment by Joao-Queiroga** [comment]
I would like to do that too. The same way neovim-web-devicons do.

**Comment by ryanmsnyder** [comment]
I would also really like this feature.

**Comment by techeddie** [comment]
I am missing this feature as well, would be awesome to have it.. thanks

**Comment by limaceous-bushwhacker** [comment]
Would love to see this implemented in lf.

**Comment by joelim-work** [comment]
This is now officially supported by #1674
