### ISSUE TITLE
How to map shift+enter?

### ISSUE THREAD

**Issue by yogeshdcool** [gokcehan/lf#943]
shift uses uppercase letters bit enter is inside <> so how to combine these two

**Comment by lahwaacz** [comment]
shift+enter is not defined in https://github.com/gokcehan/lf/blob/e03143299d4596bbc9bb8a2d8a1b0931e3183410/ui.go#L24-L143 so there is currently no way to map it.

**Comment by ilyagr** [comment]
There is no way. Terminal programs can't distinguish between `<enter>` and `Shift+<enter>`.

**Comment by joelim-work** [comment]
Yeah I can confirm `tcell` doesn't distinguish between `<enter>` and `Shift+<enter>`, so it isn't possible to map them separately.

**Comment by DusanLesan** [comment]
@yogeshdcool Maybe you can make your terminal emulator send some other sequence when pressing shift+enter. 

I have in alacritty config:

```
key_bindings:
  - { key: Return,   mods: Shift,    chars: "\x0a" }
```
That translates `shift+enter` into `ctrl+j` so you can use that combination in other programs like:
```
map <c-j> echo "Pressing shift + enter"

```
