### ISSUE TITLE
package for Slackware 

### ISSUE THREAD

**Issue by adcdam** [gokcehan/lf#949]
Hi im making a lf Slackbuild for Slackware.  To be accepted it has to be build in offline mode, i got all the sources of the modules.txt
and the program build and if i launch it start with no problem, but i dont know how to build the man pages and how to get the .desktop file for the package.
this is part of the slackbuild 
how do i build the man pages?

```
CGO_CFLAGS="$SLKCFLAGS" \
CGO_CXXFLAGS="$SLKCFLAGS" \
go build -mod vendor

install -sDm 0755 lf -t $PKG/usr/bin
```

**Comment by ilyagr** [comment]
`lf.1` is included in the git repository. You can rebuild it with the `go generate` command, which calls `gen/man.sh`. Because of https://github.com/gokcehan/lf/issues/959, you need to use Go version <=1.18.
