### ISSUE TITLE
Source local Config file?

### ISSUE THREAD

**Issue by fredbsc** [gokcehan/lf#952]
Is there a way to"source" a second config file? In lfrc something like "source <hostname>.config". To have a global lfrc and on each host a local one ....

**Comment by DusanLesan** [comment]
Have you tried with a full path? Like: `source ~/.config/lf/lfrc_X`

**Comment by joelim-work** [comment]
I would advise against specifying a relative path for `source`, since it is evaluated relative to the CWD of `lf`, and not relative to the path of the original config file.

Provided you use an absolute path as suggested above, I think there should be no issues with `source`.

**Comment by joelim-work** [comment]
Also seems to be related to #1173
