### ISSUE TITLE
Symbolic links for folders and files share the same icon

### ISSUE THREAD

**Issue by DeeGeeMan** [gokcehan/lf#957]
There should be different symlink icons for folders and files in `lf`.  A folder in `lf` is showing a file symlink icon which is confusing, **Ranger** shows two distinct icons for symlinks.

**Comment by pc00per** [comment]
You actually don't need an icon. `lf` colors symlinks as green in my machine with alacritty/nvim setup (may depend on your application set). And status bar even shows the pointer location when you're on it.

**Comment by joelim-work** [comment]
Added in #1644. To show icons based on the symbolic link target, use `target` instead of an actual icon like below:

`icons` file:

```
ln	target
di	d
fi	f
```
