### ISSUE TITLE
When using Go 1.19, `gen/man.sh` generates a badly formatted manpage

### ISSUE THREAD

**Issue by ilyagr** [gokcehan/lf#959]
For example, for headings, instead of `.SH HEADING` it outputs `# Heading`. Thus, `go generate` creates a mess.

The reason for this is that `gen/man.sh` processes the output of `go doc`. Before Go 1.19, that was formatted in plain text. After Go 1.19, it's formatted in markdown, which the awk script in `man.sh` does not parse correctly.

A possible solution would be to modify the `awk` script in `gen/man.sh` so that it reads the `doc.go` file directly, ignoring all the lines before `/*` and all the lines after `*/`.

`gen/docstring.sh` has a similar, but less severe, issue. The output differs from before on Go 1.19, which is a problem when preparing pull requests, but it is still readable.

**Comment by ilyagr** [comment]
`gen/docstring.sh` has a similar, but less severe, issue.

**Comment by laktak** [comment]
Thanks, I was just wondering about the broken output.

**Comment by ilyagr** [comment]
This was resolved by https://github.com/gokcehan/lf/commit/654b8737b8a35729aa89aa93acf05ed5871b2616.
