### ISSUE TITLE
Change how a filename or dirname is printed

### ISSUE THREAD

**Issue by sucrecacao** [gokcehan/lf#964]
Hello !

It would be super awesome to change how the name of a file or directory  is displayed on lf. 
For example let's say I have:
```
  lf_example tree          
.
└── home
    ├── documents
    │   ├── file_1
    │   ├── file_2
    │   ├── file_3
    │   └── file_4
    └── downloads
        ├── file_5
        ├── file_6
        └── file_7

3 directories, 7 files
```

Then I could add a script to my lfrc: ( in bash pseudocode )
```
if $filename == 'download' then
   filename = "download [ $(ls download | wc -l) files ]"
```

Then instead of having this lf view:
![image](https://user-images.githubusercontent.com/55893070/195994884-be76a8cc-48d4-406d-afa6-8ea63f26950f.png)

I would have someting like:
![image](https://user-images.githubusercontent.com/55893070/195994927-bcff3b34-184e-4039-ae76-8ec7b5ff7057.png)

Is that already possible with lf?

**Comment by lahwaacz** [comment]
If you want to show the number of files in a directory, you can set the `dircounts` option and include `size` in the `info` option. See https://pkg.go.dev/github.com/gokcehan/lf#section-documentation

Note that the output of the `ls` command should not be parsed: https://mywiki.wooledge.org/ParsingLs

**Comment by sucrecacao** [comment]
No no `ls` was just an example..

The question is: 
As lf show the names of the files and directory, is it possible to script lf in order to show different value than the original filenames?

**Comment by lahwaacz** [comment]
No, it's not possible.
