### ISSUE TITLE
:cd <alt>+BackSpace to clear by words

### ISSUE THREAD

**Issue by pc00per** [gokcehan/lf#971]
I do `Alt+Backspace` most of the times. Deletes last word at a time. In `lf :cd` when I type something wrong I always have to backspace letter by letter when I make mistake at start of the word.

**Comment by pc00per** [comment]
Dropping into shell was better option btw. (I'm still new to lf, so don't mind these issues if they're dumb).

**Comment by ilyagr** [comment]
You can also use `:cmap <backspace> cmd-delete-unix-word` to get the behavior you watned. (On my machine , `<backspace>` is actually Ctrl+Backspace).

The default binding for this is `<c-w>`, see the docs for more.
