### ISSUE TITLE
Simple question Where to put configs in Windows?

### ISSUE THREAD

**Issue by fislysandi** [gokcehan/lf#973]
i just have a question where to put the configs in windows, its not said exactly where to do so does somebody know where to put them?.

**Comment by xezwary** [comment]
Looking at https://github.com/gokcehan/lf/blob/master/os_windows.go it looks like either in ProgramData\lf or %USERPROFILE%\AppData\Local\lf

**Comment by navakelvin** [comment]
If you plan to do a version control, I recommend placing the settings in C:/ProgramData/lf

Why? Because in %USERPROFILE%\AppData\Local\lf LF will constantly modify files, so it will be annoying. Unless you apply a .gitignore though.

**Comment by joelim-work** [comment]
This is mentioned in the documentation: https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/doc.go#L296-L299

In particular the location can now be customized by setting `LF_CONFIG_HOME`, although currently this feature is only available in the master branch and hasn't been officially released yet.
