### ISSUE TITLE
drag like selection support

### ISSUE THREAD

**Issue by pc00per** [gokcehan/lf#974]
**`<space>`** behaviours to **selection + point to next item**. Here, I'm expecting **`<shift>+<space>`** for **selection + point to previous item**, which bydefault currently has the same **`<space>`** action.
A reason this is useful, because you might traverse a directory from bottom & need to select items, but in backward direction. Will also help to quickly deselect item.

**Pseudo algorithm:**
When you **`<space>`** selecting forward, **`<shift>+<space>`** should **deselect previous item + point to it**.
When you **`<shift>+<space>`** select backwards, **`<space>`** should **deselect next item + point to it**.

This is more like a mouse pointer selecting / deselecting by dragging / undragging items, but with **`<space>`** & **`<shift>+<space>`**. 
I think this functionality needs two loops maintaining a selection buffer for both directions. And break the continuity when manual traverse triggered (h/j/k/l).

**Comment by ilyagr** [comment]
I think you could get a lot of mileage from  `map <backspace2> : up; toggle`. You can also do `map <backspace> :  toggle; up` if you want to pick between the two possible behaviors. (A bit strangely, on my keyboard, Backspace becomes `<backspace2>` while Ctrl+Backspace becomes `<backspace>`).

As far as I can tell, the terminal has no way to distinguish Space and Shift+Space. However `<c-space>` instead of backspaces should work.

**Comment by pc00per** [comment]
> I think you could get a lot of mileage from map <backspace2> : up; toggle. You can also do map <backspace> : toggle; up if you want to pick between the two possible behaviors. 

But you can't simulate drag like selection with this (as I mentioned in my pseudo algo above).
In a GUI file manager scenario, items get selected when you drag, & unselected when you undrag. It's possible to do that here with two key combos, but require some coding. Caz dragging (continuous selection in case of lf) should be a continuous selection loop, that brakes whenever a key is pressed (h,j,k,l).
Caz when you continuous select forward / backward, both key combos need to have altered behaviour.
> As far as I can tell, the terminal has no way to distinguish Space and Shift+Space. However <c-space> instead of backspaces should work.

Oh. I thought Shift+space is some character like space. Ctrl+Space should be preferrable too.

**Comment by pc00per** [comment]
Or there's a better way I can think. As this is a vim binding like file manager, atleast give us visual mode, that starts selection through `v`, where you can `j,k` your way up or down to drag select (as you would do in vim).
Right now, I think `v`does nothing.

**Comment by pc00per** [comment]
Hm. Okay. I could live with `toggle, up` mapping. Closing the issue.
