### ISSUE TITLE
make preview pdf,picture features

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#984]
ranger can preview it.
but lf preview pdf ,pictures is diff~ config.

**Comment by DusanLesan** [comment]
I have difficulty understanding what the issue/request is. You want to be able to preview PDFs and pictures in lf?

**Comment by newyorkthink** [comment]
yes. I tall about the request, is about lf can able to preview PDFs and pictures

**Comment by newyorkthink** [comment]
I like lf more than ranger. 
lf is binary file, it can run everywhere. better to ranger.
not use apt-get install. 

lf is great project.

：）

**Comment by DusanLesan** [comment]
Could you look into https://github.com/NikitaIvanovV/ctpv. It is the easiest way to set up previews

**Comment by newyorkthink** [comment]
> Could you look into https://github.com/NikitaIvanovV/ctpv. It is the easiest way to set up previews

I see it ctpv.
but i don't know how can use it with lf file manager

i don't like use "sudo make install"
it is bad my dependent environment.

so, i like cp file to folder , 
i like the simple method . just c> Could you look into https://github.com/NikitaIvanovV/ctpv. It is the easiest way to set up previews

I see it ctpv.
but i don't know how can use it with lf file manager

i don't like use "sudo make install"
it is bad my dependent environment.

so, i like cp file to folder , 
i like the simple method . just copy config file to folder 

are you known how can copy ctpv file to where, and how configopy config file to folder 

are you known how can copy ctpv file to where, and how config

**Comment by DusanLesan** [comment]
ctpv is just a faster version of [stpv](https://github.com/Naheel-Azawy/stpv)(you can use that if it is easier to set up). 
1. You need to install ctpv: Git page gives the install instruction:
```
git clone https://github.com/NikitaIvanovV/ctpv
cd ctpv
sudo make install
```
2. You need to add config lines from ctpv readme to your lf config:
```
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id
```
3. You need to install all needed dependencies. For images and PDFs you would need `ueberzug` and `pdftoppm`(provided by `poppler` in my case )

I have it working so you can look into my config as an example

**Comment by DusanLesan** [comment]
> @DusanLesan I prefer chafa, caz it generates the "actual preview" of 244x244 16bit, instead of directly opening higher res images like ueberzug. Thus faster & smoother experience.

I did use chafa and img2txt and they were great to quickly recognize a random image, but I often search through screenshots where the difference is impossible to see with them. I might be wrong, but ctpv feels faster than scripting a preview. Plus it does have support for chafa

**Comment by joelim-work** [comment]
You should be able to use something like `pdftoppm -jpeg -f 1 -singlefile <pdf_file> <output_file>` to create an image from a PDF file and then display that. Closing as it is not an issue.
