### ISSUE TITLE
Red glob

### ISSUE THREAD

**Issue by cv1618** [gokcehan/lf#987]
I'm not sure how it got there but just to the left of a folder icon in my home directory there's a red glob that I'm not sure how to get rid of. It's persistant even if I close lf it's still there. I assume it's to mark files/dirs but hitting c,v, or u doens't get rid of it.

**Comment by ilyagr** [comment]
That file is probably marked for moving by the `d` command. `:clear` should get rid of it.

**Comment by p-ouellette** [comment]
By "glob" I guess you mean an asterisk, which is a tag (press 't').

**Comment by cv1618** [comment]
Yep that was it. I can see where tags would be handy when you have to look through a lot of files and you need to keep track of where you left off or if you sort of want to favorite a file or directory. Thanks, issue closed.
