### ISSUE TITLE
Flickering during open

### ISSUE THREAD

**Issue by devnull09** [gokcehan/lf#988]
When opening files in external applications, lf seems to display  a "loading..." message for a split second every time before the file is opened inside the target application. This is extremely annoying and while it may have some use case when applications take a while to start, it should not be displayed at all when the target application responds quickly.

I was unable to find any way to disable this behavior and would be very grateful if anyone could point out such an option to me.

To explain the problematic behavior a bit more:

After navigating to a target file, example.pdf and pressing the right arrow or l to open it, lf flickers and seems to be completely redrawn, shortly showing a loading message for 0.1 seconds on the right side before the target file is opened in the configured application and lf is redrawn again.

To reiterate how this looks on a tiling wm with clean separation of windows:

The screen shows lf with a preview dominating the right side of the screen.
Upon opening the file through lf, the right side of lf with the preview is shortly replaced with a loading message, then again with the preview and then finally with the target application. Each time lf is redrawn and seems to flicker.

Doing the same in ranger will not create a single flicker and even the left side with the file listing is not visibly redrawn (ranger would still redraw the window but it is not noticeable other then the right borders shifting to the left)

It does not seem to make any difference how the file is opened, I have reproduced the same behavior with xdg-open, mimeopen, handlr and rifle.

**Comment by devnull09** [comment]
Interestingly, if I remove the "cmd open" line from lfrc, the lf window is not redrawn and only the "loading" message flashes up shortly. 

If I then remove this line https://github.com/gokcehan/lf/blob/a94015d2210a7983744f47395f542459a56175d9/ui.go#L264 in addition to removing the cmd open configuration, lf behaves exactly like ranger when opening files.

However, it seems not possible to use a custom open command without having lf flashing to be redrawn whenever a file is opened in an external application. With the loading message patched out, but witha  custom open comamnd in lfrc, opening a file will cause lf to disappear for a split second, showing the terminal it was started from (alacritty in my case), before lf is redrawn again and the file is opened.

**Comment by devnull09** [comment]
Ok, so while I was not able to find the core of this issue, I did find out some workarounds/hints:

When there is no custom open command specified in lfrc, the behavior of lf is as intended.
lf also works fine if a custom file opener is configured using the $OPENER environment variable.

Only when a "cmd open" command is specified in lfrc will this flickerbug trigger.

Additionally, one flicker is caused by the loading message mentioned above, but that seems to be a separate issue.
For now the only option to avoid this issue is to patch out the loading message above and use the OPENED variable to configure custom file openers.

**Comment by devnull09** [comment]
When there is no custom lfrc file available in ~/.config/lf/ the application works without flickering but it does not open text files.

Looking into it, the default command to open files is as follows:
`cmd open &$OPENER $f`

Every time a file is opened in lf, the log shows the following entry
`shell-async: &{{ $OPENER "$f" }} -- []`

This entry is also generated when a file (e.g. png or pdf) is successfully opened as well as in cases where a textfile failed to open in the editor 

If a custom lfrc is available and includes the above line to open files, the behavior is actually the same, meaning no flicker and no textfiles being opened.

If the lfrc config includes either the default configuration or simply this command

`cmd open $set -f; $OPENER $f`

Textfiles are opened again but the flicker is back.

Using this configuration the log will show this instead:
```
shell: ${{ case $(file --mime-type -Lb $f) in ... }} -- []
Got EventError: 'read /dev/tty: i/o timeout' at 2022-11-01 13:14:46.673863238 +0100 CET m=+22.885078399

```


This issue is probably caused by something simple to fix but I cant find it. Perhaps someone has a clue what may cause this.

**Comment by ilyagr** [comment]
Try replacing the first `$` with an `&` in your `cmd open` command.

**Comment by devnull09** [comment]
> Try replacing the first `$` with an `&` in your `cmd open` command. This only works if your opener opens in another window, since `lf` will not wait for it to finish.

Thank you for the reply

After replacing 
`cmd open $set -f; $OPENER $f`
with
`cmd open &$set -f; $OPENER $f`

lf behaves just like when using
`cmd open &$OPENER $f`

However, as you mentioned it wont work when I try to open a file without starting another terminal window which is exactly what I am trying to do. All text files are supposed to be opened in vim, using the same terminal lf is running in.

It seems that the flickering is caused when a subshell is used to run the open command and I have no clue why that is.

**Comment by pc00per** [comment]
`&$OPENER` never works on my machine (archlinux). It just doesn't use my OPENER at all.
I had to force it to `$$OPENER` inorder to use my OPENER, which is xdg-open.

**Comment by ilyagr** [comment]
@devnull09 Yeah, that has been bothering me too. I'm surprised to hear that ranger doesn't have this issue. Perhaps it would be possible to disable clearing the screen before launching an opener program (with a special command). I'm not sure if that would work and be safe. Feel free to investigate what's going on, or I might look at it at some point.

@pc00per That sounds like a separate issue. I remember other people mentioning some problems with environment variables not being set. It might be worth double-checking if `lf` sets those correctly when launching background programs.

**Comment by pc00per** [comment]
No issues with env vars which is why `$$` works. Not sure why `&$` is used anyways.

**Comment by devnull09** [comment]
> @devnull09 Yeah, that has been bothering me too. I'm surprised to hear that ranger doesn't have this issue. Perhaps it would be possible to disable clearing the screen before launching an opener program (with a special command). I'm not sure if that would work and be safe. Feel free to investigate what's going on, or I might look at it at some point.

It already is working when is use "e" to open a text file with the $EDITOR command. There is no flicker in that case.
All Im trying to do is get the same behavior when I open the file normally with the open command.

**Comment by pc00per** [comment]
> All Im trying to do is get the same behavior when I open the file normally with the open command.

You can't. cmd open is trying to open xdg-open first, which ofcourse gets executed like a shell, which inturn opens your preferred mime application from there. To remove flicker, you gotta get rid of your opener & declare of all your defaults right inside the case.

**Comment by devnull09** [comment]
When using the default `cmd open &$OPENER $f` this will also run xdg-open to start external applications without flickering.

Im not sure myself where the issue is exactly, but since ranger has already proven that is it possible, we should be able to implement it in lf as well. Still trying to find the responsible code though

**Comment by pc00per** [comment]
ranger uses rifle, not xdg-open.

**Comment by kmarius** [comment]
Whenever a foreground command (i.e. one with the `$` prefix) is executed, the UI is suspended (and cleared in the process) and resumed afterwards, causing the flicker. The same thing happens in ranger when you run e.g. `:shell true`. One way around it is to configure your `open` command with `&` and call back via  `lf -remote ...` to run a foreground program in the current shell, or directly run the external program.

I have previously used `rifle` for this:

```
cmd open &{{
	if ! rule=$(rifle -l $f | head -1); then
                # no matching rule, show an error?
		exit
	fi
	case $rule in (*ask)
                # prompt in lf or something
		exit
	esac
	flags=$(echo "$rule" | cut -d : -f 3)
	case $flags in (*f*)
                # fork flag is present
		exec rifle $fx ;;
	esac
	lf -remote "send $id \$rifle \$fx"
}}

```

**Comment by devnull09** [comment]
> ranger uses rifle, not xdg-open.

Its not relevant which opener is used, rifle has the same effect in lf.

**Comment by devnull09** [comment]
> Whenever a foreground command (i.e. one with the `$` prefix) is executed, the UI is suspended (and cleared in the process) and resumed afterwards, causing the flicker. The same thing happens in ranger when you run e.g. `:shell true`. One way around it is to configure your `open` command with `&` and call back via `lf -remote ...` to run a foreground program in the current shell, or directly run the external program.
> 
> I have previously used `rifle` for this:
> 
> ```
> cmd open &{{
> 	if ! rule=$(rifle -l $f | head -1); then
>                 # no matching rule, show an error?
> 		exit
> 	fi
> 	case $rule in (*ask)
>                 # prompt in lf or something
> 		exit
> 	esac
> 	flags=$(echo "$rule" | cut -d : -f 3)
> 	case $flags in (*f*)
>                 # fork flag is present
> 		exec rifle $fx ;;
> 	esac
> 	lf -remote "send $id \$rifle \$fx"
> }}
> ```

This works, thanks a lot.

Is there a reason this behavior is not the default in lf?
Having lf flicker every time a file is opened is quite annoying after all.

I also could not reproduce this at all in ranger even with :shell true but in any case, the default behavior in ranger avoids this issue and I would argue that lf should as well.

**Comment by kmarius** [comment]
@devnull09 The reason it works in ranger is that the opener `rifle` is integrated into it (it doesn't call `rifle` as I described above). Ranger has knowledge about how the program wants to be started and can do so accordingly. Lf doesn't bring an opener and to achieve the same behavior there is no way around doing what I suggested above.

**Comment by devnull09** [comment]
> @devnull09 The reason it works in ranger is that the opener `rifle` is integrated into it (it doesn't call `rifle` as I described above). Ranger has knowledge about how the program wants to be started and can do so accordingly. Lf doesn't bring an opener and to achieve the same behavior there is no way around doing what I suggested above.

Thanks for explaining the details.

Should the instruction you listed above to fix this not be part of the default lf configuration then? Just with $OPENER instead of rifle to keep a generic config. So far I have not noticed any issues with this configuration.

**Comment by devnull09** [comment]
#991 Should implement the solution from @kmarius in a generic way to fix this issue.

**Comment by ilyagr** [comment]
I appreciate @kmarius's idea and https://github.com/gokcehan/lf/pull/991, but I think there's a deeper problem to fix here.

I don't understand why `lf -remote "send $id \$rifle \$fx"` behaves any differently than typink `$rifle $fx` inside lf, and I think that indicates some sort of an issue. Ideally, there should be no need for the former and the latter should just do the right thing.

**Comment by kmarius** [comment]
@ilyagr `lf -remote ...` is only run after we *know* that the command needs to be run in the current terminal. Any command you run with a `$` prefix will cause a flicker and I don't think there is a way around it. Not clearing the screen might leave the terminal to the command in an unclean state. In a similar context I've seen the output of `less` then being colored because of this. **If** something can be done, I would need happen in [tcell](https://github.com/gdamore/tcell).

**Comment by ilyagr** [comment]
Yes, perhaps I misunderstood what this is about. See https://github.com/gokcehan/lf/pull/991/files#r1014737080.
