### ISSUE TITLE
? on dircounts

### ISSUE THREAD

**Issue by ghost** [gokcehan/lf#989]
`set dircounts` always show `?`
I've read some issues saying you need appropriate permissions for that. All of my user folders have `drwxr-xr-x` permissions which is enough isn't it?

**Comment by joelim-work** [comment]
If a directory is loaded while `dircounts` is disabled, the count won't actually be calculated and will show `?`. Enabling `dircounts` won't change that, you have to use `reload` to reload the directory again afterwards.
