### ISSUE TITLE
Trouble enabling mouse in the "/etc/lfrc" sample file

### ISSUE THREAD

**Issue by Jeff-411** [gokcehan/lf#997]
I'm using the r27 release for Windows. I'm running `C:\\Program Files\\Git\\bin\\bash.exe` in Windows Terminal.

I'm new to LF, and really liking it. I've copied the `/etc/lfrc` example file to `~AppsData/local/lf/` and:
1. Changed: `set shell sh` to `set shell bash`.
2. Added: set `dropbox` to make sure things were working.
3. Tried: left & right mouse clicks => no results.
4. Tried: adding `set mouse` => "unknown mapping: " errors `<m-1>` `<m-2>` `<m-up>` `<m-down>`.
5. Tried: adding `set mouse!` => same "unknown mapping: " errors.

I'm obviously missing some (mapping?) step here. Could somebody point me in the right direction to get LF's mouse features working?

TIA ~ Jeff

**Comment by p-ouellette** [comment]
Full mouse support was added in https://github.com/gokcehan/lf/pull/963 and hasn't made it into a release yet. If you want to use it you can build lf from source.

**Comment by Jeff-411** [comment]
Thanks p-ouellette.

**Comment by Susensio** [comment]
Hi @p-ouellette , how can I manually map the same behaviour as #963 while I wait for an official release?

**Comment by p-ouellette** [comment]
@Susensio you can't get the same behavior, but you can create mappings for mouse buttons (there's no click position information).
See this section of the documentation:
https://github.com/gokcehan/lf/blob/aa78b26e44574f3fef7cfdd4e6496dac405ba52f/doc.go#L1066-L1082
